### PR TITLE
Don't rename pod if container has the same name

### LINKED ISSUE #12722: Podman play kube adds _pod suffix if container is named like pod.
**BUG REPORT**

/kind bug

**Description**

I wanted to create a pod via `podman play kube` with the name `nginx` and a single container also named `nginx`. I got the warning `a container exists with the same name ("nginx") as the pod in your YAML file; changing pod name to nginx_pod` and the resulting pod had the name `nginx_pod`. I expected the pod to be named `nginx`. If I name the pod `fancy` in the YAML, I get a pod named `fancy`.
The created containers however are named `nginx_pod-nginx` and `fancy-nginx`. There is no container named `nginx` in my system.

**Steps to reproduce the issue:**

1. Create the file `pod.yaml`:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
```

2. Apply it via `podman play kube pod.yaml`

**Describe the results you received:**
I get a pod named `nginx_pod`:
```
root@dev-vps:~# podman pod ps 
POD ID        NAME        STATUS      CREATED        INFRA ID      # OF CONTAINERS
8750d3ad45a4  nginx_pod   Running     9 seconds ago  982c66dbd233  2
root@dev-vps:~# podman ps -a
CONTAINER ID  IMAGE                           COMMAND               CREATED         STATUS             PORTS       NAMES
982c66dbd233  k8s.gcr.io/pause:3.5                                  13 seconds ago  Up 11 seconds ago              8750d3ad45a4-infra
6ab1519f1e71  docker.io/library/nginx:1.14.2  nginx -g daemon o...  11 seconds ago  Up 11 seconds ago              nginx_pod-nginx
```

**Describe the results you expected:**
I expect a pod named `nginx` and a container named `nginx-nginx`. 

Like in this example:
```
root@dev-vps:~# cat example-pod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: fancy
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
root@dev-vps:~# podman play kube example-pod.yaml 
Pod:
c388d9d2d86dde65b75b8e623d5609d728adcf3cbd7ff49274bfee6af246ec7b
Container:
79ea1bb19360b897b42213e61fc5e6e5bd2f07feb8be349bc7e091c52ccc4cee

root@dev-vps:~# podman pod ps
POD ID        NAME        STATUS      CREATED        INFRA ID      # OF CONTAINERS
c388d9d2d86d  fancy       Running     7 seconds ago  8e97b14e4813  2
8750d3ad45a4  nginx_pod   Running     3 minutes ago  982c66dbd233  2
root@dev-vps:~# podman ps -a
CONTAINER ID  IMAGE                           COMMAND               CREATED         STATUS            PORTS       NAMES
982c66dbd233  k8s.gcr.io/pause:3.5                                  3 minutes ago   Up 3 minutes ago              8750d3ad45a4-infra
6ab1519f1e71  docker.io/library/nginx:1.14.2  nginx -g daemon o...  3 minutes ago   Up 3 minutes ago              nginx_pod-nginx
8e97b14e4813  k8s.gcr.io/pause:3.5                                  10 seconds ago  Up 9 seconds ago              c388d9d2d86d-infra
79ea1bb19360  docker.io/library/nginx:1.14.2  nginx -g daemon o...  9 seconds ago   Up 9 seconds ago              fancy-nginx
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.6
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
podman info --debug
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 1
  distribution:
    codename: focal
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: dev-vps
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.0-90-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 160804864
  memTotal: 2033893376
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: ea1fe3938eefa14eb707f1d22adff4db670645d6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 0
  swapTotal: 0
  uptime: 48m 16.18s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 4
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.4.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
apt list podman
Listing... Done
podman/unknown,now 100:3.4.2-1 amd64 [installed]
podman/unknown 100:3.4.2-1 arm64
podman/unknown 100:3.4.2-1 armhf
podman/unknown 100:3.4.2-1 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

### PR DESCRIPTION
**Pull request by hikhvar**
We enforce the naming scheme "podname-containername" here [1].
Therefore we must not rename the pod in case of a naming conflict
between pod name and container name. Not renaming the pod increases the
usability for the user and easies scripting based on the name. Otherwise
a user must set some label to reliable find a pod after creation. Or
have to implement the renaming logic in the script.

[1] https://github.com/containers/podman/blob/main/pkg/specgen/generate/kube/kube.go#L140

Fixes #12722

Signed-off-by: Christoph Petrausch <chrobbert@gmail.com>

### CODE REVIEW

File: pkg/domain/infra/abi/play.go [hunk 1]
```diff
@@ -15,6 +15,13 @@ import (
 	"github.com/containers/common/libimage"
 	"github.com/containers/common/pkg/config"
 	"github.com/containers/image/v5/types"
+	"github.com/ghodss/yaml"
```
Comment (rhatdan) [inline pkg/domain/infra/abi/play.go:18]: Why is this change here?

**Comment by rhatdan** [comment]
@mheon PTAL

File: pkg/domain/infra/abi/play.go (hunk 1 above)
Comment (hikhvar) [reply pkg/domain/infra/abi/play.go:18]: I think that is a left over of my IDE. It has auto sorting of imports enabled. The sorting is configured for our internal projects.

**Comment by flouthoc** [comment]
@hikhvar Newly added tests are failing.

File: pkg/domain/infra/abi/play.go (hunk 1 above)
Comment (flouthoc) [reply pkg/domain/infra/abi/play.go:18]: @hikhvar Could you please amend and remove this.

**Comment by hikhvar** [comment]
Fixes the tests, reverted the import reordering. PTAL.

**Comment by hikhvar** [comment]
Had a look over the code. Saw I removed a check too much. Sorry for the inconvenience. PTAL.

**Comment by umohnani8** [comment]
Updates LGTM
re-ran the failing tests

**Comment by rhatdan** [comment]
rebase and  repush.

**Comment by hikhvar** [comment]
Rebased and pushed again.

File: pkg/domain/infra/abi/play.go [hunk 2]
```diff
@@ -178,17 +178,10 @@ func (ic *ContainerEngine) playKubePod(ctx context.Context, podName string, podY
...
 	if podName == "" {
 		return nil, errors.Errorf("pod does not have a name")
 	}
-	for _, n := range podYAML.Spec.Containers {
-		if n.Name == podName {
-			playKubePod.Logs = append(playKubePod.Logs,
-				fmt.Sprintf("a container exists with the same name (%q) as the pod in your YAML file; changing pod name to %s_pod\n", podName, podName))
-			podName = fmt.Sprintf("%s_pod", podName)
-		}
-	}
```
Comment (TomSweeneyRedHat) [inline pkg/domain/infra/abi/play.go:191]: I'm just wondering if it makes sense to keep this warning in play, although maybe changing the wording a bit, to let the user know of the collision so they could adjust afterwards if they wanted to.  I agree with dropping the auto renam though.

**Comment by TomSweeneyRedHat** [comment]
One last test to convince, one question, and I've restarted the unhappy test.

File: pkg/domain/infra/abi/play.go (hunk 2 above)
Comment (hikhvar) [reply pkg/domain/infra/abi/play.go:191]: The warning is missleasing. There never will be a container with the same name as the pod, since all container names in the pod will be prefixed with the pod name.
