### PR TITLE
Set network ID if available during container inspect. Fixes #24910

### LINKED ISSUE #24910: Container inspect endpoint is not Docker-API compatible
### Issue Description

I am currently playing with `podman compose` utilizing the upstream `docker-compose` as backend. It always recreates the container because the network config is not as it should be. I added some debug prints to the `docker-compose` code and it cannot match the networks because the `NetworkID` returned by podman is wrong.

Running something along the lines of `podman inspect 4cb3ce78cde3 --format="{{ json .NetworkSettings.Networks }}"|jq` returns:
```json
{
  "tmp_default": {
    "EndpointID": "",
    "Gateway": "10.89.0.1",
    "IPAddress": "10.89.0.3",
    "IPPrefixLen": 24,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "c2:79:d5:75:e5:09",
    "NetworkID": "tmp_default",
    "DriverOpts": null,
    "IPAMConfig": null,
    "Links": null,
    "Aliases": [
      "tmp-traefik-1",
      "traefik",
      "4cb3ce78cde3"
    ]
  }
}
```

Here we can see that `NetworkID` is the network name and not the id of the network (`podman network inspect tmp_default`):
```json
[
     {
          "name": "tmp_default",
          "id": "675bea81a6d49e9f1ae909c58a2269524a9a9c910f91bce12a85b05b882ab5cb",
          "driver": "bridge",
          "network_interface": "podman1",
          "created": "2024-12-28T20:54:28.320995381+01:00",
          "subnets": [
               {
                    "subnet": "10.89.0.0/24",
                    "gateway": "10.89.0.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": true,
          "labels": {
               "com.docker.compose.config-hash": "4bd7e5f2ecc11ab238c4eb5931f77d1e2196619bcc8daeeb80428562a7210c37",
               "com.docker.compose.network": "default",
               "com.docker.compose.project": "tmp",
               "com.docker.compose.version": "2.32.1"
          },
          "options": {
               "isolate": "true"
          },
          "ipam_options": {
               "driver": "host-local"
          },
          "containers": {
               "4cb3ce78cde33f763bdd6abe5b19a5d93f5bb30043c94fa489114a48da5d4290": {
                    "name": "tmp-traefik-1",
                    "interfaces": {
                         "eth0": {
                              "subnets": [
                                   {
                                        "ipnet": "10.89.0.3/24",
                                        "gateway": "10.89.0.1"
                                   }
                              ],
                              "mac_address": "c2:79:d5:75:e5:09"
                         }
                    }
               }
          }
     }
]
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman run --rm -it --name testing ubuntu:latest sleep infinity`
2. `podman inspect testing --format="{{ json .NetworkSettings.Networks.podman }}"|jq`
3. Observe that the `NetworkID` is the network name

### Describe the results you received

I would have expected the actual `NetworkID` to be shown

### Describe the results you expected

The network name is shown as ID

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.38.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.12-3.fc41.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 97.27
    systemPercent: 0.8
    userPercent: 1.93
  cpus: 16
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: workstation
    version: "41"
  eventLogger: journald
  freeLocks: 2046
  hostname: apollo13
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.12.4-200.fc41.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 6023499776
  memTotal: 32395685888
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.13.1-1.fc41.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.13.1
    package: netavark-1.13.1-1.fc41.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.13.1
  ociRuntime:
    name: crun
    package: crun-1.19.1-1.fc41.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.19.1
      commit: 3e32a70c93f5aa5fea69b50256cca7fd4aa23c80
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20241211.g09478d5-1.fc41.x86_64
    version: |
      pasta 0^20241211.g09478d5-1.fc41.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.3.1-1.fc41.x86_64
    version: |-
      slirp4netns version 1.3.1
      commit: e5e368c4f5db6ae75c2fce786e31eef9da6bf236
      libslirp: 4.8.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.5
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 11h 16m 31.00s (Approximately 0.46 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /usr/lib/containers/storage
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 536854134784
  graphRootUsed: 403665657856
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 5.3.1
  Built: 1732147200
  BuiltTime: Thu Nov 21 01:00:00 2024
  GitCommit: ""
  GoVersion: go1.23.3
  Os: linux
  OsArch: linux/amd64
  Version: 5.3.1
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by apollo13**
#### Does this PR introduce a user-facing change?

```release-note
Properly return NetworkID during container inspect reports for docker-compose compatibility.
```

### CODE REVIEW

**Comment by mheon** [comment]
I'd certainly consider this user-facing, so feel free to add a release note.

Looks like the compose tests have broken, but a cursory glance suggests it's small breaks from error message changes.

**Comment by apollo13** [comment]
@mheon Is there any chance that the tests somehow don't use the locally built podman? The "mac address is set" failure is due to a bug in compose: https://github.com/docker/compose/pull/12439 but the other failure in compose I cannot explain (works locally *scratches head*)

File: test/compose/uptwice_idempotent/tests.sh [hunk 1]
```diff
@@ -0,0 +1,11 @@
+# -*- bash -*-
+
+NL=$'\n'
```
Comment (Luap99) [inline test/compose/uptwice_idempotent/tests.sh:3]: this is not used here

File: test/compose/uptwice_idempotent/docker-compose.yml [hunk 2]
```diff
@@ -0,0 +1,8 @@
+services:
+  app:
+    image: alpine
+    command: [sleep, infinity]
+    networks:
+      - net1
+networks:
+  net1:
```
Comment (Luap99) [inline test/compose/uptwice_idempotent/docker-compose.yml:8]: compose creates and used custom networks by default, what is the point to declare one here?

**Review by Luap99 — COMMENTED** [review]
The change should be fine, ID should be the ID after all and for actual usage it should make no difference if you pass name or id to another command so I don't think there is a risk of breaking anything.

You also have to update all the int test that match the network id as well.

File: test/compose/uptwice_idempotent/docker-compose.yml (hunk 2 above)
Comment (apollo13) [reply test/compose/uptwice_idempotent/docker-compose.yml:8]: Good point.

**Comment by Luap99** [comment]
> @mheon Is there any chance that the tests somehow don't use the locally built podman? The "mac address is set" failure is due to a bug in compose: [docker/compose#12439](https://github.com/docker/compose/pull/12439) but the other failure in compose I cannot explain (works locally _scratches head_)

Tests will almost certainly not use the new build podman. The packaged podman binary in $PATH is even deleted on our CI setup AFAICT so it should be impossible.

What does works locally mean? Are you actually running the tests via the test suite
`./test/compose/test-compose [test-name]`?

**Comment by apollo13** [comment]
> What does works locally mean? Are you actually running the tests via the test suite
./test/compose/test-compose [test-name]?

Yes, let me fix up all the remaining issues and then I'll double check.

**Comment by apollo13** [comment]
Note that the error in the compose tests:
```
[+0132s] ok 42 uptwice_idempotent - up
[+0132s] not ok 43 no container recreation in compose up (#24950)
[+0132s] #  expected:  Container uptwice_idempotent-app-1  Running
[+0132s] #    actual:  Container uptwice_idempotent-app-1  Created
[+0132s]  Container uptwice_idempotent-app-1  Starting
[+0132s]  Container uptwice_idempotent-app-1  Started
[+0133s] ok 44 uptwice_idempotent - down
```

Suggests that step 42 did not actually "up" the container in the first place.

**Comment by Luap99** [comment]
> Also do you think that the kube tests are flaky and unrelated? 

Yes these are flakes.

I take a look at the compose test issue.


Also if you repush please change the commit message to
```
Set network ID if available during container inspect

Fixes #24910
```
This makes github properly link the issue and close it on merge. The number is meaningless in the title for a reader anyway.

**Comment by Luap99** [comment]
I see the PR was merged which is good, we can wait a bit. Podman 5.4-rc1 is planned in two weeks and given that such a ID field change is not a minor bug fix we should ensure it is merged for rc1.

I guess if nothing else I would be fine to temporarily skip/disable the mac test until we get a new docker-compose with the fix released.

**Comment by apollo13** [comment]
@Luap99 Updated to the new compose release. The currently failing check is unrelated from what I can tell and the compose tests did already pass. So I guess this is good to go?

**Comment by apollo13** [comment]
Hi @mheon & @Luap99, I am sorry to be annoying but I'd really love to get this into 5.4-rc1 and want to ensure that it doesn't fall through the cracks. Can you just shortly confirm that you will merge this in time and whether there is anything else you need me to do to get this in? Thank you very much!

**Comment by Luap99** [comment]
@apollo13 The machine tests issues are unrelated to your changes, they are known to be flaky so I re-run them and hope this makes them pass.

**Review by Luap99 — APPROVED** [review]
LGTM
@mheon PTAL

**Comment by mheon** [comment]
Both machine jobs failed again, restarted again. Might be a real issue though. @apollo13 if this doesn't merge in a few hours, I recommend rebasing on latest main.

**Comment by mheon** [comment]
Quay flaking a lot, restarted

**Comment by apollo13** [comment]
Mhm, still apple mac failures? I have no idea what is happening here and no mac to even try :/

**Comment by apollo13** [comment]
Thank you Matt and Paul for your reviews and helping to get this over the finish line.
