### PR TITLE
compat: map internal states to Docker equivalents in LibpodToContainer

### LINKED ISSUE #28359: Listing containers with docker compat API can leaks `stopped` state
### Issue Description

The list container `/containers/json` endpoint (docker compat) can return `stopped` as the container state. This is a transient state, but this breaks the interface, which can cause libraries that depend on the docker API to break. I caught this while using bollard with a container that is getting restarted

```
Error: ReadState(Oci(Error { context: Some("failed to list containers"), source: Connection(JsonDataError { message: "unknown variant `stopped`, expected one of ``, `created`, `running`, `paused`, `restarting`, `exited`, `removing`, `dead` at line 1 column 707", column: 707 }) }))
```

### Steps to reproduce the issue

I don't have a reproduction since this state is temporary, however there is a clear bug in the tests, that are accepting `stopped` as a valid state.

https://github.com/containers/podman/blob/main/test/apiv2/20-containers.at#L70

The issue seems to be here in the `LibpodToContainer` function used by `ListContainers`

https://github.com/containers/podman/blob/07aa62f82f4429d58304a8c72cecb38bf874e90e/pkg/api/handlers/compat/containers.go#L310

while `GetContainer` returns the result of `LibpodToContainerJSON` that correctly re-maps the stopped state to exited here 

https://github.com/containers/podman/blob/07aa62f82f4429d58304a8c72cecb38bf874e90e/pkg/api/handlers/compat/containers.go#L486

there is no such conversion for `ListContainers` allowing the state to pass straight through

### Describe the results you received

`/containers/json` leaks `state: "stopped"`

### Describe the results you expected

states should match what's returned by `/containers/{name}/json` and not leak internal implementation dependent states

### podman info output

```yaml
Client:
  APIVersion: 5.8.0
  BuildOrigin: brew
  Built: 1770910886
  BuiltTime: Thu Feb 12 12:41:26 2026
  GitCommit: ""
  GoVersion: go1.26.0
  Os: darwin
  OsArch: darwin/arm64
  Version: 5.8.0
host:
  arch: arm64
  buildahVersion: 1.43.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.13-2.fc43.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: '
  cpuUtilization:
    idlePercent: 98.75
    systemPercent: 0.63
    userPercent: 0.62
  cpus: 5
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: coreos
    version: "43"
  emulatedArchitectures:
  - linux/386
  - linux/amd64
  - linux/arm64be
  eventLogger: journald
  freeLocks: 2042
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.18.5-200.fc43.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 34787328
  memTotal: 2038493184
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    defaultNetwork: podman
    dns:
      package: aardvark-dns-1.17.0-1.fc43.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.17.0
    package: netavark-1.17.2-1.fc43.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.17.2
  ociRuntime:
    name: crun
    package: crun-1.26-1.fc43.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.26
      commit: 3241e671f92c33b0c003cd7de319e4f32add6231
      rundir: /run/user/501/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20260117.g81c97f6-1.fc43.aarch64
    version: |
      pasta 0^20260117.g81c97f6-1.fc43.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: unix:///run/user/501/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.3.1-3.fc43.aarch64
    version: |-
      slirp4netns version 1.3.1
      commit: e5e368c4f5db6ae75c2fce786e31eef9da6bf236
      libslirp: 4.9.1
      SLIRP_CONFIG_VERSION_MAX: 6
      libseccomp: 2.6.0
  swapFree: 0
  swapTotal: 0
  uptime: 285h 50m 32.00s (Approximately 11.88 days)
  variant: v8
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 3
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 10232139776
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 15
  runRoot: /run/user/501/containers
  transientStore: false
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 5.8.0
  BuildOrigin: 'Copr: packit/containers-podman-28079'
  Built: 1770854400
  BuiltTime: Wed Feb 11 21:00:00 2026
  GitCommit: 37bfeded1f9df9577b138cbad90a5da95fdf9b89
  GoVersion: go1.25.7 X:nodwarf5
  Os: linux
  OsArch: linux/arm64
  Version: 5.8.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by crawfordxx**
## Description

The Docker compat `/containers/json` endpoint was leaking podman-internal container states (`stopped`, `stopping`) that are not part of the Docker API state vocabulary. Docker clients that strictly validate the `State` field against the documented set (`created`, `running`, `paused`, `restarting`, `exited`, `removing`, `dead`) would fail with deserialization errors like:

```
unknown variant `stopped`, expected one of ``, `created`, `running`, `paused`,
`restarting`, `exited`, `removing`, `dead`
```

`LibpodToContainerJSON` (used by `GET /containers/{name}/json`) already performs the correct mapping:
- `stopped` → `exited`
- `stopping` → `running`

This PR applies the same remapping in `LibpodToContainer` (used by `GET /containers/json`) so both endpoints behave consistently.

A test assertion is added to the compat list endpoint test to verify that a stopped container is reported with `State="exited"`.

Fixes #28359

### CODE REVIEW

File: pkg/api/handlers/compat/containers.go [hunk 1]
```diff
@@ -313,6 +313,14 @@ func LibpodToContainer(l *libpod.Container, sz bool) (*handlers.Container, error
...
 		stateStr = define.ContainerStateConfigured.String()
 	}
+	// "stopped" and "stopping" are podman-internal states with no Docker equivalent.
+	// Map them to the nearest Docker state so the compat API never leaks internal states.
+	if state == define.ContainerStateStopped {
+		stateStr = define.ContainerStateExited.String()
+	}
+	if state == define.ContainerStateStopping {
+		stateStr = define.ContainerStateRunning.String()
+	}
```
Comment (Honny1) [inline pkg/api/handlers/compat/containers.go]: I would use `switch`.

**Review by Honny1 — APPROVED** [review]
LGTM, I have just style code comment.

**Comment by TomSweeneyRedHat** [comment]
LGTM
I won't merge in case you want to convert to the switch, which I would prefer too.

**Review by Honny1 — COMMENTED** [review]
LGTM! Once you fix the DCO and squash commits, we can merge.

**Comment by crawfordxx** [comment]
Updated: squashed to a single commit and converted the if-chain to a switch statement as suggested. The switch cleanly handles all three state remappings (created→configured, stopped→exited, stopping→running) in one place. DCO sign-off is included.

**Review by Honny1 — APPROVED** [review]

**Comment by Theaxiom** [comment]
Thank you! I just found this bug a few hours ago and it was crashing bollard!
