### PR TITLE
Fix: Rootless Podman-in-Podman on WSL

### LINKED ISSUE #27411: Bug: Rootless Podman-in-Podman on WSL
### Issue Description

Running rootless Podman inside a rootless Podman container on WSL fails because the default user's `SUB_UID` and `SUB_GID` ranges inside the machine are too short.

### Steps to reproduce the issue

1. On Windows, start Podman:

   ```powershell
   podman machine start
   ```
2. Open a Debian container without root:

   ```powershell
   podman run -it debian bash
   ```
3. Inside the container:

   ```bash
   useradd -m testuser
   apt-get install -y podman
   su - testuser
   podman images
   ```

### Describe the results you received

Running `podman images` as the non-root user fails with:

```bash
ERRO[0000] running `/usr/bin/newuidmap 52258 0 1000 1 1 100000 65536`: newuidmap: write to uid_map failed: Operation not permitted 
Error: cannot set up namespace using "/usr/bin/newuidmap": exit status 1
```

Running with `sudo` works:

```bash
sudo podman images
```

## Cause

The default user inside the Podman machine has limited sub-ID ranges:

```bash
$ cat /etc/subuid /etc/subgid
user:100000:65536
user:100000:65536
```

Meanwhile, inside the container, the ID mappings are:

```bash
$ cat /proc/self/uid_map
         0       1000          1
         1     100000      65536
```

Same for `/proc/self/gid_map`.

This is because the user  `SUB_UID`/`SUB_GID` ranges (100000–165535) are smaller than the mapped range (100000:), nested rootless Podman cannot allocate sufficient IDs, causing namespace setup to fail.

## Workaround

Manually increasing the user’s sub-ID range inside the Podman machine by editing `/etc/subuids` and `/etc/subgids`, then restarting the machine, solves the issue.

### podman info output

```yaml
N/A
```

### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

WSL on Windows

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dvorst**
Fixes: #27411

## pkg/machine/wsl/declares.go
Adjust SUB_UID and SUB_GID ranges to support running rootless Podman inside a rootless run Podman container.

By default, a new user is assigned the following sub-ID ranges:
  SUB_UID_MIN=100000, SUB_GID_MIN=100000, SUB_UID_COUNT=65536, SUB_GID_COUNT=65536
This means the user’s sub-UID and sub-GID ranges are 100000–165535.

When the container is run rootless by the user in WSL, ID mappings occur as follows:
- Container ID 0 (root) maps to user ID 1000 on the host (user in WSL).
- Container IDs 1–65536 map to IDs 100000–165535 on host (the subid range previously mentioned).

If a new user is created inside this container (to build containers for example), it will attempt to use the default sub-ID range (100000–165535). However, this exceeds the container’s available ID mapping, since only IDs up to 65536 are mapped, causing rootless PinP to fail.

To enable container-in-container builds, the sub-ID ranges for the user in WSL must be large enough to provide at least 65536 usable IDs. A minimum SUB_UID_COUNT and SUB_GID_COUNT of 165536 is thus required, but 200000 is used here to provide additional margin.

#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
Fixed Rootless Podman-in-Podman on WSL, by sufficiently increasing the SUB_GID and SUB_UID range of the user on WSL (#27411).
```

### CODE REVIEW

**Comment by baude** [comment]
i think you should add a test to the PR that validates your change; otherwise, if we change how the image is built or someone makes an unknowing chnage, you could easily have a regression.   wdyt ?

also thanks for your diligence on this this PR.

otherwise, this LGTM

**Comment by dvorst** [comment]
Sure, I can add a test. Had a quick look at the tests dir but it isn't clear to me at first sight where I should place it. Can you point me in the right direction? Maybe there are already tests that I can use to start from

**Comment by TomSweeneyRedHat** [comment]
@dvorst thanks for the PR!
If @baude says differently, go with his thinking.  Otherwise the machine tests live in  `./pkg/machine/e2e`

**Comment by TomSweeneyRedHat** [comment]
And code LGTM too

File: pkg/machine/wsl/declares.go [hunk 1]
```diff
@@ -38,6 +38,8 @@ ln -fs /dev/null /etc/systemd/system/console-getty.service
 ln -fs /dev/null /etc/systemd/system/systemd-oomd.socket
 mkdir -p /etc/systemd/system/systemd-sysusers.service.d/
 echo CREATE_MAIL_SPOOL=no >> /etc/default/useradd
+sed -ir 's/SUB_UID_COUNT.*/SUB_UID_COUNT 200000/' /etc/login.defs
+sed -ir 's/SUB_GID_COUNT.*/SUB_GID_COUNT 200000/' /etc/login.defs
```
Comment (Luap99) [inline pkg/machine/wsl/declares.go]: This is fixing this differently on WSL than compared to our providers which only set a range for the one user we create by writing subuid/subgid directly. So I would rather match that.
https://github.com/containers/podman/blob/69b397af49acd595b8d5b36971988d49951c043a/pkg/machine/ignition/ignition.go#L284-L289

In particular they use a range of `1000000` uids not `200000` which I think is important to keep the behaviours consistent between providers

File: pkg/machine/e2e/init_test.go [hunk 2]
```diff
@@ -124,6 +125,62 @@ var _ = Describe("podman machine init", func() {
...
+		 * Container ID 0 (root) maps to user ID on the host.
+		 * Container IDs 1–65536 map to IDs 100000–165535 on host (range previously mentioned).
+		 *
+		 * If a new user is created inside the container and used to build containers with
+		 * (rootless PinP), it will attempt to use the default sub-ID range (100000–165535). Given
+		 * the mapping, this means that the host must at least have a SUB_UID_COUNT and
+		 * SUB_GID_COUNT of 165536. Since 165536 would only allow rootless PinP for the first
+		 * user (with ID 1000), the check is run against a count of 166536 (=165536+1000) as to
+		 * provide additional margin.
+		 */
```
Comment (Luap99) [inline pkg/machine/e2e/init_test.go]: rootless PinP is not really relevant to this test at all, it could just be called check subuid/gid ranges.

But in any case adding new test cases is quite slow as they all require new Vm to be created. As such I would strongly advise to not a a new It() block for something simple as this. Instead just add a new ssh command at the end of `simple init with username` for example

File: pkg/machine/e2e/init_test.go [hunk 3]
```diff
@@ -124,6 +125,62 @@ var _ = Describe("podman machine init", func() {
...
+		ssh := new(sshMachine)
+		sshSession, err := mb.setName(name).setCmd(ssh.withSSHCommand([]string{"cat", "/etc/subuid", "/etc/subgid"})).run()
+		Expect(err).ToNot(HaveOccurred())
+		if sshSession.ExitCode() != 0 {
+			Fail(fmt.Sprintf("SSH session failed with exit code %d\nstdout:\n%s\nstderr:\n%s",
+				sshSession.ExitCode(),
+				sshSession.outputToString(),
+				sshSession.errorToString(),
+			))
+		}
```
Comment (Luap99) [inline pkg/machine/e2e/init_test.go]: That doesn't add anything so please don't do that.

File: pkg/machine/e2e/init_test.go [hunk 4]
```diff
@@ -124,6 +125,62 @@ var _ = Describe("podman machine init", func() {
...
+		// should exist for it, so 2 lines in total.
+		Expect(len(counts)).To(BeNumerically(">=", 2), "expected at least 1 user/line in /etc/subuid and /etc/subgid each, got %d", len(counts))
+
+		// Verify the count. At the moment only 1 user is created in the machine. If multiple users
+		// are ever created, this will check that all users have a sufficient subid range.
+		for _, count := range counts {
+			n, err := strconv.Atoi(count[1])
+			Expect(err).ToNot(HaveOccurred())
+			Expect(n).To(BeNumerically(">=", count_min), "expected last number %d to be >= %d", n, count_min)
+		}
```
Comment (Luap99) [inline pkg/machine/e2e/init_test.go]: There should be no reason to harden that for multiple user we only ever create one and should not create multiple. If that ever were to be the case we can adapt tests later. For now I don't see the value in complicating the check for this.

**Review by Luap99 — COMMENTED** [review]
You need to rebase your PR to pass the search failure in the integration tests (not related to your code).

And please squash both commits into one, we prefer code and test in the same commits.

File: pkg/machine/wsl/declares.go (hunk 1 above)
Comment (dvorst) [reply pkg/machine/wsl/declares.go]: Thanks for the intermediate review.

I'll change the count to `1 000 000` instead of `200 000`. I’m quite busy with work at the moment, but I might have time to work on this around Christmas.

I'll also modify `/etc/subuid` and `/etc/subgid` directly, right after the adduser command is run, to align it with the `ignition.go` script.

My initial approach was based on the fact that adduser doesn’t provide an option to configure the sub-ID ranges, so these had to be set in a different way. Changing the defaults seemed to be a cleaner approach than modifying subuid/subgid directly, since that will give issues if adduser/useradd behavior ever changes (though i don't think that will ever change without backwards compatibility).

File: pkg/machine/e2e/init_test.go (hunk 2 above)
Comment (dvorst) [reply pkg/machine/e2e/init_test.go]: The end goal is to fix rootles PinP, but i'll make a batch script as you suggest instead.

File: pkg/machine/e2e/init_test.go (hunk 3 above)
Comment (dvorst) [reply pkg/machine/e2e/init_test.go]: I was hoping I could create the test without having to set everything up locally. The test is failing at this point so i was hoping to print out more information to the log, without success though. It seems I have to set up everything locally, which will require resetting the podman machine as what I could tell, which is a bit cumbersome for me as I need it for work. Hopefully I have time for this around Christmas. I was not planning on leaving this in once all tests succeed

File: pkg/machine/e2e/init_test.go (hunk 4 above)
Comment (dvorst) [reply pkg/machine/e2e/init_test.go]: There is a count for the user and group id, so there will be a for loop anyway. The comment is meant to be informative for if a second user is ever created, and that this test will basically be run for all users.

**Comment by dvorst** [comment]
[machine-hyperv podman windows rootless host](https://github.com/containers/podman/pull/27412/checks?check_run_id=58708680311)
Is not failing on a test, but on creating a SSH connection with the machine, while the code used to do so does run with success for other tests. Interestingly the SSH error occurs before a message is shown that the machine is successfully started. Can it be that the test case fails due to a racing condition of starting the machine and ssh'ing into it to run the test?

ssh error: `  Error: ssh: handshake failed: read tcp 127.0.0.1:50878->127.0.0.1:50870: wsarecv: An existing connection was forcibly closed by the remote host.`
what i would expect to see before this error: `Machine "ff60d78bf620" started successfully`

**Comment by dvorst** [comment]
[int remote fedora-42 root host](https://github.com/containers/podman/pull/27412/checks?check_run_id=58708680353)
The command `CMD ["echo", "hello"]` somehow does not result in `hello` ending up in the logs, though it does for fedora-43. I therefore suspect this is not a result from the changes of this PR

**Comment by Luap99** [comment]
@dvorst Sorry this got lost over the holidays, can you rebase this again to make sure this still passes on main. CI is a bit flaky if there are failures I will retrigger them and we should be good to merge I think

**Comment by dvorst** [comment]
No worries, I rebased it

**Comment by dvorst** [comment]
The three that have failed are different from the ones that previously failed, so I'm pretty confident they are unrelated to the proposed changes. Could you restart those again?

**Review by Luap99 — APPROVED** [review]
LGTM
