### PR TITLE
In SQLite state, use defaults for empty-string checks

### LINKED ISSUE #24738: Error: database graph driver "" does not match our graph driver "overlay": database configuration mismatch
### Issue Description

Since November, a server has been logging this error when attempting an auto-update cronjob:

> podman[895410]: Error: database graph driver "" does not match our graph driver "overlay": database configuration mismatch

During this time period my distro upgraded from 5.2.1 to 5.2.2.

I am now running 5.2.5.

### Steps to reproduce the issue

Since November, a server has been logging an error when attempting an auto-update cronjob.

Steps to reproduce the issue
1. Use podman with auto-update cronjob

### Describe the results you received

> podman[895410]: Error: database graph driver "" does not match our graph driver "overlay": database configuration mismatch

During this time period my distro upgraded from 5.2.1 to 5.2.2.

I am now running 5.2.5.

### Describe the results you expected

I expected the cronjob to succeed

### podman info output

```yaml
$ podman info
host:
  arch: arm64
  buildahVersion: 1.37.5
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2.1.12-3_arm64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: unknown'
  cpuUtilization:
    idlePercent: 99.64
    systemPercent: 0.17
    userPercent: 0.19
  cpus: 8
  databaseBackend: sqlite
  distribution:
    codename: trixie
    distribution: debian
    version: unknown
  eventLogger: journald
  freeLocks: 2036
  hostname: hubble
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.11.0
  linkmode: dynamic
  logDriver: journald
  memFree: 3758686208
  memTotal: 16489906176
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns_1.12.2-1_arm64
      path: /usr/lib/podman/aardvark-dns
      version: aardvark-dns 1.12.2
    package: netavark_1.12.1-3_arm64
    path: /usr/lib/podman/netavark
    version: netavark 1.12.1
  ociRuntime:
    name: runc
    package: runc_1.1.15+ds1-1_arm64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.15+ds1
      commit: 1.1.15+ds1-1
      spec: 1.2.0
      go: go1.23.2
      libseccomp: 2.5.5
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt_0.0~git20241030.ee7d0b6-1_arm64
    version: |
      pasta 0.0~git20241030.ee7d0b6-1
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.1-1+b2_arm64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.8.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.5
  swapFree: 0
  swapTotal: 0
  uptime: 1477h 41m 29.00s (Approximately 61.54 days)
  variant: v8
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/joel/.config/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 7
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/joel/.local/share/containers/storage
  graphRootAllocated: 111714734080
  graphRootUsed: 105411731456
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 7
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/joel/.local/share/containers/storage/volumes
version:
  APIVersion: 5.2.5
  Built: 1729890366
  BuiltTime: Sat Oct 26 07:36:06 2024
  GitCommit: ""
  GoVersion: go1.23.2
  Os: linux
  OsArch: linux/arm64
  Version: 5.2.5
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Debian testing

### Additional information

I upgraded to the latest version 5.3.1. The error is now:

```
Dec 03 09:26:41 hubble systemd[1]: Starting podman-restart.service - Podman Start All Containers With Restart Policy Set To Always...
Dec 03 09:26:41 hubble podman[959599]: time="2024-12-03T09:26:41+10:30" level=info msg="/usr/bin/podman filtering at log level info"
Dec 03 09:26:41 hubble podman[959599]: time="2024-12-03T09:26:41+10:30" level=info msg="Using sqlite as database backend"
Dec 03 09:26:41 hubble podman[959599]: Error: database graph driver "" does not match our graph driver "overlay": database configuration mismatch
Dec 03 09:26:41 hubble systemd[1]: podman-restart.service: Main process exited, code=exited, status=125/n/a
```

The top hit on DDG for this issue is https://github.com/containers/podman/issues/7396, which was closed.

### PR DESCRIPTION
**Pull request by mheon**
As part of our database init, we perform a check of the current values for a few fields (graph driver, graph root, static dir, and a few more) to validate that Libpod is being started with a sane & sensible config, and the user's containers can actually be expected to work. Basically, we take the current runtime config and compare against values cached in the database from the first time Podman was run.

We've had some issues with this logic before this year around symlink resolution, but this is a new edge case. Somehow, the database is being loaded with the empty string for some fields (at least graph driver) which is causing comparisons to fail because we will never compare against "" for those fields - we insert the default value instead, assuming we have one.

Having a value of "" in the database largely invalidates the check so arguably we could just drop it, but what BoltDB did - and what SQLite does after this patch - is to use the default value for comparison instead of "". This should still catch some edge cases, and shouldn't be too harmful.

What this does not do is identify or solve the reason that we are seeing the empty string in the database at all. From my read on the logic, it must mean that the graph driver is explicitly set to "" in the c/storage config at the time Podman is first run and I'm not precisely sure how that happens.

Fixes #24738

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug where Podman would fail to start due to a database configuration mismatch when certain fields were configured to the empty string.
```

### CODE REVIEW

**Comment by mheon** [comment]
Adding no new tests as we don't do database config tests like this in CI

**Comment by Luap99** [comment]
The way to trigger this is create an empty storage.conf without driver then run podman to init db (you must reset the storage before of course)
```
$ podman ps
WARN[0000] The storage 'driver' option should be set in /home/pholzing/.config/containers/storage.conf. A driver was picked automatically. 
WARN[0000] The storage 'driver' option should be set in /home/pholzing/.config/containers/storage.conf. A driver was picked automatically. 
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES

# Follow the advice and add the driver, i.e. overlay
$ vi ~/.config/containers/storage.conf
$ cat ~/.config/containers/storage.conf
[storage]
driver="overlay"
$ podman ps
Error: database graph driver "" does not match our graph driver "overlay": database configuration mismatch
```

I think we can must test this somehow in CI. 

I really must say they for every bug I dislike the validation logic more and more

**Comment by baude** [comment]
could we just use the podman cli and the `--storage-driver`  string? I think if you did an e2e test you could skip the step to prepopulate the image cache and then add the storage driver option as a one-off ?

**Comment by Luap99** [comment]
`--storage-driver ""` is ignored AFAIk so it must come from the config file I think. But that should not be much more difficult as we can use the `CONTAINERS_STORAGE_CONF` env to set it for a single test

File: test/e2e/info_test.go [hunk 1]
```diff
@@ -291,4 +291,52 @@ var _ = Describe("Podman Info", func() {
 		Expect(info).ToNot(ExitCleanly())
 		podmanTest.StartRemoteService() // Start service again so teardown runs clean
 	})
+
+	It("podman startup: ensure database checks for graph driver accommodate empty string", func() {
```
Comment (Luap99) [inline test/e2e/info_test.go:295]: Actually this will never work because all the e2e test pass all option via cli such as --storage-driver so it not matter what we set in the config.

I think this might have to be in test/system and you pass your own --root/-runroot/--tmpdir and just leave the driver to the storage .conf

File: test/system/005-info.bats [hunk 2]
```diff
@@ -305,4 +305,23 @@ EOF
...
 }
 
+@test "podman - empty string defaults for certain values" {
+    skip_if_remote "Test uses nonstandard paths for c/storage directories"
+
+    # We just want this to be empty - so graph driver will be set to the empty string
+    touch $PODMAN_TMPDIR/storage.conf
+
+    # Force all custom directories so we don't pick up an existing database
+    CONTAINERS_STORAGE_CONF=$PODMAN_TMPDIR/storage.conf run_podman --root $PODMAN_TMPDIR/root --runroot $PODMAN_TMPDIR/runroot --tmpdir $PODMAN_TMPDIR/tmpdir info
```
Comment (Luap99) [inline test/system/005-info.bats:315]: use `safe_opts=$(podman_isolation_opts ${PODMAN_TMPDIR})`

and then just add $safe_opts as args here and below, see the test above as example.

Second storage prints an warning for the unset driver so you need to tell the test to ignore it
```
run_podman 0+w $safe_opts info
    require_warning "The storage 'driver' option should be set" \
                    "c/storage should warn on empty storage driver"
```

**Comment by mheon** [comment]
F40 rootless is using VFS by default. That seems odd.

**Comment by Luap99** [comment]
> F40 rootless is using VFS by default. That seems odd.

Because we should test all storage drivers we actively "support" so vfs for fedora -1 and overlayfs for 41/rawhide AFAIK to have good coverage.

That said we are using a custom --root here and custom storage conf so I don't follow with the env around it matters at all...

**Comment by mheon** [comment]
That was my thinking - everything that would configure storage driver is being overridden... Maybe I should do a `system reset` first to make sure there isn't a database at the location?

**Comment by Luap99** [comment]
system reset would not help, podman_isolation_opts is just an echo an the tmpdir is unique for each test so there really should not be any podman content prior to running the first command. 

The test environment creates /etc/containers/storage.conf with vfs so maybe the empty storage conf file does not actual overwrite it somehow despite c/storage complaining about it?

**Comment by mheon** [comment]
@nalind `CONTAINERS_STORAGE_CONF` should fully override the default `/etc/containers/storage.conf` and not layer on top of it, right?

**Comment by nalind** [comment]
It should, yes.  Experimentally verified using the a sample file from the storage library's repository and `env CONTAINERS_STORAGE_CONF=./types/storage_test.conf strace -f podman info` as root.

File: test/system/005-info.bats [hunk 3]
```diff
@@ -305,4 +305,27 @@ EOF
...
+
+    # Force all custom directories so we don't pick up an existing database
+    CONTAINERS_STORAGE_CONF=$PODMAN_TMPDIR/storage.conf run_podman 0+w $safe_opts info
+    require_warning "The storage 'driver' option should be set" \
+       	            "c/storage should warn on empty storage driver"
+
+    # Now add a valid graph driver to storage.conf
+    cat >$PODMAN_TMPDIR/storage.conf <<EOF
+[storage]
+driver="overlay"
```
Comment (Luap99) [inline test/system/005-info.bats:324]:
```suggestion
driver="$(podman_storage_driver)"
```

That should use the right storage driver and turn into vfs on fedora -1, I am somewhat sure this is the *right* fix for the test instead of ignoring the vfs error

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by mheon** [comment]
@containers/podman-maintainers PTAL and merge

**Comment by mheon** [comment]
@containers/podman-maintainers Anyone care to merge?
