### PR TITLE
test/e2e: fix default signal exit code test

### LINKED ISSUE #24213: e2e: ExitWithError() will determine an incorrect exit code and result in an error.
### Issue Description

It seems that the changes made by #22661 might not be completely accurate. 
When I ran the command in test environment, it returned an error: "Command exited with status 134 (expected 2)". 
Could this test result be different depending on the environment? 

I believe this code is causing the error output. 
- Expect(session).To(ExitWithError(2, "SIGFPE: floating-point exception"))

### Steps to reproduce the issue

  1. Run run_signal_test.go
```
# FOCUS_FILE="run_signal_test.go" QUADLET_BINARY=/usr/libexec/podman/quadlet PATH=${PATH}:$(pwd)/hack PODMAN_BINARY=$(which podman) PODMAN_REMOTE_BINARY=$(which podman-remote) CGROUP_MANAGER=$(podman info --format {{.Host.CgroupManager}}) NETWORK_BACKEND=$(podman info --format {{.Host.NetworkBackend}}) OCI_RUNTIME=$(podman info --format {{.Host.OCIRuntime.Name}}) STORAGE_FS=overlay ROOTLESS_STORAGE_FS=overlay make localintegration`
```

  2.The results will be output, so I will check them.
```
...snip...
  SIGQUIT: quit
  PC=0x561b8b47ba41 m=10 sigcode=0

  goroutine 0 gp=0xc0004d6380 m=10 mp=0xc0004a4808 [idle]:
  runtime.futex(0xc0004a4948, 0x80, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/runtime/sys_linux_amd64.s:557 +0x21 fp=0x7f7a99fffa78 sp=0x7f7a99fffa70 pc=0x561b8b47ba41
  runtime.futexsleep(0x7f7a99fffaf0?, 0x8b410750?, 0x561b8b410750?)
        /usr/lib/golang/src/runtime/os_linux.go:69 +0x30 fp=0x7f7a99fffac8 sp=0x7f7a99fffa78 pc=0x561b8b43adb0
  runtime.notesleep(0xc0004a4948)
        /usr/lib/golang/src/runtime/lock_futex.go:170 +0x87 fp=0x7f7a99fffb00 sp=0x7f7a99fffac8 pc=0x561b8b4108e7
  runtime.mPark(...)
        /usr/lib/golang/src/runtime/proc.go:1761
  runtime.stopm()
        /usr/lib/golang/src/runtime/proc.go:2782 +0x8c fp=0x7f7a99fffb30 sp=0x7f7a99fffb00 pc=0x561b8b445aec
  runtime.findRunnable()
        /usr/lib/golang/src/runtime/proc.go:3512 +0xd5f fp=0x7f7a99fffca8 sp=0x7f7a99fffb30 pc=0x561b8b44765f
  runtime.schedule()
        /usr/lib/golang/src/runtime/proc.go:3868 +0xb1 fp=0x7f7a99fffce0 sp=0x7f7a99fffca8 pc=0x561b8b448731
  runtime.goexit0(0xc0002d96c0?)
        /usr/lib/golang/src/runtime/proc.go:4181 +0x18 fp=0x7f7a99fffcf8 sp=0x7f7a99fffce0 pc=0x561b8b4495d8
  runtime.mcall()
        /usr/lib/golang/src/runtime/asm_amd64.s:458 +0x50 fp=0x7f7a99fffd10 sp=0x7f7a99fffcf8 pc=0x561b8b477bf0
  rax    0xca
  rbx    0x0
  rcx    0x561b8b47ba43
  rdx    0x0
  rdi    0xc0004a4948
  rsi    0x80
  rbp    0x7f7a99fffab8
  rsp    0x7f7a99fffa70
  r8     0x0
  r9     0x0
  r10    0x0
  r11    0x286
  r12    0x15
  r13    0x1
  r14    0xc0004d6380
  r15    0x1
  rip    0x561b8b47ba41
  rflags 0x286
  cs     0x33
  fs     0x0
  gs     0x0
  test2
  [FAILED] Command exited with status 134 (expected 2)
  In [It] at: /root/podman-upstream/test/e2e/run_signal_test.go:115 @ 10/07/24 04:51:30.368

  Full Stack Trace
    github.com/containers/podman/v5/test/e2e.init.func98.2()
        /root/podman-upstream/test/e2e/run_signal_test.go:115 +0x428
  < Exit [It] signals are not forwarded to container with sig-proxy false - /root/podman-upstream/test/e2e/run_signal_test.go:93 @ 10/07/24 04:51:30.368 (2.071s)
  > Enter [AfterEach] TOP-LEVEL - /root/podman-upstream/test/e2e/common_test.go:122 @ 10/07/24 04:51:30.368
  Running: /usr/bin/podman --storage-opt overlay.imagestore=/tmp/podman-e2e-2134768457/imagecachedir --root /tmp/podman-e2e-2134768457/subtest-2968878380/root --runroot /tmp/podman-e2e-2134768457/subtest-2968878380/runroot --runtime crun --conmon /usr/bin/conmon --network-config-dir /etc/containers/networks --network-backend netavark --cgroup-manager systemd --tmpdir /tmp/podman-e2e-2134768457/subtest-2968878380 --events-backend file --db-backend sqlite --storage-driver overlay stop --all -t 0
  3f7501ec1389c8da7224ec95ec58cc4ad10c8334bfd082c7f7f271975f5c0d16
  Running: /usr/bin/podman --storage-opt overlay.imagestore=/tmp/podman-e2e-2134768457/imagecachedir --root /tmp/podman-e2e-2134768457/subtest-2968878380/root --runroot /tmp/podman-e2e-2134768457/subtest-2968878380/runroot --runtime crun --conmon /usr/bin/conmon --network-config-dir /etc/containers/networks --network-backend netavark --cgroup-manager systemd --tmpdir /tmp/podman-e2e-2134768457/subtest-2968878380 --events-backend file --db-backend sqlite --storage-driver overlay pod rm -fa -t 0
  Running: /usr/bin/podman --storage-opt overlay.imagestore=/tmp/podman-e2e-2134768457/imagecachedir --root /tmp/podman-e2e-2134768457/subtest-2968878380/root --runroot /tmp/podman-e2e-2134768457/subtest-2968878380/runroot --runtime crun --conmon /usr/bin/conmon --network-config-dir /etc/containers/networks --network-backend netavark --cgroup-manager systemd --tmpdir /tmp/podman-e2e-2134768457/subtest-2968878380 --events-backend file --db-backend sqlite --storage-driver overlay rm -fa -t 0
  3f7501ec1389c8da7224ec95ec58cc4ad10c8334bfd082c7f7f271975f5c0d16
  < Exit [AfterEach] TOP-LEVEL - /root/podman-upstream/test/e2e/common_test.go:122 @ 10/07/24 04:51:30.514 (146ms)
  << Timeline
------------------------------
...snip...

Summarizing 1 Failure:
  [FAIL] Podman run with --sig-proxy [It] signals are not forwarded to container with sig-proxy false
  /root/podman-upstream/test/e2e/run_signal_test.go:115
```

### Describe the results you received

This test will output an error.
"Command exited with status %d (expected %d)", matcher.ExitCode, matcher.ExpectedExitCode

### Describe the results you expected

The test will end successfully if the exit status is 134 (128+6 SIGABRT).

### podman info output

# podman info
```
host:
  arch: amd64
  buildahVersion: 1.37.3
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.12-2.fc40.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 85.37
    systemPercent: 4.03
    userPercent: 10.6
  cpus: 2
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: workstation
    version: "40" 
  eventLogger: journald
  freeLocks: 2039
  hostname: fedora
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.10.11-200.fc40.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 719458304
  memTotal: 4098375680
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.12.2-2.fc40.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.12.2
    package: netavark-1.12.2-1.fc40.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.12.2
  ociRuntime:
    name: crun
    package: crun-1.17-1.fc40.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.17
      commit: 000fa0d4eeed8938301f3bcf8206405315bc1017
      rundir: /run/user/0/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240906.g6b38f07-1.fc40.x86_64
    version: |
      pasta 0^20240906.g6b38f07-1.fc40.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: false
    path: /run/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: "" 
    package: "" 
    version: "" 
  swapFree: 3194482688
  swapTotal: 4097830912
  uptime: 1h 6m 16.00s (Approximately 0.04 days)
  variant: "" 
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /usr/lib/containers/storage
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 20397948928
  graphRootUsed: 5803491328
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false" 
    Supports d_type: "true" 
    Supports shifting: "true" 
    Supports volatile: "true" 
    Using metacopy: "true" 
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 5.2.3
  Built: 1727136000
  BuiltTime: Mon Sep 23 20:00:00 2024
  GitCommit: "" 
  GoVersion: go1.22.7
  Os: linux
  OsArch: linux/amd64
  Version: 5.2.3
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by Luap99**
By default golang programs exit 2 on special exit signals that can be cought and produce a stack trace. However this is behavior that can be modfied via GOTRACEBACK=crash[1], in that case it does not exit(2) but rather sends itself SIGABRT to the parent sees the signal exit and out test sees that es exit code 134, 128 + 6 (SIGABRT), like most shells do.

As it turns out GOTRACEBACK=crash is the default mode on all fedora and RHEL rpm builds as they patch the build with a special "rpm_crashtraceback" go build tag.

While that change is old and existing for a very long time it was never caught until commit 5e240ab1f5, which switched the old ExitWithError() check that accepted anything > 0, to just accept 2. And as CI only test upstream builds that are build without rpm_crashtraceback we did not catch in CI either. Only once a user actually used distro build against the source e2e test it failed.

I like to highlight that running distro builds against upstream e2e tests is not something we really support or plan to support but given this is a easy fix I decided to just fix it here as any user with GOTRACEBACK=crash set would face the same issue.

While I touch this test remove the unnecessary RestoreArtifact() call which is not needed at all as we do nothing with the image and just slows the test down for now reason.

[1] https://pkg.go.dev/runtime#section-sourcefiles

Fixes #24213

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

File: test/e2e/run_signal_test.go [hunk 1]
```diff
@@ -112,7 +108,8 @@ var _ = Describe("Podman run with --sig-proxy", func() {
 		Expect(killSession).Should(ExitCleanly())
 
 		session.WaitWithDefaultTimeout()
-		Expect(session).To(ExitWithError(2, "SIGFPE: floating-point exception"))
+		errorMsg := "SIGFPE: floating-point exception"
+		Expect(session).To(Or(ExitWithError(2, errorMsg), ExitWithError(134, errorMsg)))
```
Comment (Luap99) [inline test/e2e/run_signal_test.go:112]: @edsantiago Not sure if you like this like that? It is certainly more duplication that I wanted but the alternative is to switch ExitWithError() to accept a list of exit codes which seems much more complicated.

Comment (Luap99) [reply test/e2e/run_signal_test.go:115]: Done, the alternative is to patch ExitWithError() to accept `any` as first arg and then use it to pass an int like we do now or an array of int's to allow several exit codes. But this is much more complicated and for a single test overkill.
