### PR TITLE
getContainerNetworkInfo: lock netNsCtr before sync

### LINKED ISSUE #10090: Deadlocks using the gitlab runner docker executor on the docker-compatible socket API
/kind bug

**Description**

Trying to use gitlab-ci with the docker executor and the podman 3.x docker-compatible API socket very frequently yields to deadlock-like situations. These manifest in the Gitlab CI pipelines hanging for a while, and in addition, `podman ps`  and other CLI commands hanging indefinitely. When this happens, only a `systemctl restart podman` helps.

The setup uses podman 3.1.0 from the `container-tools` module stream of CentOS8. The Gitlab runner itself is run as a podman container, using the latest ` docker.io/gitlab/gitlab-runner:alpine` image, with `/run/docker.sock` mounted inside the runner. The socket is also mounted into a traefik container on the same machine.

As a side note, intermediate containers created by the CI are stopped, but not cleaned up.

Looking at the podman journal, I repeatedly see some messages like this:
```
Request Failed(Not Found): no container with name or ID \"...\" found: no such container"
Request Failed(Internal Server Error): can only kill running containers. ... is in state stopped: container state improper"
Request Failed(Internal Server Error): can only attach to created or running containers - currently in state stopped: container state improper"
Request Failed(Internal Server Error): container ... does not exist in database: no such container
```
not sure if these are really related or not.

**Output of `podman version`:**
```
Version:      3.1.0-dev
API Version:  3.1.0-dev
Go Version:   go1.16.1
Built:        Fri Mar 26 19:32:03 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**
```
host:
  arch: amd64
  buildahVersion: 1.19.8
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.27-1.module_el8.5.0+733+9bb5dffa.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: dc08a6edf03cc2dadfe803eac14b896b44cc4721'
  cpus: 16
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: *****
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-301.1.el8.x86_64
  linkmode: dynamic
  memFree: 52090458112
  memTotal: 67455647744
  ociRuntime:
    name: crun
    package: crun-0.18-1.module_el8.5.0+733+9bb5dffa.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.18
      commit: 808420efe3dc2b44d6db9f1a3fac8361dde42a95
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 20000530432
  swapTotal: 20000530432
  uptime: 89h 5m 49.06s (Approximately 3.71 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 22
    paused: 0
    running: 22
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 26
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.1.0-dev
  Built: 1616783523
  BuiltTime: Fri Mar 26 19:32:03 2021
  GitCommit: ""
  GoVersion: go1.16.1
  OsArch: linux/amd64
  Version: 3.1.0-dev

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
```
podman-3.1.0-0.13.module_el8.5.0+733+9bb5dffa.x86_64
```

### PR DESCRIPTION
**Pull request by Luap99**
`syncContainer()` requires the container to be locked, otherwise we can
end up with undefined behavior.

[NO TESTS NEEDED]

### CODE REVIEW

File: libpod/networking_linux.go [hunk 1]
```diff
@@ -888,6 +888,8 @@ func (c *Container) getContainerNetworkInfo() (*define.InspectNetworkSettings, e
 		if err != nil {
 			return nil, err
 		}
+		netNsCtr.lock.Lock()
```
Comment (vrothberg) [inline libpod/networking_linux.go:891]: Can you drop a comment above that mentions the issue number?  I find such breadcrumbs extremely helpful and time saving.

**Review by vrothberg — COMMENTED** [review]
Other than the nit, LGTM

Thanks!

File: libpod/networking_linux.go (hunk 1 above)
Comment (Luap99) [reply libpod/networking_linux.go:893]: done

**Comment by Luap99** [comment]
It does not fix #10090 according to @thmo on IRC

**Comment by mheon** [comment]
LGTM, even if this isn't a fix for the issue - this could cause no end of trouble elsewhere at some point.

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but one of the TTY tests is failing.  I can't imagine it's due to this change, but it doesn't look flakey either....

**Comment by vrothberg** [comment]
> Changes LGTM, but one of the TTY tests is failing. I can't imagine it's due to this change, but it doesn't look flakey either....

It's a very frequent flake in CI at the moment ( see https://github.com/containers/podman/issues/10710).
