### PR TITLE
report healthcheck start errors

### LINKED ISSUE #25034: Healthcheck always shows "starting" for quadlet service
### Issue Description

I'm trying to setup some containers using quadlet and podman but the healthchecks are stuck at "starting" and never execute. It is basically the same thing that was discussed here https://github.com/containers/podman/discussions/19381, but I definitely have systemd on my system. I am doing this on a NixOS machine.
```json
               "Health": {
                    "Status": "starting",
                    "FailingStreak": 0,
                    "Log": null
               },
```
It does work when I manually run `podman healthcheck run id` and it works if I run the same container just from my user with `podman run`. So it definitely is an issue with systemd.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Setup a NixOS
2. Create a Quadlet service for podman that includes a HealthCmd
3. Watch the status of that container never change

### Describe the results you received

The container never reaches a `healthy` state.

### Describe the results you expected

A container with a healthy state.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.38.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /nix/store/fpm49w5pv1fnnnczbwngnr7pfnqbmp7f-podman-helper-binary-wrapper/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 81.31
    systemPercent: 2.84
    userPercent: 15.84
  cpus: 8
  databaseBackend: sqlite
  distribution:
    codename: warbler
    distribution: nixos
    version: "25.05"
  eventLogger: journald
  freeLocks: 2013
  hostname: hati
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.6.64
  linkmode: dynamic
  logDriver: journald
  memFree: 25469820928
  memTotal: 33221525504
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: Unknown
      path: /nix/store/szxc93qlzmy33si8nvwnl33qn4ypf8qd-podman-5.3.1/libexec/podman/aardvark-dns
      version: aardvark-dns 1.13.1
    package: Unknown
    path: /nix/store/szxc93qlzmy33si8nvwnl33qn4ypf8qd-podman-5.3.1/libexec/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: Unknown
    path: /nix/store/fpm49w5pv1fnnnczbwngnr7pfnqbmp7f-podman-helper-binary-wrapper/bin/crun
    version: |-
      crun version 1.18.2
      commit: 1.18.2
      rundir: /run/user/0/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: /nix/store/szxc93qlzmy33si8nvwnl33qn4ypf8qd-podman-5.3.1/libexec/podman/pasta
    package: Unknown
    version: |
      pasta 2024_10_30.ee7d0b6
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 11h 30m 29.00s (Approximately 0.46 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 15
    paused: 0
    running: 4
    stopped: 11
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 66795933696
  graphRootUsed: 53149421568
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 6
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 5.3.1
  Built: 315532800
  BuiltTime: Tue Jan  1 01:00:00 1980
  GitCommit: ""
  GoVersion: go1.23.3
  Os: linux
  OsArch: linux/amd64
  Version: 5.3.1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

NixOS on a Proxmox VM

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Luap99**
When starting a container consider healthcheck errors fatal. That way user know when systemd-run failed to setup the timer to run the healthcheck and we don't get into a state where the container is running but not the healthcheck.

This also fixes the broken error reporting from the systemd-run exec, if the binary could not be run the output was just empty leaving the users with no idea what failed.

Fixes #25034

#### Does this PR introduce a user-facing change?

```release-note
If podman fails to setup the healthcheck on with systemd-run on container start proper errors are now being reported.
```

### CODE REVIEW

File: libpod/healthcheck.go [hunk 1]
```diff
@@ -256,27 +260,27 @@ func (c *Container) incrementStartupHCSuccessCounter(ctx context.Context) {
...
-		// SIGTERM and we exit.
-		// Special case, via SIGTERM we exit(1) which means systemd logs a failure in the unit.
-		// We do not want this as the unit will be leaked on failure states unless "reset-failed"
-		// is called. Fundamentally this is expected so switch it to exit 0.
-		// NOTE: This is only safe while being called from "podman healthcheck run" which we know
-		// is the case here as we should not alter the exit code of another process that just
-		// happened to call this.
-		shutdown.SetExitCode(0)
-		c.recreateHealthCheckTimer(ctx, false, true)
+		return nil
```
Comment (baude) [inline libpod/healthcheck.go:263]: return err or at least a warning ?

Comment (Luap99) [reply libpod/healthcheck.go:263]: yeah this should return err

**Comment by mheon** [comment]
LGTM
