### PR TITLE
Reject `--cpus` above host CPU count on podman machine init and set

### LINKED ISSUE #28322: `podman machine set --cpus` accepts invalid CPU counts -> VM fails to start (krunkit abort / vfkit exit 1)
### Issue Description

The `podman machine set --cpus` accepts very large values (e.g. `200`) without validating them against the host. After that, `podman machine start` fails with low-level errors instead of a clear validation message. By contrast, podman machine set `--memory` rejects values above total system memory with an explicit error.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman machine init test2`
2. `podman machine set --cpus 200 test2` -> no error
3. `podman machine start test2` -> fails

### Describe the results you received

`libkrun`: `Error: krunkit was terminated by signal: abort trap`
`vfkit`: `Error: vfkit exited unexpectedly with exit code 1`

### Describe the results you expected

Reject `--cpus` values that exceed a sensible upper bound (e.g. logical CPU count on the host, and a documented cap (libkrun max: 16 cpus), with a message similar in spirit to memory validation.

Something like this but for `--cpus`:
```
podman machine set --memory 9999999999 test
Error: requested amount of memory (9999999999 MB) greater than total system memory (36864 MB)
```

### podman info output

```yaml
Client:
  APIVersion: 5.8.1
  BuildOrigin: pkginstaller
  Built: 1773258905
  BuiltTime: Wed Mar 11 20:55:05 2026
  GitCommit: c6077f645788743258a1a749f8005b4fb3cbe533
  GoVersion: go1.26.1
  Os: darwin
  OsArch: darwin/arm64
  Version: 5.8.1
host:
  arch: arm64
  buildahVersion: 1.43.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.13-2.fc43.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: '
  cpuUtilization:
    idlePercent: 96.36
    systemPercent: 2.12
    userPercent: 1.52
  cpus: 6
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: coreos
    version: "43"
  emulatedArchitectures:
  - linux/386
  - linux/amd64
  - linux/arm64be
  eventLogger: journald
  freeLocks: 2048
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.18.10-200.fc43.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 1427214336
  memTotal: 2037989376
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    defaultNetwork: podman
    dns:
      package: aardvark-dns-1.17.0-1.fc43.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.17.0
    package: netavark-1.17.2-1.fc43.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.17.2
  ociRuntime:
    name: crun
    package: crun-1.25.1-1.fc43.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.25.1
      commit: 156ae065d4a322d149c7307034f98d9637aa92a2
      rundir: /run/user/501/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20260120.g386b5f5-1.fc43.aarch64
    version: |
      pasta 0^20260120.g386b5f5-1.fc43.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: unix:///run/user/501/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.3.1-3.fc43.aarch64
    version: |-
      slirp4netns version 1.3.1
      commit: e5e368c4f5db6ae75c2fce786e31eef9da6bf236
      libslirp: 4.9.1
      SLIRP_CONFIG_VERSION_MAX: 6
      libseccomp: 2.6.0
  swapFree: 0
  swapTotal: 0
  uptime: 0h 0m 24.00s
  variant: v8
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 4210409472
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/501/containers
  transientStore: false
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 5.8.1
  BuildOrigin: 'Copr: packit/containers-podman-28250'
  Built: 1773187200
  BuiltTime: Wed Mar 11 01:00:00 2026
  GitCommit: c6077f645788743258a1a749f8005b4fb3cbe533
  GoVersion: go1.25.7 X:nodwarf5
  Os: linux
  OsArch: linux/arm64
  Version: 5.8.1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by Honny1**
Fixes: https://github.com/containers/podman/issues/28322

#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [ ] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [ ] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [ ] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [ ] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [ ] All commits pass `make validatepr` (format/lint checks)
- [ ] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
The `podman machine init` and `podman machine set` now reject `--cpus` values larger than the number of logical CPUs on the host, with a clear error instead of accepting an invalid value.
```

### CODE REVIEW

**Comment by Honny1** [comment]
I know that libkrun has its own CPU limit, which could be smaller than the host machine's CPU count. I am not sure how to check that without hardcoding the value. Is there a dynamic way to check this so our code doesn't break if libkrun changes in the future? Alternatively, we can provide a better error message to users and call it a day. 

WDYT? @jakecorrenti

**Comment by jakecorrenti** [comment]
> I know that libkrun has its own CPU limit, which could be smaller than the host machine's CPU count. I am not sure how to check that without hardcoding the value. Is there a dynamic way to check this so our code doesn't break if libkrun changes in the future? Alternatively, we can provide a better error message to users and call it a day.
> 
> WDYT? @jakecorrenti

Functionally speaking, if the user were to provide more vCPUs than the limit of 16 it won't fail, the CPU count will stay at 16.

We set `CONFIG_NR_CPUS` in the guest kernel so there's currently no way to determine the max CPU count unless you're already in the guest AFAIK. However, we might be able to change this so that the kernel cmdline in libkrun uses `nr_cpus=n` and have an API that can get the value we set for `n`.

WDYT of this approach @slp? I know this would only work for variants where we don't set `CONFIG_CMDLINE_OVERRIDE=y` in the kernel, but this is only an issue on TEE kernels. Additionally, this wouldn't apply in scenarios where the user provides their own kernel, but that could just be noted in the API documentation.

**Comment by slp** [comment]
> > I know that libkrun has its own CPU limit, which could be smaller than the host machine's CPU count. I am not sure how to check that without hardcoding the value. Is there a dynamic way to check this so our code doesn't break if libkrun changes in the future? Alternatively, we can provide a better error message to users and call it a day.
> > WDYT? @jakecorrenti
> 
> Functionally speaking, if the user were to provide more vCPUs than the limit of 16 it won't fail, the CPU count will stay at 16.

This limitation is in `libkrunfw` (the library bundling the custom kernel), not in `libkrun` itself. Since podman-machine doesn't make use of `libkrunfw`, it's not affected by this limitation. It can set up as many vCPUs as the hypervisor allows to configure.

File: cmd/podman/machine/init.go [hunk 1]
```diff
@@ -257,6 +258,11 @@ func initMachine(cmd *cobra.Command, args []string) error {
 			return err
 		}
 	}
+	if cmd.Flags().Changed("cpus") {
```
Comment (Luap99) [inline cmd/podman/machine/init.go]: That seem wrong in the sense that users do not have to set the cpus via cli, we have a containers.conf option as well. In other words we should always validate the value.

Comment (Honny1) [reply cmd/podman/machine/init.go]: Okay, good catch. I did the same thing I did for memory, so the memory check is also incorrect.

**Comment by Honny1** [comment]
@jakecorrenti @slp Thanks for the explanation.

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
restarting what appears to be flakey tests

**Comment by TomSweeneyRedHat** [comment]
Happy Green Tests
/lgtm
