### PR TITLE
Fix Docker compat `/wait` hanging for next-exit condition

### LINKED ISSUE #28514: Docker hangs waiting for podman daemon to tell it to die
### Issue Description

This issue is kinda subtle and I don't fully understand it. I ran into it on an Amazon Linux 2023 server where I use podman daemon and docker client from Nixpkgs. Podman works normally for the login user, but for a system user that I created, even in interactive sessions I start via `sudo -u some-user -i`, `docker run hello-world` hangs.

There aren't any interesting configuration differences I could find. Using `docker run --rm` avoids the hang.

I understand vaguely that it has to do with running things as a system user who doesn't have normal systemd-logind treatment or something.

### Steps to reproduce the issue

I asked Claude Code to write me a little reproducer script, and I've tested it in a fresh Fedora 43 VM via Lima. Please just use it in your own Fedora 43 VM; that's the easiest way. I've attached it here. The reproducer script does need root. Please run it anyway (it's short and easy to read).

If you want to play interactively:

1. Set up a Fedora 43 VM.
2. Run the reproducer script once (as root).
3. Log in as `podman-hang-test` with `sudo -u podman-hang-test -i`
4. Run some `docker run` commands, with and without `--rm`, like `XDG_RUNTIME_DIR=/run/user/$(id -u podman-hang-test) DOCKER_HOST=unix:///run/user/$(id -u podman-hang-test)/podman/podman.sock docker run --rm docker.io/hello-world`
5. note that Docker is hung :)

on Docker 25 this is more painful because the signal proxy stops `^C` from working and you have to kill it from outside. On Docker 29 it's not so bad; just hit `^C` three times.

[reproduce.sh](https://github.com/user-attachments/files/26733045/reproduce.sh)

### Describe the results you received

The thing hangs! You should see output like mine:

```
[patcal04@lima-podman-repro podman-compat-wait-hang]$ sudo bash reproduce.sh 
=== Podman compat API hang reproducer ===
kernel: 6.17.1-300.fc43.aarch64

Installing podman + docker CLI...
Updating and loading repositories:
Repositories loaded.
Package "podman-5:5.6.2-1.fc43.aarch64" is already installed.

Nothing to do.
File "/etc/yum.repos.d/docker-ce.repo" already exists and configures repositories with IDs "docker-ce-stable docker-ce-stable-source docker-ce-test docker-ce-test-source". Add "--overwrite" to overwrite.
Updating and loading repositories:
Repositories loaded.
Package "docker-ce-cli-1:29.4.0-1.fc43.aarch64" is already installed.

Nothing to do.
podman: podman version 5.6.2
docker: Docker version 29.4.0, build 9d7ad9f

--- Setting up system user with rootless podman ---
useradd: user 'podman-hang-test' already exists
Podman socket: /run/user/501/podman/podman.sock

--- docker run (hangs if bug is present) ---
If this hangs after printing hello-world output, the bug is confirmed.
Will be killed after 30s.


Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm64v8)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

reproduce.sh: line 75:  5079 Killed                     timeout --kill-after=5 30 sudo -u "$TESTUSER" XDG_RUNTIME_DIR="$RUN_DIR" DOCKER_HOST="unix://$SOCK" docker run docker.io/hello-world

Cleanup: sudo bash reproduce.sh --cleanup
[patcal04@lima-podman-repro podman-compat-wait-hang]$ 

```

### Describe the results you expected

I should get my terminal back when the container dies

### podman info output

```yaml
# on the server where I originally hit this
host:
  arch: amd64
  buildahVersion: 1.43.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /nix/store/9xyrsx6d0bd1dwxbcibq7mcm10w5lkh4-podman-helper-binary-wrapper/bin/conmon
    version: 'conmon version 2.2.1, commit: c8cc2c4db27531bd4e084ce7857f73cd21ee639d'
  cpuUtilization:
    idlePercent: 82.6
    systemPercent: 4.44
    userPercent: 12.96
  cpus: 2
  databaseBackend: sqlite
  distribution:
    distribution: amzn
    version: "2023"
  eventLogger: journald
  freeLocks: 2035
  hostname: ip-10-191-208-93.us-west-2.compute.internal
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 992
      size: 1
    - container_id: 1
      host_id: 1999934464
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 993
      size: 1
    - container_id: 1
      host_id: 1999934464
      size: 65536
  kernel: 6.1.163-186.299.amzn2023.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 396636160
  memTotal: 4026089472
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    defaultNetwork: podman
    dns:
      package: Unknown
      path: /nix/store/bmw82lk8h792b128zvbcaff5mnwrk6m6-podman-5.8.1/libexec/podman/aardvark-dns
      version: aardvark-dns 1.17.1
    package: Unknown
    path: /nix/store/bmw82lk8h792b128zvbcaff5mnwrk6m6-podman-5.8.1/libexec/podman/netavark
    version: netavark 1.17.2
  ociRuntime:
    name: crun
    package: Unknown
    path: /nix/store/9xyrsx6d0bd1dwxbcibq7mcm10w5lkh4-podman-helper-binary-wrapper/bin/crun
    version: |-
      crun version 1.27
      commit: a718a92cc9a94955a5a550b6fdec1378c247ec50
      rundir: /run/user/993/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +YAJL
  os: linux
  pasta:
    executable: /nix/store/bmw82lk8h792b128zvbcaff5mnwrk6m6-podman-5.8.1/libexec/podman/pasta
    package: Unknown
    version: |
      pasta 2025_09_19.623dbf6
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/993/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8520462336
  swapTotal: 8589930496
  uptime: 3h 8m 20.00s (Approximately 0.12 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  docker.io:
    Blocked: false
    Insecure: false
    Location: mirror.gcr.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: docker.io
    PullFromMirror: ""
  search:
  - 802594744377.dkr.ecr.us-west-2.amazonaws.com
store:
  configFile: /home/gitlab-runner/.config/containers/storage.conf
  containerStore:
    number: 13
    paused: 0
    running: 0
    stopped: 13
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/gitlab-runner/.local/share/containers/storage
  graphRootAllocated: 34280026112
  graphRootUsed: 20709519360
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/993/containers
  transientStore: false
  volumePath: /home/gitlab-runner/.local/share/containers/storage/volumes
version:
  APIVersion: 5.8.1
  Built: 315532800
  BuiltTime: Tue Jan  1 00:00:00 1980
  GitCommit: ""
  GoVersion: go1.26.1
  Os: linux
  OsArch: linux/amd64
  Version: 5.8.1

============================

# my little reproducer vm
host:
  arch: arm64
  buildahVersion: 1.41.5
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.13-2.fc43.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: '
  cpuUtilization:
    idlePercent: 99.51
    systemPercent: 0.23
    userPercent: 0.27
  cpus: 4
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: cloud
    version: "43"
  emulatedArchitectures:
  - linux/386
  - linux/amd64
  - linux/arm64be
  - linux/loong64
  - linux/mips
  - linux/mips64
  - linux/ppc
  - linux/ppc64
  - linux/ppc64le
  - linux/riscv32
  - linux/riscv64
  - linux/s390x
  eventLogger: journald
  freeLocks: 2040
  hostname: lima-podman-repro
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 2000000000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 2000000000
      size: 65536
  kernel: 6.17.1-300.fc43.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 1955094528
  memTotal: 4079656960
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.16.0-1.fc43.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.16.0
    package: netavark-1.16.1-1.fc43.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.16.1
  ociRuntime:
    name: crun
    package: crun-1.24-1.fc43.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.24
      commit: 54693209039e5e04cbe3c8b1cd5fe2301219f0a1
      rundir: /run/user/501/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/sbin/pasta
    package: passt-0^20250919.g623dbf6-1.fc43.aarch64
    version: |
      pasta 0^20250919.g623dbf6-1.fc43.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/local/sbin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.3.3
      commit: 944fa94090e1fd1312232cbc0e6b43585553d824
      libslirp: 4.9.1
      SLIRP_CONFIG_VERSION_MAX: 6
      libseccomp: 2.5.3
  swapFree: 4078956544
  swapTotal: 4078956544
  uptime: 0h 43m 48.00s
  variant: v8
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /home/podman-hang-test/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 0
    stopped: 4
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/podman-hang-test/.local/share/containers/storage
  graphRootAllocated: 105171103744
  graphRootUsed: 1212952576
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/501/containers
  transientStore: false
  volumePath: /home/podman-hang-test/.local/share/containers/storage/volumes
version:
  APIVersion: 5.6.2
  BuildOrigin: Fedora Project
  Built: 1759190400
  BuiltTime: Mon Sep 29 17:00:00 2025
  GitCommit: 9dd5e1ed33830612bc200d7a13db00af6ab865a4
  GoVersion: go1.25.1 X:nodwarf5
  Os: linux
  OsArch: linux/arm64
  Version: 5.6.2
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

I'm sorry I couldn't give a better bug report than this, but it's at least reproducible via that script on Fedora 43. Feel free to tweak it as desired. Please lmk what you discover

### PR DESCRIPTION
**Pull request by Honny1**
The issue is caused because the container exists before podman setups wainting for the event. 

Fixes: https://github.com/containers/podman/issues/28514

#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [ ] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [ ] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [ ] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [ ] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [ ] All commits pass `make validatepr` (format/lint checks)
- [ ] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug where Docker clients would hang indefinitely on `docker run` when using the Podman Docker-compatible API
```

### CODE REVIEW

File: pkg/api/handlers/utils/containers.go [hunk 1]
```diff
@@ -233,29 +243,44 @@ func waitRemoved(ctrWait containerWaitFn) (int32, error) {
...
 		return -1, err
 	}
+	logrus.Debugf("waitNextExit: currentState=%s, newState=%s", currentState, newState)
+	if currentState != newState && (newState == define.ContainerStateExited || newState == define.ContainerStateStopped) {
+		exitCode, _, err := ctr.ExitCode()
+		if err != nil {
+			return -1, err
+		}
+		return exitCode, nil
+	}
```
Comment (Luap99) [inline pkg/api/handlers/utils/containers.go:279]: I don't really agree with that kind of logic, state checks without locks are basically broken by design.
Getting the state then checking unlocked means the container can be in a totally different state again, in particular the ctr.ExitCode() has to lock again and resync state so you can get a totally different result from the time State() was called.

**Review by Luap99 — COMMENTED** [review]
overall here I am not sure this really fixes the problem. You claim the container exits before the event can be observed, yet your logic is no different, the container can exit before you do the first ctr.State().

I don't know what you debugged but if they call wait after start this problem can always happen theoretically. I don't know what exactly the docker daemon and cli do to avoid this?
On the podman side we call first start and only then wait but not for "next exit" just exited so it does not matter if it already exited.

I guess your patch might change the timings enough to no longer cause this on your system but I do not think this is really any better. If we want to improve the timings just a bit could we not just get time.Now() first thing in the handler and then use the since option on the event to post process any events that happens since the api endpoint was called and we actually start processing events.

**Comment by Luap99** [comment]
https://github.com/docker/cli/blob/dea3ebaa87f4a1979e24e82c1b062da5ff5c481c/cli/command/container/run.go#L203-L206

so wait is called before start which seems ok if they use next-exit. But then because the wait call from the client gets the 200 OK right away from us and then continues to start while waiting for the actual wait payload which can come much later.

So now I see why your patch works because you get the state pre the 200 ok status code. But knowing this then I think we can improve this instead by making sure the event subscriber is registered before we send the status code and then it should no longer miss the exit event as docker only starts once it has the 200 status code response

**Comment by Luap99** [comment]
(oh and would definitely be good to get this context in the commit message)

**Comment by Honny1** [comment]
That is a much cleaner approach. I have made the changes.

**Review by Luap99 — APPROVED** [review]
LGTM

**Review by baude — APPROVED** [review]
LGTM
