### PR TITLE
fix: skip execution of probes when initialDelaySeconds is not elapsed

### LINKED ISSUE #27678: initialDelaySeconds is not respected and probes are executed
There is a small inconsistency with the `initialDelaySeconds`. As defined in [Kubernetes docs]( https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes), it is mentioned that the probes will be executed after the  `initialDelaySeconds` is elapsed. It is even more clear in the [examples of the documentation]( https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/?utm_source=chatgpt.com#define-a-liveness-command) where it is mentioned that: `The initialDelaySeconds field tells the kubelet that it should wait 5 seconds before performing the first probe.` 

[Podman executes the probe immediately]( https://github.com/containers/podman/pull/20789) and ignores the results until the time defined in `initialDelaySeconds` is elapsed. 

So I am guessing it is by design, but was it on purpose to have this discrepancy from the specs of Kubernetes? 
Would it be of interest to fix this discrepency ?

How to test:

Create `health-check-pod.yaml` with

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: healthcheck-test
spec:
  containers:
  - name: tester
    image: docker.io/library/alpine:3.19
    command: ["/bin/sh", "-c"]
    args:
      - |
        ts=$(date +"%Y-%m-%d %H:%M:%S");
        echo "Starting container at $ts" | tee /tmp/healthcheck.log;
        # Keep container alive
        sleep infinity
    livenessProbe:
      exec:
        command:
          - /bin/sh
          - -c
          - |
            ts=$(date +"%Y-%m-%d %H:%M:%S");
            echo "Healthcheck at $ts" | tee -a /tmp/healthcheck.log;
            # Real check: just always succeed
            true
      initialDelaySeconds: 120
      periodSeconds: 5
    volumeMounts:
    - name: tmp
      mountPath: /tmp
  volumes:
  - name: tmp
    emptyDir: {}
```

Then run:

```sh
podman kube play --replace health-check-pod.yaml
```

Observe that healthchecks are performed already from the start, before the 120 seconds have passed:

```sh
podman exec -it healthcheck-test-tester tail -f /tmp/healthcheck.log
Starting container at 2025-12-04 10:18:47
Healthcheck at 2025-12-04 10:18:47
Healthcheck at 2025-12-04 10:18:53
Healthcheck at 2025-12-04 10:18:59

```

Check health state, it should be in "Starting" until initial delay is over:

```sh
podman inspect healthcheck-test-tester --format '{{ json .State.Health }}' | jq
{
  "Status": "starting",
  "FailingStreak": 0,
  "Log": null
}
```

Tested on Podman 5.7.0

<details>
<summary>Podman info</summary>

```
host:
  arch: amd64
  buildahVersion: 1.42.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-1:2.1.13-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: 82de887596ed8ee6d9b2ee85e4f167f307bb569b'
  cpuUtilization:
    idlePercent: 95.2
    systemPercent: 0.76
    userPercent: 4.05
  cpus: 24
  databaseBackend: boltdb
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  freeLocks: 1948
  hostname: desk
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
  kernel: 6.17.9-zen1-1-zen
  linkmode: dynamic
  logDriver: journald
  memFree: 6554480640
  memTotal: 84244418560
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.17.0-1
      path: /usr/lib/podman/aardvark-dns
      version: aardvark-dns 1.17.0
    package: netavark-1.17.0-1
    path: /usr/lib/podman/netavark
    version: netavark 1.17.0
  ociRuntime:
    name: crun
    package: crun-1.25.1-1
    path: /usr/bin/crun
    version: |-
      crun version 1.25.1
      commit: 156ae065d4a322d149c7307034f98d9637aa92a2
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-2025_09_19.623dbf6-1
    version: |
      pasta 2025_09_19.623dbf6
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 11357241344
  swapTotal: 17179865088
  uptime: 191h 25m 44.00s (Approximately 7.96 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  p53:5000:
    Blocked: false
    Insecure: true
    Location: p53:5000
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: p53:5000
    PullFromMirror: ""
store:
  configFile: /home/patrick/.config/containers/storage.conf
  containerStore:
    number: 61
    paused: 0
    running: 2
    stopped: 59
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/patrick/.local/share/containers/storage
  graphRootAllocated: 1964318392320
  graphRootUsed: 1450332147712
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 167
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/patrick/.local/share/containers/storage/volumes
version:
  APIVersion: 5.7.0
  Built: 1763023417
  BuiltTime: Thu Nov 13 09:43:37 2025
  GitCommit: 0370128fc8dcae93533334324ef838db8f8da8cb
  GoVersion: go1.25.4 X:nodwarf5
  Os: linux
  OsArch: linux/amd64
  Version: 5.7.0
```

</details>

### PR DESCRIPTION
**Pull request by anagno**
According to the [Kubernetes docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes) the probes should be executed after the `initialDelaySeconds`. So to be consistent with the kubernetes specs, skip the execution of the probes until the `initialDelaySeconds` is elapsed.

Closes #27678

Executing the same test mentioned in the issue we get:

```
podman exec -it healthcheck-test-tester tail -f /tmp/healthcheck.log
Starting container at 2025-12-07 12:33:23
Healthcheck at 2025-12-07 12:35:27
Healthcheck at 2025-12-07 12:35:33
Healthcheck at 2025-12-07 12:35:39
Healthcheck at 2025-12-07 12:35:45
```

#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed) -- To be honest I do not know how to add a bats script to check that the healthcheck cmd is executed afterwards.
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
The first liveness probe is executed after the `initialDelaySeconds` is elapsed
```

### CODE REVIEW

**Comment by baude** [comment]
is there any possible way you can add a test to re-enforce the behavior ?

**Comment by anagno** [comment]
> is there any possible way you can add a test to re-enforce the behavior ?

I am not certain that there is a "visible effect" using only the podman API.  Already the podman API was not reporting the results of the health check until the initialDelaySeconds was elapsed. Is there a way of retrieving the results of the healtcheck that I have missed ?


If not, then the only alternative is to use some "special" container as it was described in the issue. Is that something that can be implemented using `bats` ?

**Comment by mheon** [comment]
I think it'd be easier to write a healthcheck command that created a sentinel file in the container filesystem (something like `touch /myfile`) and an extremely long initialDelaySeconds to ensure that it never ran. To guarantee it's not racing, you can run `podman healthcheck run` manually on the container to ensure that the HC ran at least once, then do a `podman exec` to make sure the file wasn't created?

File: libpod/healthcheck.go [hunk 1]
```diff
@@ -58,6 +58,24 @@ func (c *Container) runHealthCheck(ctx context.Context, isStartup bool) (define.
...
+		// there is a start-period we need to honor; we add startPeriod to container start time
+		startPeriodTime := c.state.StartedTime.Add(c.HealthCheckConfig().StartPeriod)
+		if timeStart.Before(startPeriodTime) {
+			// we are still in the start period, flip the inStartPeriod bool
+			inStartPeriod = true
+			logrus.Debugf("healthcheck for %s being run in start-period", c.ID())
+		}
+	}
+
+	// If we are playing a kube yaml then let's honor the start period time for
```
Comment (mheon) [inline libpod/healthcheck.go:72]: @Luap99 Feelings on this? I don't think we've done this type of Kube-only behavior change before.

Comment (Luap99) [reply libpod/healthcheck.go:72]: we already have that exact logic https://github.com/containers/podman/commit/f35d1c1c2544e251bfbadb1ec217a88577636319 which is being removed here, so all this does is move the check above the command execution which seem fine.

**Comment by anagno** [comment]
> I think it'd be easier to write a healthcheck command that created a sentinel file in the container filesystem (something like `touch /myfile`) and an extremely long initialDelaySeconds to ensure that it never ran. To guarantee it's not racing, you can run `podman healthcheck run` manually on the container to ensure that the HC ran at least once, then do a `podman exec` to make sure the file wasn't created?

I went with this approach :)

**Comment by anagno** [comment]
And I discover a small mistake... Give some minutes and I will fix it and then make the PR again ready :)

update: fixed

File: test/system/700-play.bats [hunk 2]
```diff
@@ -964,6 +964,63 @@ EOF
     done
 }
 
+# bats test_tags=ci:parallel
+@test "podman kube play healthcheck should wait initialDelaySeconds before executing healthcheck" {
```
Comment (anagno) [inline test/system/700-play.bats:968]: I think it is sufficient to just check that the healtcheck is NOT executed before the time is elapsed, because the test above is testing that the healtcheck is executed

**Comment by anagno** [comment]
And I do not think that my changes are causing the failure ... Is there a way of re-triggering the test ?

File: test/system/700-play.bats [hunk 3]
```diff
@@ -964,6 +964,63 @@ EOF
...
+    run_podman kube play $fname
+    ctrName="$podname-$ctrname"
+
+    # WHEN then healthcheck is executed
+    run_podman 1 healthcheck run $ctrName
+
+    # THEN the execution of the liveness probe should be skipped because initialDelaySeconds has not yet elapsed
+    # We check for some time so, we can make certain that the healtcheck is not later executed
+    local i=1
+    while [[ $i -lt 15 ]]; do
```
Comment (Honny1) [inline test/system/700-play.bats]: Multiple checks for `healthcheck.log` aren't necessary. Since `podman healthcheck run` runs synchronously as an exec session, the command won't exit until the process is complete.

Comment (anagno) [reply test/system/700-play.bats]: I set the `periodSeconds` low, so the healtcheck could be also executed from the pod itself, and make certain that this scenario is also covered. If you prefer, I can then completely remove the loop then.

**Comment by mheon** [comment]
LGTM
@Luap99 PTAL

File: test/system/700-play.bats [hunk 4]
```diff
@@ -964,6 +964,57 @@ EOF
...
+  labels:
+  name: $podname
+spec:
+  containers:
+  - name: $ctrname
+    image: $IMAGE
+    args:
+    - /bin/sh
+    - -c
+    - touch /tmp/healthy && sleep 100
```
Comment (Luap99) [inline test/system/700-play.bats]: we never do anything with touch /tmp/healthy so this could just be dropped

File: test/system/700-play.bats [hunk 5]
```diff
@@ -964,6 +964,57 @@ EOF
...
+      exec:
+        # /tmp/healthy will exist in healthy container
+        command:
+        - /bin/sh
+        - -c
+        - |
+          ts=$(date +"%Y-%m-%d %H:%M:%S");
+          echo "Healthcheck at $ts" | tee -a /tmp/healthcheck.log;
+          # Real check: just always succeed
+          true
```
Comment (Luap99) [inline test/system/700-play.bats]: nit: any reason to overcomplicate this compared to `touch /tmp/healthcheck.log`, we never do anything with the date

File: test/system/700-play.bats [hunk 6]
```diff
@@ -964,6 +964,57 @@ EOF
...
+    run_podman kube play $fname
+    ctrName="$podname-$ctrname"
+
+    # WHEN then healthcheck is executed
+    run_podman 1 healthcheck run $ctrName
+
+    # THEN the execution of the liveness probe should be skipped because initialDelaySeconds has not yet elapsed
+    run_podman 1 exec $ctrName test -e /tmp/healthcheck.log
+
+    run_podman '?' stop -t0 $ctrNam
```
Comment (Luap99) [inline test/system/700-play.bats]: That seems wrong. We should not ignore the exit code of stop but also  the car name is broken, it needs to be ` $ctrName`

**Review by Luap99 — CHANGES_REQUESTED** [review]
one blocker as the test var is wrong

And also please squash the commits into one, we want fix and test as one commit.

File: test/system/700-play.bats (hunk 6 above)
Comment (anagno) [reply test/system/700-play.bats]: Good catch. I fixed the spelling mistake. 

As far as it concerns the ignoring of the exit code, I follow the example of the code above... Maybe it is better if removed completely ?

Comment (anagno) [reply test/system/700-play.bats]: I remove the line completely. I do not think it is necessary ...

Comment (Luap99) [reply test/system/700-play.bats]: The line is needed because sleep does not respond to SIGTERM and kube down tries a graceful stop waiting for 10s by default before we sue SIGKILL. As such this is wasting 10s of test time which quickly adds up so please fix that.

Comment (Luap99) [reply test/system/700-play.bats]: >          ok 449 |700| podman kube play healthcheck should wait initialDelaySeconds before executing healthcheck in 11613ms

You can see the time of each test case in the CI logs
https://api.cirrus-ci.com/v1/artifact/task/6673947841789952/html/sys-podman-rawhide-rootless-host.log.html
