### PR TITLE
Set NetNS mode instead of value

### LINKED ISSUE #8790: Using `hostNetwork` with `play kube` results in error
/kind bug

**Description**

Using `hostNetwork` in pod yaml with `play kube` results in `Error: namespace value host cannot be provided with namespace mode `. 

**Steps to reproduce the issue:**

1. Having the following simple pod.yaml:
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test
  name: test_pod
spec:
  hostNetwork: true
  containers:
    - name: test
      image: docker.io/alpine
      command: ["/bin/sh", "-c"]
      args: ["while true; do date; sleep 2; done"]
```

2. Using `podman play kube pod.yaml`

**Describe the results you received:**

The error: `Error: namespace value host cannot be provided with namespace mode `

**Describe the results you expected:**

I expected the pod to start in host network mode as happened with podman 2.1

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 3.0.0-dev
```
*(same happens on the 2.2.1 release)*

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.0-dev
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.22-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.22, commit: 9c34a8663b85e479e0c083801e89a2b2835228ed'
  cpus: 8
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: lunar
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.9.14-zen1-1-zen
  linkmode: dynamic
  memFree: 1011572736
  memTotal: 33614442496
  ociRuntime:
    name: runc
    package: /usr/bin/runc is owned by runc 1.0.0rc92-1
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc92
      commit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 4h 4m 47.03s (Approximately 0.17 days)
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 10
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1608469638
  BuiltTime: Sun Dec 20 14:07:18 2020
  GitCommit: 5c6b5ef34905f40562b518799c35be8d06694e65-dirty
  GoVersion: go1.15.6
  OsArch: linux/amd64
  Version: 3.0.0-dev
```
*(again: same happens on 2.2.1 release)*

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ pacman -Si podman
Repository      : community
Name            : podman
Version         : 2.2.1-1
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/libpod
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : cni-plugins  conmon  containers-common  device-mapper  iptables  libseccomp  runc  slirp4netns  libsystemd  fuse-overlayfs  libgpgme.so=11-64
Optional Deps   : podman-docker: for Docker-compatible CLI
                  btrfs-progs: support btrfs backend devices
                  catatonit: --init flag support
                  crun: support for unified cgroupsv2
Conflicts With  : None
Replaces        : None
Download Size   : 19,57 MiB
Installed Size  : 79,09 MiB
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : Di 08 Dez 2020 22:48:23 CET
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

happens on two physical machines.

### PR DESCRIPTION
**Pull request by bziemons**
Set NetNS mode instead of value when HostNetwork is true in the pod spec.
Also propagate whether host network namespace should be used for containers.

Closes #8790

### CODE REVIEW

**Comment by mheon** [comment]
LGTM, good catch
/approve

**Comment by zhangguanzhang** [comment]
need add a test for it

**Comment by bziemons** [comment]
> need add a test for it

Will look into testing, but *go* and this project is all new to me so I wont promise anything.

File: pkg/domain/infra/abi/play.go [hunk 1]
```diff
@@ -226,7 +226,7 @@ func (ic *ContainerEngine) playKubePod(ctx context.Context, podName string, podY
 			return nil, err
 		}
 
-		specGen, err := kube.ToSpecGen(ctx, container, container.Image, newImage, volumes, pod.ID(), podName, podInfraID, configMaps, seccompPaths, ctrRestartPolicy)
+		specGen, err := kube.ToSpecGen(ctx, container, container.Image, newImage, volumes, pod.ID(), podName, podInfraID, configMaps, seccompPaths, ctrRestartPolicy, p.NetNS.IsHost())
```
Comment (rhatdan) [inline pkg/domain/infra/abi/play.go:229]: I think it is time that this function take a struct, instead of constantly adding params.  Not for this PR,  But this function is too big.

**Review by rhatdan — APPROVED** [review]

**Comment by rhatdan** [comment]
This PR is failing tests.

**Comment by bziemons** [comment]
True, the test needs to be skipped when running rootless. Will push a fix tomorrow.

**Comment by bziemons** [comment]
On second thought that is not true. `podman run --network host` works rootless and I just tested this change on Fedora 33 successfully as a user. Can somebody help with understanding the test's problem? The error message is very generic and is what I got ***before*** I passed the network *NSMode* of *host* down to the pod's containers.

PS: For reference, this is the kube.yaml I used for testing:
```yaml
# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-2.2.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-12-22T00:08:39Z"
  labels:
    app: distractedjemison
  name: distracted_jemison
spec:
  restartPolicy: Never
  hostNetwork: true
  containers:
  - command:
    - ip
    - a
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: HOSTNAME
      value: xeto
    image: quay.io/libpod/alpine
    name: distractedjemison
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /
status: {}
---
metadata:
  creationTimestamp: null
spec: {}
status:
  loadBalancer: {}
```

**Comment by zhangguanzhang** [comment]
need rebase the commits to one commit

**Comment by zhangguanzhang** [comment]
need rebase all the commits to one commit😁

**Comment by bziemons** [comment]
you mean squash them together? Doesn't make sense to me, but fine.

**Comment by zhangguanzhang** [comment]
They are related, so they need to be in the same commit

**Comment by bziemons** [comment]
So I have found the problem.. It seems to be a limitation on *runc*, since I cannot run
```
$ podman --runtime runc run --pod "$(podman --runtime runc pod create --network host)" --rm -it quay.io/libpod/alpine ip a
```
It results in the same error (but also results in an error when run as root). This works fine on *crun* though, which was the default for me on Fedora 32. I will therefor exclude everything except *crun* for the `HostNetwork` test (as done for other tests).
