### PR TITLE
Don't try to resolve host path if copying from stdin

### LINKED ISSUE #25472: Copying files into a container via stdin with `podman container cp -a - ...` fails on Windows
### Issue Description

When attempting to copy files into a container on Windows via `docker container cp -a - ...` the CLI returns an error: `Error: "/dev/stdin" could not be found on the host: no such file or directory`.

Looking at the code for the cp command, the issue is due to the [`copy.ResolveHostPath(hostPath)` call in cp.go](https://github.com/containers/podman/blob/7f27a6661ae12052516bc27f692b4278b2fe574d/cmd/podman/containers/cp.go#L349). When copying from stdio on Windows, `copy.ResolveHostPath` ends up trying to do an `os.Stat` call for `/dev/stdio` due to that still being the value for `os.Stdin.Name()` on Windows, but this understandably fails and exits out. However, there's no real reason to do the `copy.ResolveHostPath` check when the input is from stdin, as the result isn't actually used during stdin copy. Ideally, the call to `copy.ResolveHostPath` can be conditioned on `!isStdin`.

### Steps to reproduce the issue

Steps to reproduce the issue
1. On Windows, prepare a tar file to copy into a container
2. Create or run a new container
3. Run `Get-Content -Raw input.tar | podman container cp -a - <container>:/tmp` in PowerShell

### Describe the results you received

Command failed with `Error: "/dev/stdin" could not be found on the host: no such file or directory`

### Describe the results you expected

Contents of tar file are copied into the container. This works on MacOS and in Linux, but fails on Windows.

### podman info output

```yaml
Client:
  APIVersion: 5.4.0
  Built: 1739297196
  BuiltTime: Tue Feb 11 10:06:36 2025
  GitCommit: f9f7d48b24b1ca4403f189caaeab1cb8ff4a9aa2
  GoVersion: go1.23.6
  Os: windows
  OsArch: windows/amd64
  Version: 5.4.0
host:
  arch: amd64
  buildahVersion: 1.36.0-dev
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.10-1.20240313132120223048.main.19.gaffab49.fc39.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: '
  cpuUtilization:
    idlePercent: 98.79
    systemPercent: 0.21
    userPercent: 1
  cpus: 16
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: container
    version: "39"
  eventLogger: journald
  freeLocks: 2026
  hostname: CPC-daneg-UN5C5
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.167.4-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 30125613056
  memTotal: 33632358400
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.10.0-1.20240327154432243377.main.24.g9e8db9c.fc39.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.11.0-dev
    package: netavark-1.10.1-1.20240327174936429720.main.58.gd5be5ad.fc39.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.11.0-dev
  ociRuntime:
    name: crun
    package: crun-1.14.4-1.20240327203052128727.main.16.gdcbdf9d.fc39.x86_64
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: fc5c0828a410a954dc1c864f6bba070d1443d297
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240220.g1e6f92b-1.fc39.x86_64
    version: |
      pasta 0^20240220.g1e6f92b-1.fc39.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8589934592
  swapTotal: 8589934592
  uptime: 270h 42m 42.00s (Approximately 11.25 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 1
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 15046189056
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 31
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 5.1.0-dev-8ec821452
  Built: 1711497600
  BuiltTime: Wed Mar 27 00:00:00 2024
  GitCommit: ""
  GoVersion: go1.21.8
  Os: linux
  OsArch: linux/amd64
  Version: 5.1.0-dev-8ec821452
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Running Podman Desktop (1.17.1) on Windows 11

### Additional information

I've tested changing lines 348-352 in cp.go from

```Go
	// Make sure that host path exists.
	hostInfo, err := copy.ResolveHostPath(hostPath)
	if err != nil {
		return fmt.Errorf("%q could not be found on the host: %w", hostPath, err)
	}
```

to

```Go
	hostInfo := &copy.FileInfo{}
	var err error

	if !isStdin {
		// Make sure that host path exists.
		hostInfo, err = copy.ResolveHostPath(hostPath)
		if err != nil {
			return fmt.Errorf("%q could not be found on the host: %w", hostPath, err)
		}
	}
```

and running a local build of the CLI and that resolves the issue.

### PR DESCRIPTION
**Pull request by danegsta**
#### Does this PR introduce a user-facing change?

```release-note
None
```

Resolves #25472

Calling `copy.ResolveHostPath` fails when copying from stdin on Windows as /dev/stdin isn't a real folder. The result of `copy.ResolveHostPath` isn't actually used in the stdin code flow, so an easy fix is to condition the call on whether isStdin is true or false. The only potential behavior change is that, if for some unlikely reason /dev/stdin was missing on Linux or MacOS, the copy command would fail with a different error than it did previously.

### CODE REVIEW

**Comment by danegsta** [comment]
This scenario is [already covered in the existing tests](https://github.com/containers/podman/blob/919247a77cbea0b0d5edab573b287ca481f5b700/test/system/065-cp.bats#L863); there's not really any additional test coverage to add outside of the general ability to run the tests on Windows.

**Comment by l0rd** [comment]
> This scenario is [already covered in the existing tests](https://github.com/containers/podman/blob/919247a77cbea0b0d5edab573b287ca481f5b700/test/system/065-cp.bats#L863); there's not really any additional test coverage to add outside of the general ability to run the tests on Windows.

Right. Machine tests are the ones that are run on Windows, and you can find them in [pkg/machine/e2e/](https://github.com/containers/podman/blob/main/pkg/machine/e2e/README.md)

**Comment by danegsta** [comment]
I'm updating the e2e tests to include copy over stdin.

File: pkg/machine/e2e/config_test.go [hunk 1]
```diff
@@ -44,6 +45,7 @@ type machineSession struct {
 
 type machineTestBuilder struct {
 	cmd          []string
+	stdin        *bytes.Buffer
```
Comment (Luap99) [inline pkg/machine/e2e/config_test.go:48]: This should just be an `io.Reader` so it is not limited to one specific type

File: pkg/machine/e2e/basic_test.go [hunk 2]
```diff
@@ -253,6 +255,62 @@ var _ = Describe("run basic podman commands", func() {
...
+		Expect(createAlp.outputToStringSlice()).To(HaveLen(1))
+
+		containerID := createAlp.outputToStringSlice()[0]
+		cpTar, err := mb.setCmd(bm.withPodmanCommand([]string{"cp", "-", containerID + ":/tmp"})).setStdin(tarBuffer).run()
+		Expect(err).ToNot(HaveOccurred())
+		Expect(cpTar).To(Exit(0))
+
+		exec, err := mb.setCmd(bm.withPodmanCommand([]string{"start", containerID})).run()
+		Expect(err).ToNot(HaveOccurred())
+		Expect(exec).To(Exit(0))
```
Comment (Luap99) [inline pkg/machine/e2e/basic_test.go:312]: This doesn't actually verify anything useful other than the the cp command worked without an error.
start here just executes the ls command which will always work regardless of if the dir exists or not.

you likely want to use `start --attach` here and then please make sure to check the actual command output that is containers your file.

File: pkg/machine/e2e/basic_test.go [hunk 3]
```diff
@@ -253,6 +255,62 @@ var _ = Describe("run basic podman commands", func() {
...
+		i := new(initMachine)
+		session, err := mb.setName(name).setCmd(i.withImage(mb.imagePath).withNow()).run()
+		Expect(err).ToNot(HaveOccurred())
+		Expect(session).To(Exit(0))
+
+		bm := basicMachine{}
+		imgs, err := mb.setCmd(bm.withPodmanCommand([]string{"images", "-q"})).run()
+		Expect(err).ToNot(HaveOccurred())
+		Expect(imgs).To(Exit(0))
+		Expect(imgs.outputToStringSlice()).To(BeEmpty())
```
Comment (Luap99) [inline pkg/machine/e2e/basic_test.go:293]: This can be removed, it does nothing for you test

File: cmd/podman/containers/cp.go [hunk 4]
```diff
@@ -345,10 +345,15 @@ func copyToContainer(container string, containerPath string, hostPath string) er
...
 	}
 
-	// Make sure that host path exists.
-	hostInfo, err := copy.ResolveHostPath(hostPath)
-	if err != nil {
-		return fmt.Errorf("%q could not be found on the host: %w", hostPath, err)
+	hostInfo := &copy.FileInfo{}
+	var err error
+
+	if !isStdin {
```
Comment (Luap99) [inline cmd/podman/containers/cp.go:351]: this could just be an else on the conditional above instead of a new if

**Review by Luap99 — COMMENTED** [review]
Also please squash all commits into one.

File: cmd/podman/containers/cp.go (hunk 4 above)
Comment (danegsta) [reply cmd/podman/containers/cp.go]: Simplified into a single if/else with the stdin check.

File: pkg/machine/e2e/basic_test.go (hunk 2 above)
Comment (danegsta) [reply pkg/machine/e2e/basic_test.go]: I updated the test to do create, copy, start, and then run stat to check the expected directory and file were created.

**Comment by l0rd** [comment]
LGTM, I have retriggered the tests that are failing as failures don't seem related to this PR.

**Comment by Luap99** [comment]
Sorry for just mention this now but can you fix up the commit message.
```
Add e2e test for podman cp using stdio

Fix lint error

Simplify resetting stdin

Update new test case, avoid additional if check

Make test stdio a Reader

Fix lint errors
```

There is no useful information in this so just drop it. And instead `Fixes: #25472` should be added in the commit message not just the PR description, https://github.com/containers/podman/blob/main/CONTRIBUTING.md#describe-your-changes-in-commit-messages

**Comment by mheon** [comment]
LGTM, ready to merge once the commit message is updated.
/approve

**Comment by baude** [comment]
thank you for the submission @danegsta

**Comment by danegsta** [comment]
I've amended the commit message to remove the messages from the individual squashed commits (and added the fixed issue reference).

**Review by Luap99 — APPROVED** [review]
/lgtm
