### PR TITLE
Fixes format inconsistencies with docker for certain history fields

### LINKED ISSUE #17767: `podman history --format '{{.Size}}' IMG` outputs an extra space (compared to docker)
### Issue Description

The commands
```
docker history --format '{{.Size}}' alpine:3.17.2 | head -1
```
and

```
podman history --format '{{.Size}}' alpine:3.17.2 | head -1
```
do not print the same output. (Podman prints an extra space).

### Steps to reproduce the issue

1. `sudo -i`
2. `dnf install -y podman`
3. `dnf install -y moby-engine`
4. `systemctl start docker`
5. `useradd test1`
6. `usermod -aG docker test1`
7. `machinectl shell test1@`
8. `podman pull alpine:3.17.2`
9. `docker pull alpine:3.17.2`
10. `docker history --format '{{.Size}}' alpine:3.17.2 | head -1`
11. `podman history --format '{{.Size}}' alpine:3.17.2 | head -1`

### Describe the results you received

```
$ podman history --format '{{.Size}}' alpine:3.17.2 | head -1
0 B
$ docker history --format '{{.Size}}' alpine:3.17.2 | head -1
0B
$
```

### Describe the results you expected

```
$ podman history --format '{{.Size}}' alpine:3.17.2 | head -1
0B
$ docker history --format '{{.Size}}' alpine:3.17.2 | head -1
0B
$
```

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.6-3.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: '
  cpuUtilization:
    idlePercent: 99.92
    systemPercent: 0.02
    userPercent: 0.06
  cpus: 16
  distribution:
    distribution: fedora
    variant: workstation
    version: "37"
  eventLogger: journald
  hostname: asus
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 50147
      size: 1
    - container_id: 1
      host_id: 37020512
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 50147
      size: 1
    - container_id: 1
      host_id: 37020512
      size: 65536
  kernel: 6.1.15-200.fc37.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 838037504
  memTotal: 7691788288
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.1-1.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/user/50147/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/user/50147/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 7691300864
  swapTotal: 7691300864
  uptime: 11h 10m 1.00s (Approximately 0.46 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/test612/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/test612/.local/share/containers/storage
  graphRootAllocated: 407822663680
  graphRootUsed: 378301325312
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/50147/containers
  transientStore: false
  volumePath: /home/test612/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.2
  Built: 1677669779
  BuiltTime: Wed Mar  1 12:22:59 2023
  GitCommit: ""
  GoVersion: go1.19.6
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.2
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

_No response_

### Additional information

_No response_

### LINKED ISSUE #17768: `podman history --format '{{.CreatedAt}}' IMG` prints different output than docker
### Issue Description

The commands
```
docker history --format '{{.CreatedAt}}' alpine:3.17.2
```
and

```
podman history --format '{{.CreatedAt}}' alpine:3.17.2
```
do not print the same output.

### Steps to reproduce the issue

On a Fedora 37 computer (arch: amd64)

1. `sudo -i`
2. `dnf install -y podman`
3. `dnf install -y moby-engine`
4. `systemctl start docker`
5. `useradd test1`
6. `usermod -aG docker test1`
7. `machinectl shell test1@`
8. `podman pull alpine:3.17.2`
9. `docker pull alpine:3.17.2`
10. `docker history --format '{{.CreatedAt}}' alpine:3.17.2`
11. `podman history --format '{{.CreatedAt}}' alpine:3.17.2`

### Describe the results you received

```
$ docker history --format '{{.CreatedAt}}' alpine:3.17.2
2023-02-11T05:46:42+01:00
2023-02-11T05:46:42+01:00
$ podman history --format '{{.CreatedAt}}' alpine:3.17.2
2023-02-11 04:46:42 +0000 UTC
2023-02-11 04:46:42 +0000 UTC
```

### Describe the results you expected

```
$ docker history --format '{{.CreatedAt}}' alpine:3.17.2
2023-02-11T05:46:42+01:00
2023-02-11T05:46:42+01:00
$ podman history --format '{{.CreatedAt}}' alpine:3.17.2
2023-02-11T05:46:42+01:00
2023-02-11T05:46:42+01:00
```

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.6-3.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: '
  cpuUtilization:
    idlePercent: 99.92
    systemPercent: 0.02
    userPercent: 0.06
  cpus: 16
  distribution:
    distribution: fedora
    variant: workstation
    version: "37"
  eventLogger: journald
  hostname: asus
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 50147
      size: 1
    - container_id: 1
      host_id: 37020512
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 50147
      size: 1
    - container_id: 1
      host_id: 37020512
      size: 65536
  kernel: 6.1.15-200.fc37.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 838037504
  memTotal: 7691788288
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.1-1.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/user/50147/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/user/50147/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 7691300864
  swapTotal: 7691300864
  uptime: 11h 10m 1.00s (Approximately 0.46 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/test612/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/test612/.local/share/containers/storage
  graphRootAllocated: 407822663680
  graphRootUsed: 378301325312
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/50147/containers
  transientStore: false
  volumePath: /home/test612/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.2
  Built: 1677669779
  BuiltTime: Wed Mar  1 12:22:59 2023
  GitCommit: ""
  GoVersion: go1.19.6
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.2
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rbagd**
Closes #17767
Closes #17768

#### Does this PR introduce a user-facing change?

```release-note
Fixes a format inconsistency where podman and docker return slightly different output for `history --format {{.CreatedAt}}` and `history --format {{.Size}}` (#17767, #17768)
```

### CODE REVIEW

**Comment by rbagd** [comment]
CI indicates that one of the `bats` tests failed, namely `podman image history Created`. Besides a regex check which is fixable, it also requires that `podman image list --format {{.CreatedAt}}` would be the same as `podman image history --format {{.CreatedAt}}`. But Docker itself outputs them in a different format, so it's unclear now if this comparison should be dropped to favor docker compatibility... :man_shrugging: 

Assuming PR is merged,

```
$ docker image list --format {{.CreatedAt}} busybox | head -n 1
2023-03-17 02:35:43 +0100 CET
$ docker image history --format {{.CreatedAt}} busybox | head -n 1
2023-03-17T02:35:43+01:00

$ podman image list --format {{.CreatedAt}} busybox | head -n 1
2023-03-17 01:35:43 +0000 UTC
$ podman image history --format {{.CreatedAt}} busybox | head -n 1
2023-03-17T02:35:43+01:00

```

**Comment by rhatdan** [comment]
I am fine with fixing this, but I will allow @vrothberg and @mheon to chime in.

**Comment by mheon** [comment]
I'd prefer to retain the test - it seems like it could be changed to parse the fields back to a `time.Time` and compare them that way. LGTM otherwise.

**Review by vrothberg — COMMENTED** [review]
The changes look good to me.

One system test isn't passing (see https://cirrus-ci.com/task/5421900956958720?logs=main#L284).  @edsantiago, we probably need to your scripting skills.  I tried normalizing the two dates but one fails with

`$ date -d '2022-10-18 16:28:08 +0000 UTC'`

File: test/e2e/history_test.go [hunk 1]
```diff
@@ -44,6 +44,13 @@ var _ = Describe("Podman history", func() {
 		session.WaitWithDefaultTimeout()
 		Expect(session).Should(Exit(0))
 		Expect(session.OutputToStringArray()).ToNot(BeEmpty())
+
+		session = podmanTest.Podman([]string{"history", "--format", "{{.CreatedAt}};{{.Size}}", ALPINE})
+		session.WaitWithDefaultTimeout()
+		Expect(session).Should(Exit(0))
+		lines := session.OutputToStringArray()
+		Expect(lines).ToNot(BeEmpty())
+		Expect(lines[0]).ToNot(ContainSubstring(" "))
```
Comment (Luap99) [inline test/e2e/history_test.go:53]: Please do not make negative checks. You should check for the real output you expect. I know there a bunch of bad examples in the existing tests but we should do a better job for new tests.

If the numbers are not consistent you can use `To(MatchRegexp(...))` to match a regex instead.
Also just call `session.OutputToString()` to get the output as one string.

**Comment by edsantiago** [comment]
The failing system test is: `CreatedSince and CreatedAt from image history should == image list`. TL;DR this PR makes `podman image list` and `podman image history` inconsistent with each other:
```console
$ for i in list history;do echo;bin/podman image $i --format '{{.CreatedAt}}' quay.io/libpod/testimage:20221018;done

2022-10-18 16:28:08 +0000 UTC     <--- until now, this has been the format for both

2022-10-18T10:28:08-06:00         <--- new, changed format
2022-10-18T10:28:08-06:00
2022-10-18T10:28:08-06:00
2022-10-18T10:28:08-06:00
2022-10-18T10:28:20-06:00
2022-10-18T10:28:20-06:00
2022-10-18T10:28:20-06:00
```

File: test/e2e/history_test.go (hunk 1 above)
Comment (rbagd) [reply test/e2e/history_test.go]: No problem, I update the PR with an extra regex.

**Comment by eriksjolund** [comment]
In the commit message it's written

```
Closes #17767 and #17768 
```

The GitHub linking only works for the first one (17767) but not the second one (17768)

I would guess the commit message needs to be written like this for it to work

```
Closes #13797 
Closes #17768 
```

Quote:

```
Multiple issues	Use full syntax for each issue
```
from 
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by rbagd** [comment]
I updated the relevant system test to maintain the equality check of `podman image history` and `podman image list` output for `CreatedAt` and `CreatedSince`. Please let me know if this look good enough. To make the whole thing more readable I switched field separator in the test to `;` from `--`.

CI failed for one of the jobs but it's a [runtime error which does not seem related to the PR](https://cirrus-ci.com/task/5606446105100288?logs=main#L454).

**Comment by Luap99** [comment]
@edsantiago PTAL at system tests

File: test/system/110-history.bats [hunk 2]
```diff
@@ -57,15 +57,26 @@ size      | -\\\?[0-9]\\\+
...
+    imagehist_since=$(echo "$from_imagehistory" | cut -d';' -f1)
+
+    assert "$imagehist_since" == "$imagelist_since" \
+           "CreatedSince from image history should == image list"
+
+    imagelist_at=$(date --rfc-3339=seconds -f <(echo "$from_imagelist" | cut -d';' -f2 | sed 's/ UTC//'))
+    imagehist_at=$(date --rfc-3339=seconds -f <(echo "$from_imagehistory" | cut -d';' -f2))
+
+    assert "$imagehist_at" == "$imagelist_at" \
+           "CreatedAt from image history should == image list"
```
Comment (edsantiago) [inline test/system/110-history.bats:79]: I find all the `cut/sed`s a little hard to read, and they're actually unnecessary. I also think it's important to explain what's going on, because this is now super-confusing. Suggestion:
```bash
@test "podman image history Created" {
    # Values from image LIST
    run_podman image list --format '{{.CreatedSince}}\n{{.CreatedAt}}' $IMAGE
    imagelist_since="${lines[0]}"
    imagelist_at="${lines[1]}"
    assert "${imagelist_since}" =~ "^[0-9].* ago" \
           "image list: CreatedSince looks reasonable"
    assert "${imagelist_at}" =~ "^[0-9]+-[0-9]+-[0-9]+ [0-9:]+ \+0000 UTC\$" \
           "image list: CreatedAt looks reasonable"

    # Values from image HISTORY. For docker compatibility, this command now
    # honors $TZ (#18213) for CreatedAt.
    TZ=UTC run_podman image history --format '{{.CreatedSince}}\n{{.CreatedAt}}' $IMAGE
    imagehistory_since="${lines[0]}"
    imagehistory_at="${lines[1]}"

    assert "$imagehistory_since" == "$imagelist_since" \
           "CreatedSince from image history should == image list"

    # More docker compatibility: both commands emit ISO8601-ish dates but
    # with different separators so we need to compare date & time separately.
    assert "${imagehistory_at:0:10}" == "${imagelist_at:0:10}" \
           "CreatedAt (date) from image history should == image list"
    assert "${imagehistory_at:11:8}" == "${imagelist_at:11:8}" \
           "CreatedAt (time) from image history should == image list"
}
```

Comment (rbagd) [reply test/system/110-history.bats:79]: This looks very nice! I'll push an update later today. Thanks for looking into it!

**Comment by edsantiago** [comment]
LGTM. Thanks @rbagd.

@containers/podman-maintainers PTAL, especially the docker compatibility (I don't have a good way to test docker).

**Comment by eriksjolund** [comment]
@rbagd Thanks for adjusting the commit message so that it now says

```
Closes #17767
Closes #17768
```

Unfortunately it didn't fix the the GitHub linking. Sorry for my misleading information. 
I made a test in another GitHub repository and saw that we can fix the GitHub linking by editing the [pull request's description](https://github.com/containers/podman/pull/18213#issue-1669357754) and replace

```
Closes #17767 and #17768
```

with 

```
Closes #17767
Closes #17768
```

**Comment by rbagd** [comment]
It seems to be working! Both issues appear on the right sidebar now as expected.

**Comment by TomSweeneyRedHat** [comment]
LGTM
