### PR TITLE
Engine.Remote from containers.conf

### LINKED ISSUE #12866: It seems podman doesn't read "remote" in config by now
### Discussed in https://github.com/containers/podman/discussions/12864

<div type='discussions-op-text'>

<sup>Originally posted by **hsupu** January 14, 2022</sup>
I set my `containers.conf` as below but it didn't work.

```conf
[engine] 
remote = true
```

I believe that the `podman` should behave like `podman -r` by default if the remote flag is on.

This feature is [documented](https://www.mankier.com/5/containers.conf).

I found the code is [here](https://github.com/containers/podman/blob/eeb76db0fd0dc2a1115c2f2ad12c82eadbc62509/vendor/github.com/containers/common/pkg/config/config.go#L342)

```go
// EngineConfig contains configuration options used to set up a engine runtime
type EngineConfig struct {
	// Indicates whether the application should be running in Remote mode
	Remote bool `toml:"remote,omitempty"`
}
```

I saw there is another struct (that looked critical) contains a `Remote bool`. It's [here](https://github.com/containers/podman/blob/eeb76db0fd0dc2a1115c2f2ad12c82eadbc62509/pkg/domain/entities/engine.go#L45)

```go
// PodmanConfig combines the defaults and settings from the file system with the
// flags given in os.Args. Some runtime state is also stored here.
type PodmanConfig struct {
	*config.Config
	Remote         bool       // Connection to Podman API Service will use RESTful API
}
```

I found the working function in code is `IsRemote` which is defined [here](https://github.com/containers/podman/blob/0144f46ac5067196019225430847691502d74da7/cmd/podman/registry/remote.go).

This feature, read remote flag from config file, does it not work by design, or it's just under development so I maybe could try to fix it ?

Thanks!
</div>

### PR DESCRIPTION
**Pull request by jwhonce**
Heuristic to initialize TunnelMode/remote podman:
- Podman built with remote tag
- Podman running on darwin or windows GOOS
- CONTAINER_HOST or CONTAINER_CONNECTION set in environment
- --remote flag given on command line
- From containers.conf, Engine.Remote == true and GOOS == linux

Otherwise, podman will run in ABIMode/linked against libpod library.

Fixes #12866

Signed-off-by: Jhon Honce <jhonce@redhat.com>

### CODE REVIEW

File: test/e2e/containers_conf_test.go [hunk 1]
```diff
@@ -472,16 +493,37 @@ var _ = Describe("Podman run", func() {
...
-		Expect(result.ErrorToString()).To(ContainSubstring(errorString))
+		Expect(result.Err.Contents()).To(ContainSubstring(errorString))
+	})
+
+	It("set .engine.remote=true", func() {
+		SkipIfRemote("only meaningful when running ABI/local")
+
+		// Need to restore CONTAINERS_CONF or AfterEach() will fail
+		oldConfigPath := os.Getenv("CONTAINERS_CONF")
+		defer os.Setenv("CONTAINERS_CONF", oldConfigPath)
```
Comment (rhatdan) [inline test/e2e/containers_conf_test.go:514]: Shojld only defer if oldConfigPath != ""

**Comment by rhatdan** [comment]
Tried it out and it works for me.

LGTM

**Comment by TomSweeneyRedHat** [comment]
@jwhonce all kinds of test unhappiness here.
Changes LGTM otherwise

**Comment by TomSweeneyRedHat** [comment]
LGTM 
and happy green test buttons!

**Comment by rhatdan** [comment]
/lgtm
Thanks @jwhonce seemed like a lot of work.

**Comment by jwhonce** [comment]
@rhatdan Getting the tests stable took much longer than the code change.
