### PR TITLE
Fix locale issues with WSL version detection

### LINKED ISSUE #20209: Can't create machine with user-mode-networking
### Issue Description

I ran:

`podman machine init --now --rootful --user-mode-networking`

and got:

`Error: user-mode networking requires a newer version of WSL: apply all outstanding windows updates, and then run 'wsl --update'`

So I ran:

wsl --update 

and got

```
Recherche des mises à jour.
La version la plus récente de Sous-système Windows pour Linux est déjà installée.
```

which is translated to:
```

Check for updates.
The latest version of Windows Subsystem for Linux is already installed.
```

`wsl -v` 
```

Version WSL : 1.2.5.0
Version du noyau : 5.15.90.1
Version WSLg : 1.0.51
Version MSRDC : 1.2.3770
Version direct3D : 1.608.2-61064218
Version de DXCore : 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Version de Windows : 10.0.22621.2283
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman machine init --now --rootful --user-mode-networking`

### Describe the results you received

Failed to create the machine

### Describe the results you expected

Should be created

### podman info output

```yaml
podman version 4.7.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by n1hility**
Fixes #20209

Since wsl --version triggers help, which triggers an error code, use that instead of text detection.

```release-note
Fix an issue on non-English locales of Windows where machine installs using user-mode networking were rejected due to erroneous version detection
```

### CODE REVIEW

File: pkg/machine/wsl/wutil/wutil.go [hunk 1]
```diff
@@ -50,20 +50,13 @@ func IsWSLInstalled() bool {
 
 func IsWSLStoreVersionInstalled() bool {
 	cmd := SilentExecCmd("wsl", "--version")
-	out, err := cmd.StdoutPipe()
+	cmd.Stdout = nil
```
Comment (vrothberg) [inline pkg/machine/wsl/wutil/wutil.go:53]: Non-blocking nit: consider using a `bytes.Buffer` for stdout and stderr and write that to `logrus.Debugf`.

**Review by vrothberg — COMMENTED** [review]
Code LGTM
Needs the magic `[NO NEW TESTS NEEDED]`  to pass CI
