### PR TITLE
compat: Add Health field to /containers/json endpoint

### LINKED ISSUE #27786: Docker-compat API: `/containers/json` missing `Health` field added in v1.52
### Issue Description

Podman's Docker-compatible API endpoint for listing containers (`/containers/json`) is missing the health field that Docker Engine API added in `v1.52`. See [docker docs](https://docs.docker.com/reference/api/engine/version/v1.52/#tag/Container/operation/ContainerList):
> Added in v1.52, before that version all container summary not include Health. After this attribute introduced, it includes containers with no health checks configured, or containers that are not running with none. 

### Steps to reproduce the issue

1. Create a podman container
2. Query the `/containers/json` endpoint, i.e. ```curl --unix-socket /run/user/1000/podman/podman.sock http://localhost/containers/json```

### Describe the results you received

```json
$curl --unix-socket /run/user/1000/podman/podman.sock http://localhost/containers/json
[
  {
    "Id": "25f2d0d295fb0952135b8b5961a5c114a461011d759d257c788c63297ccf0a4f",
    "Names": [
      "/test"
    ],
    "Image": "docker.io/traefik/whoami:latest",
    "ImageID": "sha256:6fee7566e4273ee6078f08e167e36434b35f72152232a5e6f1446288817dabe5",
    "Command": "",
    "Created": 1765930126,
    "Ports": [
      {
        "PrivatePort": 80,
        "Type": "tcp"
      }
    ],
    "Labels": {
      "org.opencontainers.image.created": "2025-03-13T14:25:39Z",
      "org.opencontainers.image.description": "Tiny Go webserver that prints OS information and HTTP request to output",
      "org.opencontainers.image.documentation": "https://github.com/traefik/whoami",
      "org.opencontainers.image.revision": "7e57190724ca7c0a74aa7f878b6cefe13b11994f",
      "org.opencontainers.image.source": "https://github.com/traefik/whoami",
      "org.opencontainers.image.title": "whoami",
      "org.opencontainers.image.url": "https://github.com/traefik/whoami",
      "org.opencontainers.image.version": "1.11.0"
    },
    "State": "running",
    "Status": "Up 30 minutes",
    "NetworkSettings": {
      "Networks": null
    },
    "Mounts": [],
    "Name": "",
    "Config": null,
    "NetworkingConfig": null,
    "Platform": null,
    "DefaultReadOnlyNonRecursive": false
  }
]
```

### Describe the results you expected

Expected the field
```json
"Health": "healthy"
```
to be present.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.42.2
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.13-2.fc43.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: '
  cpuUtilization:
    idlePercent: 97.43
    systemPercent: 0.54
    userPercent: 2.03
  cpus: 12
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: workstation
    version: "43"
  eventLogger: journald
  freeLocks: 2047
  hostname: framework.allenliao.org
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 6.17.10-300.fc43.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 15561879552
  memTotal: 31302524928
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.17.0-1.fc43.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.17.0
    package: netavark-1.17.1-1.fc43.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.17.1
  ociRuntime:
    name: crun
    package: crun-1.25.1-1.fc43.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.25.1
      commit: 156ae065d4a322d149c7307034f98d9637aa92a2
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20250919.g623dbf6-1.fc43.x86_64
    version: |
      pasta 0^20250919.g623dbf6-1.fc43.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8589824000
  swapTotal: 8589930496
  uptime: 32h 0m 6.00s (Approximately 1.33 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /home/allenliao/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/allenliao/.local/share/containers/storage
  graphRootAllocated: 998500204544
  graphRootUsed: 159617306624
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/allenliao/.local/share/containers/storage/volumes
version:
  APIVersion: 5.7.1
  BuildOrigin: Fedora Project
  Built: 1765324800
  BuiltTime: Tue Dec  9 18:00:00 2025
  GitCommit: f845d14e941889ba4c071f35233d09b29d363c75
  GoVersion: go1.25.4 X:nodwarf5
  Os: linux
  OsArch: linux/amd64
  Version: 5.7.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

NA

### Additional information

NA

### PR DESCRIPTION
**Pull request by kairosci**
#### Checklist

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all commits. (`git commit -s`).
- [x] Referenced issues using `Fixes: #27786` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [ ] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
Add Health field to /containers/json endpoint, providing container health status in the summary output.
```

Fixes: #27786

### CODE REVIEW

File: pkg/api/handlers/compat/containers.go [hunk 1]
```diff
@@ -401,6 +401,13 @@ func LibpodToContainer(l *libpod.Container, sz bool) (*handlers.Container, error
 		return nil, err
 	}
 
+	health := container.NoHealthcheck
+	if l.HasHealthCheck() && state != define.ContainerStateConfigured && state != define.ContainerStateCreated {
```
Comment (jankaluza) [inline pkg/api/handlers/compat/containers.go]: Does this set `health` to `none` if the container is not running, despite the fact that it had a healthcheck configured while running?

I have not checked the Docker behavior, but the documentation says `... After this attribute introduced, it includes containers with no health checks configured, or containers that are not running with none`

As I understand from the docs, if container is not running, Docker returns `none`. Can you check that, please?

File: test/apiv2/20-containers.at [hunk 2]
```diff
@@ -82,7 +82,8 @@ t GET /containers/json?all=true 200 \
   .[0].Id~[0-9a-f]\\{64\\} \
   .[0].Image=$IMAGE \
   .[0].Mounts~.*/tmp \
-  .[0].NetworkSettings.$network_expect
+  .[0].NetworkSettings.$network_expect \
+  .[0].Health=none
```
Comment (jankaluza) [inline test/apiv2/20-containers.at]: I think it would be great to add additional test for a case where health check is actually set.

There are already tests creating `running` container and tests creating containers with `healthcheck`, so combining these two should be easy and would test the `inspect.State.Health.Status` propagation to API response.

**Comment by kairosci** [comment]
@jankaluza I think I have satisfied all requests. 

I'm ready for a new review!

File: pkg/api/handlers/compat/containers.go (hunk 1 above)
Comment (kairosci) [reply pkg/api/handlers/compat/containers.go]: I checked and you were right, then added a check and strengthened the logic to avoid nils

**Comment by kairosci** [comment]
This bot never works the first time!

I'll start a new trigger!

**Comment by jankaluza** [comment]
LGTM.

This looks good to me now, but it needs review from one of the maintainers :-).

**Comment by kairosci** [comment]
I added a new small test that ensures that if a container is shut down, the API does not say that it is “healthy” or “unhealthy,” but correctly says that there is no active health status; therefore none

File: pkg/api/handlers/compat/containers.go [hunk 3]
```diff
@@ -483,7 +491,11 @@ func LibpodToContainerJSON(l *libpod.Container, sz bool) (*container.InspectResp
 	if l.HasHealthCheck() && state.Status != "created" {
 		state.Health = &container.Health{}
 		if inspect.State.Health != nil {
-			state.Health.Status = inspect.State.Health.Status
+			if state.Status == "running" || state.Status == "paused" {
+				state.Health.Status = inspect.State.Health.Status
+			} else {
+				state.Health.Status = "none"
```
Comment (danishprakash) [inline pkg/api/handlers/compat/containers.go]:
```suggestion
				state.Health.Status = container.NoHealthcheck
```

File: pkg/api/handlers/types.go [hunk 4]
```diff
@@ -104,6 +104,7 @@ type Info struct {
 type Container struct {
 	docker.Container
 	dockerBackend.ContainerCreateConfig
+	Health string `json:"Health,omitempty"`
```
Comment (danishprakash) [inline pkg/api/handlers/types.go]:
```suggestion
	dockerContainer.HealthStatus
```

**Comment by kairosci** [comment]
@Luap99 PTAL

**Comment by kairosci** [comment]
@mheon PTAL, thanks!

**Comment by mheon** [comment]
Why is this being added to the Docker-compat endpoint? I don't see if in the Docker API documentation.

**Review by Honny1 — COMMENTED** [review]
The code change LGTM, but I am not entirely sure. This change is related to porting Podman over to the new moby/moby module instead of the old docker/docker one. It might be interesting to investigate that approach first (https://github.com/containers/podman/issues/27536).

File: test/apiv2/20-containers.at [hunk 5]
```diff
@@ -888,3 +888,66 @@ t POST containers/create?platform=linux/aarch64 \
   Image=$IMAGE \
   404
 podman rmi -f $IMAGE
+
+# Test Compat Create with healthcheck, check status propagation
+# Regression test for correct Health status when stopped (should be 'none')
+# and running (should be 'starting' or 'healthy')
+t POST containers/create Image=$IMAGE Cmd='["top"]' Healthcheck='{"Test":["CMD","echo","healthy"],"Interval":1000000000,"Retries":1}' 201 \
```
Comment (Honny1) [inline test/apiv2/20-containers.at]: Image is removed: `response: {"cause":"image not known","message":"no such image: quay.io/libpod/testimage:20241011: image not known","response":404}`

Comment (kairosci) [reply test/apiv2/20-containers.at]: I've added a `podman pull $IMAGE` before the test to ensure the image is available.

**Comment by kairosci** [comment]
@Honny1 this PR fixes a specific user-facing bug.

The change is small and self-contained, so I think it's worth merging now rather than blocking on the broader moby/moby migration.

**Comment by kairosci** [comment]
CC: @jankaluza

**Comment by mheon** [comment]
Alright, so it's in 1.52... We really need to get up to speed on API changes.

**Comment by mheon** [comment]
Can we restrict this to only send if API version 1.52 or above is requested?

**Comment by kairosci** [comment]
@mheon I think I did it, can you check if I did it correctly?

File: pkg/api/handlers/compat/images_remove.go [hunk 6]
```diff
@@ -51,7 +51,7 @@ func RemoveImage(w http.ResponseWriter, r *http.Request) {
 	if len(rmerrors) > 0 && rmerrors[0] != nil {
 		err := rmerrors[0]
 		if errors.Is(err, storage.ErrImageUnknown) {
-			utils.ImageNotFound(w, name, fmt.Errorf("failed to find image %s: %w", name, err))
+			utils.Error(w, http.StatusNotFound, fmt.Errorf("No such image: %s", name))
```
Comment (Honny1) [inline pkg/api/handlers/compat/images_remove.go]: Is this change part of this PR?

File: test/apiv2/20-containers.at [hunk 7]
```diff
@@ -913,3 +888,67 @@ t POST containers/create?platform=linux/aarch64 \
...
+done
+
+t GET containers/$cid/json 200 \
+  .State.Health.Status~"\(starting\|healthy\)"
+
+t GET v1.52/containers/json?all=true 200 \
+  .[0].Id=$cid \
+  .[0].Health~"\(starting\|healthy\)"
+
+t POST containers/$cid/stop 204
```
Comment (Honny1) [inline test/apiv2/20-containers.at]: Stopping the container doesn't reset the healthcheck status. I think it would be good to keep this behavior the same as interaction via the command line.

File: pkg/api/handlers/compat/images_remove.go (hunk 6 above)
Comment (kairosci) [reply pkg/api/handlers/compat/images_remove.go]: Not directly, it was to be consistent with the Moby standard (404 + “No such image”), let's say that thinking about it, it shouldn't be there.

I'll open a new PR later if it hasn't been changed.

**Comment by kairosci** [comment]
I think I have registered the request to manage health via cmd.

@Honny1 PTAL, thanks!

File: test/apiv2/20-containers.at [hunk 8]
```diff
@@ -901,6 +902,23 @@ t DELETE containers/$cid 204
...
+t GET containers/json?filters='{"name":["healthcheck-test-running"]}' 200 \
+  .[0].Health~"\(starting\|healthy\)"
+t GET containers/healthcheck-test-running/json 200 \
+  .State.Health.Status~"\(starting\|healthy\)"
+
+podman stop -t0 healthcheck-test-running
+t GET "containers/json?all=true&filters={\"name\":[\"healthcheck-test-running\"]}" 200 \
+  .[0].Health=none
+t GET containers/healthcheck-test-running/json 200 \
+  .State.Health.Status=none
```
Comment (Honny1) [inline test/apiv2/20-containers.at]:
```
$ podman run --replace --name test -dt --health-cmd true --health-interval 5s docker.io/busybox
$ podman stop test
$ podman inspect test --format {{.State.Health.Status}}
healthy
```

This is what I meant by my comment about stopping the container and the healthcheck. The `podman stop` command (or API call) does not update the health in the container state. So, I would expect the API call to return the same output as `podman inspect`. The other possibility is that `podman inspect` is incorrect, in which case we need to open an issue to fix it. What docker does?

Comment (kairosci) [reply test/apiv2/20-containers.at]: Docker keeps the last known health status when the container stops, so that part is consistent. The real issue is whether podman inspect should still report a health value for a container that isn’t running.

Once the container is stopped, the healthcheck isn’t running anymore. Returning healthy can easily mislead anything that relies on the API to know if the service is actually up.

If the intended behavior is to keep the last known status, then the API should match it. Otherwise, it would make more sense for the health status to switch to none (or something like stopped) as soon as the container exits.

Comment (Honny1) [reply test/apiv2/20-containers.at]: In terms of the compat API, we must match Docker's behavior. Also, since Podman is a drop-in replacement for Docker, I would keep the 'last known health' status everywhere to ensure consistency. You can still check if the container is running; if it isn't, the health check status shouldn't matter to you.

Comment (kairosci) [reply test/apiv2/20-containers.at]: For containers with health checks, the status no longer reverts to none when the container stops and retains the last valid status, for example healthy, in line with Docker. 

For containers without health checks, none remains the standard indication that no check is configured. 

When a container is only in the created state and has never been started, the status remains none because no initial health check has been performed.

Comment (kairosci) [reply test/apiv2/20-containers.at]: Another PTAL, thank you!

File: test/apiv2/20-containers.at [hunk 9]
```diff
@@ -901,6 +902,23 @@ t DELETE containers/$cid 204
...
+t GET containers/json?filters='{"name":["healthcheck-test-running"]}' 200 \
+  .[0].Health~"\(starting\|healthy\)"
+t GET containers/healthcheck-test-running/json 200 \
+  .State.Health.Status~"\(starting\|healthy\)"
+
+podman stop -t0 healthcheck-test-running
+t GET "containers/json?all=true&filters={\"name\":[\"healthcheck-test-running\"]}" 200 \
+  .[0].Health~"\(starting\|healthy\)"
+t GET containers/healthcheck-test-running/json 200 \
+  .State.Health.Status~"\(starting\|healthy\)"
```
Comment (Honny1) [inline test/apiv2/20-containers.at]:
```
# not ok 1185 [20-containers] GET containers/json?all=true&filters={"name":["healthcheck-test-running"]} : .[0].Health
#  expected: ~ \(starting\|healthy\)
#    actual: stopped
ok 1186 [20-containers] GET containers/healthcheck-test-running/json : status=200
not ok 1187 [20-containers] GET containers/healthcheck-test-running/json : .State.Health.Status
 #  expected: ~ \(starting\|healthy\)
 #    actual: stopped
```

**Review by Honny1 — COMMENTED** [review]
LGTM

PTAL @jankaluza

**Comment by Honny1** [comment]
@kairosci Can you please rebase on main.

File: test/apiv2/20-containers.at [hunk 10]
```diff
@@ -913,3 +912,21 @@ t POST containers/create?platform=linux/aarch64 \
   Image=$IMAGE \
   404
 podman rmi -f $IMAGE
+
+# Test health status in /containers/json (GH #27786)
+podman run -d --name healthcheck-test-running --health-cmd "true" --health-interval 1s $IMAGE top
+# Give it a moment to initialize and run health check
+sleep 3
+t GET containers/json?filters='{"name":["healthcheck-test-running"]}' 200 \
+  .[0].Health="healthy"
```
Comment (Honny1) [inline test/apiv2/20-containers.at]:
```suggestion
  .[0].Health.Status="healthy"
```

File: test/apiv2/20-containers.at [hunk 11]
```diff
@@ -913,3 +912,21 @@ t POST containers/create?platform=linux/aarch64 \
...
+t GET containers/healthcheck-test-running/json 200 \
+  .State.Health.Status="healthy"
+
+# Verify that health status is preserved after container is stopped
+podman stop -t0 healthcheck-test-running
+t GET "containers/json?all=true&filters={\"name\":[\"healthcheck-test-running\"]}" 200 \
+  .[0].Health="healthy"
```
Comment (Honny1) [inline test/apiv2/20-containers.at]:
```suggestion
  .[0].Health.Status="healthy"
```

File: test/apiv2/20-containers.at [hunk 12]
```diff
@@ -903,8 +903,7 @@ rm -rf $TMPD
 
 podman container rm -fa
 
-# 18951: Make sure container create supports the platform parameter.  Force an
-# initial architecture to make sure the test runs on all platforms.
```
Comment (Honny1) [inline test/apiv2/20-containers.at:924]: This change is unrelated to the Health field feature and shouldn't be in this PR.

File: pkg/api/handlers/compat/containers.go [hunk 13]
```diff
@@ -418,6 +418,15 @@ func LibpodToContainer(l *libpod.Container, sz bool) (*handlers.Container, error
 		return nil, err
 	}
 
+	var healthSummary *container.HealthSummary
```
Comment (Honny1) [inline pkg/api/handlers/compat/containers.go:434]: Docker populates it for ALL containers with "none" as the default. 

https://github.com/moby/moby/blob/6e7a2c830d2577af2a7a9ad5b94f50e857b582d4/api/swagger.yaml#L5349-L5374

File: pkg/api/handlers/compat/containers.go [hunk 14]
```diff
@@ -418,6 +418,15 @@ func LibpodToContainer(l *libpod.Container, sz bool) (*handlers.Container, error
...
+	if l.HasHealthCheck() {
+		healthSummary = &container.HealthSummary{}
+		if inspect.State.Health != nil {
```
Comment (Honny1) [inline pkg/api/handlers/compat/containers.go]: When `inspect.State.Health` is `nil` but the container has a healthcheck, is created `HealthSummary{}` with `Status: ""`.  Docker doesn't set `""`. https://github.com/moby/moby/pull/50281/changes

**Review by Honny1 — CHANGES_REQUESTED** [review]
Sorry, it slipped off my radar.

File: version/version.go [hunk 15]
```diff
@@ -40,7 +40,7 @@ var APIVersion = map[Tree]map[Level]semver.Version{
 		MinimalAPI: semver.MustParse("4.0.0"),
 	},
 	Compat: {
-		CurrentAPI: semver.MustParse("1.44.0"),
+		CurrentAPI: semver.MustParse("1.52.0"),
```
Comment (Honny1) [inline version/version.go:43]: `01-basic.at` is not updated for version bump.

File: test/apiv2/20-containers.at [hunk 16]
```diff
@@ -915,3 +915,44 @@ t POST containers/create?platform=linux/aarch64 \
...
+
+# Test health status is 'none' for containers without a healthcheck
+podman create --name no-healthcheck $IMAGE top
+t GET containers/json?all=true\&filters='{"name":["no-healthcheck"]}' 200 \
+  .[0].Health.Status="none"
+podman rm -f no-healthcheck
+
+# Test health status with explicit v1.52 API
+podman create --name healthcheck-v152 --health-cmd "true" $IMAGE top
+t GET v1.52/containers/json?all=true\&filters='{"name":["healthcheck-v152"]}' 200 \
```
Comment (Honny1) [inline test/apiv2/20-containers.at:933]: This becomes: `/v1.44/v1.52/cont...`
```suggestion
t GET /v1.52/containers/json?all=true\&filters='{"name":["healthcheck-v152"]}' 200 \
```

File: test/apiv2/20-containers.at [hunk 17]
```diff
@@ -915,3 +915,44 @@ t POST containers/create?platform=linux/aarch64 \
...
+  .[0].Health.Status="starting"
+podman rm -f healthcheck-v152
+
+# Test health status is HIDDEN for API versions < 1.52
+podman create --name healthcheck-v144 --health-cmd "true" $IMAGE top
+t GET v1.44/containers/json?all=true\&filters='{"name":["healthcheck-v144"]}' 200 \
```
Comment (Honny1) [inline test/apiv2/20-containers.at:939]: This becomes: `/v1.44/v1.44/cont...`
```suggestion
t GET /v1.44/containers/json?all=true\&filters='{"name":["healthcheck-v144"]}' 200 \
```

File: test/apiv2/20-containers.at [hunk 18]
```diff
@@ -915,3 +915,44 @@ t POST containers/create?platform=linux/aarch64 \
   Image=$IMAGE \
   404
 podman rmi -f $IMAGE
+
```
Comment (Honny1) [inline test/apiv2/20-containers.at:918]: Tests are failing because the wrong default version is seen here, how it is added https://github.com/containers/podman/blob/9a5335f86c4ce11e2e9161036622d36a82b2960e/test/apiv2/test-apiv2#L312-L318

File: test/apiv2/20-containers.at [hunk 19]
```diff
@@ -915,3 +915,44 @@ t POST containers/create?platform=linux/aarch64 \
...
+sleep 3
+t GET containers/json?filters='{"name":["healthcheck-test-running"]}' 200 \
+  .[0].Health.Status="healthy"
+t GET containers/healthcheck-test-running/json 200 \
+  .State.Health.Status="healthy"
+
+# Verify that health status is preserved after container is stopped
+podman stop -t0 healthcheck-test-running
+t GET "containers/json?all=true&filters={\"name\":[\"healthcheck-test-running\"]}" 200 \
+  .[0].Health.Status="healthy"
```
Comment (Honny1) [inline test/apiv2/20-containers.at:954]: `none`?

**Review by Honny1 — CHANGES_REQUESTED** [review]

File: pkg/api/handlers/compat/containers.go [hunk 20]
```diff
@@ -165,8 +166,13 @@ func ListContainers(w http.ResponseWriter, r *http.Request) {
 		}
 	}
 	list := make([]*handlers.Container, 0, len(containers))
+	// only include health if API version is >= 1.52 or no version is given (latest)
+	includeHealth := false
+	if _, err := utils.SupportedVersion(r, ">= 1.52"); err == nil || errors.Is(err, apiutil.ErrVersionNotGiven) {
```
Comment (Honny1) [inline pkg/api/handlers/compat/containers.go:171]:
```suggestion
	if _, err := utils.SupportedVersion(r, ">= 1.52.0"); err == nil || errors.Is(err, apiutil.ErrVersionNotGiven) {
```

File: test/apiv2/20-containers.at [hunk 21]
```diff
@@ -929,23 +914,45 @@ t POST containers/create?platform=linux/amd64 \
...
+
+# Test health status is HIDDEN for API versions < 1.52
+podman create --name healthcheck-v144 --health-cmd "true" $IMAGE top
+t GET /v1.44/containers/json?all=true\&filters='{"name":["healthcheck-v144"]}' 200 \
+  .[0].Health=null
+podman rm -f healthcheck-v144
+
+podman run -d --name healthcheck-test-running --health-cmd "true" --health-interval 1s $IMAGE top
+# Give it a moment to initialize and run health check
+sleep 3
```
Comment (Honny1) [inline test/apiv2/20-containers.at:945]: I would use `podman wait` or trigger hc with `podman healtcheck run`.

File: version/version.go (hunk 15 above)
Comment (Honny1) [inline version/version.go:43]: I am not sure about this change.

**Review by Honny1 — CHANGES_REQUESTED** [review]

File: version/version.go (hunk 15 above)
Comment (kairosci) [reply version/version.go:43]: Why?

Comment (Honny1) [reply version/version.go:43]: I think it is not needed.

Comment (mheon) [reply version/version.go:43]: There's a reasonable argument that we don't support anything over 1.44, API wise, so doing this without a comprehensive set of changes to actually support the API version we're claiming is a bad idea

**Comment by Honny1** [comment]
Hello, please rebase on the upstream main branch. We changed import paths recently. Thanks.

**Review by Honny1 — APPROVED** [review]
LGTM, Thanks! @kairosci I think PR is ready for merge.

PTAL @containers/podman-maintainers

**Comment by mheon** [comment]
LGTM
