### PR TITLE
SQLite verify that a Volume config was actually deleted

### LINKED ISSUE #28376: SQLite `RemoveVolume` does not verify a volume was actually removed
### Issue Description

The `RemoveVolume` function in SQLite does not validate the number of rows deleted, so it can return no error if no volume was actually removed. This should be fixed - we need to check that only 1 row was removed, and error otherwise.

### Steps to reproduce the issue

N/A

### Describe the results you received

N/A

### Describe the results you expected

N/A

### podman info output

```yaml
N/A
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by osullivandonal**
This PR checks the result from the volume config deletion to verify rows were actually affected. If no rows were deleted, return ErrNoSuchVolume.

Fixes #28376 

> [!IMPORTANT]
> ~~Tests have been omitted because this is a defensive code change. Testing this edge case would require removing the volume from the database between the volume lookup and the RemoveVolume call to simulate a race condition. The normal "volume not found" case is already covered by existing tests in test/e2e/volume_rm_test.go.~~

#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by mheon** [comment]
If you want to test: there are unit tests for the SQLite DB in `libpod/state_test.go`

File: libpod/sqlite_state.go [hunk 1]
```diff
@@ -2007,26 +2007,32 @@ func (s *SQLiteState) RemoveVolume(volume *Volume) (defErr error) {
...
+	if err != nil {
 		return fmt.Errorf("removing volume %s config from DB: %w", volume.Name(), err)
 	}
 
+	affected, err := result.RowsAffected()
+	if err != nil {
+		return fmt.Errorf("getting rows affected for volume %q remove: %w", volume.Name(), err)
+	}
+
+	if affected == 0 {
```
Comment (mheon) [inline libpod/sqlite_state.go:2032]: Can you check for affected > 1 as well? If we deleted more than 1, something else has gone seriously wrong

Comment (osullivandonal) [reply libpod/sqlite_state.go:2032]: Sounds good, I can check for `affected > 1` too.

File: libpod/sqlite_state.go [hunk 2]
```diff
@@ -2007,26 +2007,32 @@ func (s *SQLiteState) RemoveVolume(volume *Volume) (defErr error) {
...
-	// Need to verify that at least 1 row was deleted from VolumeConfig.
-	// Otherwise return ErrNoSuchVolume
-
-	if _, err := tx.Exec("DELETE FROM VolumeConfig WHERE Name=?;", volume.Name()); err != nil {
+	result, err := tx.Exec("DELETE FROM VolumeConfig WHERE Name=?;", volume.Name())
+	if err != nil {
 		return fmt.Errorf("removing volume %s config from DB: %w", volume.Name(), err)
 	}
 
+	affected, err := result.RowsAffected()
```
Comment (danishprakash) [inline libpod/sqlite_state.go:2027]: nit: in line with the existing invocations
```suggestion
	rows, err := result.RowsAffected()
```

File: libpod/sqlite_state.go [hunk 3]
```diff
@@ -2007,26 +2007,32 @@ func (s *SQLiteState) RemoveVolume(volume *Volume) (defErr error) {
...
+	if err != nil {
+		return fmt.Errorf("getting rows affected for volume %q remove: %w", volume.Name(), err)
+	}
+
+	if affected == 0 {
+		return fmt.Errorf("no volume with name %q found in DB: %w", volume.Name(), define.ErrNoSuchVolume)
+	}
+
 	if _, err := tx.Exec("DELETE FROM VolumeState WHERE Name=?;", volume.Name()); err != nil {
```
Comment (danishprakash) [inline libpod/sqlite_state.go:2036]: Does it make sense to do a similar check here? It'd be quite an edge case though @mheon

File: libpod/sqlite_state.go (hunk 1 above)
Comment (osullivandonal) [reply libpod/sqlite_state.go]: Done, however, I couldn't add a test as the DB has a unique constraint on the Name field: `insert failed: UNIQUE constraint failed: VolumeConfig.Name`.

File: libpod/sqlite_state.go (hunk 2 above)
Comment (osullivandonal) [reply libpod/sqlite_state.go]: I have updated the name to be `rowsAffected`, there is already a `rows` variable declared above.

File: libpod/sqlite_state.go (hunk 3 above)
Comment (osullivandonal) [reply libpod/sqlite_state.go:2036]: Would this be valid? I believe a Volume can exist without a VolumeState? So if there is no VolumeState to delete we would return an error here which may be misleading?

**Comment by osullivandonal** [comment]
> If you want to test: there are unit tests for the SQLite DB in `libpod/state_test.go`

Tests added for error `define.ErrNoSuchVolume`

**Review by giuseppe — COMMENTED** [review]
please squash the commits

File: libpod/sqlite_state.go (hunk 3 above)
Comment (mheon) [reply libpod/sqlite_state.go:2036]: We could check it, but if we do I'd only print a warning on `removed != 0` - no actual error. There should always be a 1:1 relationship between config and state, so there is a reason to warn - but at the same time, there's nothing the user can really do about it.

**Review by mheon — APPROVED** [review]
LGTM. Can address the last comment on catching state removal != 1 if you want, but I'm good to merge without that.

**Comment by mheon** [comment]
Rerunning one flake. Testing farm jobs are nonblocking and known broken.

@containers/podman-maintainers PTAL

**Review by Honny1 — APPROVED** [review]
LGTM
