### PR TITLE
`podman volume prune`: match Docker defaults, add `--all` flag

### LINKED ISSUE #24597: CLI UX Consistency Pruning Volumes
### Issue Description

Inconsistency for the CLI UX which makes documentation harder and muscle memory more expensive. Adding a simple compatibility option would bring the two UX for volume management closer together.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `docker volume prune -a` (and `podman volume prune -a`

### Describe the results you received

```
jon@dahome:~$ docker volume prune -a
Error: unknown shorthand flag: 'a' in -a
See 'podman volume prune --help'
```

### Describe the results you expected

To maintain a compatible UX for the CLI, we should support `-a` for the volume prune. The default behaviors between docker and podman are different and we should unify them more.

In Docker CE you need to pass `-a` to do a proper dangling volume cleanup.
In Podman it does the right thing.

We should add `-a` as compatibility so both `docker volume prune -a` and `podman volume prune -a` work.

### podman info output

```yaml
jon@dahome:~$ podman version
Client:       Podman Engine
Version:      5.3.0
API Version:  5.3.0
Go Version:   go1.22.7
Built:        Tue Nov 12 17:00:00 2024
OS/Arch:      linux/amd64
jon@dahome:~$ podman info
host:
  arch: amd64
  buildahVersion: 1.38.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.12-2.fc40.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 93.91
    systemPercent: 1.33
    userPercent: 4.76
  cpus: 24
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: workstation
    version: "40"
  eventLogger: journald
  freeLocks: 2047
  hostname: dahome.damaestro.us
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 6.11.8-200.fc40.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 48293961728
  memTotal: 67290427392
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.13.1-1.fc40.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.13.1
    package: netavark-1.13.0-1.fc40.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.13.0
  ociRuntime:
    name: crun
    package: crun-1.18.2-1.fc40.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.18.2
      commit: 00ab38af875ddd0d1a8226addda52e1de18339b5
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20241030.gee7d0b6-1.fc40.x86_64
    version: |
      pasta 0^20241030.gee7d0b6-1.fc40.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 0h 46m 42.00s
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /home/jon/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/jon/.local/share/containers/storage
  graphRootAllocated: 998483427328
  graphRootUsed: 76022562816
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 19
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/jon/.local/share/containers/storage/volumes
version:
  APIVersion: 5.3.0
  Built: 1731456000
  BuiltTime: Tue Nov 12 17:00:00 2024
  GitCommit: ""
  GoVersion: go1.22.7
  Os: linux
  OsArch: linux/amd64
  Version: 5.3.0

jon@dahome:~$ rpm -q podman
podman-5.3.0-1.fc40.x86_64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Honny1**
The `podman volume prune` now matches *Docker behavior* by pruning only anonymous unused volumes by default, adds `--all` to prune `named` and `anonymous` volumes, and aligns filter docs/completion, volume prune e2e tests were also refactored to use `PodmanExitCleanly` with no functional change.

Fixes: https://github.com/containers/podman/issues/24597
Fixes: https://issues.redhat.com/browse/RUN-4404

#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
Breaking change: `podman volume prune` now defaults to pruning only anonymous unused volumes (Docker-compatible), adds `--all` for pruning all unused volumes.
```

### CODE REVIEW

**Review by ashley-cui — COMMENTED** [review]
LGTM

File: cmd/podman/volumes/prune.go [hunk 1]
```diff
@@ -42,8 +41,9 @@ func init() {
 
 	filterFlagName := "filter"
 	flags.StringArrayVar(&filter, filterFlagName, []string{}, "Provide filter values (e.g. 'label=<key>=<value>')")
-	_ = pruneCommand.RegisterFlagCompletionFunc(filterFlagName, common.AutocompleteVolumeFilters)
+	_ = pruneCommand.RegisterFlagCompletionFunc(filterFlagName, common.AutocompleteVolumePruneFilters)
 	flags.BoolP("force", "f", false, "Do not prompt for confirmation")
+	flags.BoolP("all", "a", false, "Remove all unused volumes (anonymous and named), not just anonymous ones")
```
Comment (TomSweeneyRedHat) [inline cmd/podman/volumes/prune.go]: Nit for consideration.
```suggestion
	flags.BoolP("all", "a", false, "Remove all unused volumes, both anonymous and named")
```

File: docs/source/markdown/podman-volume-prune.1.md [hunk 2]
```diff
@@ -49,18 +53,27 @@ Print usage statement
...
+```
+$ podman volume prune --all --force
+```
+
+Prune all unused volumes using the filter (equivalent to **--all**).
+```
+$ podman volume prune --filter all=true --force
+```
+
+Prune unused volumes that have the specified label.
```
Comment (TomSweeneyRedHat) [inline docs/source/markdown/podman-volume-prune.1.md:76]: It would be good to add examples with `label` and `label!` involved.

File: pkg/bindings/test/volumes_test.go [hunk 3]
```diff
@@ -199,5 +202,28 @@ var _ = Describe("Podman volumes", func() {
...
+		session = bt.runPodman([]string{"create", "-v", "/anon2", alpine.name, "top"})
+		session.Wait(45)
+		Expect(session.ExitCode()).To(BeZero())
+
+		_, err = volumes.Create(connText, entities.VolumeCreateOptions{Name: namedVolume}, nil)
+		Expect(err).ToNot(HaveOccurred())
+
+		pruned, err := volumes.Prune(connText, nil)
+		Expect(err).ToNot(HaveOccurred())
+		Expect(pruned).To(HaveLen(1))
```
Comment (TomSweeneyRedHat) [inline pkg/bindings/test/volumes_test.go:227]: I don't see a test for `label!`.  If there isn't one here, could you add one please?

Comment (TomSweeneyRedHat) [reply pkg/bindings/test/volumes_test.go:227]: I'm doing a lot of never minds in reviews today, I see it in the prune test.

File: docs/source/markdown/podman-volume-prune.1.md (hunk 2 above)
Comment (Honny1) [reply docs/source/markdown/podman-volume-prune.1.md:76]: I have added examples.

**Comment by Honny1** [comment]
PTAL @containers/podman-maintainers

File: docs/source/markdown/podman-volume.1.md [hunk 4]
```diff
@@ -20,7 +20,7 @@ podman volume is a set of subcommands that manage volumes.
 | inspect | [podman-volume-inspect(1)](podman-volume-inspect.1.md) | Get detailed information on one or more volumes.                               |
 | ls      | [podman-volume-ls(1)](podman-volume-ls.1.md)           | List all the available volumes.                                                |
 | mount   | [podman-volume-mount(1)](podman-volume-mount.1.md)     | Mount a volume filesystem.                                                     |
-| prune   | [podman-volume-prune(1)](podman-volume-prune.1.md)     | Remove all unused volumes.                                                     |
+| prune   | [podman-volume-prune(1)](podman-volume-prune.1.md)     | Remove unused volumes                                                         |
```
Comment (giuseppe) [inline docs/source/markdown/podman-volume.1.md]: missing `.` at the end of the statement

**Review by giuseppe — COMMENTED** [review]
nitpick, otherwise LGTM

**Review by lsm5 — COMMENTED** [review]
Is this expected: 

```
# ./bin/podman volume prune
WARNING! This will remove anonymous local volumes not used by at least one container. The following volumes will be removed:
named1
named2
34902fb92c8450a0e69f8182a1fe93ac1b30b6eb805b328bc0bb4aace47ebbf1
Are you sure you want to continue? [y/N] Y

# ./bin/podman volume ls
DRIVER      VOLUME NAME
local       named1
local       named2
local       34902fb92c8450a0e69f8182a1fe93ac1b30b6eb805b328bc0bb4aace47ebbf1
```

**Comment by Honny1** [comment]
Good catch, let me check that. Could you give me a hint as to how you created those volumes? Or did you base them on a specific test scenario? I think I missed something.

**Comment by lsm5** [comment]
> Good catch, let me check that. Could you give me a hint as to how you created those volumes? Or did you base them on a specific test scenario? I think I missed something.

```
# ./bin/podman system reset

# ./bin/podman volume create named1
named1
# ./bin/podman volume create named2
named2
# ./bin/podman volume create
<UNNAMED_STRING>

Followed by the `volume prune` and `volume ls` commands from earlier comment.
```

**Comment by Honny1** [comment]
@lsm5 Very good catch. The `podman volume create (no name)` creates a volume with a random ID, but never sets `IsAnon`, so it stayed `Anonymous: false`. That is why it is not removed. Also, I have a bug in the listing of verbose prune.

**Review by lsm5 — APPROVED** [review]
```
$ ./bin/podman volume prune
WARNING! This will remove all volumes not used by at least one container. The following volumes will be removed:
named1
named2
5264366d0f02e3db807ccfe9dfffbd7ea687067e2b069abb15320a116db9dd3e
Are you sure you want to continue? [y/N] y
named1
named2
5264366d0f02e3db807ccfe9dfffbd7ea687067e2b069abb15320a116db9dd3e
$ ./bin/podman volume ls
DRIVER      VOLUME NAME
$
```

LGTM

**Comment by lsm5** [comment]
@Honny1 I think the tests need to be adjusted.

**Comment by Honny1** [comment]
> ```
> $ ./bin/podman volume prune
> WARNING! This will remove all volumes not used by at least one container. The following volumes will be removed:
> named1
> named2
> 5264366d0f02e3db807ccfe9dfffbd7ea687067e2b069abb15320a116db9dd3e
> Are you sure you want to continue? [y/N] y
> named1
> named2
> 5264366d0f02e3db807ccfe9dfffbd7ea687067e2b069abb15320a116db9dd3e
> $ ./bin/podman volume ls
> DRIVER      VOLUME NAME
> $
> ```
> 
> LGTM

@lsm5  I'm not sure about your output; you are probably using the wrong binary. This should be the correct behavior after merging this PR:
```bash

# ./bin/podman system reset
WARNING! This will remove:
        - all containers
        - all pods
        - all images
        - all networks
        - all build cache
        - all machines
        - all volumes
        - the graphRoot directory: "/var/lib/containers/storage"
        - the runRoot directory: "/run/containers/storage"
Are you sure you want to continue? [y/N] y
# ./bin/podman volume create named1
named1
# ./bin/podman volume create named2
named2
# ./bin/podman volume create       
c9f0a19c0109786b693a976cde42ffa9aad4a5bbb966f3130565ac6361eb3818
# ./bin/podman volume ls
DRIVER      VOLUME NAME
local       named1
local       named2
local       c9f0a19c0109786b693a976cde42ffa9aad4a5bbb966f3130565ac6361eb3818
# ./bin/podman volume prune
WARNING! This will remove anonymous local volumes not used by at least one container. The following volumes will be removed:
c9f0a19c0109786b693a976cde42ffa9aad4a5bbb966f3130565ac6361eb3818
Are you sure you want to continue? [y/N] y
c9f0a19c0109786b693a976cde42ffa9aad4a5bbb966f3130565ac6361eb3818
# ./bin/podman volume ls   
DRIVER      VOLUME NAME
local       named1
local       named2
# ./bin/podman volume create
bd64dcbe9e6a009135dc2e17f7e72c954386fec03958847dffff0e97e1da8b4e
# ./bin/podman volume ls    
DRIVER      VOLUME NAME
local       named1
local       named2
local       bd64dcbe9e6a009135dc2e17f7e72c954386fec03958847dffff0e97e1da8b4e
# ./bin/podman volume prune -a
WARNING! This will remove all volumes not used by at least one container. The following volumes will be removed:
named1
named2
bd64dcbe9e6a009135dc2e17f7e72c954386fec03958847dffff0e97e1da8b4e
Are you sure you want to continue? [y/N] y
named1
named2
bd64dcbe9e6a009135dc2e17f7e72c954386fec03958847dffff0e97e1da8b4e
# ./bin/podman volume ls      
DRIVER      VOLUME NAME
```

**Comment by Honny1** [comment]
@containers/podman-maintainers PTAL for final review and merging.

**Comment by lsm5** [comment]
@Honny1 that was my bad.

```
$ ./bin/podman volume prune
WARNING! This will remove anonymous local volumes not used by at least one container. The following volumes will be removed:
cba4811fb38214ba9391c0ebdb658978f8634328719499ded0d50182aa367c0b
Are you sure you want to continue? [y/N] y
cba4811fb38214ba9391c0ebdb658978f8634328719499ded0d50182aa367c0b
$ ./bin/podman volume ls
DRIVER      VOLUME NAME
local       named1
local       named2
```

LGTM for real this time.

**Review by lsm5 — APPROVED** [review]
LGTM

**Comment by lsm5** [comment]
Lots of `crun: systemd failed to install eBPF device filter on cgroup ` errors in testing-farm rawhide job. May not be a blocker here but could bite us in bodhi.

**Comment by TomSweeneyRedHat** [comment]
LGTM
Four of the Fedora test failed with flakes.  I'll let @mheon or @Luap99 decide if they should complete or not before merge.

**Comment by Luap99** [comment]
packit is not blocking and not related to this PR so good to merge, though these do look like real errors that need to be fixed I ping folks on matrix
