### PR TITLE
Change API socket to be machine name isolated

### LINKED ISSUE #21899: `podman machine rm` removes socket used by other machines
### Issue Description

When I have several podman machines and I remove one of them using `podman machine rm <name>`, the socket is deleted, as part of the process. But, if I understand correctly, all the machines share the same socket, and so, this socket is not available anymore for other machines.

### Steps to reproduce the issue

Steps to reproduce the issue

```
# a machine exists
$ podman machine list               
NAME                    VM TYPE     CREATED        LAST UP            CPUS        MEMORY      DISK SIZE
podman-machine-default  qemu        4 weeks ago    Currently running  6           16.76GiB    186GiB 

# and the socket exists
$ ls /Users/me/.local/share/containers/podman/machine/qemu/podman.sock
/Users/me/.local/share/containers/podman/machine/qemu/podman.sock

# I create a second machine
$ podman machine init podman-machine-2

# the socket still exists
$ ls /Users/me/.local/share/containers/podman/machine/qemu/podman.sock
/Users/me/.local/share/containers/podman/machine/qemu/podman.sock

# I remove a machine, the socket will be deleted
$ podman machine rm podman-machine-2

The following files will be deleted:

[...]
/Users/me/.local/share/containers/podman/machine/qemu/podman.sock

Are you sure you want to continue? [y/N] y

# the socket has been deleted
$ ls /Users/me/.local/share/containers/podman/machine/qemu/podman.sock
ls: /Users/me/.local/share/containers/podman/machine/qemu/podman.sock: No such file or directory

```

### Describe the results you received

See above

### Describe the results you expected

I would expect that the socket ie deleted only when the latest machine is deleted (or never deleted)

### podman info output

```yaml
$ podman version
Client:       Podman Engine
Version:      4.9.1
API Version:  4.9.1
Go Version:   go1.21.6
Git Commit:   118829d7fc68c34d5a317cda90b69884f3446f5c
Built:        Thu Feb  1 15:12:40 2024
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.8.3
API Version:  4.8.3
Go Version:   go1.21.5
Built:        Wed Jan  3 15:10:40 2024
OS/Arch:      linux/arm64
```

```
$  podman info
host:
  arch: arm64
  buildahVersion: 1.33.2
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.8-2.fc39.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: '
  cpuUtilization:
    idlePercent: 99.4
    systemPercent: 0.38
    userPercent: 0.21
  cpus: 6
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: coreos
    version: "39"
  eventLogger: journald
  freeLocks: 2039
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.6.13-200.fc39.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 16395878400
  memTotal: 17503678464
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.9.0-1.fc39.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.9.0
    package: netavark-1.9.0-1.fc39.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.9.0
  ociRuntime:
    name: crun
    package: crun-1.13-1.fc39.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.13
      commit: c761349704905da07cfe67f38dda6850334a160f
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20231230.gf091893-1.fc39.aarch64
    version: |
      pasta 0^20231230.gf091893-1.fc39.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-1.fc39.aarch64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 5m 54.00s
  variant: v8
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 0
    stopped: 4
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 199110930432
  graphRootUsed: 35228422144
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 117
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.8.3
  Built: 1704291040
  BuiltTime: Wed Jan  3 15:10:40 2024
  GitCommit: ""
  GoVersion: go1.21.5
  Os: linux
  OsArch: linux/arm64
  Version: 4.8.3
````
```


### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Mac OS

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by n1hility**
Fixes  #21899

Change API socket to be machine name isolated

- Fixes conflicts such as removal of second machine deleting a socket of a the first machine while it's running
- Move API socket into runtime directory for consistency
- Add API and gvproxy sockets to removal list
- Cleanup related logic

#### Does this PR introduce a user-facing change?

```release-note
Fixes a problem where podman machine rm removes a socket used by other machines - #21899
```

### CODE REVIEW

**Comment by afbjorklund** [comment]
This needs to be addressed in the Podman Desktop configuration, so that it can find the "new" socket.

**Comment by afbjorklund** [comment]
Should probably only do this for 5.0, to make it easier to "Know" when the breaking change occurs.

**Comment by Luap99** [comment]
Nobody should need to "guess" the socket location, the location is printed on machine start and part of podman machine inspect so users should get it from there and not rely on a fixed path in general.

File: pkg/machine/e2e/inspect_test.go [hunk 1]
```diff
@@ -68,10 +68,12 @@ var _ = Describe("podman inspect stop", func() {
 		Expect(err).ToNot(HaveOccurred())
 
 		switch testProvider.VMType() {
+		case define.HyperVVirt:
+			fallthrough
 		case define.WSLVirt:
```
Comment (Luap99) [inline pkg/machine/e2e/inspect_test.go:73]: you can just write `case define.HyperVVirt, define.WSLVirt:`

File: pkg/machine/shim/networking_unix.go [hunk 2]
```diff
@@ -10,16 +10,22 @@ import (
...
 		return nil, "", 0, err
 	}
 
-	linkSocketPath := filepath.Dir(dirs.DataDir.GetPath())
+	dataDir, err := mc.DataDir()
+	if err != nil {
+		return nil, "", 0, err
+	}
+
+	linkSocketPath := filepath.Dir(dataDir.GetPath())
```
Comment (Luap99) [inline pkg/machine/shim/networking_unix.go:28]: I have a hard time understanding the purpose of the linkSocket, doesn't this means we still conflict there?

**Review by Luap99 — COMMENTED** [review]
overall LGTM, although I do not really understand why we need the extra linkSocket on darwin.

**Comment by Luap99** [comment]
@baude @ashley-cui @mheon PTAL

**Comment by mheon** [comment]
LGTM, but I'd prefer to have an answer on the MacOS thing before we merge. Is it a socket path-length restriction?

File: pkg/machine/shim/networking_unix.go [hunk 3]
```diff
@@ -10,16 +10,22 @@ import (
...
-func setupMachineSockets(name string, dirs *define.MachineDirs) ([]string, string, machine.APIForwardingState, error) {
-	hostSocket, err := dirs.DataDir.AppendToNewVMFile("podman.sock", nil)
+func setupMachineSockets(mc *vmconfigs.MachineConfig) ([]string, string, machine.APIForwardingState, error) {
+	hostSocket, err := mc.APISocket()
 	if err != nil {
 		return nil, "", 0, err
 	}
 
-	linkSocketPath := filepath.Dir(dirs.DataDir.GetPath())
+	dataDir, err := mc.DataDir()
```
Comment (baude) [inline pkg/machine/shim/networking_unix.go:23]: is there a reason to not keep the dirs from the original signature or maybe just pass datadir in? it looks like the caller already has it ?

File: pkg/machine/shim/networking_unix.go (hunk 2 above)
Comment (n1hility) [reply pkg/machine/shim/networking_unix.go:28]: Thanks for pointing out there is a clarity issue here. There's a comment a few lines below thats in the file in setupForwardingLinks that talks about this, and the name could be better. I'll improve that.

Yes, this link structure is shared, but cooperatively managed.  It looks like:

/var/run/docker.sock -> user global sock (link) -> machine sock (socket)

The purpose is to enable the podman-mac-helper to effectively manage the global /var/run/docker.sock, since its security sensitive code running as root, its kept simple and links /var/run/docker.dock to a user global socket link, which in turn links to the machine socket. Then various podman machine start executions manage that link structure indecently of the service. The rule is first come first serve, whoever is active first wins, everyone else backs off, and as soon as the winner is no longer active another machine start will become the new active winner. The same applies to a competing container runtime trying to use /var/run/docker.sock, if its in use machine will fallback to the machine socket. 

This behavior is all preexisting, however the change here is that machine sock is now in the runtime directory.

Comment (Luap99) [reply pkg/machine/shim/networking_unix.go:28]: thanks, I will keep this comment in mind and will add some comments there and restructure the flow a bit as this socket is only used on macos with the claim helper to make it more obvious to future readers

File: pkg/machine/shim/networking_unix.go (hunk 3 above)
Comment (n1hility) [reply pkg/machine/shim/networking_unix.go:23]: Not a great one. Previously the machine config was not passed, so sig needed to change to bring over the API socket method, and so when I changed it I was thinking the config struct already has the data dir on it. Although since that method adds error handling  it does bloat the code here, so I'll restore passing it to delete that bit of code.

**Comment by n1hility** [comment]
Will push a change to address two points in next few mins

File: pkg/machine/shim/networking_unix.go (hunk 2 above)
Comment (Luap99) [reply pkg/machine/shim/networking_unix.go:28]: from a flow point it makes no sense to "create" a socket that is never used by most users.
The linkSocket creation should be moved into setupForwardingLinks() IMO, where we actually have this claim helper.

Anyhow non of this is blocking your PR to be clear, this was just a comment because I found it confusing.

I am totally fine to merge as is.

Comment (n1hility) [reply pkg/machine/shim/networking_unix.go]: Yeah totally agree. Let me know what you think of the version I just pushed

**Review by Luap99 — APPROVED** [review]
LGTM
