### PR TITLE
fix race conditions in start/attach logic

### LINKED ISSUE #23246: podman start --filter restart-policy=always : container state improper
Looks related to #22914, although probably not a regression (that one was a reliable panic, this is a flaky podman error):
```
[+0319s] not ok 151 [045] podman start --filter - start only containers that match the filter in 1914ms
...
<+010ms> # $ podman start --filter restart-policy=always   <<< first restart
<+268ms> # e214e6b649c557e0b24e610cb2bb986694f01f16e5545337195319b5f86763c8
         # 877d80fe7cfa11755af13fe02dbf4a359887ac6ca40e41b17f67b3d1c08392d9
         #
<+074ms> # $ podman start --filter restart-policy=always    <<<< second restart
<+351ms> # Error: unable to start container "e214e6b649c557e0b24e610cb2bb986694f01f16e5545337195319b5f86763c8": container e214e6b649c557e0b24e610cb2bb986694f01f16e5545337195319b5f86763c8 must be in Created or Stopped state to be started: container state improper
```
For extra credit, maybe someone could fix that error message to indicate the actual current container state

* fedora-39 : sys podman fedora-39 rootless host boltdb
  * PR #22726
    * [07-10 09:35](https://api.cirrus-ci.com/v1/artifact/task/6475531296702464/html/sys-podman-fedora-39-rootless-host-boltdb.log.html#t--00151) in [sys] [045] podman start --filter - start only containers that match the filter
    * [07-08 14:00](https://api.cirrus-ci.com/v1/artifact/task/5449520568336384/html/sys-podman-fedora-39-rootless-host-boltdb.log.html#t--00151) in [sys] [045] podman start --filter - start only containers that match the filter
* rawhide : sys podman rawhide rootless host sqlite
  * PR #22425
    * [07-10 13:35](https://api.cirrus-ci.com/v1/artifact/task/5628035582394368/html/sys-podman-rawhide-rootless-host-sqlite.log.html#t--00151) in [sys] [045] podman start --filter - start only containers that match the filter

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| sys(3) | podman(3) | fedora-39(2) | rootless(3) | host(3) | boltdb(2) |
|  |  | rawhide(1) |  |  | sqlite(1) |

### PR DESCRIPTION
**Pull request by Luap99**
The current code did something like this:
lock()
getState()
unlock()

if state != running
  lock()
  getState() == running -> error
  unlock()

This of course is wrong because between the first unlock() and second lock() call another process could have modified the state. This meant that sometimes you would get a weird error on start because the internal setup errored as the container was already running.

In general any state check without holding the lock is incorrect and will result in race conditions. As such refactor the code to combine both StartAndAttach and Attach() into one function that can handle both. With that we can move the running check into the locked code.

Also use typed error for this specific error case then the callers can check and ignore the specific error when needed. This also allows us to fix races in the compat API that did a similar racy state check.

Fixes #23246

#### Does this PR introduce a user-facing change?

```release-note
Fix several race conditions in the start/attach commands.
```

### CODE REVIEW

**Comment by Luap99** [comment]
@mheon PTAL

File: libpod/container_api.go [hunk 1]
```diff
@@ -175,9 +173,27 @@ func (c *Container) StartAndAttach(ctx context.Context, streams *define.AttachSt
 		}
 	}
 
-	if err := c.prepareToStart(ctx, recursive); err != nil {
-		return nil, err
+	if c.state.State != define.ContainerStateRunning {
```
Comment (giuseppe) [inline libpod/container_api.go:176]: could we attach to a container in the `ContainerStatePaused` state?

**Review by giuseppe — APPROVED** [review]
LGTM, just left a comment

File: libpod/container_api.go (hunk 1 above)
Comment (Luap99) [reply libpod/container_api.go:176]: I would think yes as conmon wouldn't care? But I just copied pre existing condition without thinking about it to much. If we attach to a paused container it could be confusing as no IO will be consumed, so a users could think the process/terminal hangs?

**Comment by Luap99** [comment]
There is one change in behaivor in the code,
Currently `podman start name` does not print the name when the container is already running. I find this rather confusing and broken as it sort of breaks the idempotence of the start command. This patch always shows the name regardless of state. I think the only place where this makes sense is when using --all so I will fix the code to handle the all case.

**Comment by Luap99** [comment]
> can it be one of these weird "Docker does it" cases?

I just tested and docker behaves like this commit does. It always prints the name.

File: libpod/container_api.go [hunk 2]
```diff
@@ -175,9 +173,27 @@ func (c *Container) StartAndAttach(ctx context.Context, streams *define.AttachSt
...
+		if !start {
+			return nil, errors.New("you can only attach to running containers")
+		}
+
+		if err := c.prepareToStart(ctx, true); err != nil {
+			return nil, err
+		}
+	}
+
+	if !start {
```
Comment (mheon) [inline libpod/container_api.go:186]: Why only !start on these checks? I can't imagine starting and attaching to a PassthroughLogging container makes sense

Comment (Luap99) [reply libpod/container_api.go:186]: Is the comment below not good enough? This code path is used by podman run so we cannot reject it on a start. We are not doing a real attach, you can see the short cut in the ConmonOCIRuntime Attach interface

Comment (mheon) [reply libpod/container_api.go:186]: It feels fundamentally incorrect to be calling the Attach API when we have no intention of actually attaching but it seems like the fix would be very intrusive (having to look up log driver in the frontend code, and spreading the concern of log driver into the frontend as well). I suppose we could do an ErrCannotAttach for these log drivers and retry with the standard Start API in the frontend code if we get that, but that seems sufficiently separate to not block this.

**Comment by mheon** [comment]
LGTM

File: libpod/container_api.go (hunk 2 above)
Comment (Luap99) [reply libpod/container_api.go:186]: Normal start would work but it is more communicated in the fronted because we still have to call Wait() in order to wait for the container to exit which is why this code path makes most sense currently.

But yeah I agree it is confusing and does not make much sense logically within Attach()

File: libpod/container_api.go (hunk 1 above)
Comment (giuseppe) [reply libpod/container_api.go:176]: we can deal with it in a separate PR.

**Review by giuseppe — APPROVED** [review]
/lgtm
