### PR TITLE
Fix resize race with podman exec -it

### LINKED ISSUE #10560: podman exec --tty resizes only after the process is started
/kind bug

**Description**

`podman exec -it` only resizes the terminal after the exec process is started. This issues exists in both local and remote podman.

**Steps to reproduce the issue:**

1. `podman run -dit --name test alpine top`

2. `podman exec -it test stty size`

**Describe the results you received:**
`stty: standard input`

**Describe the results you expected:**
two numbers, the real terminal size
`19 194`

### PR DESCRIPTION
**Pull request by Luap99**
When starting a process with `podman exec -it` the terminal is resized
after the process is started. To fix this allow exec start to accept the
terminal height and width as parameter and let it resize right before
the process is started.

Fixes #10560

### CODE REVIEW

File: pkg/api/server/register_exec.go [hunk 1]
```diff
@@ -272,7 +272,13 @@ func (s *APIServer) registerExecHandlers(r *mux.Router) error {
 	//          description: Detach from the command. Not presently supported.
```
Comment (mheon) [inline pkg/api/server/register_exec.go:272]: This is definitely supported, I don't know why the docs say it isn't.

**Comment by edsantiago** [comment]
Uh-oh. My flake catcher detected that the new test [flaked (sys podman ubuntu-2104 root host)](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6429990330826752/html/sys-podman-ubuntu-2104-root-host.log.html):
```
# # podman exec -it mystty stty size
# stty: standard input

# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #|     FAIL: stty under podman exec reads the correct dimensions
# #| expected: '41 62'
# #|   actual: 'stty: standard input
'
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
This is really really bad: it means that the test is not reliable, and is going to start flaking in CI.
