### PR TITLE
manifest list inspect single image

### LINKED ISSUE #8023: unable to load manifest list: unsupported format
/kind bug

**Description**

Podman does not support inspecting non-list type manifests which may be returned from a registry mirror.

**Steps to reproduce the issue:**

1. Configure ~/.config/containers/registries.conf with
```
unqualified-search-registries = ['registry.fedoraproject.org', 'registry.access.redhat.com', 'registry.centos.org', 'docker.io']

[[registry]]
location="docker.io"

[[registry.mirror]]
location="mirror.gcr.io"
```

2. run `podman manifest inspect docker://busybox:latest`

**Describe the results you received:**

```
Error: error inspect manifest docker://busybox:latest: manifest is of type application/vnd.docker.distribution.manifest.v2+json (not a list type)
```

**Describe the results you expected:**

```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 1493,
      "digest": "sha256:f0b02e9d092d905d0d87a8455a1ae3e9bb47b4aa3dc125125ca5cd10d6441c9f"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 764619,
         "digest": "sha256:9758c28807f21c13d05c704821fdd56c0b9574912f9b916c65e1df3e6b8bc572"
      }
   ]
}
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.0-dev
API Version:  2.0.0
Go Version:   go1.14.9
Git Commit:   e3eb6fd0e4115162e10caf6ae2196fd8774657e0-dirty
Built:        Wed Oct 14 15:55:43 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.19-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.19, commit: 5dce9767526ed27f177a8fa3f281889ad509fea7'
  cpus: 12
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 4179
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 4179
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.7.16-200.fc32.x86_64
  linkmode: dynamic
  memFree: 1411776512
  memTotal: 33392246784
  ociRuntime:
    name: crun
    package: crun-0.15-5.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.15
      commit: 56ca95e61639510c7dbd39ff512f80f626404969
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/4179/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 4275412992
  swapTotal: 4290768896
  uptime: 1181h 36m 12.37s (Approximately 49.21 days)
registries:
  docker.io:
    Blocked: false
    Insecure: false
    Location: docker.io
    MirrorByDigestOnly: false
    Mirrors:
    - Insecure: false
      Location: mirror.gcr.io
    Prefix: docker.io
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/cevich/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/cevich/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 27
  runRoot: /run/user/4179/containers
  volumePath: /home/cevich/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601494271
  BuiltTime: Wed Sep 30 15:31:11 2020
  GitCommit: ""
  GoVersion: go1.14.9
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Built from source

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Tested with F31 but have [reproduced this behavior in CI using both F32](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5873133926219776/html/int-podman-fedora-32-root-host.log.html#t--podman-manifest-inspect--1).

### PR DESCRIPTION
**Pull request by QiWang19**
If the image name not a manifest list type, enable `manifest inspect` to return manifest of single image with manifest type `application/vnd.docker.distribution.manifest.v2+json` 
close #8023

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@QiWang19 can you touch up the title please?   "insepct" -> "inspect"

File: pkg/domain/infra/abi/manifest.go [hunk 1]
```diff
@@ -90,18 +91,34 @@ func (ir *ImageEngine) ManifestInspect(ctx context.Context, name string) ([]byte
...
+			return nil, errors.Errorf("manifest is of type %s (not a list type)", manType)
+		}
+		schema2Manifest, err := manifest.Schema2FromManifest(result)
+		if err != nil {
+			return nil, errors.Wrapf(err, "error parsing manifest blob %q as a %q", string(result), manType)
+		}
+		if result, err = schema2Manifest.Serialize(); err != nil {
+			return nil, err
+		}
+	default:
```
Comment (TomSweeneyRedHat) [inline pkg/domain/infra/abi/manifest.go:121]: I really don't like the yes/no answer here, it will be a headache for scripting purposes.  If we don't have a manifest list, can't we just print out a warning and then continue on as if they answered 'Y' here?  "

```
fmt.Printf(`The manifest type %s is not a manifest list.  Displaying the the manifest of the single image.\n`, manType)
```

Comment (QiWang19) [reply pkg/domain/infra/abi/manifest.go:121]: I'm not sure which implementation is more user-friendly. If it's using for scripting porpose, users may expect to receive the manifest list, not a single manifest.

**Comment by TomSweeneyRedHat** [comment]
I'd like to hear @edsantiago 's thought on the friendliness.  Personally I don't think a query that only happens sometimes is not friendly at all, I think it's better to get the info with a warning.

**Comment by edsantiago** [comment]
I'm trying to focus every minute I have today on Chris's big PR, and can't give this the attention it deserves. (And I'm out tomorrow and Friday). Sorry. My first reaction, though, is that I really dislike being prompted. I like error messages that indicate what went wrong and how to fix it (e.g. by a special command-line flag), and I like command-line flags that are forgiving or at least offer a best-effort attempt to Do The Right Thing so that scripts can be written robustly. HTH.

**Comment by rhatdan** [comment]
I agree on avoiding the query, unless you are going to add a `-y` option so I can script it.

I also think this is not a mainstream command, so having it fail or print a warning would be better.  If someone is playing with manifests they will quickly learn how to deal with them.  Most users will never touch this code.

File: pkg/domain/infra/abi/manifest.go (hunk 1 above)
Comment (QiWang19) [reply pkg/domain/infra/abi/manifest.go:111]: Change to just printout the warning.

**Comment by QiWang19** [comment]
If having it fail is expected, https://github.com/containers/podman/issues/8023 may not be treated as a podman bug. The code used to report the manifest type error. But just tried docker manifest inspect, it returns the single manifest directly without any errors.

File: pkg/domain/infra/abi/manifest.go [hunk 2]
```diff
@@ -90,18 +90,25 @@ func (ir *ImageEngine) ManifestInspect(ctx context.Context, name string) ([]byte
...
 		break
 	}
 	if len(result) == 0 && latestErr != nil {
 		return nil, latestErr
 	}
-	if manType != manifest.DockerV2ListMediaType {
+
+	switch manType {
+	case manifest.DockerV2Schema2MediaType:
+		fmt.Printf("Warning! The manifest type %s is not a manifest list.  Displaying the the manifest of the single image.\n", manType)
```
Comment (jwhonce) [inline pkg/domain/infra/abi/manifest.go:103]:
```suggestion
		fmt.Fprintf(os.Stderr, "Warning! The manifest type %s is not a manifest list.  Displaying the the manifest of the single image.\n", manType)
```
I know this has been bashed around a bit but errors should go to stderr  IMHO

Comment (QiWang19) [reply pkg/domain/infra/abi/manifest.go]: Thanks. Fixed.

File: pkg/domain/infra/abi/manifest.go [hunk 3]
```diff
@@ -90,18 +90,25 @@ func (ir *ImageEngine) ManifestInspect(ctx context.Context, name string) ([]byte
...
 		break
 	}
 	if len(result) == 0 && latestErr != nil {
 		return nil, latestErr
 	}
-	if manType != manifest.DockerV2ListMediaType {
+
+	switch manType {
+	case manifest.DockerV2Schema2MediaType:
+		fmt.Fprintf(os.Stderr, "Warning! The manifest type %s is not a manifest list.  Displaying the the manifest of the single image.\n", manType)
```
Comment (rhatdan) [inline pkg/domain/infra/abi/manifest.go:103]: Once we start displaying at the Warning level, this should be logrus.Warnf.

**Comment by rhatdan** [comment]
Could you cleanup you commit message to match latest reality and fix spelling mistakes.
```
 manifest list insepct single image

Use prompt to enable `manifest inspect` to return manifest of single image if it's not a manfiest list type.
```

**Comment by rhatdan** [comment]
/approve
LGTM
@jwhonce PTAL

**Comment by QiWang19** [comment]
@containers/podman-maintainers PTAL.

**Review by vrothberg — COMMENTED** [review]
Just a wording nit. @QiWang19 could you add some tests? I always want a test for fixes to make sure we're not re-regressing in the future.

File: pkg/domain/infra/abi/manifest.go [hunk 4]
```diff
@@ -90,18 +91,25 @@ func (ir *ImageEngine) ManifestInspect(ctx context.Context, name string) ([]byte
...
 		break
 	}
 	if len(result) == 0 && latestErr != nil {
 		return nil, latestErr
 	}
-	if manType != manifest.DockerV2ListMediaType {
+
+	switch manType {
+	case manifest.DockerV2Schema2MediaType:
+		logrus.Warnf("Warning! The manifest type %s is not a manifest list but a single image.\n", manType)
```
Comment (vrothberg) [inline pkg/domain/infra/abi/manifest.go:104]:
```suggestion
		logrus.Warnf("Warning! The manifest type %s is not a manifest list but a single image", manType)
```

**Review by vrothberg — COMMENTED** [review]
One tiny non-blocking format suggestion but LGTM

**Comment by QiWang19** [comment]
@containers/podman-maintainers PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM
and happy green test buttons.  Nice work @QiWang19
