### PR TITLE
Unconditionally retrieve pod names via API

### LINKED ISSUE #7214: "PodName" property in Containers object never filled by the Rest API
/kind bug

**Description**

When listing containers through the Rest API there is PodName property which should be there according to the documentation but it's always empty string. "Pod" property contains the Pod ID and can be used to identify the pods instead.

**Steps to reproduce the issue:**

1.  sudo curl --unix-socket /run/podman/podman.sock http://d/v1.24/libpod/containers/json | jq
``` json  
{
    "Command": [
      "bash"
    ],
...
    "Pod": "8cc10866fa4c22029afc01846525ed96fa726384ad95884b7d99e9a09ed4c642",
    "PodName": "",
...
  }
]
```

**Output of `podman version`:**

```
podman version 2.0.4
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.19-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.19, commit: 5dce9767526ed27f177a8fa3f281889ad509fea7'
  cpus: 4
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: sequioa
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.7.8-200.fc32.x86_64
  linkmode: dynamic
  memFree: 241860608
  memTotal: 11945615360
  ociRuntime:
    name: runc
    package: runc-1.0.0-144.dev.gite6555cc.fc32.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10+dev
      commit: fbdbaf85ecbc0e077f336c03062710435607dbf1
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4742705152
  swapTotal: 6039793664
  uptime: 26h 3m 13.98s (Approximately 1.08 days)
registries:
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: localhost:5000
  search:
  - localhost:5000
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 8
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.14.6
  OsArch: linux/amd64
  Version: 2.0.4

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.4-1.fc32.x86_64
```

### PR DESCRIPTION
**Pull request by mheon**
The ListContainers API previously had a Pod parameter, which determined if pod name was returned (but, notably, not Pod ID, which was returned unconditionally). This was fairly confusing, so we decided to deprecate/remove the parameter and return it unconditionally.

To do this without serious performance implications, we need to avoid expensive JSON decodes of pod configuration in the DB. The way our Bolt tables are structured, retrieving name given ID is actually quite cheap, but we did not expose this via the Libpod API. Add a new GetName API to do this.

Fixes #7214

### CODE REVIEW

File: pkg/bindings/test/containers_test.go [hunk 1]
```diff
@@ -755,8 +755,23 @@ var _ = Describe("Podman containers ", func() {
 		// Validate list container with id filter
 		filters := make(map[string][]string)
 		filters["id"] = []string{cid}
-		c, err := containers.List(bt.conn, filters, bindings.PTrue, nil, nil, nil, nil)
+		c, err := containers.List(bt.conn, filters, bindings.PTrue, nil, nil, nil)
 		Expect(err).To(BeNil())
 		Expect(len(c)).To(Equal(1))
 	})
+
+	It("List containers always includes pod information", func() {
```
Comment (baude) [inline pkg/bindings/test/containers_test.go:763]: dont we need a test in the test/endpoint that would protect this?

Comment (mheon) [reply pkg/bindings/test/containers_test.go:763]: Do we? I think the bindings test captures it adequately - verifies it's in the response?

File: pkg/api/server/register_containers.go [hunk 2]
```diff
@@ -661,11 +661,10 @@ func (s *APIServer) registerContainersHandlers(r *mux.Router) error {
 	//    type: boolean
 	//    description: Include namespace information
 	//    default: false
-	//  - in: query
 	//    name: pod
 	//    type: boolean
 	//    default: false
-	//    description: Include Pod ID and Name if applicable
+	//    description: Ignored. Previously included details on pod name and ID that are currently included by default.
```
Comment (TomSweeneyRedHat) [inline pkg/api/server/register_containers.go:667]: Is this a change that might mess up someone who's still expecting to find the Pod ID and name here?  I don't think so, but I'm not 100% sure.

Comment (rhatdan) [reply pkg/api/server/register_containers.go:667]: They will get the data whether they specify the option or not.

**Comment by rhatdan** [comment]
LGTM

File: pkg/bindings/containers/containers.go [hunk 3]
```diff
@@ -24,7 +24,7 @@ var (
 // the most recent number of containers.  The pod and size booleans indicate that pod information and rootfs
 // size information should also be included.  Finally, the sync bool synchronizes the OCI runtime and
 // container state.
-func List(ctx context.Context, filters map[string][]string, all *bool, last *int, pod, size, sync *bool) ([]entities.ListContainer, error) { // nolint:typecheck
```
Comment (vrothberg) [inline pkg/bindings/containers/containers.go:27]: I prefer to keep it as it would break existing users. I'd rather mark it as deprecated and remove it with 3.0.

Comment (mheon) [reply pkg/bindings/containers/containers.go:27]: This is just in the bindings code; do we consider that public API? The actual API still handles the request without issue.

Comment (baude) [reply pkg/bindings/containers/containers.go:27]: i think we'd be bad players to break existing users. on the other hand, we do not want to mislead them.  how would you feel about leaving it but noting in the docs (above the func) that it is a no-op ?

Comment (vrothberg) [reply pkg/bindings/containers/containers.go:27]: I really want the bindings to be stable. @lsm5 is writing a blog post about them as we wanted to promote the bindings to Go developers. The blog does not use containers.List but could have.

**Comment by mheon** [comment]
Bindings have been restored

**Comment by mheon** [comment]
Rebased, should go green
