### PR TITLE
fix(quadlet): correct replace behavior and prevent duplicates in .app files

### LINKED ISSUE #27960: podman quadlet install/rm issues
### Issue Description

I'm using `podman quadlet install --replace` and `rm` commands.

Is it really intended, that with every '--replace' command the 'application' file (here: `.lara.app`) is appended to?
Like, if you do this several times with the same quadlet files, a `podman quadlet rm .lara.app` gives this output:

```
podman quadlet rm .lara.app
lara-api.container
lara-proxy.container
lara-api.container
lara-proxy.container
lara-api.container
lara-proxy.container
lara-api.container
lara-proxy.container
lara-api.container
lara-proxy.container
lara-api.container
lara-proxy.container
lara-api.container
lara-proxy.container
lara-api.container
lara-proxy.container
lara-api.container
lara-proxy.container
lara-api.container
...etc...
```

Moreover, my expectation of the `install --replace` command is, that the installed quadlet files will be overwritten completely  in `~/.config/containers/systemd`, but this is not the case:

Example:
`/storage/lara/lara/lara-api.container` is:
```
[Unit]
PartOf=lara.target

[Container]
ContainerName=lara-api
HostName=lara-api.sws.internal
Image=harbor.sws.internal:8453/lara/app/api:latest
Volume=/storage/lara/config/ssl/lara-api.sws.internal.crt:/app/ssl/certificate.crt:z,U
Volume=/storage/lara/config/ssl/lara-api.sws.internal.key:/app/ssl/certificate.key:z,U
PublishPort=44363:44363
Pull=newer
Network=lara

[Service]
Restart=always
```
Do a `podman quadlet install --replace /storage/lara/lara`
This is fine the first time.
Now, edit `~/.config/containers/systemd` and add at the end of the service-section:
```
[Service]
Restart=always
a=b
```

Do another `podman quadlet install --replace /storage/lara/lara` (without `rm` first!)
and... the `a=b` is still there?

If this is not reliable (or, i misunderstood the purpose) i'm back to copying quadlet-files by hand into ~/.config. 
Am i missing something?

### Steps to reproduce the issue

Steps to reproduce the issue
see description

### Describe the results you received

see description

### Describe the results you expected

- the app-file '.lara.app' must not have multiple entries of the same app-parts.
- a `--replace` command should really replace the files in ~/.config/containers/systemd`, not only parts of them

### podman info output

```yaml
podman info 
host:
  arch: amd64
  buildahVersion: 1.42.2
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.13-1.fc42.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: '
  cpuUtilization:
    idlePercent: 98.67
    systemPercent: 0.42
    userPercent: 0.91
  cpus: 4
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: cloud
    version: "42"
  emulatedArchitectures:
  - linux/arm
  - linux/arm64
  - linux/arm64be
  - linux/loong64
  - linux/mips
  - linux/mips64
  - linux/ppc
  - linux/ppc64
  - linux/ppc64le
  - linux/riscv32
  - linux/riscv64
  - linux/s390x
  eventLogger: journald
  freeLocks: 2046
  hostname: AZ-CBC-VM-GammaSwat
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 10070
      size: 1
    - container_id: 1
      host_id: 2031616
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 10070
      size: 1
    - container_id: 1
      host_id: 2031616
      size: 65536
  kernel: 6.17.13-200.fc42.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 836608000
  memTotal: 16749846528
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.17.0-1.fc42.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.17.0
    package: netavark-1.17.1-1.fc42.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.17.1
  ociRuntime:
    name: crun
    package: crun-1.26-1.fc42.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.26
      commit: 3241e671f92c33b0c003cd7de319e4f32add6231
      rundir: /run/user/10070/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20251223.g2ba9fd5-1.fc42.x86_64
    version: |
      pasta 0^20251223.g2ba9fd5-1.fc42.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/10070/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 820527104
  swapTotal: 8589930496
  uptime: 614h 55m 40.00s (Approximately 25.58 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  alpha:5001:
    Blocked: false
    Insecure: true
    Location: alpha:5001
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: alpha:5001
    PullFromMirror: ""
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /home/lara/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/lara/.local/share/containers/storage
  graphRootAllocated: 549755813888
  graphRootUsed: 88772018176
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 6
  runRoot: /run/user/10070/containers
  transientStore: false
  volumePath: /home/lara/.local/share/containers/storage/volumes
version:
  APIVersion: 5.7.1
  BuildOrigin: Fedora Project
  Built: 1765324800
  BuiltTime: Wed Dec 10 01:00:00 2025
  GitCommit: f845d14e941889ba4c071f35233d09b29d363c75
  GoVersion: go1.24.10
  Os: linux
  OsArch: linux/amd64
  Version: 5.7.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by amyssnippet**
#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:
- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs) for more information.
- [x] Referenced issues using `Fixes: #27960 ` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Description

This PR fixes two issues with `podman quadlet install`:

1.  **Duplicate Entries:** Previously, `podman quadlet install` would blindly append entries to the hidden `.app` tracking files. Repeated installations (especially with `--replace`) caused the same container file to be listed multiple times in the `.app` file. I added a check to ensure idempotency.
2.  **Replace Failure:** When using `--replace`, the destination file was opened without `O_TRUNC`. If the new quadlet file was shorter than the existing one, trailing data from the old file would persist (e.g., `Restart=always` + `old_garbage`). I added the `os.O_TRUNC` flag to ensure a clean overwrite.

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug where 'podman quadlet install --replace' failed to truncate existing files and caused duplicate entries in application tracking files.
```

fixes: #27960

### CODE REVIEW

**Comment by amyssnippet** [comment]
**BEFORE**

Image

i build the podman because i was not getting the quadlet

```bash
amol@Amols-MacBook-Air podman %podman --help
Manage pods, containers and images

Usage:
  podman [options] [command]

Available Commands:
  attach      Attach to a running container
  auto-update Auto update containers according to their auto-update policy
  build       Build an image using instructions from Containerfiles
  commit      Create new image based on the changed container
  compose     Run compose workloads via an external provider such as docker-compose or podman-compose
  container   Manage containers
  cp          Copy files/folders between a container and the local filesystem
  create      Create but do not start a container
  diff        Display the changes to the object's file system
  events      Show podman system events
  exec        Run a process in a running container
  export      Export container's filesystem contents as a tar archive
  farm        Farm out builds to remote machines
  generate    Generate structured data based on containers, pods or volumes
  healthcheck Manage health checks on containers
  help        Help about any command
  history     Show history of a specified image
  image       Manage images
  images      List images in local storage
  import      Import a tarball to create a filesystem image
  info        Display podman system information
  init        Initialize one or more containers
  inspect     Display the configuration of object denoted by ID
  kill        Kill one or more running containers with a specific signal
  kube        Play containers, pods or volumes from a structured file
  load        Load image(s) from a tar archive
  login       Log in to a container registry
  logout      Log out of a container registry
  logs        Fetch the logs of one or more containers
  machine     Manage a virtual machine
  manifest    Manipulate manifest lists and image indexes
  mount       Mount a working container's root filesystem
  network     Manage networks
  pause       Pause all the processes in one or more containers
  pod         Manage pods
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image from a registry
  push        Push an image to a specified destination
  rename      Rename an existing container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images from local storage
  run         Run a command in a new container
  save        Save image(s) to an archive
  search      Search registry for image
  secret      Manage secrets
  start       Start one or more containers
  stats       Display a live stream of container resource usage statistics
  stop        Stop one or more containers
  system      Manage podman
  tag         Add an additional name to a local image
  top         Display the running processes of a container
  unmount     Unmount working container's root filesystem
  unpause     Unpause the processes in one or more containers
  unshare     Run a command in a modified user namespace
  untag       Remove a name from a local image
  update      Update an existing container
  version     Display the Podman version information
  volume      Manage volumes
  wait        Block on one or more containers

Options:
      --cgroup-manager string       Cgroup manager to use ("cgroupfs"|"systemd") (default "systemd")
      --conmon string               Path of the conmon binary
  -c, --connection string           Connection to use for remote Podman service
      --events-backend string       Events backend to use ("file"|"journald"|"none") (default "journald")
      --help                        Help for podman
      --hooks-dir strings           Set the OCI hooks directory path (may be set multiple times) (default [/usr/share/containers/oci/hooks.d])
      --identity string             path to SSH identity file, (CONTAINER_SSHKEY)
      --imagestore string           Path to the 'image store', different from 'graph root', use this to split storing the image into a separate 'image store', see 'man containers-storage.conf' for details
      --log-level string            Log messages above specified level (trace, debug, info, warn, warning, error, fatal, panic) (default "warn")
      --module strings              Load the containers.conf(5) module
      --network-cmd-path string     Path to the command for configuring the network
      --network-config-dir string   Path of the configuration directory for networks
      --out string                  Send output (stdout) from podman to a file
  -r, --remote                      Access remote Podman service
      --root string                 Path to the graph root directory where images, containers, etc. are stored
      --runroot string              Path to the 'run directory' where all state information is stored
      --runtime string              Path to the OCI-compatible binary used to run containers. (default "runc")
      --runtime-flag stringArray    add global flags for the container runtime
      --ssh string                  define the ssh mode (default "golang")
      --storage-driver string       Select which storage driver is used to manage storage of images and containers
      --storage-opt stringArray     Used to pass an option to the storage driver
      --syslog                      Output logging information to syslog as well as the console (default false)
      --tmpdir string               Path to the tmp directory for libpod state content.
                                    
                                    Note: use the environment variable 'TMPDIR' to change the temporary storage location for container images, '/var/tmp'.
                                     (default "/run/user/1000/libpod/tmp")
      --transient-store             Enable transient container storage
      --url string                  URL to access Podman service (CONTAINER_HOST) (default "unix:///run/user/1000/podman/podman.sock")
  -v, --version                     version for podman
      --volumepath string           Path to the volume directory in which volume data is stored
amol@Amols-MacBook-Air podman %./bin/podman
Manage pods, containers and images

Usage:
  podman [options] [command]

Available Commands:
  artifact    Manage OCI artifacts
  attach      Attach to a running container
  auto-update Auto update containers according to their auto-update policy
  build       Build an image using instructions from Containerfiles
  commit      Create new image based on the changed container
  compose     Run compose workloads via an external provider such as docker-compose or podman-compose
  container   Manage containers
  cp          Copy files/folders between a container and the local filesystem
  create      Create but do not start a container
  diff        Display the changes to the object's file system
  events      Show podman system events
  exec        Run a process in a running container
  export      Export container's filesystem contents as a tar archive
  farm        Farm out builds to remote machines
  generate    Generate structured data based on containers, pods or volumes
  healthcheck Manage health checks on containers
  help        Help about any command
  history     Show history of a specified image
  image       Manage images
  images      List images in local storage
  import      Import a tarball to create a filesystem image
  info        Display podman system information
  init        Initialize one or more containers
  inspect     Display the configuration of object denoted by ID
  kill        Kill one or more running containers with a specific signal
  kube        Play containers, pods or volumes from a structured file
  load        Load image(s) from a tar archive
  login       Log in to a container registry
  logout      Log out of a container registry
  logs        Fetch the logs of one or more containers
  machine     Manage a virtual machine
  manifest    Manipulate manifest lists and image indexes
  mount       Mount a working container's root filesystem
  network     Manage networks
  pause       Pause all the processes in one or more containers
  pod         Manage pods
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image from a registry
  push        Push an image to a specified destination
  quadlet     Allows users to manage Quadlets
  rename      Rename an existing container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images from local storage
  run         Run a command in a new container
  save        Save image(s) to an archive
  search      Search registry for image
  secret      Manage secrets
  start       Start one or more containers
  stats       Display a live stream of container resource usage statistics
  stop        Stop one or more containers
  system      Manage podman
  tag         Add an additional name to a local image
  top         Display the running processes of a container
  unmount     Unmount working container's root filesystem
  unpause     Unpause the processes in one or more containers
  unshare     Run a command in a modified user namespace
  untag       Remove a name from a local image
  update      Update an existing container
  version     Display the Podman version information
  volume      Manage volumes
  wait        Block on one or more containers

Options:
      --cdi-spec-dir stringArray    Set the CDI spec directory path (may be set multiple times) (default [/etc/cdi,/var/run/cdi])
      --cgroup-manager string       Cgroup manager to use ("cgroupfs"|"systemd") (default "systemd")
      --config string               Path to directory containing authentication config file
      --conmon string               Path of the conmon binary
  -c, --connection string           Connection to use for remote Podman service (CONTAINER_CONNECTION)
      --events-backend string       Events backend to use ("file"|"journald"|"none") (default "journald")
      --help                        Help for podman
      --hooks-dir stringArray       Set the OCI hooks directory path (may be set multiple times) (default [/usr/share/containers/oci/hooks.d])
      --identity string             path to SSH identity file, (CONTAINER_SSHKEY)
      --imagestore string           Path to the 'image store', different from 'graph root', use this to split storing the image into a separate 'image store', see 'man containers-storage.conf' for details
      --log-level string            Log messages above specified level (trace, debug, info, warn, warning, error, fatal, panic) (default "warn")
      --module stringArray          Load the containers.conf(5) module
      --network-config-dir string   Path of the configuration directory for networks
      --out string                  Send output (stdout) from podman to a file
  -r, --remote                      Access remote Podman service
      --root string                 Path to the graph root directory where images, containers, etc. are stored
      --runroot string              Path to the 'run directory' where all state information is stored
      --runtime string              Path to the OCI-compatible binary used to run containers. (default "runc")
      --runtime-flag stringArray    add global flags for the container runtime
      --ssh string                  define the ssh mode (default "golang")
      --storage-driver string       Select which storage driver is used to manage storage of images and containers
      --storage-opt stringArray     Used to pass an option to the storage driver
      --syslog                      Output podman-internal logs to syslog as well as the console (default false)
      --tls-ca string               path to TLS certificate Authority PEM file for remote.
      --tls-cert string             path to TLS client certificate PEM file for remote.
      --tls-key string              path to TLS client certificate private key PEM file for remote.
      --tmpdir string               Path to the tmp directory for libpod state content.
                                    
                                    Note: use the environment variable 'TMPDIR' to change the temporary storage location for container images, '/var/tmp'.
                                     (default "/run/user/1000/libpod/tmp")
      --transient-store             Enable transient container storage
      --url string                  URL to access Podman service (CONTAINER_HOST) (default "unix:///run/user/1000/podman/podman.sock")
  -v, --version                     version for podman
      --volumepath string           Path to the volume directory in which volume data is stored
Error: missing command 'podman COMMAND'
amol@Amols-MacBook-Air podman %podman --version 
podman version 4.9.3
amol@Amols-MacBook-Air podman %./bin/podman --version
podman version 6.0.0-dev
amol@Amols-MacBook-Air podman %git status
On branch fix/27977
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        my_quadlet_dir/
        test.container

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by amyssnippet** [comment]
**AFTER**

```bash
amol@Amols-MacBook-Air podman %git status
On branch fix/27977
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   pkg/domain/infra/abi/quadlet.go

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        my_quadlet_dir/
        test.container

no changes added to commit (use "git add" and/or "git commit -a")
amol@Amols-MacBook-Air podman %make bin/podman
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build \
         \
        -ldflags '-X github.com/containers/podman/v6/libpod/define.gitCommit=b60d234da4266d7ce08b950a68dc2c37844b018c-dirty -X github.com/containers/podman/v6/libpod/define.buildInfo=1769650004  -X github.com/containers/podman/v6/libpod/config._installPrefix=/usr/local -X github.com/containers/podman/v6/libpod/config._etcDir=/etc -X github.com/containers/podman/v6/pkg/systemd/quadlet._binDir=/usr/local/bin -X go.podman.io/image/v5/signature/internal/sequoia.sequoiaLibraryDir='""' -X go.podman.io/common/pkg/config.additionalHelperBinariesDir= ' \
        -tags "grpcnotrace   libsqlite3 systemd   seccomp " \
        -o bin/podman ./cmd/podman
test -z "" || chcon -t container_runtime_exec_t bin/podman
amol@Amols-MacBook-Air podman %./bin/podman --version
podman version 6.0.0-dev
amol@Amols-MacBook-Air podman %rm ~/.config/containers/systemd/myservice.container
amol@Amols-MacBook-Air podman %rm ~/.config/containers/systemd/.my_quadlet_dir.app
amol@Amols-MacBook-Air podman %./bin/podman quadlet install my_quadlet_dir
/home/amol/.config/containers/systemd/myservice.container
amol@Amols-MacBook-Air podman %./bin/podman quadlet install --replace my_quadlet_dir
/home/amol/.config/containers/systemd/myservice.container
amol@Amols-MacBook-Air podman %cat ~/.config/containers/systemd/.my_quadlet_dir.app
myservice.container
amol@Amols-MacBook-Air podman %   
amol@Amols-MacBook-Air podman %
                                                                                                                             
amol@Amols-MacBook-Air podman %
```

**Comment by amyssnippet** [comment]
i guess this solves pr solves the issue completely. if any comments then let me know. Thanks!

File: pkg/domain/infra/abi/quadlet.go [hunk 1]
```diff
@@ -339,6 +339,10 @@ func (ic *ContainerEngine) installQuadlet(_ context.Context, path, destName, ins
 
 	if !replace {
 		osFlags |= os.O_EXCL
+	} else {
+		// If replacing, truncate the file to ensure no old content persists	
+        // if the new file is smaller than the original.
+		osFlags |= os.O_TRUNC
```
Comment (jankaluza) [inline pkg/domain/infra/abi/quadlet.go]: This will do the right thing, but even with this the code is not ideal.

If the `fileutils.ReflinkOrCopy` fails for any reason (it is somehow unlikely and rare, but can definitely happen), then we end up with an empty file. Without your patch, we would also end up in the wrong situation - the file could be empty or contain half of data. Therefore I think it is not a blocker for a review, because the situation overall is improved.

If you like to do it "right", you would need to create a new temporary file, write data to it and rename the temporary file to finalPath. The rename is atomic, so this would ensure the new file replaces the old one or the old one remains there in case of any error. There would be no way we could end up with broken file if this method is used.

File: pkg/domain/infra/abi/quadlet.go [hunk 2]
```diff
@@ -384,6 +388,19 @@ func (ic *ContainerEngine) installQuadlet(_ context.Context, path, destName, ins
 // appendStringToFile appends the given text to the specified file.
```
Comment (jankaluza) [inline pkg/domain/infra/abi/quadlet.go]: Can you mention the behavior change in the comment? Something like `... if it does no exist there` and maybe rename it to `appendLineToFile`, because with your change, it more or less treats `text` as a single line.

**Comment by jankaluza** [comment]
Thanks for your contribution.

It would be great to add tests for these two cases.

For the first one, you could extend https://github.com/containers/podman/blob/main/test/system/253-podman-quadlet.bats#L467. I think the only change needed there to reproduce the issue is ensuring the first `quadlet_file` is longer than the second one. Currently, this is not the case.

For the second issue, maybe you can use the very same test with --replace and simply check the .app file?

You can run the tests using `$ hack/bats --rootless 253-podman-quadlet`, more info in test/README.md.

File: pkg/domain/infra/abi/quadlet.go (hunk 1 above)
Comment (amyssnippet) [reply pkg/domain/infra/abi/quadlet.go]: Thanks @jankaluza! That is a great point. I agree that the atomic rename approach (write to temp + rename) is much safer and cleaner than truncating in place, i will update the pr to implement that

**Comment by amyssnippet** [comment]
@jankaluza i guess you changes are made, so have a look. and i am stuck at the ci checks failures, i am not sure why its happening. i am very doubtful to this failures

File: pkg/domain/infra/abi/quadlet.go [hunk 3]
```diff
@@ -315,7 +319,7 @@ func getFileName(resp *http.Response, fileURL string) (string, error) {
 // Perform some minimal validation, but not much.
 // We can't know about a lot of problems without running the Quadlet binary, which we
 // only want to do once.
-func (ic *ContainerEngine) installQuadlet(_ context.Context, path, destName, installDir, assetFile string, isQuadletFile, replace bool) (string, error) {
+func (ic *ContainerEngine) installQuadlet(_ context.Context, path, destName, installDir, assetFile string, isQuadletFile, _ bool) (string, error) {
```
Comment (jankaluza) [inline pkg/domain/infra/abi/quadlet.go]: Hmm, why did you remove the `replace`. We still want to fail with an error in case `replace == false` and the destDir exists.

File: test/system/253-podman-quadlet.bats [hunk 4]
```diff
@@ -464,43 +464,40 @@ EOF
...
+    echo "DEBUG DIR LISTING:" >&3
+    echo "$output" >&3
+
+    # Define the expected app file path explicitly
+    local app_file="$install_dir/.long.container.app"
+
+    # Check if the file exists
+    if [ ! -f "$app_file" ]; then
+        # If .app is missing, check if .asset was created instead (debugging IsExtSupported)
+        if [ -f "$install_dir/.long.container.asset" ]; then
```
Comment (jankaluza) [inline test/system/253-podman-quadlet.bats:510]: This is weird. You end up in the middle of the if statement here without any continuation. That's also why CI tests fail.

File: test/system/helpers.bash [hunk 5]
```diff
@@ -1399,7 +1399,7 @@ function gen-cert-pair {
   cn=$1 key=$2 cert=$3
   shift 3
   openssl req -x509 \
-    -quiet \
```
Comment (jankaluza) [inline test/system/helpers.bash:1402]: This is probably left by a mistake here I guess.

Comment (amyssnippet) [reply test/system/helpers.bash:1402]: yes local test pushed, i will restore the file

File: test/system/253-podman-quadlet.bats (hunk 4 above)
Comment (amyssnippet) [reply test/system/253-podman-quadlet.bats:510]: lemme fix this

File: pkg/domain/infra/abi/quadlet.go (hunk 3 above)
Comment (amyssnippet) [reply pkg/domain/infra/abi/quadlet.go]: now it fails appropriately when replace=false and destination exists

File: test/system/253-podman-quadlet.bats (hunk 4 above)
Comment (amyssnippet) [reply test/system/253-podman-quadlet.bats:510]: the test function was missing its closing brace and content. Added the complete test logic including checking the .app file content, verifying duplicates and proper cleanup

**Comment by amyssnippet** [comment]
@jankaluza everything good now??

**Comment by amyssnippet** [comment]
hi @jankaluza , i have reviewed both the ci failures very carefully and  thats flaky not related to my quadlet changes. i am telling the reasons here

1. which is the debian14 root failure. which is a podman kube play test with reserved Seccomp annotation in yaml and is located at test/e2e/play_kube_test.go:6090 and thats a timeout error in the test, it is declared as hardcoded 90 seconds in test/utils/utils.go:33 and in the test the failure is at `PodmanTestIntegration.Cleanup()` where 3 tasks are executed, podman stop --all -t 0, podman pod rm -fa -t 0, podman rm -fa -t 0. out of these 3 tasks a random one is causing the issue. and thats why this ci is failing.

2. which is the fedora42 one, and is caused by podman kube play [It] test with sysctl defined located at test/e2e/play_kube_test.go:5891, caused by the `rmAll()` function during temp directory cleanup where container rootfs directory contains files, preventing cleanup (container didn't shut down cleanly or overlay unmount failed)

my observation tells these are flaky, whats  your opinion, and my working style also suggests to report these flaky tests as issue in the repo and solve them in a new pr so that code doesnt broke. 

what should i do, guide me, Thanks!

File: pkg/domain/infra/abi/quadlet.go [hunk 6]
```diff
@@ -335,63 +339,95 @@ func (ic *ContainerEngine) installQuadlet(_ context.Context, path, destName, ins
...
-func appendStringToFile(filePath, text string) error {
-	f, err := os.OpenFile(filePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
+// appendLineToFile appends the given text as a line to the specified file,
+// ensuring it does not already exist (idempotency).
+func appendLineToFile(path, text string) error {
+	// 1. Read existing content to check for duplicates
+	content, err := os.ReadFile(path)
+	if err == nil {
+		// If file exists, check if it already has the line
+		if strings.Contains(string(content), text+"\n") || string(content) == text {
```
Comment (jankaluza) [inline pkg/domain/infra/abi/quadlet.go]: I would probably remove the first part of this condition (`strings.Contains(string(content), text+"\n")`). Is there a reason to not match exact lines?

File: test/system/253-podman-quadlet.bats [hunk 7]
```diff
@@ -464,43 +464,54 @@ EOF
...
-    # Verify install output contains the quadlet name on a single line
-    assert "$output" =~ "alpine-quadlet.container" "install output should contain quadlet name"
+@test "podman quadlet install --replace" {
+    # 1. Create a "Long" quadlet file
+    echo "## Long Quadlet File to test truncation" > "$PODMAN_TMPDIR/long.container"
+    for i in {1..10}; do echo "Environment=VAR$i=VAL$i" >> "$PODMAN_TMPDIR/long.container"; done
 
-    # Without replace should fail
-    run_podman 125 quadlet install $quadlet_file
-    assert "$output" =~ "refusing to overwrite" "reinstall without --replace must fail with the overwrite error message"
```
Comment (jankaluza) [inline test/system/253-podman-quadlet.bats:489]: We still need to test that overwrite without --replace fails with an error message.

File: test/system/253-podman-quadlet.bats [hunk 8]
```diff
@@ -464,43 +464,54 @@ EOF
...
 
-    cat > $quadlet_file <<EOF
-[Container]
-Image=$IMAGE
-Exec=sh -c "echo STARTED CONTAINER UPDATED; trap 'exit' SIGTERM; while :; do sleep 0.1; done"
-EOF
-    # With replace should pass and update quadlet
-    run_podman quadlet install --replace $quadlet_file
+    # 3. Overwrite the source file with "Short" content
+    echo "## Short" > "$PODMAN_TMPDIR/long.container"
```
Comment (jankaluza) [inline test/system/253-podman-quadlet.bats]: I would personally genereate valid quadlet file here. If some validation of quadlet files is enabled (or we add it in the future), the test will fail unexpectedly.

File: pkg/domain/infra/abi/quadlet.go [hunk 9]
```diff
@@ -335,63 +339,95 @@ func (ic *ContainerEngine) installQuadlet(_ context.Context, path, destName, ins
...
-	err = fileutils.ReflinkOrCopy(srcFile, file)
+	err = fileutils.ReflinkOrCopy(srcFile, tmpFile)
 	if err != nil {
-		return "", fmt.Errorf("unable to copy file from %s to %s: %w", path, finalPath, err)
+		return "", fmt.Errorf("unable to copy file from %s to %s: %w", path, tmpPath, err)
+	}
+
+	// Close the temp file before rename
+	tmpFile.Close()
+
```
Comment (jankaluza) [inline pkg/domain/infra/abi/quadlet.go]: We should also do chmod here to ensure the temp file has proper permissions:

`if err := os.Chmod(tmpPath, 0o644); err != nil { ... }`

File: pkg/domain/infra/abi/quadlet.go [hunk 10]
```diff
@@ -335,63 +339,95 @@ func (ic *ContainerEngine) installQuadlet(_ context.Context, path, destName, ins
 		return "", fmt.Errorf("%q is not a supported Quadlet file type", filepath.Ext(finalPath))
 	}
 
-	osFlags := os.O_CREATE | os.O_WRONLY
-
-	if !replace {
-		osFlags |= os.O_EXCL
+	// Create a temp file in the same directory as the destination
+	// "quadlet-install-*" is the prefix for the temp file name.
+	destDir := filepath.Dir(finalPath)
```
Comment (jankaluza) [inline pkg/domain/infra/abi/quadlet.go]: I think you could move the whole "create temp file" block after the `if !replace`, so you don't have to clean-up the tmpFile here there, right?

File: pkg/domain/infra/abi/quadlet.go [hunk 11]
```diff
@@ -335,63 +339,95 @@ func (ic *ContainerEngine) installQuadlet(_ context.Context, path, destName, ins
...
+	tmpFile, err := os.CreateTemp(destDir, ".quadlet-install-*")
+	if err != nil {
+		return "", fmt.Errorf("unable to create temporary file: %w", err)
 	}
+	tmpPath := tmpFile.Name()
 
-	file, err := os.OpenFile(finalPath, osFlags, 0o644)
```
Comment (jankaluza) [inline pkg/domain/infra/abi/quadlet.go:344]: I think we should keep the OpenFile(..., O_CREATE|O_WRONLY|O_EXCL) path for the !replace case. Doing os.Stat followed by "tmp-file + rename" is racy: Stat may say the file doesn’t exist, another process can create it, and then our os.Rename would overwrite it even though --replace wasn’t set.

O_EXCL gives us an atomic "create only if absent" guarantee and avoids that TOCTOU issue. For --replace, we can use the tmp-file + os.Rename approach to get atomic replacement semantics (never a partially-written destination).

File: test/system/253-podman-quadlet.bats (hunk 7 above)
Comment (amyssnippet) [reply test/system/253-podman-quadlet.bats:489]: it covers both the failure case (no replace) and the success case (with replace)

**Comment by amyssnippet** [comment]
i did all the changes you recommended still there are failing checks

**Comment by amyssnippet** [comment]
@jankaluza any updates??

**Comment by jankaluza** [comment]
@amyssnippet , sorry, I had to miss your previous comment.

If you open https://github.com/containers/podman/pull/27980/checks?check_run_id=62218815918 and open the "Annotated result" link (  https://api.cirrus-ci.com/v1/artifact/task/6610308623499264/html/sys-podman-debian-14-root-host.log.html), you will find out:

```
[+0412s] not ok 215 [253] podman quadlet install --replace in 2124ms
         # (from function `bail-now' in file test/system/[helpers.bash, line 230](https://github.com/containers/podman/blob/665fb7feca30cbcf9648db5cf4ae59477df2008a/test/system/helpers.bash#L230),
         #  from function `assert' in file test/system/[helpers.bash, line 1083](https://github.com/containers/podman/blob/665fb7feca30cbcf9648db5cf4ae59477df2008a/test/system/helpers.bash#L1083),
         #  in test file test/system/[253-podman-quadlet.bats, line 509](https://github.com/containers/podman/blob/665fb7feca30cbcf9648db5cf4ae59477df2008a/test/system/253-podman-quadlet.bats#L509))
         #   `assert "$output" == "long.container" ".app file should contain the quadlet name"' failed
         #
<+     > # # podman  quadlet install /tmp/CI_QUrD/podman_bats.0rdEGq/long.container
<+402ms> # /etc/containers/systemd/long.container
         #
<+019ms> # # podman  quadlet install --replace /tmp/CI_QUrD/podman_bats.0rdEGq/long.container
<+401ms> # /etc/containers/systemd/long.container
         # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
         # #|     FAIL: .app file should contain the quadlet name
         # #| expected: long.container
         # #|   actual: long.container
         # #|         > long.container
         # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I think that means the `long.container` string is stored twice in the .app file.

File: pkg/domain/infra/abi/quadlet.go [hunk 12]
```diff
@@ -357,41 +387,74 @@ func (ic *ContainerEngine) installQuadlet(_ context.Context, path, destName, ins
...
-func appendStringToFile(filePath, text string) error {
-	f, err := os.OpenFile(filePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
+// appendLineToFile appends the given text as a line to the specified file,
+// ensuring it does not already exist (idempotency).
+func appendLineToFile(path, text string) error {
+	// 1. Read existing content to check for duplicates
+	content, err := os.ReadFile(path)
+	if err == nil {
+		// If file exists, check if it already has the line
+		if string(content) == text {
```
Comment (jankaluza) [inline pkg/domain/infra/abi/quadlet.go]: This is not good. You need to compare line by line, not full content. That's also why test fails.

**Comment by jankaluza** [comment]
I think we are getting closer. I will do the proper review once the tests work, the issue is appendLineToFile.

File: pkg/domain/infra/abi/quadlet.go (hunk 12 above)
Comment (amyssnippet) [reply pkg/domain/infra/abi/quadlet.go]: done

**Comment by amyssnippet** [comment]
@jankaluza i guess now everything is fine. i have checked the ci failures are flaky, kindly have a review

**Comment by amyssnippet** [comment]
@jankaluza any updates??

**Comment by jankaluza** [comment]
I think this looks fine. There is still a possibility for a small race in `appendLineToFile`. In theory the appendLineToFile can be called twice concurrently and both processes can read the file and decide to add new line there at the same time, leading to duplication. But I think this is not a common scenario.

@containers/podman-maintainers , what do you think? I think we did lot of work on this PR and its ready for a review from maintainer now :-).

**Review by mheon — APPROVED** [review]
LGTM. Test looks good, thank you.
Restarted the flake.

**Review by Luap99 — DISMISSED** [review]
@amyssnippet Can you please squash the commits into logical chunks (one commit should be fine), there should be no fixup commits or anything as part of the PR as we merge commits as is and like this it makes no sense right now to look at commits one by one.

(Note I did not do an actual review of the changes)

**Comment by amyssnippet** [comment]
@Luap99 i squashed all commits into a single commit,

the failure is a consistent version mismatch issue. The golangci-lint v2.6.0 was built with Go 1.25, but some files in the codebase require Go 1.26 features, causing the panic.

File: pkg/domain/infra/abi/quadlet.go [hunk 13]
```diff
@@ -335,20 +339,46 @@ func (ic *ContainerEngine) installQuadlet(_ context.Context, path, destName, ins
...
+	defer func() {
+		destFile.Close()
+		// If we are in 'replace' mode and failed before renaming, clean up the temp file
+		if tempPath != "" {
+			// If the rename didn't happen, this cleans up.
+			// If rename happened, Remove returns an error which we ignore or check context.
+			// A simple check is to Stat the tempPath; if it still exists, remove it.
+			if _, err := os.Stat(tempPath); err == nil {
+				os.Remove(tempPath)
+			}
```
Comment (giuseppe) [inline pkg/domain/infra/abi/quadlet.go]: there is no need for the `Stat` here, just `Remove` and ignore errors as you are already doing

Comment (amyssnippet) [reply pkg/domain/infra/abi/quadlet.go]: done!

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by amyssnippet** [comment]
@Luap99 and @jankaluza any updates??

**Comment by jankaluza** [comment]
@amyssnippet , the test fails with AWS issue. I think the solution to that is to rebase the PR against the latest `main` branch. Can you try to do that?

**Comment by amyssnippet** [comment]
> @amyssnippet , the test fails with AWS issue. I think the solution to that is to rebase the PR against the latest `main` branch. Can you try to do that?

Yeah sure

**Comment by amyssnippet** [comment]
+ ./bin/golangci-lint run --build-tags=remote,containers_image_openpgp
panic: file requires newer Go version go1.26 (application built with go1.25) [recovered, repanicked]

File: pkg/domain/infra/abi/quadlet.go [hunk 14]
```diff
@@ -357,41 +384,75 @@ func (ic *ContainerEngine) installQuadlet(_ context.Context, path, destName, ins
...
 	defer srcFile.Close()
 
-	err = fileutils.ReflinkOrCopy(srcFile, file)
+	err = fileutils.ReflinkOrCopy(srcFile, destFile)
 	if err != nil {
 		return "", fmt.Errorf("unable to copy file from %s to %s: %w", path, finalPath, err)
 	}
 
+	// Explicitly close before rename/chmod to flush writes
+	destFile.Close()
```
Comment (Honny1) [inline pkg/domain/infra/abi/quadlet.go]: I suspect this causes a double `Close()` on the file.

File: test/system/253-podman-quadlet.bats [hunk 15]
```diff
@@ -469,43 +469,65 @@ EOF
...
+    local install_dir=$(get_quadlet_install_dir)
+    run cat "$install_dir/long.container"
+    assert "$output" == "$(<$PODMAN_TMPDIR/long.container)" "File was correctly truncated/replaced atomically"
+
+    # --- VERIFICATION 2: CHECK FOR DUPLICATES IN .APP FILE ---
+
+    # DEBUG: List all hidden files to see if we have .asset or .app
+    run ls -la "$install_dir/"
+    echo "DEBUG DIR LISTING:" >&3
+    echo "$output" >&3
```
Comment (Honny1) [inline test/system/253-podman-quadlet.bats]: Do we need debug output for every test run?

**Review by Honny1 — COMMENTED** [review]
Overall, the code looks good, but I have one suspicion. 

I am not sure about adding comments for every single change. This is just my personal opinion, as I prefer a clean code approach, though the information about TOCTOU is great. 

Regarding the CI: please rebase on main and drop the commit that edits the Makefile.

**Comment by amyssnippet** [comment]
@Honny1 now??

**Review by Honny1 — APPROVED** [review]
LGTM, once CI passes.

The CI is failing:

```
time="2026-03-01T09:07:58-06:00" level=info msg="using commit range: 559dce7bf836cf78458cff3aa1410517b4003825..HEAD"
 * 0e5daa47e5 "fixed: quadlet.go with simple check for duplicates and a func to fix race condition and better permission handling" ... FAIL
  - FAIL - commit subject exceeds 90 characters
1 commits to fix
```

**Comment by amyssnippet** [comment]
> LGTM, once CI passes.
> 
> The CI is failing:
> 
> ```
> time="2026-03-01T09:07:58-06:00" level=info msg="using commit range: 559dce7bf836cf78458cff3aa1410517b4003825..HEAD"
>  * 0e5daa47e5 "fixed: quadlet.go with simple check for duplicates and a func to fix race condition and better permission handling" ... FAIL
>   - FAIL - commit subject exceeds 90 characters
> 1 commits to fix
> ```

i shortened the commit msg, it should pass now!!

**Comment by Honny1** [comment]
PTAL @Luap99

**Comment by amyssnippet** [comment]
@Luap99 any reviews?

**Comment by Honny1** [comment]
PTAL @containers/podman-maintainers

**Review by mheon — APPROVED** [review]
