### PR TITLE
Quote systemd DefaultEnvironment Proxy values

### LINKED ISSUE #23277: Podman machine wrongfully escapes special characters in proxy env
### Issue Description

```
% cat ~/.config/containers/containers.conf

[containers]

[engine]

env = [
	'https_proxy=http://192.168.1.21:3128',
	'http_proxy=http://192.168.1.21:3128',
	'no_proxy=localhost,127.0.0.0/24',
]
```

### Steps to reproduce the issue

Steps to reproduce the issue

1. Set env variables in config file:
```
% cat ~/.config/containers/containers.conf

[containers]

[engine]

env = [
	'https_proxy=http://192.168.1.21:3128',
	'http_proxy=http://192.168.1.21:3128',
	'no_proxy=locahost,127.0.0.1/24',
]
```
2. create and start podman machine
3. check settings in VM:
```
$ podman machine ssh
$ cat /etc/systemd/system.conf.d/default-env.conf 
[Manager]
DefaultEnvironment=http_proxy=http://192.168.1.21:3128
DefaultEnvironment=https_proxy=http://192.168.1.21:3128
DefaultEnvironment=no_proxy=localhost\,127.0.0.0/24

```

### Describe the results you received

The value of the env is escaped: `no_proxy=localhost\,127.0.0.0/24`

### Describe the results you expected

Not escaped value (`,` instead of `\,`): `no_proxy=localhost,127.0.0.0/24`

### podman info output

```yaml
host:
  arch: arm64
  buildahVersion: 1.36.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.10-1.fc40.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: '
  cpuUtilization:
    idlePercent: 98.85
    systemPercent: 0.63
    userPercent: 0.52
  cpus: 6
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: coreos
    version: "40"
  eventLogger: journald
  freeLocks: 2048
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.8.11-300.fc40.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 1507635200
  memTotal: 2044387328
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.11.0-1.20240628130058229856.main.10.g5ad6420.fc40.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.12.0-dev
    package: netavark-1.11.0-1.20240702123536284903.main.32.g49fb0c2.fc40.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.12.0-dev
  ociRuntime:
    name: crun
    package: crun-1.15-1.20240708144150212138.main.51.g6c158dd.fc40.aarch64
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: 54f958d21c4e2299eae6b0f4d8b742304540dce6
      rundir: /run/user/501/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240624.g1ee2eca-1.fc40.aarch64
    version: |
      pasta 0^20240624.g1ee2eca-1.fc40.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-2.fc40.aarch64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.5
  swapFree: 0
  swapTotal: 0
  uptime: 0h 1m 20.00s
  variant: v8
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 4496261120
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/501/containers
  transientStore: false
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 5.1.2
  Built: 1720569600
  BuiltTime: Wed Jul 10 02:00:00 2024
  GitCommit: ""
  GoVersion: go1.22.5
  Os: linux
  OsArch: linux/arm64
  Version: 5.1.2
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

First reported in https://github.com/containers/podman-desktop/issues/7894

### PR DESCRIPTION
**Pull request by feloy**
Quote systemd DefaultEnvironment Proxy values, as documented in systemd.conf man page:

```
Example:
DefaultEnvironment="VAR1=word1 word2" VAR2=word3 "VAR3=word 5 6" Sets three variables "VAR1", "VAR2", "VAR3".
```

Double quote is not escaped, as there is no chance it appears in a proxy value. User can still espace it if really necessary

Fixes #23277 
Fixes https://github.com/containers/podman-desktop/issues/7894

#### How to test 

1. Declare proxy env vars in `containers.conf` file, with comma special character in `no_proxy`, for example (please replace proxy IP/port with your own):

```
env = [
	'https_proxy=http://192.168.1.21:3128',
	'http_proxy=http://192.168.1.21:3128',
	'no_proxy=localhost,quay.io',
]
```

2. Create and start a new podman machine, and ssh to it

3. Check that no_proxy and NO_PROXY values are not escaped:

```
$ cat /etc/systemd/system.conf.d/default-env.conf 
[Manager]
DefaultEnvironment="http_proxy=http://192.168.1.21:3128"
DefaultEnvironment="https_proxy=http://192.168.1.21:3128"
DefaultEnvironment="no_proxy=host.containers.internal,quay.io"
DefaultEnvironment="HTTP_PROXY=http://192.168.1.21:3128"
DefaultEnvironment="HTTPS_PROXY=http://192.168.1.21:3128"
DefaultEnvironment="NO_PROXY=host.containers.internal,quay.io"
```

4. Restart podman machine so podman process takes these values into consideration

5. Check that proxy env vars are passed to podman process:

```
$ ps eww `pidof podman`
    PID TTY      STAT   TIME COMMAND
   1282 ?        Ssl    0:00 /usr/bin/podman --log-level=info system service HTTPS_PROXY=http://192.168.1.21:3128 HTTP_PROXY=http://192.168.1.21:3128 NO_PROXY=host.containers.internal,quay.io http_proxy=http://192.168.1.21:3128 https_proxy=http://192.168.1.21:3128 no_proxy=host.containers.internal,quay.io [...]
```

6. From a client (podman outside of VM or podman-desktop):
  - pull an image from docker.io: proxy should log requests
  - pull an image from quay.io: proxy should not log any request
  
#### Does this PR introduce a user-facing change?

Values for proxy env variables won't be escaped anymore. 

```release-note
Changed the way the proxy environment variables are defined in the systemd configuration file. These values were previously escaped for shell input reuse (%q), they are now not escaped.
```

### CODE REVIEW

**Comment by feloy** [comment]
I'll add some tests

**Comment by feloy** [comment]
> I'll add some tests

Tests added, the PR is ready for review

**Comment by rhatdan** [comment]
LGTM

File: pkg/machine/proxyenv/env.go [hunk 1]
```diff
@@ -24,7 +24,7 @@ rm -f $SYSTEMD_CONF $ENVD_CONF $PROFILE_CONF
 
 echo "[Manager]" >> $SYSTEMD_CONF
 for proxy in %s; do
-	printf "DefaultEnvironment=%%q\n" "$proxy"  >> $SYSTEMD_CONF
+	printf "DefaultEnvironment=\"%%s\"\n" "$proxy"  >> $SYSTEMD_CONF
```
Comment (Luap99) [inline pkg/machine/proxyenv/env.go:27]: This will break if the vars contains a quote, I guess I am fine to trade quote is broken vs command is broken because the later is actually used in these vars while the quote most likely is never used.

However please fix the test and add a comma there
https://github.com/containers/podman/blob/77f5b4d67867aa76676442b74b5621e21885038e/pkg/machine/e2e/proxy_test.go#L79

**Review by Luap99 — COMMENTED** [review]
you will need to rebase on latest main to fix the CI

File: pkg/machine/proxyenv/env_test.go [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+		t.Run(tt.name, func(t *testing.T) {
+			for _, e := range tt.args.envs {
+				t.Setenv(e.name, e.value)
+			}
+			got := getProxyScript(tt.args.isWSL)
+			buf := new(bytes.Buffer)
+			_, err := buf.ReadFrom(got)
+			if err != nil {
+				t.Errorf("readFrom: %v", err)
+			}
```
Comment (Luap99) [inline pkg/machine/proxyenv/env_test.go:71]: we already use assert `github.com/stretchr/testify/assert` so please use that instead, i.e.
```
assert.NoError(t, err)
```

File: pkg/machine/proxyenv/env_test.go [hunk 3]
```diff
@@ -0,0 +1,78 @@
...
+			str := buf.String()
+			if str != tt.want {
+				t.Errorf("getProxyScript()\n\n%v\n\nwant\n\n%v", str, tt.want)
+			}
```
Comment (Luap99) [inline pkg/machine/proxyenv/env_test.go:75]: here you can use
```
assert.Equal(t, tt.want, str)
```

**Review by Luap99 — COMMENTED** [review]
please squash your commits into one
changes LGTM otherwise

**Review by Luap99 — APPROVED** [review]
/lgtm

**Comment by TheConen** [comment]
Is this fix already included in the latest 5.2.3 release? I could not find it in the changelog.

**Comment by Luap99** [comment]
It was not backported so it will be in 5.3

**Comment by TheConen** [comment]
Is there something like a timeline / roadmap when 5.3 will be released?

**Comment by Luap99** [comment]
End of October/early November most likely
