### PR TITLE
Safer use of `filepath.EvalSymlinks()` on Windows

### LINKED ISSUE #24557: Podman 5.3.0 win-sshproxy.tid: The system cannot find the file specified. (install via scoop)
### Issue Description

after upgrading to the Podman 5.3.0 (via scoop), when starting the podman machine, there is a message 

API forwarding for Docker API clients is not available due to the following startup failures.
        The system cannot find the path specified.

it turned out that the c:\<user_profile>\.local\share\containers\podman\machine\wsl\podman-machine-default\win-sshproxy.tid  is not created.

Downgrading to Podman 5.2.5 , the message is gone.

Podman machine runs in WSL2.

### Steps to reproduce the issue

As above in the description

### Describe the results you received

As above in the description

### Describe the results you expected

podman machine starts and API forwarding for Docker API  clients on Windows machine works as expected without error message.

### podman info output

```yaml
Podman 5.3.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by l0rd**
The behavior of function `path/filepath.EvalSymlinks()` has changed in Go v1.23:

- https://go-review.googlesource.com/c/go/+/565136
- https://go.dev/doc/go1.23#minor_library_changes
- https://tip.golang.org/doc/godebug

As a consequence, starting with Podman 5.3.0, when installing on Windows (WSL) using [Scoop](https://scoop.sh/#/), Podman fails to start because it fails to find helper binaries. Scoop copies Podman binaries in a folder of type Junction and `EvalSymlinks` returns an error. The problem is described in #24557.

To address this problem, we check if a path is a `Symlink` before calling `EvalSymlinks`, and if it's not (hard links, mount points, or canonical files), we call `path/filepath.Clean` for consistency. In fact, `path/filepath.EvalSymlinks`, after evaluating a path, calls `Clean`, too.

Fixes #24557

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug that prevented Podman from starting when installed using Scoop on Windows.
```

### CODE REVIEW

File: pkg/machine/machine_windows_test.go [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+//   - path: The path where the new item will be created.
+//   - itemType: The type of the item to be created (e.g., "File", "SymbolicLink", "Junction").
+//   - target: The target for the new item, if applicable.
+func CreateNewItemWithPowerShell(path string, itemType string, target string) {
+	var pwshCmd string
+	pwshCmd = "New-Item -Path " + path + " -ItemType " + itemType
+	if target != "" {
+		pwshCmd += " -Target " + target
+	}
+	cmd := exec.Command("pwsh", "-Command", pwshCmd)
```
Comment (Luap99) [inline pkg/machine/machine_windows_test.go:28]: please add 
```
cmd.Stdout = os.Stdout
cmd.Stderr = os.Stderr
```
Otherwise any output from the command is hidden and any error message are not shown making it impossible to debug.

File: pkg/machine/machine_windows_test.go [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+	if err := cmd.Run(); err != nil {
+		log.Fatal(err)
```
Comment (Luap99) [inline pkg/machine/machine_windows_test.go:30]: `log.Fatal()` is not how to deal with errors in tests
The proper go std thing is to use `t.Fatal()` however I suggest you switch to using the assert/require package instead.
```
err := cmd.Run()
require.NoError(t, err)
```

same in all other palces here

File: pkg/machine/machine_windows_test.go [hunk 3]
```diff
@@ -0,0 +1,137 @@
...
+// The old behavior of filepath.EvalSymlinks can be tested with
+// the directive "//go:debug winsymlink=0" and replacing EvalSymlinksOrClean()
+// with filepath.EvalSymlink().
+func TestEvalSymlinksOrClean(t *testing.T) {
+	// Create a temporary directory to store the normal file
+	normalFileDir, err := os.MkdirTemp("", "")
+	if err != nil {
+		log.Fatal(err)
+	}
+	defer os.RemoveAll(normalFileDir)
```
Comment (Luap99) [inline pkg/machine/machine_windows_test.go:48]: just use `t.TempDir()` it will clean up automatically

File: pkg/machine/machine_windows_test.go [hunk 4]
```diff
@@ -0,0 +1,137 @@
...
+	CreateNewItemWithPowerShell(mountPoint, "Junction", normalFileDir)
+
+	// Replaces the backslashes with forward slashes in the normal file path
+	normalFileWithBadSeparators := filepath.ToSlash(normalFile)
+
+	tests := []struct {
+		name     string
+		filePath string
+		want     string
+		wantErr  bool
```
Comment (Luap99) [inline pkg/machine/machine_windows_test.go:88]: wantErr is always false so it pointless to have that

File: pkg/machine/machine_windows_test.go [hunk 5]
```diff
@@ -0,0 +1,137 @@
...
+			if err != nil && !tt.wantErr {
+				t.Errorf("EvalSymlinksOrClean() failed: %v", err)
+				return
+			}
+			if err == nil && tt.wantErr {
+				t.Fatal("EvalSymlinksOrClean() succeeded unexpectedly")
+			}
+			if got != tt.want {
+				t.Errorf("EvalSymlinksOrClean() = %v, want %v", got, tt.want)
+			}
```
Comment (Luap99) [inline pkg/machine/machine_windows_test.go:134]: here again use assert/require

```
require.NoError(t, err)
assert.Equal(t, tt.want, got)
```

**Comment by Luap99** [comment]
Also I don't think we run any windows/macos unit tests at all in CI. unit tests are only run on linux AFAICT so if we have platform specific test we need to fix that otherwise we are not covered.

File: pkg/machine/machine_windows_test.go (hunk 1 above)
Comment (l0rd) [reply pkg/machine/machine_windows_test.go:31]: fixed thanks

File: pkg/machine/machine_windows_test.go (hunk 2 above)
Comment (l0rd) [reply pkg/machine/machine_windows_test.go]: fixed thanks

File: pkg/machine/machine_windows_test.go (hunk 3 above)
Comment (l0rd) [reply pkg/machine/machine_windows_test.go]: fixed thanks

File: pkg/machine/machine_windows_test.go (hunk 4 above)
Comment (l0rd) [reply pkg/machine/machine_windows_test.go]: fixed thanks

File: pkg/machine/machine_windows_test.go (hunk 5 above)
Comment (l0rd) [reply pkg/machine/machine_windows_test.go]: fixed thanks

**Comment by l0rd** [comment]
> Also I don't think we run any windows/macos unit tests at all in CI. unit tests are only run on linux AFAICT so if we have platform specific test we need to fix that otherwise we are not covered.

I think you are right. If you don't mind, I would not fix it in this PR, though Also, Windows builds are run on Linux too (CI doesn't use `winmake.ps1`), and I would be interested in improving so that instead of cross-compilation, we use the PowerShell script to run the build on Windows + a new target to run unit tests.

**Comment by Luap99** [comment]
> If you don't mind, I would not fix it in this PR, though

Yes that is fine, I wasn't trying to stay that you should fix that right now just that we have a testing gap for platform specific unit tests.

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by mheon** [comment]
LGTM
