### PR TITLE
Use Regexp in volume ls --filter name

### LINKED ISSUE #14583: podman volume list, filtering by wildcard in name
/kind bug

**Description**

According to the [docs](https://github.com/containers/podman/blob/main/docs/source/markdown/podman-volume-ls.1.md) you can use a regex/wildcard for filtering `podman volume list` by name.

**Steps to reproduce the issue:**

```
[user@server ~]$ podman volume create testvolume_1
testvolume_1
[user@server ~]$ podman volume create testvolume_2
testvolume_2
[podmanager@server ~]$ podman volume list --filter name=testvolume*
<emtpy>
```

**Describe the results you expected:**
```
[podmanager@server ~]$ podman volume list --filter name=testvolume*
DRIVER      VOLUME NAME
local       testvolume_1
local       testvolume_2
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Sun May 15 18:45:11 2022
OS/Arch:    linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

### PR DESCRIPTION
**Pull request by boaz0**
closes #14583  
#### Does this PR introduce a user-facing change?

```release-note
Added Regexp support to filtering volumes by name
```

### CODE REVIEW

**Comment by rhatdan** [comment]
This needs glob support not regex support.  This also needs tests added.

You can use filepath.Match I believe.

**Comment by boaz0** [comment]
@rhatdan
Oh, sorry. I will fix this and almost done with the testing.

**Comment by Luap99** [comment]
The man page says regex and the other comands use regex so this is fine.

**Comment by rhatdan** [comment]
Docker supports GLOB and we were looking for compatibility.  We could perhaps support both, but I believe GLOB is always much more easily understood by the average computer user the regex. And working with shell makes the most sense.

**Comment by Luap99** [comment]
I am pretty sure that docker uses regex not glob.

**Comment by rhatdan** [comment]
$ docker volume list --filter name=testvolume_*
DRIVER    VOLUME NAME
local     testvolume_1
local     testvolume_2

A Regex would have only matched testvolume testvolume_ testvolume__ ...
IT should not match 1 and 2.

**Comment by Luap99** [comment]
No, your regex matches everything which contains `testvolume_` or `testvolume__`. What you want is this regex: `^testvolume_*$`.
Just try out `testvolume_[12]`, it will work because it uses regex not glob

**Comment by rhatdan** [comment]
My understanding of * in regex matches this description from Wikipedia But I am missing something.

```
* | The asterisk indicates zero or more occurrences of the preceding element. For example, ab*c matches "ac", "abc", "abbc", "abbbc", and so on.
-- | --
```

**Comment by edsantiago** [comment]
@boaz0 please rebase on latest main (08f35dab5) to fix CI breakage

**Review by flouthoc — APPROVED** [review]
@boaz0 Could you please squash the commit.

File: test/e2e/volume_ls_test.go [hunk 1]
```diff
@@ -152,6 +152,37 @@ var _ = Describe("Podman volume ls", func() {
...
+		session = podmanTest.Podman([]string{"volume", "ls", "--filter", "name=volumex"})
+		session.WaitWithDefaultTimeout()
+		Expect(session).Should(Exit(0))
+		Expect(session.OutputToStringArray()).To(BeEmpty())
+
+		session = podmanTest.Podman([]string{"volume", "ls", "--filter", "name=volume1"})
+		session.WaitWithDefaultTimeout()
+		Expect(session).Should(Exit(0))
+		Expect(session.OutputToStringArray()).To(HaveLen(2))
+		Expect(session.OutputToStringArray()[1]).To(ContainSubstring(volName1))
```
Comment (nalind) [inline test/e2e/volume_ls_test.go:183]: Can we add a check that filters using `name=volume1*`?

File: test/system/160-volumes.bats [hunk 2]
```diff
@@ -64,6 +64,28 @@ function teardown() {
...
+    for i in 1 2; do
+        myvolume=${prefix}_${i}_${suffix}
+        run_podman volume create $myvolume
+        is "$output" "$myvolume" "output from volume create $i"
+    done
+
+    run_podman volume ls --filter name=${prefix}_1.+ --format "{{.Name}}"
+    is "$output" "${prefix}_1_${suffix}" "--filter name=${prefix}_1.+ shows only one volume"
+
+    run_podman volume ls --filter name=${prefix}* --format "{{.Name}}"
```
Comment (edsantiago) [inline test/system/160-volumes.bats:81]: Since you're adding _regex_, not glob, I would like to see this changed to `name=${prefix}_1*` with a comment loudly stating something like "yes, the '1' is intentional, blah blah this is regex". That will hammer the point to a casual reader who might be expecting globs.

**Review by edsantiago — COMMENTED** [review]
LGTM with a couple of nits.  Nice work.

File: test/e2e/volume_ls_test.go (hunk 1 above)
Comment (boaz0) [reply test/e2e/volume_ls_test.go:183]: Sure we can!

**Comment by flouthoc** [comment]
Failing test was a flake restarted.

File: test/system/160-volumes.bats [hunk 3]
```diff
@@ -64,6 +64,29 @@ function teardown() {
...
+        run_podman volume create $myvolume
+        is "$output" "$myvolume" "output from volume create $i"
+    done
+
+    run_podman volume ls --filter name=${prefix}_1.+ --format "{{.Name}}"
+    is "$output" "${prefix}_1_${suffix}" "--filter name=${prefix}_1.+ shows only one volume"
+
+    # The _1* is intentional as asterisk has different meaning in glob and regexp. Make sure this is regexp
+    run_podman volume ls --filter name=${prefix}_1* --format "{{.Name}}"
+    is "$output" "${prefix}_1_${suffix}" "--filter name=${prefix}_1* shows only one volume"
```
Comment (edsantiago) [inline test/system/160-volumes.bats:83]: This is EXACTLY why I requested the change I requested: because regexps are counterintuitive to many people. `_1*` will (and should) match **BOTH** volumes, because `1*` means "zero or more instances of the character 1`.

Comment (Luap99) [reply test/system/160-volumes.bats:83]: yes we are, docker uses regex and we also use regex for all other commands.
I have no idea where the glob idea comes from, anyway this is the filter line in moby: https://github.com/moby/moby/blob/c17a566b0dc5074de8ce25a88ba1d43e10667d19/api/types/filters/parse.go#L190

Comment (boaz0) [reply test/system/160-volumes.bats]: Yep, my bad. I accidentally copied the wrong line. I updated the expected results.

**Comment by edsantiago** [comment]
LGTM and CI is green; but I'd like one more set of eyeballs simply because anything using regexps is fraught with peril.

File: pkg/domain/filters/volumes.go [hunk 4]
```diff
@@ -17,7 +18,11 @@ func GenerateVolumeFilters(filters url.Values) ([]libpod.VolumeFilter, error) {
 			case "name":
 				nameVal := val
 				vf = append(vf, func(v *libpod.Volume) bool {
-					return nameVal == v.Name()
+					match, err := regexp.MatchString(nameVal, v.Name())
+					if err != nil {
+						return false
+					}
+					return match
```
Comment (nalind) [inline pkg/domain/filters/volumes.go:25]: I think it would be faster to use `regex.Compile()` to compile the expression into a new `Regexp` object outside of the new anonymous filter function.  This would also give us the opportunity to flag any syntax errors while we're still in `GenerateVolumeFilters()`.

The anonymous filter function that's created here would then call that `Regexp` object's `MatchString()` method instead of calling the regexp package's `MatchString()` function, which I expect has to compile the regex every time it's called.

It looks like `libpod.Runtime.Volumes()` will call each of these filter functions for every volume, and that's got to add up.

File: test/system/160-volumes.bats [hunk 5]
```diff
@@ -64,6 +64,29 @@ function teardown() {
...
+        myvolume=${prefix}_${i}_${suffix}
+        run_podman volume create $myvolume
+        is "$output" "$myvolume" "output from volume create $i"
+    done
+
+    run_podman volume ls --filter name=${prefix}_1.+ --format "{{.Name}}"
+    is "$output" "${prefix}_1_${suffix}" "--filter name=${prefix}_1.+ shows only one volume"
+
+    # The _1* is intentional as asterisk has different meaning in glob and regexp. Make sure this is regexp
+    run_podman volume ls --filter name=${prefix}_1* --format "{{.Name}}"
```
Comment (nalind) [inline test/system/160-volumes.bats:82]: Should the "name=" argument be quoted here?

File: pkg/domain/filters/volumes.go (hunk 4 above)
Comment (boaz0) [reply pkg/domain/filters/volumes.go:25]: I thought about it, the problem I still need to pass the pattern which is available only inside the scope of `GenerateVolumeFilters()` - `nameVal := val` which this will be `Compile`d everytime `GenerateVolumeFilters()` is called. Unless, I can "cache" this in a map.

Or maybe I am missing something. Lemme know. Thanks.

File: test/system/160-volumes.bats (hunk 5 above)
Comment (boaz0) [reply test/system/160-volumes.bats:82]: idk. I think not... :man_shrugging:

File: pkg/domain/filters/volumes.go (hunk 4 above)
Comment (nalind) [reply pkg/domain/filters/volumes.go:25]: The anonymous function (I looked it up and it turns out I should have used the phrase "function literal") can access variables defined in `GenerateVolumeFilters()` so long as the function itself is within the scope where the variable exists, as described at https://go.dev/ref/spec#Function_literals.

Comment (boaz0) [reply pkg/domain/filters/volumes.go]: Oh right! This will work because `vfs` holds anonymous functions. Yes, that'll work. Thanks for the suggestions.

**Comment by edsantiago** [comment]
LGTM but there's a merge conflict; you need to rebase.

**Comment by mheon** [comment]
Could be related, but it's a very different presentation than what we saw in that bug. Have we seen this anywhere else?

**Comment by edsantiago** [comment]
This seems surprising, but I've double-checked a different way: `cirrus-flake-grep "sending signal"` finds no relevant hits.

**Comment by mheon** [comment]
I'm going to rerun and hope it goes away, but if we see this again I'll take a more detailed look.

**Comment by edsantiago** [comment]
/hold cancel

It passed on rerun, but I'm betting this is going to come back.

**Comment by edsantiago** [comment]
P.S. thank you @boaz for your initiative and perseverance
