### PR TITLE
fix(artifact): show :latest tag in ls output when no explicit tag given

### LINKED ISSUE #27083: podman artifact add does not default to latest when creating a new artifact without a tag.
### Issue Description

When I create an artifact without a tag, the latest tag does not get added, like they do with container images.  This is surprising and end up with some tagged images and others tagged with "".  I believe it should be consistent with images.

### Steps to reproduce the issue

Steps to reproduce the issue
  podman artifact add quay.io/myimage/myartifact /tmp/foobar.txt

### Describe the results you received

Describe the results you received
REPOSITORY               TAG         DIGEST        SIZE
 quay.io/myimage/myartifact                 9f6c351a7733  637.7MB

### Describe the results you expected

Describe the results you expected
REPOSITORY               TAG         DIGEST        SIZE
 quay.io/myimage/myartifact :latest                9f6c351a7733  637.7MB

### podman info output

```yaml
$ podman info
host:
  arch: amd64
  buildahVersion: 1.41.3
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.13-1.fc42.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: '
  cpuUtilization:
    idlePercent: 97.59
    systemPercent: 0.61
    userPercent: 1.79
  cpus: 32
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: workstation
    version: "42"
  emulatedArchitectures:
  - linux/arm
  - linux/arm64
  - linux/arm64be
  - linux/loong64
  - linux/mips
  - linux/mips64
  - linux/ppc
  - linux/ppc64
  - linux/ppc64le
  - linux/riscv32
  - linux/riscv64
  - linux/s390x
  eventLogger: journald
  freeLocks: 2031
  hostname: danslaptop
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 3267
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 3267
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 6.16.4-200.fc42.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 95734956032
  memTotal: 134688739328
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.16.0-1.fc42.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.16.0
    package: netavark-1.16.1-1.fc42.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.16.1
  ociRuntime:
    name: crun
    package: crun-1.23.1-1.fc42.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.23.1
      commit: d20b23dba05e822b93b82f2f34fd5dada433e0c2
      rundir: /run/user/3267/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /bin/pasta
    package: passt-0^20250805.g309eefd-2.fc42.x86_64
    version: |
      pasta 0^20250805.g309eefd-2.fc42.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/3267/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.3.1-2.fc42.x86_64
    version: |-
      slirp4netns version 1.3.1
      commit: e5e368c4f5db6ae75c2fce786e31eef9da6bf236
      libslirp: 4.8.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.5
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 82h 35m 4.00s (Approximately 3.42 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /home/dwalsh/.config/containers/storage.conf
  containerStore:
    number: 17
    paused: 0
    running: 0
    stopped: 17
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/dwalsh/.local/share/containers/storage
  graphRootAllocated: 2046687182848
  graphRootUsed: 959119060992
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 875
  runRoot: /run/user/3267/containers
  transientStore: false
  volumePath: /home/dwalsh/.local/share/containers/storage/volumes
version:
  APIVersion: 5.6.0
  BuildOrigin: Fedora Project
  Built: 1755216000
  BuiltTime: Thu Aug 14 20:00:00 2025
  GitCommit: da671ef6cfa3fc9ac6225c18f1dd0a70a951e43f
  GoVersion: go1.24.6
  Os: linux
  OsArch: linux/amd64
  Version: 5.6.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by DeveshB-1**
## Description

Fixes #27083

When an artifact is added without an explicit tag (e.g. `quay.io/myimage/myartifact`), the `TAG` column in `podman artifact ls` was empty instead of showing `latest`, unlike container images which default to `:latest`.

## Fix

Add a call to `reference.TagNameOnly()` after parsing the stored artifact name in `outputTemplate`, so the reference is normalised before the tag is extracted. `reference.TagNameOnly` is already imported and used elsewhere in the codebase — this is a one-line display-side fix consistent with how `NewArtifactReference` already normalises on the storage side.

```go
// Before
named, ok := repo.(reference.Named)
...
if tagged, ok := named.(reference.Tagged); ok {
    tag = tagged.Tag()
}
// tag == "" for untagged artifacts → empty TAG column

// After
named = reference.TagNameOnly(named) // normalise: adds :latest if no tag present
if tagged, ok := named.(reference.Tagged); ok {
    tag = tagged.Tag()
}
// tag == "latest" ✓
```

## Testing

```bash
podman artifact add quay.io/myimage/myartifact /tmp/file.txt
podman artifact ls
# REPOSITORY                    TAG     DIGEST         CREATED       SIZE
# quay.io/myimage/myartifact    latest  sha256:abc...  1 minute ago  1.2 kB
```

### CODE REVIEW

**Comment by DeveshB-1** [comment]
cc @baude @rhatdan @mheon - you have recently worked on the artifact area, would appreciate a review when you get a chance.

**Comment by DeveshB-1** [comment]
do look into it

**Comment by DeveshB-1** [comment]
The failing `sys podman rawhide rootless host` check (`119 |060| podman mount no-dereference`) is unrelated to this PR - it exercises `podman mount`, not `podman artifact`, and does not touch any code path modified here. This appears to be a pre-existing flaky test or infrastructure issue on the CI host.

**Comment by DeveshB-1** [comment]
@mheon could you approve the workflow so the full CI can run?

Quick summary of what this PR does: when a user runs `podman artifact add` without an explicit tag (e.g. `podman artifact add localhost/myapp /path/to/file`), the `TAG` column in `podman artifact ls` was showing blank instead of `latest`. The fix normalizes the reference using `reference.TagNameOnly()` before listing, so untagged artifacts consistently show `latest`, matching the behaviour users would expect from Docker/OCI conventions.

Also included an e2e test in `test/e2e/artifact_test.go` to prevent regressions.

The two currently failing checks (`sys podman rawhide rootless host` and `testing-farm:fedora-43-x86_64:podman-fedora`) both fail on `podman mount no-dereference` which is unrelated to artifact listing. Happy to provide more context if needed.

**Review by mheon — APPROVED** [review]

**Comment by mheon** [comment]
@containers/podman-maintainers PTAL

File: cmd/podman/artifact/list.go [hunk 1]
```diff
@@ -104,6 +104,9 @@ func outputTemplate(cmd *cobra.Command, lrs []*entities.ArtifactListReport) erro
 		if !ok {
 			return fmt.Errorf("%q is an invalid artifact name", artifactName)
 		}
+		// Normalize the reference so artifacts stored without an explicit tag
+		// display ":latest" instead of an empty TAG column, matching container image behaviour.
+		named = reference.TagNameOnly(named)
```
Comment (Honny1) [inline cmd/podman/artifact/list.go:109]: Please check this PR comment:
https://github.com/containers/podman/pull/28149#discussion_r2853704931

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
Thanks @DeveshB-1

**Comment by mtrmac** [comment]
The same approach was _rejected_ in #28149, and there is no recorded discussion about why it is <s>not</s> now acceptable. What do we want to do? Revert and re-review?

**Comment by mheon** [comment]
Concur with a revert. Sorry for LGTMing, wasn't aware of earlier discussion.

**Comment by DeveshB-1** [comment]
@mtrmac @mheon - thanks for the context, I wasn't aware of the earlier rejection.

I understand the concern: fixing this at display time means `podman artifact ls` shows `:latest` but other operations (push, inspect, etc.) still operate on the untagged reference, which is inconsistent.

The correct fix would be to normalize the reference at **storage time** - apply `reference.TagNameOnly()` in `NewArtifactReference` (or wherever the name is parsed during `podman artifact add`), so `:latest` is stored from the start and all operations see it consistently.

Happy to open a follow-up PR with that approach. If you'd prefer to revert this one first, that's fine too - just let me know.

**Comment by mtrmac** [comment]
I do think that _if_ we want artifacts’s names to always include a tag or digest, that should be enforced when creating those names. I don’t at this point have an opinion on where exactly that should happen.

**Comment by DeveshB-1** [comment]
@mtrmac agreed - the right place is `NewArtifactReference` in `pkg/domain/infra/abi/artifact.go`, where the name string is first parsed into a reference. Applying `reference.TagNameOnly()` there would normalize `:latest` at creation time, so all subsequent operations (add, ls, push, inspect) see a consistent reference.

I can open a follow-up PR with that fix and revert this one if that's the preferred path.

**Comment by baude** [comment]
plrease revert this.  also, if you have something AI agentish that is doing all these responses, please consider changing your behavior because that is in part what is causing confusion.

**Comment by mtrmac** [comment]
… also, _now that we have users that have untagged references in stores_, do we need to worry about managing such stores if we disable repo-only references?

It would be natural to normalize repo-only references using `TagNameOnly`, but we might end up with a store that contains an artifact that can’t be deleted.

**Comment by DeveshB-1** [comment]
fair point @baude I have been using AI tooling to help with some of the responses and commits. I understand the code and the fix, and I'll be more deliberate going forward

**Comment by DeveshB-1** [comment]
should i revert the pr ?

**Comment by mtrmac** [comment]
Yes, I would appreciate a PR that reverts this and proposes a cleaner fix. (I don’t have a specific clean fix in mind, that would need to be figured out.)

**Comment by DeveshB-1** [comment]
got it

**Comment by Luap99** [comment]
Revert in https://github.com/containers/podman/pull/28459
