### PR TITLE
rootful: do not set XDG_RUNTIME_DIR for cni plugins

### LINKED ISSUE #11725: regression: podman login: root authfile path
#11195 (my guess) broke `podman login`, in the sense that we can no longer share credentials with skopeo.
```console
# env|grep XDG_R
XDG_RUNTIME_DIR=/run/user/0

[podman 3.3]
# podman login quay.io
...
# find /run -name auth.json
/run/user/0/containers/auth.json       <---- this is good. It respects XDG

[podman 3.4.0-0.4.rc1.fc36]
# podman login quay.io
...
# find /run -name auth.json
/run/containers/0/auth.json            <---- this is BAD
```
This is caught by one of the system tests in `150-login.bats`. The test is passing in CI. My gut feel is that CI doesn't set the magic `XDG` envariables.

### PR DESCRIPTION
**Pull request by Luap99**
#### Revert "rootful: unset XDG_RUNTIME_DIR"

This reverts commit 91e21be.

XDG_RUNTIME_DIR is required for the authfile path. We cannot unset it.

Fixes #11725

#### rootful: do not set XDG_RUNTIME_DIR for cni plugins

The dnsname plugin tries to use XDG_RUNTIME_DIR to store files.
podman run will have XDG_RUNTIME_DIR set and thus the cni plugin can use
it. The problems is that XDG_RUNTIME_DIR is unset for the conmon process
for rootful users. This causes issues since the cleanup process is spawned
by conmon and thus not have XDG_RUNTIME_DIR set to same value as podman run.

Because of it dnsname will not find the config files and cannot correctly cleanup.
To fix this we should also unset XDG_RUNTIME_DIR for the cni plugins as rootful.

### CODE REVIEW

**Comment by Luap99** [comment]
@edsantiago PTAL

File: libpod/network/cni/cni_exec.go [hunk 1]
```diff
@@ -67,6 +68,10 @@ func (e *cniExec) ExecPlugin(ctx context.Context, pluginPath string, stdinData [
 	c.Stdout = stdout
 	c.Stderr = stderr
 
+	if !rootless.IsRootless() {
```
Comment (vrothberg) [inline libpod/network/cni/cni_exec.go:71]: Could you drop a comment here? The explanation in the commit message is great!

Comment (Luap99) [reply libpod/network/cni/cni_exec.go:78]: done

**Review by vrothberg — COMMENTED** [review]
LGTM, thank you

@containers/podman-maintainers PTAL

**Comment by rhatdan** [comment]
/lgtm
/hold
This will need to be backported to podman 3.4

**Comment by Luap99** [comment]
We can only backport the revert, it is not possible to backport the actual fix.

**Comment by edsantiago** [comment]
LGTM but I won't have time to actually test it today. Thank you @Luap99 .

/hold cancel
