### PR TITLE
libpod: Don't dereference ctrSpec.Linux if it is nil

### LINKED ISSUE #28289: FreeBSD: nil pointer dereference in Container.NetworkMode() during inspect when network_mode=host via REST API
- podman run --network host works correctly via CLI
- Same invocation via --url unix:///var/run/podman/podman.sock panics
- Container creation succeeds (HTTP 201), crash happens in the subsequent inspect call
- pf is loaded and active on the host
- Crash is in getContainerNetworkInfo → NetworkMode() called on nil *Container receiver
- Exact file: libpod/networking_common.go:225
- podman 5.7.1 on FreeBSD
- [log attached](https://github.com/user-attachments/files/25979417/podman.log)

### PR DESCRIPTION
**Pull request by dfr**
This prevents a nil pointer crash when running network=host containers on a FreeBSD host using podman-remote.

Fixes: #28289

#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

File: libpod/container.go [hunk 1]
```diff
@@ -1459,18 +1459,20 @@ func (c *Container) NetworkMode() string {
...
-			if ns.Type == spec.NetworkNamespace {
-				foundNetNS = true
-				if ns.Path != "" {
-					networkMode = fmt.Sprintf("ns:%s", ns.Path)
-				} else {
-					// We're making a network ns,  but not
-					// configuring with Slirp or CNI. That
-					// means it's --net=none
-					networkMode = "none"
+		if ctrSpec.Linux != nil {
```
Comment (Luap99) [inline libpod/container.go:1462]: how is `--network none` vs `--network host` handled on freebsd spec? In general this change would make it that you display `host` even when created with network `none` or network `ns:/somepath` (though I guess this does not work at all)

**Comment by mheon** [comment]
While I share the question about this doing the right thing with `--net=none` - LGTM otherwise

File: libpod/container.go (hunk 1 above)
Comment (dfr) [reply libpod/container.go:1462]: Right now, `--network=none` is broken - it behaves the same as `--network=host`.

With the FreeBSD OCI runtime extension, it is possible to represent `--network=none` by creating a private vnet for the jail which is not bridged to any network. I have a work-in-progress which adds support for the new FreeBSD OCI runtime bits but its currently blocked waiting for https://github.com/opencontainers/runtime-tools/pull/801 which adds support in the runtime-tools library.

**Review by mheon — APPROVED** [review]

**Review by Luap99 — APPROVED** [review]
LGTM
