### PR TITLE
bindings: fix handling of env secrets in remote builds

### LINKED ISSUE #27494: podman build --secrets not storing secrets
### Issue Description

I can't get secrets to work. I'm trying to follow the documentation as [described here](https://docs.podman.io/en/v5.6.2/markdown/podman-build.1.html#:~:text=secret%3Did%3Dmysecret%20.-,Build%20an%20image%20using%20a%20secret%20stored%20in%20an%20environment%20variable,%24%20podman%20build%20%2D%2Dsecret%3Did%3Dmysecret%2Cenv%3DMYSECRET%20.,-%24%20podman%20build%20%2D%2Dsecret) but am unable to reproduce it. I'm not sure if this is a bug, documentation, or a keyboard-chair interface problem.

### Steps to reproduce the issue

```Dockerfile
FROM python:3.10-slim-trixie AS builder
RUN --mount=type=secret,id=mysecret echo $(cat /run/secrets/mysecret)
```

```bash
MYSECRET='qwerty' podman build --secret=id=mysecret,env=MYSECRET . --no-cache
```

### Describe the results you received

```txt
STEP 1/2: FROM python:3.10-slim-trixie AS builder
STEP 2/2: RUN --mount=type=secret,id=mysecret echo $(cat /run/secrets/mysecret)

COMMIT
--> 256d6061a45d
256d6061a45d300be4aa0928acda4c74fd155f6293e017c57746b2bc94b6e29e
```

### Describe the results you expected

```txt
STEP 1/2: FROM python:3.10-slim-trixie AS builder
STEP 2/2: RUN --mount=type=secret,id=mysecret echo $(cat /run/secrets/mysecret)
qwerty
COMMIT
--> 256d6061a45d
256d6061a45d300be4aa0928acda4c74fd155f6293e017c57746b2bc94b6e29e
```

### podman info output

```yaml
Client:
  APIVersion: 5.6.2
  BuildOrigin: brew
  Built: 1759243846
  BuiltTime: Tue Sep 30 16:50:46 2025
  GitCommit: ""
  GoVersion: go1.25.1
  Os: darwin
  OsArch: darwin/arm64
  Version: 5.6.2
host:
  arch: arm64
  buildahVersion: 1.40.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.12-3.fc41.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 99.46
    systemPercent: 0.26
    userPercent: 0.28
  cpus: 6
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: coreos
    version: "41"
  eventLogger: journald
  freeLocks: 2031
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.12.13-200.fc41.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 1110319104
  memTotal: 3791691776
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.14.0-1.fc41.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.14.0
    package: netavark-1.14.0-1.fc41.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.14.0
  ociRuntime:
    name: crun
    package: crun-1.20-2.fc41.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.20
      commit: 9c9a76ac11994701dd666c4f0b869ceffb599a66
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20250121.g4f2c8e7-2.fc41.aarch64
    version: |
      pasta 0^20250121.g4f2c8e7-2.fc41.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: unix:///run/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.3.1-1.fc41.aarch64
    version: |-
      slirp4netns version 1.3.1
      commit: e5e368c4f5db6ae75c2fce786e31eef9da6bf236
      libslirp: 4.8.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.5
  swapFree: 0
  swapTotal: 0
  uptime: 2h 34m 5.00s (Approximately 0.08 days)
  variant: v8
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 0
    stopped: 6
  graphDriverName: overlay
  graphOptions:
    overlay.additionalImageStores:
    - /usr/lib/containers/storage
    overlay.imagestore: /usr/lib/containers/storage
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 28032839680
  graphRootUsed: 25529393152
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 142
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 5.5.2
  BuildOrigin: 'Copr: packit/containers-podman-26503'
  Built: 1750723200
  BuiltTime: Tue Jun 24 02:00:00 2025
  GitCommit: e7d8226745ba07a64b7176a7f128e4ef53225a0e
  GoVersion: go1.23.10
  Os: linux
  OsArch: linux/arm64
  Version: 5.5.2
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

macoOS 26

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ZuhairM7**
Previously, using --secret=id=foo,env=BAR in remote mode would fail because the client sent the env var name to the server, which tried to resolve it locally. This patch modifies the client to resolve the environment variable locally, write it to a temp file, and send it as a file-based secret.

This aligns Podman's remote behavior with Docker's behavior and ensures secrets are correctly passed to the build container.

Test to verify fix:
`export MYSECRET='qwerty'
podman build --secret=id=mysecret,env=MYSECRET -f - . <<EOF
FROM alpine
RUN --mount=type=secret,id=mysecret cat /run/secrets/mysecret
EOF`

Before (Remote Client): The secret is empty because the server cannot find MYSECRET in its environment.
`STEP 1/2: FROM alpine
STEP 2/2: RUN --mount=type=secret,id=mysecret cat /run/secrets/mysecret
COMMIT
--> 256d6061a45d`

After (Remote Client): The client resolves MYSECRET to qwerty and sends it to the server.
`STEP 1/2: FROM alpine
STEP 2/2: RUN --mount=type=secret,id=mysecret cat /run/secrets/mysecret
qwerty
COMMIT
--> d5c40b8863ce`

Fixes #27494

#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
Fixed an issue where `podman build --secret ... env=VAR` failed in remote mode (e.g., macOS) by correctly resolving environment variables on the client side.
```

### CODE REVIEW

**Review by lsm5 — COMMENTED** [review]
@ZuhairM7 thanks for the PR. 

For fixing the `DCO` job, you'll need to signoff on your commit.
Please also check out the `Validate source code changes` job failure. That needs to get fixed to get the other jobs moving.

Can you also add a test?

File: pkg/bindings/images/build.go [hunk 1]
```diff
@@ -637,6 +637,20 @@ func prepareSecrets(secrets []string, contextDir string, tempManager *remote_bui
 					// add tmp file to context dir
 					tarContent = append(tarContent, tmpSecretFilePath)
 
+					modifiedSrc := fmt.Sprintf("src=%s", filepath.Base(tmpSecretFilePath))
+					modifiedOpt = append(modifiedOpt, modifiedSrc)
+				}  else if opt == "env" {
+					// read specified env into a tmp file
+					// move tmp file to tar and change secret source to relative tmp file
+					secretVal := os.Getenv(val)
+					tmpSecretFilePath, err := tempManager.CreateTempFileFromReader(contextDir, "podman-build-secret-*", strings.NewReader(secretVal))
```
Comment (mheon) [inline pkg/bindings/images/build.go:647]: Looks like this could leak - a `defer os.Remove(...)` after the error check would fix that

Comment (Honny1) [reply pkg/bindings/images/build.go:647]: Cleanup is handled by `TempFileManager`.

**Review by Honny1 — COMMENTED** [review]
Thanks, it looks good, except for the thing the others mentioned. I fixed the release notes in the PR description.

**Review by ninja-quokka — COMMENTED** [review]
Thanks for your first patch!

 It looks good to me and I would approve it once a test is added like @lsm5 mentioned, `test/e2e/build_test.go` looks like a good place to me.

This function could do with a refactor some time in the future.

File: test/e2e/build_test.go [hunk 2]
```diff
@@ -99,6 +99,19 @@ var _ = Describe("Podman build", func() {
 		Expect(session).Should(ExitCleanly())
 	})
 
+	It("podman build with a secret from env", func() {
+		os.Setenv("MYSECRET", "somesecret")
+		defer os.Unsetenv("MYSECRET")
+		session := podmanTest.Podman([]string{"build", "-f", "build/Containerfile.with-secret", "-t", "secret-test", "--secret", "id=mysecret,env=MYSECRET", "build/"})
```
Comment (Honny1) [inline test/e2e/build_test.go]: Use `podmanTest.PodmanExitCleanly` to simplify waiting and exit code verification.

File: test/e2e/build_test.go [hunk 3]
```diff
@@ -99,6 +99,19 @@ var _ = Describe("Podman build", func() {
...
+		session.WaitWithDefaultTimeout()
+		Expect(session).Should(ExitCleanly())
+		Expect(session.OutputToString()).To(ContainSubstring("somesecret"))
+
+		session = podmanTest.Podman([]string{"rmi", "secret-test"})
```
Comment (Honny1) [inline test/e2e/build_test.go]: Ditto

File: test/e2e/build_test.go [hunk 4]
```diff
@@ -99,6 +99,15 @@ var _ = Describe("Podman build", func() {
 		Expect(session).Should(ExitCleanly())
 	})
 
+	It("podman build with a secret from env", func() {
+		os.Setenv("MYSECRET", "somesecret")
+		defer os.Unsetenv("MYSECRET")
```
Comment (ninja-quokka) [inline test/e2e/build_test.go:104]: Nice, we do unset some env vars on every test but not this one so it's good to unset it.

https://github.com/containers/podman/blob/4eaff6fe224bf77a4b8c732060d1da3cfec6d85d/test/e2e/common_test.go#L137-L139

**Review by ninja-quokka — APPROVED** [review]
/lgtm

**Comment by ninja-quokka** [comment]
Hey @containers/podman-maintainers , could you please take a look at this one when you get a chance. Not sure about the failing testfarm test, looks unrelated to me.

**Review by Honny1 — COMMENTED** [review]
LGTM. I reran the failed Packit tests.

**Review by Honny1 — APPROVED** [review]
LGTM

**Comment by Fryguy** [comment]
Does this fix https://github.com/containers/podman/issues/17382 ?

**Comment by Honny1** [comment]
I think so, I will check that.

**Comment by Fhoerth** [comment]
Hi everyone, thank you for addressing this issue.

  I'm still experiencing this bug on macOS with Podman 5.7.1 (released after this PR was merged).

  **System info:**
  podman version 5.7.1
  macOS (podman machine)
  I recreated the podman machine after upgrading to version `5.7.1`

  **Test command:**
  ```bash
MYSECRET='qwerty' podman build  --no-cache --secret=id=mysecret,env=MYSECRET -f - . <<'EOF'
FROM alpine
RUN --mount=type=secret,id=mysecret cat /run/secrets/mysecret
EOF

  Result (empty secret):
  STEP 1/2: FROM alpine
  STEP 2/2: RUN --mount=type=secret,id=mysecret cat /run/secrets/mysecret
  COMMIT
  --> 5147b598b5e4
```

 **Expected result:**
  The secret should contain qwerty.

  Is there additional configuration needed, or was this fix not included in the 5.7.1 release?

**Comment by Honny1** [comment]
Suspect this wasn't backported. Should we backport to v5.8?

cc @mheon @TomSweeneyRedHat

**Comment by mheon** [comment]
The fix will be in 5.8
