### PR TITLE
podman logs honor stderr correctly

### LINKED ISSUE #8683: podman logs writes stderr to stdout
/kind bug

**Description**

`podman logs` writes stderr logs to stdout. This is incompatible with `docker logs`. Applications that parse the stderr of `docker logs` hang.

**Steps to reproduce the issue:**

1. `id=$(podman run -d --rm -e POSTGRES_PASSWORD=password postgres:13-alpine)`

2. `podman logs -f $id >/dev/null`

**Describe the results you received:**

Output is empty

**Describe the results you expected:**

Output contains the line `database system is ready to accept connections`

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.6
Git Commit:   a0d478edea7f775b7ce32f8eb1a01e75374486cb
Built:        Tue Dec  8 22:48:23 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 35a2fa83022e56e18af7e6a865ba5d7165fa2a4a'
  cpus: 12
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: desk
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 100000
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 100000
  kernel: 5.9.10-arch1-1
  linkmode: dynamic
  memFree: 380436480
  memTotal: 16800301056
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc92
      commit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 0
  swapTotal: 0
  uptime: 315h 53m 15.93s (Approximately 13.12 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /home/julian/.config/containers/storage.conf
  containerStore:
    number: 11
    paused: 0
    running: 4
    stopped: 7
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fusermount3 version: 3.10.0
        fuse-overlayfs: version 1.3
        FUSE library version 3.10.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/julian/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 6
  runRoot: /run/user/1000/containers
  volumePath: /home/julian/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607464103
  BuiltTime: Tue Dec  8 22:48:23 2020
  GitCommit: a0d478edea7f775b7ce32f8eb1a01e75374486cb
  GoVersion: go1.15.6
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Name            : podman
Version         : 2.2.1-1
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/libpod
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : cni-plugins  conmon  containers-common  device-mapper  iptables  libseccomp  runc  slirp4netns  libsystemd  fuse-overlayfs  libgpgme.so=11-64
Optional Deps   : podman-docker: for Docker-compatible CLI
                  btrfs-progs: support btrfs backend devices [installed]
                  catatonit: --init flag support
                  crun: support for unified cgroupsv2 [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 79,09 MiB
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : 2020-12-08T22:48:23 CET
Install Date    : 2020-12-10T16:19:21 CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

### PR DESCRIPTION
**Pull request by Luap99**
Make the ContainerLogsOptions support two io.Writers,
one for stdout and the other for stderr. The logline already
includes the information to which Writer it has to be written.

Fixes #8683

### CODE REVIEW

File: pkg/domain/infra/tunnel/containers.go [hunk 1]
```diff
@@ -360,31 +360,35 @@ func (ic *ContainerEngine) ContainerCreate(ctx context.Context, s *specgen.SpecG
...
 	}()
 
 	for {
 		select {
 		case <-ctx.Done():
 			return err
-		case line := <-outCh:
-			_, _ = io.WriteString(options.Writer, line+"\n")
+		case line := <-stdoutCh:
+			_, _ = io.WriteString(options.StdoutWriter, line+"\n")
```
Comment (mheon) [inline pkg/domain/infra/tunnel/containers.go:389]: Is this safe if `options.StdoutWriter` is nil? Or do we need to check for that?

Comment (Luap99) [reply pkg/domain/infra/tunnel/containers.go]: Yes we need to check for that. Good catch

**Comment by rhatdan** [comment]
LGTM

**Comment by zhangguanzhang** [comment]
LGTM

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL
@mheon PTAL
