### PR TITLE
Vendor `c/common:8483ef6022b4`

### LINKED ISSUE #23331: race: completion: Top layer ... not found ... storage may be corrupted
Another parallel-system-test flake in command completion, seen in [f39 rootless](https://api.cirrus-ci.com/v1/artifact/task/4663193191055360/html/sys-podman-fedora-39-rootless-host-boltdb.log.html):
```
<+048ms> # $ podman __completeNoDesc  image tag
<+097ms> # [Debug] 2 arg(s), received 1
         # time="2024-07-18T12:56:33-05:00" level=warning msg="Top layer f6adb48d9895082456c5aa8074e44f3d32852702f03d54110bb34f01bb8821c0 of image 5fd625cf9c7cb8392d7acb93aac1276dd4fcb0c06ebb891485d01384f99932dc not found in layer tree. The storage may be corrupted, consider running `podman system reset`."
         # localhost/i_t109-kniryp3x:58ibj
         # quay.io/libpod/testimage:20240123
         # localhost/podman-pause:5.2.0-dev-1721323759
         # quay.io/libpod/systemd-image:20240124
         # :4
         # Completion ended with directive: ShellCompDirectiveNoFileComp
         # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
         # #| FAIL: Command succeeded, but issued unexpected warnings
         # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I haven't tried to look for a reproducer yet.

### PR DESCRIPTION
**Pull request by Honny1**
This PR vendor pre-release version of `c/common:8483ef6022b4` fixes #23331. It also adapts the code to the new `c/common/libimage` API.

 fixes: #23331

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
Please add the PR description also in the commit message.

**Comment by Honny1** [comment]
Should I include the part about `user-facing change`?

**Comment by Luap99** [comment]
> Should I include the part about `user-facing change`?

Not needed IMO, although you could add "fixed a race in image listing that printed spurious warnings" or something like this

**Comment by Honny1** [comment]
@Luap99 I have fixed the problem.

**Review by Luap99 — APPROVED** [review]
LGTM
@mtrmac PTAL

File: pkg/domain/infra/abi/images.go [hunk 1]
```diff
@@ -170,7 +170,14 @@ func (ir *ImageEngine) Mount(ctx context.Context, nameOrIDs []string, opts entit
...
 		listImagesOptions.Filters = []string{"readonly=false"}
 	}
-	images, err := ir.Libpod.LibimageRuntime().ListImages(ctx, nameOrIDs, listImagesOptions)
+
+	var images []*libimage.Image
+	var err error
+	if len(nameOrIDs) > 0 {
+		images, err = ir.Libpod.LibimageRuntime().ListImagesByNames(nameOrIDs)
+	} else {
+		images, err = ir.Libpod.LibimageRuntime().ListImages(ctx, listImagesOptions)
```
Comment (mtrmac) [inline pkg/domain/infra/abi/images.go:179]: I think it would be clearer to only set `listImagesOptions` inside the conditional.

… and then, probably, have the `if err != nil` check repeated inside each branch; that’s a bit tedious, but it would be more obvious that we didn’t forget.

---

It seems to me worth trying to combine all the code dealing with `opts.All`/`len(nameOrIDs)`:
- the initial “cannot mix” check
- this lookup
- determining `listMountsOnly`

in a single `switch`. It _might_ end up cleaner. I’m not 100% sure.

---

Whatever happens in this function, please update the `Unmount` code below the same way.

**Review by mtrmac — COMMENTED** [review]
This looks correct to me; some possible cleanups.

**Comment by mheon** [comment]
LGTM once comments from @mtrmac are addressed

File: pkg/domain/infra/abi/images.go [hunk 2]
```diff
@@ -146,8 +146,27 @@ func (ir *ImageEngine) History(ctx context.Context, nameOrID string, opts entiti
 }
 
 func (ir *ImageEngine) Mount(ctx context.Context, nameOrIDs []string, opts entities.ImageMountOptions) ([]*entities.ImageMountReport, error) {
-	if opts.All && len(nameOrIDs) > 0 {
+	listMountsOnly := false
+	var images []*libimage.Image
+	var err error
```
Comment (mtrmac) [inline pkg/domain/infra/abi/images.go:151]: It seems to me this forward declaration can now be removed; `err` is scoped to the individual cases.

File: pkg/domain/infra/abi/images.go [hunk 3]
```diff
@@ -146,8 +146,27 @@ func (ir *ImageEngine) History(ctx context.Context, nameOrID string, opts entiti
...
+	default:
+		listImagesOptions := &libimage.ListImagesOptions{}
+		if opts.All {
+			listImagesOptions.Filters = []string{"readonly=false"}
+		}
+		images, err = ir.Libpod.LibimageRuntime().ListImages(ctx, listImagesOptions)
+		if err != nil {
+			return nil, err
+		}
+		listMountsOnly = !opts.All && len(nameOrIDs) == 0
```
Comment (mtrmac) [inline pkg/domain/infra/abi/images.go:169]: `len() == 0` is implied being in the `default` case now.

File: pkg/domain/infra/abi/images.go (hunk 2 above)
Comment (mtrmac) [reply pkg/domain/infra/abi/images.go:151]: … also in the other copy.

Comment (Honny1) [reply pkg/domain/infra/abi/images.go:151]: The variable `err` must be declared because the compiler has a problem: `images declared and not used`. I don't know how to mix `:=` and `=`.

Comment (mtrmac) [reply pkg/domain/infra/abi/images.go:151]: Ah, OK.

It would be:
- move the `var err error` inside the switch cases
- or
  ```go
  images_, err := …
  if err != nil { …}
  images = images_
  ```

and neither is really elegant, let’s leave it as it is.

**Review by mtrmac — COMMENTED** [review]
/lgtm
