### PR TITLE
fix podman-remote exec regression with v4.8

### LINKED ISSUE #20821: Unmarshalling error when using `podman exec`
### Issue Description

When I use `podman exec ...` for any container, I get the following error:

```
Error: unmarshalling error into &errorhandling.ErrorModel{Because:"", Message:"", ResponseCode:0}, data "Not Found\n": invalid character 'N' looking for beginning of value
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run a detached container: `podman run --name httpd -p 8080:80 -d -i -t docker.io/library/httpd`
2. Try to run podman exec: `podman exec httpd pwd`
3. Error message shows up

### Describe the results you received

An unexpected error message.

### Describe the results you expected

No error message, if the command is run correctly.

### podman info output

```yaml
host:
  arch: arm64
  buildahVersion: 1.32.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.8-2.fc39.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: '
  cpuUtilization:
    idlePercent: 99.33
    systemPercent: 0.34
    userPercent: 0.33
  cpus: 4
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: coreos
    version: "39"
  eventLogger: journald
  freeLocks: 2039
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.5.11-300.fc39.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 3151986688
  memTotal: 6189867008
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.8.0-1.fc39.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.8.0
    package: netavark-1.8.0-2.fc39.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.8.0
  ociRuntime:
    name: crun
    package: crun-1.11.1-1.fc39.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.11.1
      commit: 1084f9527c143699b593b44c23555fb3cc4ff2f3
      rundir: /run/user/501/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20231004.gf851084-1.fc39.aarch64
    version: |
      pasta 0^20231004.gf851084-1.fc39.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-1.fc39.aarch64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 12h 26m 50.00s (Approximately 0.50 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 3
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 6775140352
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 33
  runRoot: /run/user/501/containers
  transientStore: false
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.7.2
  Built: 1698762633
  BuiltTime: Tue Oct 31 15:30:33 2023
  GitCommit: ""
  GoVersion: go1.21.1
  Os: linux
  OsArch: linux/arm64
  Version: 4.7.2
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

ZSH on MacOS

### Additional information

When downgrading to v4.7.2 the issue disappeared.

### PR DESCRIPTION
**Pull request by Luap99**
Commit f48a706abc added a new API endpoint to remove exec session correctly. And the bindings try to call that endpoint for exec every time. Now since client and server must not be the same version this causes a problem if a new 4.8 client calls an older 4.7 server as it has no idea about such endpoint and throws an ugly error. This is a common scenario for podman machine setups.

The client does know the server version so it should make sure to not call such endpoint if the server is older than 4.8.

I added a exec test to the machine tests as this can be reproduced with podman machine as at the moment at least the VM image does not contain podman 4.8. And it should at least make sure podman exec keeps working for podman machine without regressions.

Fixes #20821

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug where podman-remote exec would fail if the server API version is older than 4.8.0.
```

### CODE REVIEW

File: pkg/bindings/containers/exec.go [hunk 1]
```diff
@@ -114,10 +114,15 @@ func ExecStart(ctx context.Context, sessionID string, options *ExecStartOptions)
 
 // ExecRemove removes a given exec session.
 func ExecRemove(ctx context.Context, sessionID string, options *ExecRemoveOptions) error {
+	v := bindings.ServiceVersion(ctx)
+	// The exec remove endpoint was added in 4.8.
+	if v.Major < 4 || (v.Major == 4 && v.Minor < 8) {
+		// Do no call this endpoint as it will not be supported on the server and throw an "NOT FOUND" error.
+		return nil
+	}
```
Comment (vrothberg) [inline pkg/bindings/containers/exec.go:122]: Drive-by-comment:

I feel this should be handled more on the caller side.

A user may accidentally use an older server version than intended.  In this case, the user may assume that there are no leaking exec sessions anymore as it didn't receive an error.

Comment (Luap99) [reply pkg/bindings/containers/exec.go:122]: Well the version is always based on the server so the client has no choice. I do not see why any client would like to get a bogus error here. If anything it leads to even more bug reports for us.

Either way I find it broken to rely on the client to do delete the exec session as mentioned on https://github.com/containers/podman/pull/20405. This approach is way to fragile, no docker API user knows that such endpoint exists.

Comment (vrothberg) [reply pkg/bindings/containers/exec.go:122]: I was probably too ambiguous on what I meant by user.

I am in favor of adding such a conditional check to podman-remote.  But I think the caller of the bindings should handle it.

Another external user of the bindings may be surprised about that check as it can hide the fact the client is (mistakenly) talking to a too old server.

Comment (Luap99) [reply pkg/bindings/containers/exec.go:122]: Sure but retuning the current error is just bogus and a normal user would not be able to interpret such error correctly.

Comment (Luap99) [reply pkg/bindings/containers/exec.go:122]: pushed a second commit to return a custom error type that callers can match for.
This should make it future proof and all new bindings function should then throw this error if the server is to old.

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
Tests not happy.

**Comment by Luap99** [comment]
Looks like all quay.io flakes

**Review by vrothberg — APPROVED** [review]
/lgtm
