### PR TITLE
fix CLI help example indentation

### LINKED ISSUE #28178: Documentation: Examples after the first one are indented inappropriately
### Issue Description

Look at the `podman push -h` output:

```
Push an image to a specified destination
[...]
Usage:
  podman push [options] IMAGE [DESTINATION]

Examples:
  podman push imageID docker://registry.example.com/repository:tag
                podman push imageID oci-archive:/path/to/layout:image:tag

Options:
```

Note how the second example is way off to the right. Source code: https://github.com/containers/podman/blob/509e44a00599e11432a08e7d1bc680c61c98ff30/cmd/podman/images/push.go#L44-L45

```go
	// Command: podman push
	pushCmd = &cobra.Command{
		Use:               "push [options] IMAGE [DESTINATION]",
		// [...]
		Example: `podman push imageID docker://registry.example.com/repository:tag
		podman push imageID oci-archive:/path/to/layout:image:tag`,
	}
```

I suppose, the backticks string were meant to strip leading whitespaces, but they never actually behaved that way in Go?

**This issue is present in many other commands, not just `push`!**

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman push -h`

### Describe the results you received

Second example is indented.

### Describe the results you expected

Second example should not be indented.

### podman info output

```yaml
version:
  APIVersion: 5.5.2
  Built: 1754604929
  BuiltTime: Fri Aug  8 01:15:29 2025
  GitCommit: e7d8226745ba07a64b7176a7f128e4ef53225a0e
  GoVersion: go1.24.5
  Os: linux
  OsArch: linux/amd64
  Version: 5.5.2
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MayorFaj**
## Description
Go backtick (raw) string literals preserve all whitespace verbatim, including tabs and spaces from source code indentation. When Cobra renders the Example field in --help output, multi-line examples that were indented in source appeared with incorrect whitespace, some had tabs, others had 3 spaces, and some were flush-left.

Fix: Added an indentExamples template function registered via cobra.AddTemplateFunc that normalizes all Example strings to exactly 2-space indentation and strips leading/trailing blank lines. Updated the usage template to pipe through this function ({{.Example | indentExamples}}), and converted all ~95 multi-line Example fields across podman to flush-left raw strings so the template function handles indentation uniformly.

This is a defensive, centralized approach, future contributors simply write flush-left example strings in backticks, and the template function ensures correct display.

#### Checklist

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #28178` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
Fixed CLI `--help` output where multi-line command examples were incorrectly indented due to Go raw string literal whitespace being preserved verbatim. All examples now render with consistent 2-space indentation.
```
Fixes: #28178

### CODE REVIEW

**Comment by jankaluza** [comment]
I think I like it. LGTM.

File: cmd/podman/root.go [hunk 1]
```diff
@@ -41,6 +41,31 @@ Description:
...
+// Leading and trailing blank lines are also stripped.
+func indentExamples(s string) string {
+	lines := strings.Split(s, "\n")
+	for i, line := range lines {
+		trimmed := strings.TrimLeft(line, " \t")
+		if trimmed != "" {
+			lines[i] = "  " + trimmed
+		} else {
+			lines[i] = ""
+		}
```
Comment (Honny1) [inline cmd/podman/root.go]: Non-blocking:
```suggestion
		if t := strings.TrimLeft(line, " \t"); t != "" {
			lines[i] = "  " + t
		}
```

File: cmd/podman/root_test.go [hunk 2]
```diff
@@ -19,6 +19,74 @@ func TestFormatError(t *testing.T) {
...
+			expected: "",
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			got := indentExamples(tt.input)
+			if got != tt.expected {
+				t.Errorf("indentExamples() =\n%q\nwant:\n%q", got, tt.expected)
+			}
```
Comment (Honny1) [inline cmd/podman/root_test.go]: Non-blocking:
```suggestion
if got := indentExamples(tt.input); got != tt.expected {
  t.Errorf("got %q, want %q", got, tt.expected)
}
```

**Review by Honny1 — APPROVED** [review]
LGTM overall, just two minor style comments (non-blocking).

**Review by lsm5 — CHANGES_REQUESTED** [review]
change LGTM.

Please squash into a single commit after addressing other comments.

File: cmd/podman/root.go [hunk 3]
```diff
@@ -41,6 +41,31 @@ Description:
 
 {{if or .Runnable .HasSubCommands}}{{.UsageString}}{{end}}`
 
+// indentExamples is a Cobra template function registered via cobra.AddTemplateFunc.
+// It normalizes the indentation of command Example strings so that every
+// non-empty line is indented with exactly two spaces in --help output,
+// regardless of how the raw string literal was indented in source code.
```
Comment (Luap99) [inline cmd/podman/root.go]: Generally speaking should we do that? IMO allowing inconsistently formatted output in the source is a mistake. I would say you could use a test similar cmd/podman/shell_completion_test.go test loops over all commands to verify the examples follow the proper style? i.e. in the source without indentation

Then this function could be a lot simpler by just injecting two spaces always without needed additional checks at runtime

**Comment by TomSweeneyRedHat** [comment]
LGTM
And my OCD loves it!
I've restarted the failing tests.  Definite flakes due to some Google servers being unavailable.

**Comment by TomSweeneyRedHat** [comment]
@MayorFaj, I think you may be running into an issue with our build machines that was fixed earlier today.  Could you please rebase and try pushing again?

**Comment by MayorFaj** [comment]
> LGTM And my OCD loves it! I've restarted the failing tests. Definite flakes due to some Google servers being unavailable.
Glad the cleanup scratches that itch 😄. Appreciate the review

**Comment by MayorFaj** [comment]
> @MayorFaj, I think you may be running into an issue with our build machines that was fixed earlier today. Could you please rebase and try pushing again?

done

File: cmd/podman/root.go [hunk 4]
```diff
@@ -41,6 +41,21 @@ Description:
...
 
+// indentExamples is a Cobra template function registered via cobra.AddTemplateFunc.
+// It prepends two spaces to every non-empty line in a command's Example string
+// so that examples are consistently indented in --help output.
+// Example strings in source must be flush-left (no leading whitespace);
+// this is enforced by TestExampleFormat.
+func indentExamples(s string) string {
+	lines := strings.Split(s, "\n")
+	for i, line := range lines {
+		if line != "" {
```
Comment (danishprakash) [inline cmd/podman/root.go:52]: This will be true for lines that have `\t` or a pre-existing space as well. Have we added a check that prevents users from adding examples with leading whitespace?

Comment (MayorFaj) [reply cmd/podman/root.go:52]: all  `Example` fields have been converted to flush-left (no leading whitespace), and `TestExampleFormat` in root_test.go enforces this going forward. It walks every registered command via parseCommands() and fails if any Example line has leading whitespace

Comment (MayorFaj) [reply cmd/podman/root.go:52]: adding a runtime check (like stripping whitespace) is what we had before. The pattern in the codebase is to enforce code conventions via tests.
see here https://github.com/containers/podman/pull/28196#discussion_r2889756434

**Comment by lsm5** [comment]
@MayorFaj could you PTAL at the failing tests?

File: cmd/podman/root_test.go [hunk 5]
```diff
@@ -19,6 +20,75 @@ func TestFormatError(t *testing.T) {
...
+	for _, childCmd := range cmd.Commands() {
+		checkExampleFormat(t, childCmd)
+	}
+
+	if cmd.Example == "" {
+		return
+	}
+
+	for i, line := range strings.Split(cmd.Example, "\n") {
+		if line != "" && line != strings.TrimLeft(line, " \t") {
```
Comment (Honny1) [inline cmd/podman/root_test.go]: Could this be checked with regex?

File: cmd/podman/root_test.go [hunk 6]
```diff
@@ -19,6 +20,75 @@ func TestFormatError(t *testing.T) {
 	}
 }
 
+// TestExampleFormat walks all registered commands and verifies that
+// Example strings are flush-left (no leading whitespace). The
+// indentExamples template function adds the 2-space indent at render
+// time, so source examples must not contain their own indentation.
+func TestExampleFormat(t *testing.T) {
+	rootCmd := parseCommands()
```
Comment (Honny1) [inline cmd/podman/root_test.go]: I think CI failure is caused by the double registration of commands into the global `rootCmd`.

**Review by Honny1 — CHANGES_REQUESTED** [review]

File: cmd/podman/root_test.go (hunk 5 above)
Comment (MayorFaj) [reply cmd/podman/root_test.go]: IMO, appears this is simpler and more readable than regex, and also avoids the regexp import

**Comment by MayorFaj** [comment]
> @MayorFaj could you PTAL at the failing tests?

all good now, the only failing test is not related to the PR

**Review by Honny1 — APPROVED** [review]
LGTM. I reran the failed tests.

**Review by lsm5 — APPROVED** [review]
LGTM
