### PR TITLE
fix #17244: use /etc/timezone where `timedatectl` is missing on Linux

### LINKED ISSUE #17244: [Bug]: ignition_linux.go failed on systemd-free Linux due to lack of `timedatectl` executable
### Issue Description

My machine is Artix Linux, based on Arch Linux and using OpenRC instead of systemd.

`getLocalTimeZone` in [`ignition_linux.go`](https://github.com/containers/podman/blob/52d5f367b144f755dd20b18d88c5f79bc6b0c3fe/pkg/machine/ignition_linux.go) executes `timedatectl`, which is a part of systemd. Therefore, it failed in my env, and `.ign` was not created.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Use systemd-free Linux.
2. Install Podman and run `podman machine init`

### Describe the results you received

1. The error was:    
    ```console
    Extracting compressed file
    Image resized.
    Error: exec: "timedatectl": executable file not found in $PATH
    ```
2. Additionally, since `podman-machine-default.ign` was not created, running `podman machine start` in the next step also failed with the error:    
    ```console
    Starting machine "podman-machine-default"
    Waiting for VM ...
    Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-x86_64: -fw_cfg name=opt/com.coreos/config,file=/home/(...)/.config/containers/podman/machine/qemu/podman-machine-default.ign: can't load /home/(...)/.config/containers/podman/machine/qemu/podman-machine-default.ign: Failed to open file “/home/(...)/.config/containers/podman/machine/qemu/podman-machine-default.ign”: No such file or directory
    ```

### Describe the results you expected

`podman machine init` is successful with systemd-free Linux.

### podman info output

```shell
OS: Artix Linux with OpenRC x86_64
Podman: 4.3.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

\-

### Additional information

I made a custom Rust script to print my timezone named "timedatectl". After it built and placed in `$PATH`, `podman machine init` succeeded. The `.ign` file was created with content written.

In my opinion, on systemd-free Linux, `exec.Command("timedatectl", "show", "--property=Timezone").Output()` should be replaced with `exec.Command("cat", "/etc/timezone").Output()` in `ignition_linux.go`. For example:

```go
var output
o, err := exec.Command("pidof", "systemd").Output()
if string(o) == "1\n" || err != nil {
	// default
	output, err = exec.Command("timedatectl", "show", "--property=Timezone").Output()
} else {
	// systemd-free
	output, err = exec.Command("cat", "/etc/timezone").Output()
}
```

### PR DESCRIPTION
**Pull request by nabbisen**
#### Does this PR introduce a user-facing change?

```release-note
None
```
[NO NEW TESTS NEEDED]

### CODE REVIEW

File: pkg/machine/ignition_linux.go [hunk 1]
```diff
@@ -1,12 +1,22 @@
...
 func getLocalTimeZone() (string, error) {
-	output, err := exec.Command("timedatectl", "show", "--property=Timezone").Output()
+	var output []byte
+	var err error
+
+	_, lookupErr := exec.LookPath("timedatectl")
+	if lookupErr != nil {
+		output, err = os.ReadFile("/etc/timezone")
+	} else {
+		output, err = exec.Command("timedatectl", "show", "--property=Timezone").Output()
```
Comment (rhatdan) [inline pkg/machine/ignition_linux.go:17]: Why lookpath at all, why not attempt to exec.Command and if it fails with ENOEXISTS attempt to ReadFile?

**Comment by rhatdan** [comment]
@nabbisen you must sign your commit.

git commit -a --amend -s
git push --force

File: pkg/machine/ignition_linux.go (hunk 1 above)
Comment (nabbisen) [reply pkg/machine/ignition_linux.go:17]: > Why lookpath at all, why not attempt to exec.Command and if it fails with ENOEXISTS attempt to ReadFile?

Thank you for your reviewing.

It is because both were thought to be equivalent due to platforms. Also, few nesting of code.

Well, I'll try to impl to check the error first.

Comment (nabbisen) [reply pkg/machine/ignition_linux.go:17]: Update:

I checked if I could catch `ErrNotExist`. Both of the below were false.
In addition, [os/exec](https://pkg.go.dev/os/exec#Error) doesn't seem to return the Error type ?

```go
package main

import (
	"fmt"
	"os"
	"os/exec"
	// "errors"
)

func main() {
	_, err := exec.Command("timedatectl").Output()
	x := os.IsNotExist(err)
	// x := errors.Is(err, os.ErrNotExist)
	fmt.Printf("%v", x)
	// false
}
```

**Comment by nabbisen** [comment]
> @nabbisen you must sign your commit.
> 
> git commit -a --amend -s git push --force

Done.
Excuse me. I missed the last of [Sign your PRs](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs).
Thank you so much.

File: pkg/machine/ignition_linux.go (hunk 1 above)
Comment (rhatdan) [reply pkg/machine/ignition_linux.go:17]:
```
	if output, err = exec.Command("timectl", "show", "--property=Timezone").Output(); errors.Is(err, exec.ErrNotFound) {
		output, err = os.ReadFile("/etc/timezone")
	}
```

Comment (nabbisen) [reply pkg/machine/ignition_linux.go]: > ```
> 	if output, err = exec.Command("timedatectl", "show", "--property=Timezone").Output(); errors.Is(err, exec.ErrNotFound) {
> 		output, err = os.ReadFile("/etc/timezone")
> 	}
> ```

I'm so sorry. I have lots to learn.
Thank you for your really kind suggestion (almost the whole).

I sent PR again.
The re-tests were successful: Fedora 37 (systemd) and Artix (systemd-free).

**Comment by rhatdan** [comment]
Could you amend and repush again, so that the CI/CD system will not require tests.

git commit -a --amend -s
git push --force

**Comment by nabbisen** [comment]
> Could you amend and repush again, so that the CI/CD system will not require tests.
> 
> git commit -a --amend -s git push --force

Sure. Done.

**Comment by nabbisen** [comment]
Readability improved.

```diff
- 	var output []byte
- 	var err error
- 	if output, err = exec.Command("timedatectl", "show", "--property=Timezone").Output(); errors.Is(err, exec.ErrNotFound) {
+ 	output, err := exec.Command("timedatectl", "show", "--property=Timezone").Output()
+ 	if errors.Is(err, exec.ErrNotFound) {
```

**Comment by rhatdan** [comment]
/approve
LGTM
@containers/podman-maintainers PTAL

**Review by vrothberg — APPROVED** [review]
LGTM, thanks!

/lgtm
