### PR TITLE
Fix reference to deprecated types.Info

### LINKED ISSUE #22132: `github.com/docker/docker/api/types.Info` is deprecated and is removed in docker v26
### Issue Description

podman v5.0.0 uses a deprecated field in here

https://github.com/containers/podman/blob/aaa6dc3cc6a670fd707e3188097207af5be4bd31/pkg/api/handlers/types.go#L77

it is removed in docker v26

### Steps to reproduce the issue

Steps to reproduce the issue
1. Upgrade to docker v26
2. Perform the build

### Describe the results you received

The build fails with

```
 github.com/containers/podman/v5/pkg/api/handlers
/root/go/pkg/mod/github.com/containers/podman/v5@v5.0.0/pkg/api/handlers/types.go:77:9: undefined: docker.Info
```

### Describe the results you expected

Build succeeds.

### podman info output

```yaml
podman v5.0.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by baude**
upstream docker folks deprecated types.Info in favor of system.Info.

fixes #22132 and #22117

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by baude** [comment]
the test failure i think is legit ... will look tomorrow.

**Comment by edsantiago** [comment]
The test failure I see it:
```
AssertionError: 'Container' not found in blah blah
```
The PR, as I read it, removes 'Container'.

The string "Container" appears in  https://github.com/containers/podman/blob/5c39ddca5dc7ac026ba4eacfd271450e7d0c7008/test/apiv2/python/rest_api/test_v2_0_0_image.py#L48

**Comment by nalind** [comment]
> The test failure I see it:
> 
> ```
> AssertionError: 'Container' not found in blah blah
> ```
> 
> The PR, as I read it, removes 'Container'.
> 
> The string "Container" appears in
> 
> https://github.com/containers/podman/blob/5c39ddca5dc7ac026ba4eacfd271450e7d0c7008/test/apiv2/python/rest_api/test_v2_0_0_image.py#L48

It looks like the "new" Container field needed to be added to the ImageInspect type rather than the Info type.

**Comment by ashley-cui** [comment]
LGTM

File: pkg/api/handlers/compat/images.go [hunk 1]
```diff
@@ -342,6 +342,7 @@ func GetImage(w http.ResponseWriter, r *http.Request) {
 		utils.Error(w, http.StatusInternalServerError, fmt.Errorf("failed to convert ImageData to ImageInspect '%s': %w", name, err))
 		return
 	}
+	fmt.Println(inspect)
```
Comment (edsantiago) [inline pkg/api/handlers/compat/images.go:345]: debug?

**Review by edsantiago — CHANGES_REQUESTED** [review]

File: pkg/api/handlers/compat/images.go [hunk 2]
```diff
@@ -408,7 +409,7 @@ func imageDataToImageInspect(ctx context.Context, l *libimage.Image) (*handlers.
 		Variant:         "",
 		VirtualSize:     info.VirtualSize,
 	}
-	return &handlers.ImageInspect{ImageInspect: dockerImageInspect}, nil
+	return &handlers.ImageInspect{Container: "", ImageInspect: dockerImageInspect}, nil
```
Comment (nalind) [inline pkg/api/handlers/compat/images.go:412]: That's the default value for a string field, so unless there's a reason to be explicitly setting it that I'm missing, it can be omitted.

**Review by edsantiago — APPROVED** [review]

**Comment by edsantiago** [comment]
LGTM but it's a wee bit more than I can slashlgtm

**Comment by hellt** [comment]
Hi @baude 

there is still entries of docker.Info as of 5.0.3 -- https://github.com/containers/podman/blob/v5.0.3/pkg/api/handlers/types.go#L77
