### PR TITLE
fix: ensure environment variable precedence between env and envFrom

### LINKED ISSUE #27287: kube play does not follow Kubernetes precedence order for env and envFrom
### Issue Description

In Kubernetes, if the same environment variable is defined in both the `envFrom` and `env` sections, the version from `env` takes precedence. With `podman kube play`, the version from the `envFrom` section takes precedence.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create `test.yaml` as follows:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh", "-ec", "sleep infinity"]
      envFrom:
        - configMapRef:
            name: test-config-map
      env:
        - name: MY_ENV_VAR
          value: "2"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config-map
data:
  MY_ENV_VAR: "1"

```
2. Run the pod: `podman kube play test.yaml`
3. Check the value of the environment variable: `podman exec test-pod-test-container /bin/sh -c 'echo $MY_ENV_VAR'`

### Describe the results you received

The value of `MY_ENV_VAR` is `1`. This is the value from the `envFrom` section.

### Describe the results you expected

The expected value of `MY_ENV_VAR` is `2`. This is the value from the `env` section.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.41.5
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.13-1.fc42.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: '
  cpuUtilization:
    idlePercent: 90.45
    systemPercent: 2.22
    userPercent: 7.33
  cpus: 8
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: workstation
    version: "42"
  emulatedArchitectures:
  - linux/arm
  - linux/arm64
  - linux/arm64be
  - linux/loong64
  - linux/mips
  - linux/mips64
  - linux/ppc
  - linux/ppc64
  - linux/ppc64le
  - linux/riscv32
  - linux/riscv64
  - linux/s390x
  eventLogger: journald
  freeLocks: 2043
  hostname: pscmatt
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 16777216
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 16777216
  kernel: 6.16.10-200.fc42.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 5208752128
  memTotal: 67189248000
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.16.0-1.fc42.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.16.0
    package: netavark-1.16.1-1.fc42.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.16.1
  ociRuntime:
    name: crun
    package: crun-1.24-1.fc42.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.24
      commit: 54693209039e5e04cbe3c8b1cd5fe2301219f0a1
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20250919.g623dbf6-1.fc42.x86_64
    version: |
      pasta 0^20250919.g623dbf6-1.fc42.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.3.1-2.fc42.x86_64
    version: |-
      slirp4netns version 1.3.1
      commit: e5e368c4f5db6ae75c2fce786e31eef9da6bf236
      libslirp: 4.8.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.5
  swapFree: 8589922304
  swapTotal: 8589930496
  uptime: 3h 26m 3.00s (Approximately 0.12 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /home/yomatters/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/yomatters/.local/share/containers/storage
  graphRootAllocated: 1998678130688
  graphRootUsed: 260885389312
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 6
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/yomatters/.local/share/containers/storage/volumes
version:
  APIVersion: 5.6.2
  BuildOrigin: Fedora Project
  Built: 1759190400
  BuiltTime: Mon Sep 29 20:00:00 2025
  GitCommit: 9dd5e1ed33830612bc200d7a13db00af6ab865a4
  GoVersion: go1.24.7
  Os: linux
  OsArch: linux/amd64
  Version: 5.6.2
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MayorFaj**
#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

## Changes

- Reversed the processing order in `pkg/specgen/generate/kube/kube.go` to process `envFrom` before `env`
- Added integration test to verify correct precedence behavior

#### Does this PR introduce a user-facing change?

```release-note
Fix `kube play` to follow Kubernetes precedence order where `env` values override `envFrom` values for the same environment variable
```

Fixes #27287

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
LGTM

File: test/e2e/play_kube_test.go [hunk 1]
```diff
@@ -3225,6 +3225,34 @@ var _ = Describe("Podman kube play", func() {
...
+		)))
+
+		podYaml, err := getKubeYaml("pod", pod)
+		Expect(err).ToNot(HaveOccurred())
+
+		yamls := []string{cmYaml, podYaml}
+		err = generateMultiDocKubeYaml(yamls, kubeYaml)
+		Expect(err).ToNot(HaveOccurred())
+
+		kube := podmanTest.Podman([]string{"kube", "play", kubeYaml})
```
Comment (Honny1) [inline test/e2e/play_kube_test.go]: You can simplify this by using `podmanTest.PodmanExitCleanly`.

Comment (MayorFaj) [reply test/e2e/play_kube_test.go]: Done! Changed to use `PodmanExitCleanly`. Thanks for the review!

**Comment by jankaluza** [comment]
LGTM

Thanks for your contribution.

**Comment by martinpitt** [comment]
Cockpit team here. I had a look at the [rawhide failure](https://artifacts.dev.testing-farm.io/0cdeb3c8-3a11-418f-8314-ed6af334d3ee/), and that's just a flake. Please ignore.

**Comment by MayorFaj** [comment]
@Honny1 Reminder please

**Comment by jankaluza** [comment]
@MayorFaj , @Honny1 is away for some time, let's see if I can find out someone else who can move this PR forward.

**Review by giuseppe — APPROVED** [review]
/lgtm
