### PR TITLE
Fix `trust` not using local policy file

### LINKED ISSUE #19073: Podman complaining about missing global policy.json while a local one is present
### Issue Description

I installed Podman through Nix. I have a `policy.json` defined as this in `/home/MYUSER/.config/containers/policy.json`:

```json
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ]
}
```

 I don't have an `/etc/containers/policy.json`. 

If i issue a `podman image trust show` I get an `Error: open /etc/containers/policy.json: no such file or directory` . I checked running strace and I do see that `newfstatat(AT_FDCWD, "/home/MYUSER/.config/containers/policy.json", {st_mode=S_IFREG|0644, st_size=93, ...}, 0) = 0` but still get the error of the missing /etc/containers/policy.json file.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Have a local (/home/MYUSER/.config/containers/policy.json) policy file
2. Run `podman image trust show`
3. See it fail with error message regarding missing /etc/containers/policy.json

### Describe the results you received

I get an `Error: open /etc/containers/policy.json: no such file or directory`.

```bash
$ podman image trust set -t reject default
Error: open /etc/containers/policy.json: permission denied
```

If we enforce with `sudo` then /etc/containers/policy.json gets created.

### Describe the results you expected

I expect the local `policy.json` to be sufficient and be the only file read.

### podman info output

```yaml
❯❯❯ podman version
Client:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.5
Built:        Tue Jan  1 01:00:00 1980
OS/Arch:      linux/amd64

❯❯❯ podman info
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /nix/store/bbxml9qrpvlq8hijvamqwd2mk0wcknsw-conmon-2.1.7/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 88.9
    systemPercent: 3.33
    userPercent: 7.77
  cpus: 8
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: kde
    version: "35"
  eventLogger: journald
  hostname: MyMachine
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.0.12-100.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1067839488
  memTotal: 16423763968
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: Unknown
    path: /nix/store/pbmmg9k43qdj7ji7kj1dc2wz67dd86ns-crun-1.8.5/bin/crun
    version: |-
      crun version 1.8.5
      commit: 1.8.5
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /nix/store/kwdv5jw8awxw31i25i4l93qgy43srr20-slirp4netns-1.2.0/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 8513908736
  swapTotal: 8589930496
  uptime: 7h 33m 40.00s (Approximately 0.29 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/MYUSER/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/MYUSER/.local/share/containers/storage
  graphRootAllocated: 510389125120
  graphRootUsed: 218087268352
  graphStatus: {}
  imageCopyTmpDir: /tmp/nix-shell.EeYf91
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/MYUSER/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.1
  Built: 315532800
  BuiltTime: Tue Jan  1 01:00:00 1980
  GitCommit: ""
  GoVersion: go1.20.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Installed Fedora through Nix package manager 

### Additional information

nothing

### PR DESCRIPTION
**Pull request by ariasmn**
When running the `trust` command, only the global policy.json file was being taken into account.

Fixes #19073

[NO NEW TESTS NEEDED]

#### Does this PR introduce a user-facing change?

```release-note
'trust' command can now use the local policy.json file
```

### CODE REVIEW

File: pkg/trust/policy.go [hunk 1]
```diff
@@ -55,6 +59,10 @@ type genericRepoMap map[string]json.RawMessage
 // DefaultPolicyPath returns a path to the default policy of the system.
 func DefaultPolicyPath(sys *types.SystemContext) string {
 	systemDefaultPolicyPath := config.DefaultSignaturePolicyPath
+	userPolicyFilePath := filepath.Join(homedir.Get(), userPolicyFile)
+	if _, err := os.Stat(userPolicyFilePath); err == nil {
+		return userPolicyFilePath
+	}
 	if sys != nil {
```
Comment (mtrmac) [inline pkg/trust/policy.go:66]: https://github.com/containers/podman/issues/19073#issuecomment-1632731876 quotes the c/image implementation. I think this should be prioritizing alternatives the same way, and it isn’t doing so.

Comment (ariasmn) [reply pkg/trust/policy.go]: Yup, totally my bad, had a dirty stash and applied the wrong one (doubly wrong of me for not checking this when creating the PR)

I updated it, should me ok now!

**Review by mtrmac — COMMENTED** [review]
Thanks!

LGTM — but I’d appreciate a second pair of eyes for the interaction of the per-user files with `config.DefaultSignaturePolicyPath`.

File: pkg/trust/policy.go [hunk 2]
```diff
@@ -14,9 +14,13 @@ import (
 
 	"github.com/containers/common/pkg/config"
 	"github.com/containers/image/v5/types"
+	"github.com/containers/storage/pkg/homedir"
 	"github.com/sirupsen/logrus"
 )
 
+// userPolicyFile is the path to the per user policy path.
+var userPolicyFile = filepath.FromSlash(".config/containers/policy.json")
```
Comment (rhatdan) [inline pkg/trust/policy.go:22]: No need for this line, I believe.

File: pkg/trust/policy.go [hunk 3]
```diff
@@ -54,14 +58,16 @@ type genericRepoMap map[string]json.RawMessage
 
 // DefaultPolicyPath returns a path to the default policy of the system.
 func DefaultPolicyPath(sys *types.SystemContext) string {
+	if sys != nil && sys.SignaturePolicyPath != "" {
+		return sys.SignaturePolicyPath
+	}
+	userPolicyFilePath := filepath.Join(homedir.Get(), userPolicyFile)
```
Comment (rhatdan) [inline pkg/trust/policy.go:64]: userPolicyFilePath=filepath.FromSlash(filepath.Join(homedir.GetConfigDir(), "containers/policy.json"))

File: pkg/trust/policy.go [hunk 4]
```diff
@@ -54,14 +58,16 @@ type genericRepoMap map[string]json.RawMessage
...
+	if _, err := os.Stat(userPolicyFilePath); err == nil {
```
Comment (rhatdan) [inline pkg/trust/policy.go:65]: Should return error if err != nil && err != ENOEXIST.

Comment (ariasmn) [reply pkg/trust/policy.go:65]: Mm, I thought the idea was that, if the system couldn't use the local `policy.json` (whether because it doesn't exist or something else), the idea was to try to use the system's `policy.json`, right? What kind of errors might happen when trying to open the file (besides it not existing)?

Don't get me wrong, I'm not trying to question you, just asking to educate myself

File: pkg/trust/policy.go (hunk 3 above)
Comment (ariasmn) [reply pkg/trust/policy.go:64]: Sure thing, let's solve the other conversation first before committing this

Comment (mtrmac) [reply pkg/trust/policy.go:64]: I think keeping the implementation exactly the same as the c/image one is a minor benefit, but I don’t care that much about this part.

--

But `filepath.FromSlash` must be called _before_ `filepath.Join` for the code to be logically correct. `file path.Join` on a slash-delimited (not platform-delimited) path is incorrect.

File: pkg/trust/policy.go (hunk 4 above)
Comment (mtrmac) [reply pkg/trust/policy.go:65]: I’d like to strongly argue that deviating from the c/image logic here is undesirable _in this PR_. The bug we are fixing is that `podman image trust` is not editing the same config file that `podman pull` is consuming, and any deviation will (re)introduce that kind of bug.

---

That said, failing here on other errors is plausible, and we do do that in quite a few other parts of the code base.

(Detailed explanation: In some cases it’s not clear what the right thing to do is (EPERM might mean that the user has a policy but that policy is being silently ignored because of wrong permissions, or it might mean that this is a very bare system and there really is not much of a home directory at all); in some cases like I/O errors failing is _very likely_ the right thing to do.)

I’m fine with making that change; but if we are going to do it, I think it _needs_ to be paired with an equivalent change in c/image. And, _also_, `c/common/pkg/config.DefaultConfig`. (compare https://github.com/containers/image/issues/1726 )

Comment (ariasmn) [reply pkg/trust/policy.go:65]: Thank you very much for the explanation, I really appreciate it.

As I (unfortunately) cannot contribute much to this discussion, I leave it to you to find the best way to solve this problem and I will update the PR then.

Comment (rhatdan) [reply pkg/trust/policy.go:65]: Well you could split the decision and just logrus.Warn if this happens. As Miloslav points out, it is not likely to happen but you could get EPERM or potentially other errors.

Comment (ariasmn) [reply pkg/trust/policy.go]: Done, now a warning is logged if there is an error other than ENOEXIST

**Comment by ariasmn** [comment]
Done! Sorry about that, didn't know about the new code having to use `errors.Is(err, fs.ErrNotExist)` instead.

File: pkg/trust/policy.go [hunk 5]
```diff
@@ -54,14 +56,23 @@ type genericRepoMap map[string]json.RawMessage
 
 // DefaultPolicyPath returns a path to the default policy of the system.
 func DefaultPolicyPath(sys *types.SystemContext) string {
+	if sys != nil && sys.SignaturePolicyPath != "" {
+		return sys.SignaturePolicyPath
+	}
+
+	confDir, _ := homedir.GetConfigHome()
```
Comment (mtrmac) [inline pkg/trust/policy.go:63]: GetConfigHome [interprets](https://github.com/containers/storage/blob/c929d2050e4c1fb3c7a56b28230675d908bc8aeb/pkg/homedir/homedir.go#L14) `$XDG_CONFIG_HOME`, so that would again be a divergence in behavior.

I don’t have a strong opinion on which of the two behaviors should be used — it’s again the same thing, that diverging seems not the right thing to do in this PR, and that changes in behavior should happen across all three locations.

Comment (ariasmn) [reply pkg/trust/policy.go]: Ok, I just reverted this specific change. IMHO, I think the same as you. I might not be the correct way of doing it, but at least we keep the same behaviour, and changing the behaviour everywhere is beyond the scope of this PR.

**Review by mtrmac — COMMENTED** [review]
/lgtm
