### PR TITLE
Ensure that SQLite state handles name-ID collisions

### LINKED ISSUE #17905: sqlite: podman container commit: container already exists
Seen just now in [f36 rootless sqlite](https://api.cirrus-ci.com/v1/artifact/task/5923828761624576/html/sys-podman-fedora-36-rootless-host-sqlite.log.html#t--00381)

```
$ podman container commit -q c1
Error: more than one result for container "c1": container already exists
```

### PR DESCRIPTION
**Pull request by mheon**
If a container with an ID starting with "db1" exists, and a container named "db1" also exists, and they are different containers - if I run `podman inspect db1` the container named "db1" should be inspected, and there should not be an error that multiple containers matched the name or id "db1". This was already handled by BoltDB, and now is properly managed by SQLite.

Fixes #17905

```release-note
NONE
```

### CODE REVIEW

**Comment by mheon** [comment]
@vrothberg @edsantiago PTAL

**Review by Luap99 — COMMENTED** [review]
LGTM

File: test/e2e/create_test.go [hunk 1]
```diff
@@ -718,4 +718,21 @@ var _ = Describe("Podman create", func() {
 		setup.WaitWithDefaultTimeout()
 		Expect(setup).Should(Exit(0))
 	})
+
+	It("create container with name subset of existing ID", func() {
```
Comment (vrothberg) [inline test/e2e/create_test.go:722]: Can you also add a regression test for pods?

**Review by vrothberg — COMMENTED** [review]
LGTM but let's also add a regression test for pods

File: test/e2e/create_test.go (hunk 1 above)
Comment (mheon) [reply test/e2e/create_test.go:722]: Done

**Review by vrothberg — APPROVED** [review]
/lgtm
