### PR TITLE
libpod: move artifact volume validation to creation phase

### LINKED ISSUE #27747: Artifact volume validation fails at container start instead of creation, creating unstartable containers
### Issue Description

When creating a container with `--mount type=artifact`, validation of the artifact (checking if it exists and is accessible) occurs during container start rather than container creation. This allows users to create containers that can never be started, resulting in orphaned, unusable containers.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman create --name test --mount type=artifact,source=nonexistent-artifact,destination=/data alpine echo hello`
2. `podman start test`

Or
1. `podman run --name test --mount type=artifact,source=nonexistent-artifact,destination=/data alpine echo hello`
2. `podman ps -a`

### Describe the results you received

- `podman create` succeeds even with invalid/non-existent artifacts
- `podman start` fails with artifact-related errors
- `podman run` fails with  artifact-related errors but creates container
- Container exists in "created" state but can never transition to "running"

### Describe the results you expected

- `podman create/run` should validate artifacts exist and are accessible before start of container
- Prevent creation of containers that can never start
- Consistent with validation behavior of other mount types (bind mounts, volumes)

### podman info output

```yaml
host:
  arch: arm64
  buildahVersion: 1.42.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.13-1.20251202104442456352.main.122.gb0ee2e4.fc41.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: '
  cpuUtilization:
    idlePercent: 98.52
    systemPercent: 0.54
    userPercent: 0.94
  cpus: 6
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: workstation
    version: "41"
  emulatedArchitectures:
  - linux/386
  - linux/amd64
  - linux/arm64be
  - linux/loong64
  - linux/mips
  - linux/mips64
  - linux/ppc
  - linux/ppc64
  - linux/ppc64le
  - linux/riscv32
  - linux/riscv64
  - linux/s390x
  eventLogger: journald
  freeLocks: 2045
  hostname: fedora-mac-vm
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 6.17.10-100.fc41.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 9982431232
  memTotal: 16719392768
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    defaultNetwork: podman
    dns:
      package: aardvark-dns-2.0.0~dev-1.20251203121042890811.main.10.g0976393.fc41.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 2.0.0-dev
    package: netavark-2.0.0~dev-1.20251205174917558827.main.22.g6f77f76.fc41.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 2.0.0-dev
  ociRuntime:
    name: crun
    package: crun-1.25.1-1.20251209091027568508.main.7.g357d650f.fc41.aarch64
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: 38f1a12cd9fd9e444420c39365c02d2cbe71eb19
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20250919.g623dbf6-1.fc41.aarch64
    version: |
      pasta 0^20250919.g623dbf6-1.fc41.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 0h 56m 14.00s
  variant: v8
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /home/jrodak/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/jrodak/.local/share/containers/storage
  graphRootAllocated: 67014492160
  graphRootUsed: 26597588992
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 22
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/jrodak/.local/share/containers/storage/volumes
version:
  APIVersion: 6.0.0-dev
  BuildOrigin: 'Copr: rhcontainerbot/podman-next'
  Built: 1765238400
  BuiltTime: Tue Dec  9 01:00:00 2025
  GitCommit: f8e0b700638a407bab45c5a411f934e7005ff38d
  GoVersion: go1.24.10
  Os: linux
  OsArch: linux/arm64
  Version: 6.0.0-dev
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Artifact validation happens in `libpod/container_internal_common.go:generateSpec()` (called at start time) also in `pkg/specgen/generate/storage.go:finalizeMounts()` (called at creation time).

### PR DESCRIPTION
**Pull request by kairosci**
#### Checklist

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all commits. (`git commit -s`).
- [x] Referenced issues using `Fixes: #27747` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [ ] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
Move artifact volume validation from start to creation phase.
```

Fixes: #27747

### CODE REVIEW

File: libpod/container_validate.go [hunk 1]
```diff
@@ -177,6 +180,28 @@ func (c *Container) validate() error {
...
+				return err
+			}
+			_, err = artStore.BlobMountPaths(context.Background(), asr, &libartTypes.BlobMountPathOptions{
+				FilterBlobOptions: libartTypes.FilterBlobOptions{
+					Title:  artifactMount.Title,
+					Digest: artifactMount.Digest,
+				},
+			})
+			if err != nil {
+				return err
```
Comment (mheon) [inline libpod/container_validate.go:194]: Probably want to wrap these errors to make it more obvious what went wrong - something like `fmt.Errorf("artifact %s not found in store: %w", artifactMount.Source, err)`

File: test/system/702-artifact.bats [hunk 2]
```diff
@@ -151,5 +151,14 @@ function teardown() {
     run_podman artifact rm "$artifact_name"
 }
 
+@test "podman artifact volume validation at creation" {
+    # Issue #27747: Artifact volume validation should fail at creation, not start
+    local artifact_name="localhost/test/nonexistent-artifact"
+
+    # Creation should fail if the artifact does not exist
+    run_podman 125 create --name test-artifact-fail --artifact $artifact_name:/tmp $IMAGE
```
Comment (mheon) [inline test/system/702-artifact.bats]: `--mount type=artifacts,...` not `--artifact`

**Review by mheon — COMMENTED** [review]
Couple nits otherwise LGTM

**Comment by kairosci** [comment]
@mheon @Luap99 addressed feedback, PTAL!

**Comment by kairosci** [comment]
@mheon addressed feedback, PTAL!

**Comment by mheon** [comment]
Tests still red

**Comment by kairosci** [comment]
> Tests still red

I don't think I understand why they fail. Could you explain it to me?

**Comment by mheon** [comment]
`--mount type=artifact` instead of `--mount type=artifacts` in the test

**Comment by kairosci** [comment]
Done, thank you!

**Comment by mheon** [comment]
Please squash down to 1 commit

**Comment by mheon** [comment]
LGTM once squashed

**Comment by kairosci** [comment]
Squashed and ready to merge!

**Comment by kairosci** [comment]
Good, all CI works.

Since I believe I need the second LGTM:
@baude PTAL, thanks!

**Comment by kairosci** [comment]
@Luap99 PTAL, thanks!

File: libpod/container_validate.go [hunk 3]
```diff
@@ -177,6 +180,28 @@ func (c *Container) validate() error {
...
+			}
+			_, err = artStore.BlobMountPaths(context.Background(), asr, &libartTypes.BlobMountPathOptions{
+				FilterBlobOptions: libartTypes.FilterBlobOptions{
+					Title:  artifactMount.Title,
+					Digest: artifactMount.Digest,
+				},
+			})
+			if err != nil {
+				return fmt.Errorf("artifact %s not found in store: %w", artifactMount.Source, err)
+			}
```
Comment (Luap99) [inline libpod/container_validate.go]: calling BlobMountPaths seems weird, maybe calling Inspect() as exists check seems better?

That error also stutters
```
artifact localhost/test/nonexistent-artifact not found in store: localhost/test/nonexistent-artifact:latest: artifact does not exist
```
Naming the same thing twice is not great UX, I think we can just return err here

File: test/system/702-artifact.bats [hunk 4]
```diff
@@ -151,5 +151,15 @@ function teardown() {
     run_podman artifact rm "$artifact_name"
 }
 
+@test "podman artifact volume validation at creation" {
+    # Issue #27747: Artifact volume validation should fail at creation, not start
+    local artifact_name="localhost/test/nonexistent-artifact"
+
+    # Creation should fail if the artifact does not exist
+    run_podman '?' create --name test-artifact-fail --mount type=artifact,source=$artifact_name,target=/tmp $IMAGE
+    is "$status" "125" "exit code should be 125"
```
Comment (Luap99) [inline test/system/702-artifact.bats]: that should be `run_podman 125 ...` which does the exit code check as part of podman run already

File: test/system/702-artifact.bats [hunk 5]
```diff
@@ -151,5 +151,15 @@ function teardown() {
...
+    assert "$output" =~ "artifact.*not found|artifact.*does not exist" "creation should fail for nonexistent artifact"
```
Comment (Luap99) [inline test/system/702-artifact.bats]: why is this checking two different errors messages with the regex?
In general I prefer to match the full real message so the reviewers sees the full message of
``` 
artifact localhost/test/nonexistent-artifact not found in store: localhost/test/nonexistent-artifact:latest: artifact does not exist
```
which then looks off so we can ask for a better error text which does not stutter.

File: libpod/container_validate.go (hunk 3 above)
Comment (kairosci) [reply libpod/container_validate.go]: @mheon previously wrote:

```
Probably want to wrap these errors to make it more obvious what went wrong - something like fmt.Errorf("artifact %s not found in store: %w", artifactMount.Source, err)
```

I reverted at the moment the changes returning err.

Comment (kairosci) [reply libpod/container_validate.go]: Testing, I confirm that inspect() works best.

File: test/system/702-artifact.bats (hunk 5 above)
Comment (kairosci) [reply test/system/702-artifact.bats]: If I remember correctly, it was used to verify that it was explicitly error 125.

In any case, I have addressed requests

**Review by Luap99 — COMMENTED** [review]
code wise LGTM but can please squash the commits into one and add `Fixes: #27747` also as part of the commit message body please

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by kolyshkin** [comment]
This PR resulted in inability to build:

```console
[kir@kir-tp1 podman]$ make
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build \
	 \
	-ldflags '-X github.com/containers/podman/v6/libpod/define.gitCommit=2743ac34304cccfbfd3cb8903c07ad9ebb3b9955 -X github.com/containers/podman/v6/libpod/define.buildInfo=1770939650  -X github.com/containers/podman/v6/libpod/config._installPrefix=/usr/local -X github.com/containers/podman/v6/libpod/config._etcDir=/etc -X github.com/containers/podman/v6/pkg/systemd/quadlet._binDir=/usr/local/bin -X go.podman.io/image/v5/signature/internal/sequoia.sequoiaLibraryDir='""' -X go.podman.io/common/pkg/config.additionalHelperBinariesDir= ' \
	-tags "grpcnotrace   libsqlite3 systemd libsubid  seccomp " \
	-o bin/podman ./cmd/podman
libpod/container_validate.go:12:2: cannot find module providing package go.podman.io/common/pkg/libartifact/store: import lookup disabled by -mod=vendor
	(Go version in go.mod is at least 1.14 and vendor directory exists.)
make: *** [Makefile:391: bin/podman] Error 1
```

This also makes crun CI fails on podman tests (e.g. here: https://github.com/containers/crun/actions/runs/21967344818/job/63460452739?pr=2012)

Apparently @kairosci forgot to do `make vendor` and commit the resulting changes. Opened https://github.com/containers/podman/pull/28087

**Comment by kolyshkin** [comment]
I think this is the case of a missing rebase before merge, otherwise it would have been caught.

**Comment by kolyshkin** [comment]
Ah OK, here's the proper fix: PR #28088
