### PR TITLE
compat API: speed up network list

### LINKED ISSUE #20035: Listing networks via Docker compat is far slower than Docker
### Issue Description

Listing networks via the docker compat support is disproportionally slower than docker's support. 
In our case, it's slow enough (becomes multiple seconds) that we may have to switch to docker.

### Steps to reproduce the issue

Test Case: 

Requires python 3.11 and python packages:
* pytest
* pytest-mocker
* docker

```python
import contextlib
import dataclasses
import os
import tempfile
import time
import typing

import docker


def get_client():
    return docker.from_env()


@dataclasses.dataclass
class Dind:
    image: str
    cmd: typing.Optional[list[str]]


@contextlib.contextmanager
def dind_factory(dind: Dind):
    tmp_folder = tempfile.TemporaryDirectory()

    client = docker.from_env()
    container = client.containers.run(
        dind.image,
        dind.cmd,
        detach=True,
        privileged=True,
        user=os.getuid(),
        volumes=[f"{tmp_folder.name}:/sockets"],
        environment={"XDG_RUNTIME_DIR": "/sockets"},
        remove=True,
    )

    while True:
        try:
            dind_client = docker.from_env(timeout=1)
            dind_client.images.pull("quay.io/podman/hello")
            dind_client.containers.run("quay.io/podman/hello")
        except Exception:
            continue
        break

    try:
        yield f"unix://{tmp_folder.name}/docker.sock"
    finally:
        # Clear up Containers
        container.remove(force=True)
        tmp_folder.cleanup()


def test_network_list_performance(mocker):
    def test():
        client = get_client()
        client.images.pull("docker.io/library/busybox:latest")

        for i in range(25):
            client.networks.create(f"net{i}")
            client.containers.run(
                "docker.io/library/busybox:latest",
                ["sleep", "100000"],
                network=f"net{i}",
                detach=True,
            )
            client.containers.run(
                "docker.io/library/busybox:latest",
                ["sleep", "100000"],
                network=f"net{i}",
                detach=True,
            )
            client.containers.run(
                "docker.io/library/busybox:latest",
                ["sleep", "100000"],
                network=f"net{i}",
                detach=True,
            )
            client.containers.run(
                "docker.io/library/busybox:latest",
                ["sleep", "100000"],
                network=f"net{i}",
                detach=True,
            )

        before_time = time.time()
        client.networks.list(filters=dict(driver="bridge"))
        return time.time() - before_time

    with dind_factory(
        Dind(
            "quay.io/podman/stable",
            ["podman", "system", "service", "--time=0", "unix:///sockets/docker.sock"],
        )
    ) as unix_socket:
        mocker.patch.dict(os.environ, {"DOCKER_HOST": unix_socket})
        podman_before = time.time()
        podman_execution_time = test()
        print(f"Podman overall setup: {time.time() - podman_before}")

    del os.environ["DOCKER_HOST"]

    with dind_factory(Dind("docker:dind-rootless", None)) as unix_socket:
        mocker.patch.dict(os.environ, {"DOCKER_HOST": unix_socket})
        docker_before = time.time()
        docker_execution_time = test()
        print(f"Docker overall setup: {time.time() - docker_before}")

    assert podman_execution_time <= docker_execution_time
```

Run via `pytest <location of test file>`.  (written with linux in mind, with a local instance of docker running)
It launches podman and docker in containers, creates 25 networks each with 4 containers and monitors how long it takes to list networks (and cleans up after itself).

On my system, this test case takes ~1.5 seconds to list networks via docker compat and 0.003 seconds via docker. 

### Describe the results you received

In the above test case (which in terms of container arrangement is roughly to our software with light usage), listing networks via podman's docker compat layer is far slower than docker and gets disproportionally worse with more networks/containers. 

0.24 seconds vs 0.002 seconds (10 networks, each with 4 containers)
1.5 seconds vs 0.003 seconds (25 networks, each with 4 containers)

### Describe the results you expected

I'd expect podmans's docker network support to be comparable to docker's.

Our issue is that we can create many hundreds of networks with multiple containers each (we're managing IPAM manually to enable this), so podman's docker network listing becomes too slow for us to use and we may have to switch to docker if it can't be sped up. (Python doesn't have an async podman library yet, so switching to podman without the docker company layer isn't an option).

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.7-r1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: unknown'
  cpuUtilization:
    idlePercent: 70.74
    systemPercent: 6.86
    userPercent: 22.39
  cpus: 8
  databaseBackend: boltdb
  distribution:
    distribution: alpine
    version: 3.18.3
  eventLogger: file
  hostname: bbbca290abcd
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.0-162-generic
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 1470201856
  memTotal: 16508235776
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.4-r0
    path: /usr/bin/crun
    version: |-
      crun version 1.8.4
      commit: 5a8fa99a5e41facba2eda4af12fa26313918805b
      rundir: /run/crun
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-r0
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 14555238400
  swapTotal: 17179865088
  uptime: 32h 22m 32.00s (Approximately 1.33 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 500619575296
  graphRootUsed: 352948707328
  graphStatus:
    Backing Filesystem: overlayfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 8
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.5.1
  Built: 1694067067
  BuiltTime: Thu Sep  7 06:11:07 2023
  GitCommit: ""
  GoVersion: go1.20.8
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.1
```

### Podman in a container

Yes

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

We're installing/using podman in an alpine 3.18 privileged container (with fuse-overlayfs).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Luap99**
The network list compat API requires us to include all containers with
their ip addresses for the selected networks. Because we have no network
-> container mapping in the db we have to go through all containers
every time. However the old code did it in the most ineffective way
possible, it quered the containers from the db for each individual
network. The of course is extremely expensive. Now the other expensive
call is calling Inspect() on the container each time. Inspect does for
more than we need.

To fix this we fist query containers only once for the API call, then
replace the inspect call with directly accessing the network status.
This will speed things up a lot!
The reported scenario includes 100 containers and 25 networks,
previously it took 1.5s for the API call not it takes 24ms, that is a
more than a 62x improvement. (tested with curl)

[NO NEW TESTS NEEDED] We have no timing tests.

Fixes #20035

#### Does this PR introduce a user-facing change?

```release-note
The network list compat API endpoint is now much faster.
```

### CODE REVIEW

File: pkg/api/handlers/compat/networks.go [hunk 1]
```diff
@@ -56,45 +86,46 @@ func InspectNetwork(w http.ResponseWriter, r *http.Request) {
...
-	for _, con := range cons {
-		data, err := con.Inspect(false)
-		if err != nil {
-			if errors.Is(err, define.ErrNoSuchCtr) || errors.Is(err, define.ErrCtrRemoved) {
-				continue
-			}
-			return nil, err
-		}
-		if netData, ok := data.NetworkSettings.Networks[network.Name]; ok {
+func convertLibpodNetworktoDockerNetwork(runtime *libpod.Runtime, statuses []containerNetStatus, network *nettypes.Network, changeDefaultName bool) (*types.NetworkResource, error) {
```
Comment (cgiradkar) [inline pkg/api/handlers/compat/networks.go:102]: there's no case where we have an error returned

File: libpod/container.go [hunk 2]
```diff
@@ -1356,6 +1339,21 @@ func (d ContainerNetworkDescriptions) getInterfaceByName(networkName string) (st
 	return fmt.Sprintf("eth%d", val), exists
 }
 
+// GetNetworkStatus returns the current network status for this container.
+// This returns a map without deep copying which means this should only ever
+// be used as read only access, do not modify this status.
+func (c *Container) GetNetworkStatus() (map[string]types.StatusBlock, error) {
```
[the remark this answers is not in the document]
Comment (Luap99) [reply libpod/container.go:1345]: sorry, mixed up the comments

We have this as common structure for these functions. For example
`(c *Container) Start()` and `(c *Container) start` ame with Init() and init() and many more
Basically the exported one is always a wrapper that should take care of locking so this is juts in style with existing code

File: pkg/api/handlers/compat/networks.go (hunk 1 above)
Comment (Luap99) [reply pkg/api/handlers/compat/networks.go]: fixed

**Review by vrothberg — APPROVED** [review]
LGTM, nice work

**Comment by cgiradkar** [comment]
LGTM

**Review by cgiradkar — APPROVED** [review]

File: libpod/container.go (hunk 2 above)
Comment (rhatdan) [inline libpod/container.go:1345]: Nit: Remove `Get`

File: pkg/api/handlers/compat/networks.go [hunk 3]
```diff
@@ -22,6 +22,36 @@ import (
 	"github.com/sirupsen/logrus"
 )
 
+type containerNetStatus struct {
+	name   string
+	id     string
+	status map[string]nettypes.StatusBlock
+}
+
+func getContainerNetStatuses(rt *libpod.Runtime) ([]containerNetStatus, error) {
```
Comment (rhatdan) [inline pkg/api/handlers/compat/networks.go:31]: Nit: Remove get

Comment (Luap99) [reply pkg/api/handlers/compat/networks.go:31]: Are you fine with merging given all tests are green? I am good with changing but I rather avoid the force push unless necessary.
