### PR TITLE
Quadlet warning messages

### LINKED ISSUE #25339: Possible regex bug in Quadlet
### Issue Description

I'm running a Traefik container via Quadlet, there is a line in this `traefik.container` is like this:
`Label=traefik.http.middlewares.redirect.redirectregex.regex=^https://(.*)/.well-known/(webfinger|nodeinfo|host-meta)(\?.*)?$`

However, the `.service` file generated does not contain this line, after some tweaking, found out it's related to `\?`, it's perfectly fine if without it. I'm guessing it might be about the regex processing part of Quadlet?

### Steps to reproduce the issue

1. Create `traefik.container` in `~/.config/containers/systemd/`
2. Contain a line `Label=traefik.http.middlewares.redirect.redirectregex.regex=^https://(.*)/.well-known/(webfinger|nodeinfo|host-meta)(\?.*)?$`
3. Run `systemctl --user daemon-reload`
4. Run `systemctl --user cat traefik.service` and that line is not included in the `.service` file

### Describe the results you received

I've messed around with the regex, found out it's related to `\?` in the line, it can be included fine if without it. I'm guessing it might be about the regex processing part of Quadlet? I also tried wrap the line with `""` but didn't work.

### Describe the results you expected

`Label=traefik.http.middlewares.redirect.redirectregex.regex=^https://(.*)/.well-known/(webfinger|nodeinfo|host-meta)(\?.*)?$` should be included.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.38.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.12-3.fc41.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 97.79
    systemPercent: 0.84
    userPercent: 1.36
  cpus: 8
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: coreos
    version: "41"
  eventLogger: journald
  freeLocks: 2039
  hostname: REDACTED
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
  kernel: 6.12.9-200.fc41.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 683764528
  memTotal: 8994261552
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.13.1-1.fc41.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.13.1
    package: netavark-1.13.1-1.fc41.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.13.1
  ociRuntime:
    name: crun
    package: crun-1.19.1-1.fc41.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.19.1
      commit: 3e32a70c93f5aa5fea69b50256cca7fd4aa23c80
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20241211.g09478d5-1.fc41.x86_64
    version: |
      pasta 0^20241211.g09478d5-1.fc41.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.3.1-1.fc41.x86_64
    version: |-
      slirp4netns version 1.3.1
      commit: e5e368c4f5db6ae75c2fce786e31eef9da6bf236
      libslirp: 4.8.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.5
  swapFree: 1995698176
  swapTotal: 1997008896
  uptime: 58h 54m 14.00s (Approximately 2.42 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /var/home/REDACTED/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 4
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/REDACTED/.local/share/containers/storage
  graphRootAllocated: 40356524032
  graphRootUsed: 10039848960
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 6
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /var/home/REDACTED/.local/share/containers/storage/volumes
version:
  APIVersion: 5.3.1
  Built: 1732147200
  BuiltTime: Thu Nov 21 00:00:00 2024
  GitCommit: ""
  GoVersion: go1.23.3
  Os: linux
  OsArch: linux/amd64
  Version: 5.3.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ygalblum**
#### Does this PR introduce a user-facing change?
Yes

```release-note
Quadlet - Print warnings to avoid silent line skips
```

Fixes #25339

### CODE REVIEW

**Comment by mheon** [comment]
You have a spelling error. Code LGTM overall though

**Comment by ygalblum** [comment]
> You have a spelling error. Code LGTM overall though

Thanks, fixed

**Comment by Luap99** [comment]
Should this contain `Fixes #25339` as part of the commit? I assume that was done in response to that issue?

File: pkg/systemd/quadlet/quadlet.go [hunk 1]
```diff
@@ -571,15 +577,18 @@ func ConvertContainer(container *parser.UnitFile, isUser bool, unitsInfoMap map[
...
 		// We default to mixed instead of control-group, because it lets conmon do its thing
 		service.Set(ServiceGroup, "KillMode", "mixed")
 	}
 
 	// Read env early so we can override it below
-	podmanEnv := container.LookupAllKeyVal(ContainerGroup, KeyEnvironment)
+	podmanEnv, warn := container.LookupAllKeyVal(ContainerGroup, KeyEnvironment)
+	if warn != nil {
+		warnings = errors.Join(warnings, warn)
+	}
```
Comment (Luap99) [inline pkg/systemd/quadlet/quadlet.go:591]: FYI this != nil  check is not needed as that is already done inside `errors.Join()`
So you can just always call `warnings = errors.Join(warnings, warn)` which should do the exact same thing. Same in the other palaces below. It should make the code a bit simpler.

Comment (ygalblum) [reply pkg/systemd/quadlet/quadlet.go]: I didn't know that, thanks. Fixed

**Comment by ygalblum** [comment]
> Should this contain `Fixes #25339` as part of the commit? I assume that was done in response to that issue?

You're right. I've updated the PR description

**Comment by ygalblum** [comment]
I don't think the test failures are related to my change

**Comment by ygalblum** [comment]
@containers/podman-maintainers PTAL

File: cmd/quadlet/main.go [hunk 2]
```diff
@@ -631,15 +631,15 @@ func generateUnitsInfoMap(units []*parser.UnitFile) map[string]*quadlet.UnitInfo
 }
 
 func main() {
-	if err := process(); err != nil {
-		Logf("%s", err.Error())
+	if processErred := process(); processErred {
+		Logf("processing encountered some errors")
```
Comment (rhatdan) [inline cmd/quadlet/main.go:635]: Why aren't yo utelling us the error?  Why change from err :=?

Comment (rhatdan) [reply cmd/quadlet/main.go:635]: Never mind, now I read the code/
