### PR TITLE
Make the e2e test network cleanup more robust.

### LINKED ISSUE #7809: test/e2e : podman network remove with two networks: needs fail-safe cleanup
test/e2e/network_test.go:"podman network remove with two networks" does not properly clean up after itself if the test fails partway (e.g. if `net1` succeeds but `net2` fails).

### PR DESCRIPTION
**Pull request by rhatdan**
We need to handle removal of non existing network.

This allows the `removeCNINetwork` function
always to be called. This is needed by tests which are trying
to remove the network manually in order to prevent flakes.

Fixes #7809

Signed-off-by: Paul Holzinger <paul.holzinger@web.de>
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Replaces: https://github.com/containers/podman/pull/7812
@Luap99 @edsantiago PTAL

File: test/e2e/network_create_test.go [hunk 1]
```diff
@@ -58,7 +58,7 @@ func genericPluginsToPortMap(plugins interface{}, pluginType string) (network.Po
 func (p *PodmanTestIntegration) removeCNINetwork(name string) {
 	session := p.Podman([]string{"network", "rm", "-f", name})
 	session.WaitWithDefaultTimeout()
-	Expect(session.ExitCode()).To(BeZero())
+	Expect(session.ExitCode() < 2).To(BeTrue())
```
Comment (edsantiago) [inline test/e2e/network_create_test.go:61]: I'm not a ginkgo expert nor fan, but would you consider `Expect(session.ExitCode()).To(BeNumerically("<=",1))` ? I believe that will give better diagnostics in case of error. (Those `false was not true` diagnostics always make me struggle to try to find out what happened).

Comment (rhatdan) [reply test/e2e/network_create_test.go:61]: Sure, I was trying to discover the correct syntax for this.

Comment (edsantiago) [reply test/e2e/network_create_test.go]: I just remembered seeing `Numerically` in the past, then grep'ed for it in `test/e2e`.

**Comment by edsantiago** [comment]
LGTM. Thanks for your cleanup work in #7825

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL

**Review by vrothberg — COMMENTED** [review]
/lgtm
/hold
