### PR TITLE
Cirrus: Skip most tests on tag-push

### LINKED ISSUE #8538: Cirrus-CI Build validation fails on tag-push
/kind bug

When pushing a new tag, Cirrus-CI executes a special job.  A github "check suite" is created by Cirrus-CI, and associated with the tag in github.  However, this "check run" (a.k.a. "build" in Cirrus) is very hard to find in the github WebUI.  It's much easier to observe directly in the Cirrus-CI WebUI using a url of the form `https://cirrus-ci.com/github/containers/podman/<new tag>`.

[Specifically, for the v2.2.0 tag, this Cirrus-CI build failed in the validation step.](https://cirrus-ci.com/task/5693152994525184?command=main#L29)

**Steps to reproduce the issue:**

1. Create a new tag
2. Push tag

**Describe the results you received:**

The validation step fails due to a bad value being passed to the vbatts/git-validation tool.

**Describe the results you expected:**

The `validate` makefile target should pass for new tags

### PR DESCRIPTION
**Pull request by cevich**
Fixes #8538 #5278

### CODE REVIEW

**Comment by cevich** [comment]
***Note:*** [I'm forcing Cirrus to think this PR was from a tag-push](https://github.com/containers/podman/pull/8900/commits/ffafbdc982eb9d57d3f77837de52e94980eb7655).  This correctly results in [a *Verify Release* task failure](https://cirrus-ci.com/task/5213822464032768?command=main#L6), as [is expected.](https://github.com/containers/podman/issues/5278)

**Comment by edsantiago** [comment]
Here's the map, in case you find it useful. (It's what I'm primarily referring to for my review):
cirrus-map-pr8900

**Comment by edsantiago** [comment]
There's one thing I find unintuitive: there are three `alt_build` tasks (`alt_build`, `osx_alt_build`, `static_alt_build`). Each of those has different SKIPs. I see no way to consolidate those (yes, I tried) but should they maybe share the same SKIPs?

**Comment by cevich** [comment]
> Each of those has different SKIPs

Oh...actually, I think all of the 'alt build' tasks should run for a tag-push...my bad.

**Comment by cevich** [comment]
(rebased and removed the `skip` from the `alt_build_task`)

**Comment by edsantiago** [comment]
Friendly suggestion:
```diff
diff --git a/contrib/cirrus/runner.sh b/contrib/cirrus/runner.sh
index 7f9afd1fd..baf6f31fe 100755
--- a/contrib/cirrus/runner.sh
+++ b/contrib/cirrus/runner.sh
@@ -199,8 +199,9 @@ function _run_altbuild() {
 }

 function _run_release() {
-    if bin/podman info |& grep -Eq -- '-dev'; then
-        die "Releases must never contain '-dev' in output of 'podman info'"
+    dev=$(bin/podman info |& grep -- -dev)
+    if [[ -n "$dev" ]]; then
+        die "Releases must never contain '-dev' in output of 'podman info' ($dev)"
     fi
 }

```

**Comment by zhangguanzhang** [comment]
related https://github.com/containers/podman/issues/8802

**Comment by cevich** [comment]
> Friendly suggestion:

@edsantiago this is also a valid approach, though I don't see a large benefit to justify changing the code at this time.  I'm assuming that before too long, all the release-processing/testing code will be both expanded and re-implemented.  This PR is just a stop-gap while the group solves the bigger release problems...in case a release needs to go out before improvements are in place.

**Comment by edsantiago** [comment]
>though I don't see a large benefit to justify changing the code at this time.

Okay, I'll change "friendly suggestion" to "kind of important and insistent recommendation".

Here is the workflow:
1. I looked at the test failure
2. It told me "blah blah -dev blah blah"
3. It did not give any useful information whatsoever, so I had no way of knowing what it was complaining about, or what the `-dev` string was

Someone trying to debug this problem might not have the exact same setup as CI. Even if they do, it takes time and energy to check that out and rebuild. Including the offending `-dev` strings in the error output can save someone time. Please have consideration for future debuggers.

**Comment by cevich** [comment]
> Please have consideration for future debuggers.

Oh your contention is about the message, not the checking itself...I'm more than willing to improve that aspect...

**Comment by cevich** [comment]
@edsantiago [improved failure output](https://cirrus-ci.com/task/6151653336285184):

```
Checking podman release (or potential release) criteria.
************************************************
ERROR: Found unexpected '-dev' in output of 'podman info':
host:
  arch: amd64
  buildahVersion: 1.19.0-dev
...cut...
  OsArch: linux/amd64
  Version: 3.0.0-dev  (contrib/cirrus/runner.sh:211 in _run_release())
************************************************
```

File: contrib/cirrus/runner.sh [hunk 1]
```diff
@@ -199,8 +199,16 @@ function _run_altbuild() {
 }
 
 function _run_release() {
-    if bin/podman info |& grep -Eq -- '-dev'; then
-        die "Releases must never contain '-dev' in output of 'podman info'"
+    # TODO: These tests should come from code external to the podman repo.
+    # to allow test-changes (and re-runs) in the case of a correctible test
+    # flaw or flake at release tag-push time.  For now, the test is here
+    # given it's simlicity.
```
Comment (edsantiago) [inline contrib/cirrus/runner.sh:205]: Typo, simplicity. And I really don't understand this comment anyway, but trust that you do and it may help you in the future.

File: contrib/cirrus/runner.sh [hunk 2]
```diff
@@ -199,8 +199,16 @@ function _run_altbuild() {
...
+
+    msg "Checking podman release (or potential release) criteria."
+    info_output=$(bin/podman info 2>&1)
+    if grep -Eq -- '-dev'<<<"$info_output"; then
+        die "Found unexpected '-dev' in output of 'podman info':
```
Comment (edsantiago) [inline contrib/cirrus/runner.sh:210]: Could you leave my patch as it was? `podman info` is an enormous long string, and it is anti-helpful to include the whole thing. The reader only wants/needs to see the `-dev` strings.

BTW I deliberately removed the `-E` in my recommended patch. `-E` is not needed here, and its presence confuses the reader.

**Review by edsantiago — CHANGES_REQUESTED** [review]

File: contrib/cirrus/runner.sh (hunk 2 above)
Comment (cevich) [reply contrib/cirrus/runner.sh:210]: I'm in favor of the more verbose output (unprocessed by `grep`) since (for now) it supports a human catching other release-affecting mistakes, like a wrong/unexpected buildah or conmon version.  At least until we get more/improved release tests in place.

File: contrib/cirrus/runner.sh (hunk 1 above)
Comment (cevich) [reply contrib/cirrus/runner.sh:205]: got it.

File: contrib/cirrus/runner.sh (hunk 2 above)
Comment (edsantiago) [reply contrib/cirrus/runner.sh]: I'm afraid I disagree. I cannot imagine your scenario happening in reality: 

Reader: "oh, look, a failure, let me look at the entire output, cross-reference it against my expected versions, oh, wow, an unexpected difference in conmon! Thank goodness for full output".

 What I think is more likely:

Reader: "oh look, a failure, what is the error? Do I actually have to look at ONE HUNDRED AND TWO LINES of crap just to see what the problem is? Okay, I'll use my browser search function, oh darn I used two dashes for --dev, that doesn't find anything, okay let's try again, oh there it is, all right I'll fix it"
(voiceover: what our debugger doesn't know is that there were *two* -devs in the output).

Please just show the relevant error output and only the relevant error output. No distractions please.

**Comment by cevich** [comment]
Okay, tests are green.  I opened a Jira card WRT research and planning for an improved/better release process (and automation) RE: the two issues this PR will close when merged.

File: contrib/cirrus/runner.sh (hunk 2 above)
Comment (edsantiago) [reply contrib/cirrus/runner.sh]: I think you missed this (it's been a long week). It is not resolved. Please resolve it.

Comment (cevich) [reply contrib/cirrus/runner.sh]: I hear what you're saying, but I think we're spending too much time on a relatively minor item.  I'm afraid of making your changes costing a lot of testing time.  In other words, I would need an additional run to verify (fake) `$CIRRUS_TAG` activation works (fails), another run to verify the manual-activation works (fails), then a third run to have a clean CI result for merging.  This is assuming there aren't any actual problems found that need fixing  :confounded: 

IMHO, it's simply not worth our time for a code-path that is used what...three-five times per year, maybe?   I'd rather spend time working improving the overall podman-release experience, and the myriad of other testing issues which need more urgent attention.

Comment (edsantiago) [reply contrib/cirrus/runner.sh]: Then just remove the changes to runner.sh and resubmit. I'm not going to approve this as it is, it's made everything worse. I'll just fix it myself later.

Comment (cevich) [reply contrib/cirrus/runner.sh]: What motivation have you provided, for me to approve a re-fix?

 I think for the greater good and grander-schemes...it's past time we agree to disagree.  Our foreheads will thank us for it :smiley:

Comment (edsantiago) [reply contrib/cirrus/runner.sh]: The fact that I provided a simple, clean, tested fix... which you ignored in favor of a broken one. Come on, this is very simple. Please either use my fix to runner.sh (which, again, I tested fairly extensively) or undo your changes to runner.sh. I provided my reasoning above: dumping the entire `podman info` output is cruel and harmful.

Comment (cevich) [reply contrib/cirrus/runner.sh]: Ed, we're simply not going to agree on the verbosity level.  But we also need to rise above perfectionism and pettiness, it doesn't help anybody. Since any changes will require re-testing anyway...and this test isn't a long-term solution...here's a compromise:

* I'll remove this automated check (here) and instead include it as a manual check in the release docs (short-term fix).
* I've got a jira card open already, as a "SPIKE" to fully spec. requirements for improved release-related automation and manual processes.  I'd like your assistance completing this (helping define the spec).
* I'd like you to take on the (assumed) followup card for adding (proper) automated release tests (long-term fix).

okay?

**Review by edsantiago — APPROVED** [review]
I'll just fix it myself.
