### PR TITLE
Fix Docker API compatibility with network alias

### LINKED ISSUE #17167: [Bug]: host's /etc/hosts file overrides private network dns settings in podman
### Issue Description

Moving over to a new machine with podman instead of docker, still ironing out the issues using docker-compose with podman.

I used to have a custom domain let's call it foo.bar.com, car.bar.com, etc mapped to 127.0.0.1 in my host's /etc/hosts file.
In the docker-compose.yml I had a private network with those same hosts set.
Inside the containers attached to the network, they would get the private network address, using podman they get 127.0.0.1

### Steps to reproduce the issue

on host machine:
```
127.0.0.1 foo.bar.com proxy.bar.com
```

docker-compose.yml:
```yaml
version: '3.3'

services:
  proxy:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    hostname:  proxy.bar.com
    networks:
      mynet:
        aliases:
          -  proxy.bar.com
  foo:
    image: some-server:latest
    ports:
      - 9555:9555
    hostname:  foo.bar.com
    networks:
      mynet:
        aliases:
          -  foo.bar.com
    volumes:
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.10.0.0/16
```

### Describe the results you received

exec into proxy.bar.com

ping foo.bar.com

get 127.0.0.1

### Describe the results you expected

I expected an ip inside the mynet address space

### podman info output

```shell
host:
  arch: amd64
  buildahVersion: 1.27.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: 56561007b6a59ea175ee9a67384639721499e160'
  cpuUtilization:
    idlePercent: 99.42
    systemPercent: 0.23
    userPercent: 0.36
  cpus: 20
  distribution:
    distribution: '"rhel"'
    version: "9.1"
  eventLogger: journald
  hostname: frisbee
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.0-162.6.1.el9_1.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 26817802240
  memTotal: 66804899840
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9_0.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 33592176640
  swapTotal: 33592176640
  uptime: 41h 58m 30.00s (Approximately 1.71 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/ddumont/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 1
    stopped: 4
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/ddumont/.local/share/containers/storage
  graphRootAllocated: 988412391424
  graphRootUsed: 45282320384
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 13
  runRoot: /run/user/1000/containers
  volumePath: /home/ddumont/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1666809014
  BuiltTime: Wed Oct 26 14:30:14 2022
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0


```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

RHEL 9.1

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gavinkflam**
Fixes #17167

I fixed this issue by applying @Luap99's suggestions - https://github.com/containers/podman/issues/17167#issuecomment-1486959315

> This is needed for it to work:
> 1. Add the `base_hosts_file` option to the container spec and config so it can be set for specific containers.
> 2. Then make sure the docker compat api sets this field to `none` to match the docker behavior.

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug in Docker API where the entries in /etc/hosts file are copied into the container resulting in incompatibility with network alias.
```

### CODE REVIEW

File: pkg/specgen/specgen.go [hunk 1]
```diff
@@ -507,6 +507,13 @@ type ContainerNetworkConfig struct {
 	// specgen is stable so we can not change this right now.
 	// TODO (5.0): change to pointer
 	UseImageHosts bool `json:"use_image_hosts"`
+	// BaseHostsFile is the path to a hosts file, the entries from this file
+	// are added to the containers hosts file. As special value "image" is
+	// allowed which uses the /etc/hosts file from within the image and "none"
+	// which uses no base file at all. If it is empty we should default
+	// to the base_hosts_file configuration in containers.conf.
+	// Optional.
+	BaseHostsFile string `json:"baseHostsFile,omitempty"`
```
Comment (Luap99) [inline pkg/specgen/specgen.go:516]: specgen uses snake case for the json names.

File: test/compose/etc_hosts/setup.sh [hunk 2]
```diff
@@ -0,0 +1,2 @@
+cp /etc/hosts $TMPDIR/etc_hosts.backup
+echo -e '\n127.0.0.1 foobar' >> /etc/hosts
```
Comment (Luap99) [inline test/compose/etc_hosts/setup.sh:2]: I am not sure I like doing this by default as these tests are also run on local developers systems not just CI.
It also fails as rootless obviously, it is somewhat concerning that this does not cause a test failure and errors are just ignored. cc @edsantiago 

I think it would be a bit safer to bind mount a new hosts file over it: `mount --bind $TMPDIR/new_hosts /etc/hosts` and as rootless you can do this with `podman unshare mount ...`. This allows you to write any content in the hosts file and then you could also `cat /etc/hosts` in the container and check that the entries were not added.

The main advantage of a mount would be that we never leak the entry permanently (i.e. it is gone after a reboot) if the tests were interrupted.

File: test/compose/etc_hosts/docker-compose.yml [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+        aliases:
+          - foobar
+
+networks:
+  net1:
+    driver: bridge
+    ipam:
+      driver: default
+      config:
+        - subnet: 10.123.0.0/16
```
Comment (Luap99) [inline test/compose/etc_hosts/docker-compose.yml:19]: use a /24

**Review by Luap99 — CHANGES_REQUESTED** [review]
Thanks for the PR, code mostly looks good except one naming nit.
I think for the test it would be better to bind mount the hosts file as this could work as rootless as well.

File: test/compose/etc_hosts/setup.sh (hunk 2 above)
Comment (gavinkflam) [reply test/compose/etc_hosts/setup.sh]: I agree. Just updated the test to use bind mount.

Ignoring test errors - I can submit another PR to capture any errors running the test scripts and report them as failures.

**Comment by gavinkflam** [comment]
@Luap99 I can submit a subsequent PR adding a `--base-hosts-file` flag to CLI.

It provides flexibility for users to override hosts file at a container level. Do you think it is a good idea?

**Comment by Luap99** [comment]
> @Luap99 I can submit a subsequent PR adding a `--base-hosts-file` flag to CLI.
> 
> It provides flexibility for users to override hosts file at a container level. Do you think it is a good idea?

Yes sure. I think https://github.com/containers/podman/issues/13277 asks for this.

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
/lgtm
Thanks @gavinkflam
