### PR TITLE
fix: #23915 podman build is not parsing sbom command line arguments

### LINKED ISSUE #23915: SBOM. sbom flags are not respected
### Issue Description

SBOM flags are not respected while `podman build` command.
Meanwhile sbom options fails if wrong input.

Builds were made inside `container quay.io/containers/podman:v5`

Checked over tags 5.0 - 5.2

At the same time buildah build command works as expected.

### Steps to reproduce the issue

podman build:
```
podman build -t sbom-img --sbom=trivy-spdx \
        --sbom-image-output=/app/sbom-spdx.json \
        --sbom-output=sbom-spdx.json \
        --sbom-scanner-image=ghcr.io/aquasecurity/trivy \
        --sbom-scanner-command="trivy filesystem -q {ROOTFS} --format spdx-json --output {OUTPUT}" \
        --sbom-scanner-command="trivy filesystem -q {CONTEXT} --format spdx-json --output {OUTPUT}" \
        --sbom-merge-strategy=merge-spdx-by-package-name-and-versioninfo \
        -f Dockerfile
```

Dockerfile
```
FROM ubuntu:22.04
WORKDIR /app
```

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
- WSL ubuntu 22.04
- K8s
```

### Podman in a container

Yes

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by aguidirh**
# Issue Description
SBOM flags are not respected while podman build command.

At the same time buildah build command works as expected.

Fixes #23915 

## Steps to reproduce the issue
With the following Containerfile:
```
FROM ubuntu:22.04
WORKDIR /app
```

Run the following podman build:

```
podman build -t sbom-img --sbom=trivy-spdx \
        --sbom-image-output=/app/sbom-spdx.json \
        --sbom-output=sbom-spdx.json \
        --sbom-scanner-image=ghcr.io/aquasecurity/trivy \
        --sbom-scanner-command="trivy filesystem -q {ROOTFS} --format spdx-json --output {OUTPUT}" \
        --sbom-scanner-command="trivy filesystem -q {CONTEXT} --format spdx-json --output {OUTPUT}" \
        --sbom-merge-strategy=merge-spdx-by-package-name-and-versioninfo \
        -f Containerfile
```

Create a container with the image built in the previous step and check if the file sbom-spdx.json is inside of the container as requested:

```
podman run -it --rm sbom-img ls -al
```

Expected result:
```
drwxr-xr-x. 1 root root     28 Mar 21 13:06 .
dr-xr-xr-x. 1 root root     12 Mar 21 13:17 ..
-rw-r--r--. 1 root root 147729 Mar 21 13:06 sbom-spdx.json
```

Actual results:
```
drwxr-xr-x. 1 root root     28 Mar 21 13:06 .
dr-xr-xr-x. 1 root root     12 Mar 21 13:17 ..
```

Running the steps above with the code from this PR shows the expected result (the same as when using buildah), while running with the code from the main branch shows the actual result (with the bug).

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by baude** [comment]
please sign your commits https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs

**Comment by baude** [comment]
@nalind ptal

**Comment by baude** [comment]
and you need to add a release note ... this is cli and is an outward change.

**Comment by aguidirh** [comment]
Hi @baude,

> please sign your commits https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs

I believe the [commit](https://github.com/containers/podman/pull/25647/commits) is signed.

> and you need to add a release note

I did not add a release note because in the template it was saying to add it only in case of user-facing change, there is no user-facing change, only a bug fix for the flags that were already there.

**Comment by nalind** [comment]
This looks exactly what `github.com/containers/buildah/pkg/cli.GenBuildOptions()` does, so I expect it's going to handle the options correctly, so LGTM.
But if podman isn't calling that function, I have to wonder why we went to the trouble of exporting it there.

**Comment by aguidirh** [comment]
Hi @nalind,

I added the test requested by @baude. 

They are passing locally, I am not sure why some tests are failing in the PR.

Could you please /retest them?

**Comment by baude** [comment]
the test `[FAIL] Podman build [It] podman build with sbom flags` is failing here.

File: test/e2e/build_test.go [hunk 1]
```diff
@@ -972,4 +972,19 @@ RUN ls /dev/test1`, CITEST_IMAGE)
...
+	It("podman build with sbom flags", func() {
+		podmanTest.AddImageToRWStore(ALPINE)
+		session := podmanTest.Podman([]string{"build", "-t", "sbom-img", "--sbom-output=localsbom.txt", "--sbom-purl-output=localpurl.txt", "--sbom-image-output=/tmp/sbom.txt", "--sbom-image-purl-output=/tmp/purl.txt",
+			"--sbom-scanner-image=alpine", "--sbom-scanner-command=/bin/sh -c 'echo SCANNED ROOT {ROOTFS} > {OUTPUT}'", "--sbom-scanner-command=/bin/sh -c 'echo SCANNED BUILD CONTEXT {CONTEXT} > {OUTPUT}'",
+			"--sbom-merge-strategy=cat", "build/basicalpine"})
+
+		session.WaitWithDefaultTimeout()
+		Expect(session).Should(ExitCleanly())
+
+		session = podmanTest.Podman([]string{"run", "--rm", "sbom-img", "ls", "/tmp"})
```
Comment (baude) [inline test/e2e/build_test.go:984]: same as above PodmanExitCleanly

**Comment by baude** [comment]
also note the failures are all remote tests

File: test/e2e/build_test.go [hunk 2]
```diff
@@ -972,4 +972,19 @@ RUN ls /dev/test1`, CITEST_IMAGE)
 		session.WaitWithDefaultTimeout()
 		Expect(session).Should(ExitWithError(1, `building at STEP "RUN --mount=type=cache,target=/test,z cat /test/world": while running runtime: exit status 1`))
 	})
+	It("podman build with sbom flags", func() {
+		podmanTest.AddImageToRWStore(ALPINE)
```
[the remark this answers is not in the document]
Comment (aguidirh) [reply test/e2e/build_test.go:976]: Great suggestion, thanks. 

Done.

File: test/e2e/build_test.go (hunk 1 above)
Comment (aguidirh) [reply test/e2e/build_test.go]: Great suggestion, thanks. 

Done.

**Comment by aguidirh** [comment]
> also note the failures are all remote tests

I will have a look why they are failing for the remote tests and fix it.

**Comment by l0rd** [comment]
Great job @aguidirh , tests are passing. If you don't mind, it would be helpful to add some remote tests (see [pkg/machine/e2e](https://github.com/containers/podman/blob/main/pkg/machine/e2e)). Also, please squash your commits as CI tests were not passing for the first one.

**Comment by aguidirh** [comment]
> Great job @aguidirh , tests are passing. If you don't mind, it would be helpful to add some remote tests (see [pkg/machine/e2e](https://github.com/containers/podman/blob/main/pkg/machine/e2e)). Also, please squash your commits as CI tests were not passing for the first one.

Thanks @l0rd. 

In test/e2e/build_test.go [L977-997](https://github.com/containers/podman/pull/25647/files#diff-8b4d34c763f953caff8c6747e966aa1a7e869411747cd000370918887ba5b124R977-R997) I added `podman build with sbom flags` which I believe runs as `make localintegration` and also as remote test `make remoteintegration`

Is this kind of remote test are you asking for? Or is it other type of remote test? (@l0rd please ignore this message)

I squashed the commits, but I believe we have some flaky tests.

**Comment by aguidirh** [comment]
/hold 

TODO: discover why build with sbom flags are not working for podman machine `localmachine` on `basic_test.go` L[326-327](https://github.com/containers/podman/pull/25647/files#diff-0703eb2944434bdd3c13ee3d30076c101479b02fa257b6935e36914b06d8817eR326-R327). 

The same test works fine for `localintegration` and  `remoteintegration` on `test/e2e/build_test.go` L[995-996](https://github.com/containers/podman/pull/25647/files#diff-8b4d34c763f953caff8c6747e966aa1a7e869411747cd000370918887ba5b124R995-R996).

**Comment by aguidirh** [comment]
@mheon could you please have a look if the tests failing are only flakes? 

Please let me know if there is something missing to merge this PR.

**Comment by mheon** [comment]
The Linux machine tests are timing out consistently. Likely not a flake. Possible that your test addition just bumped us over the limit, though I would have expected us to be flaking consistently before this if that was the case?

WSL is just being WSL, that's a flake

**Comment by aguidirh** [comment]
@mheon since the machine tests will need to wait for the new vm to be built based on the server code I'm sending in this PR, is that ok if I comment the entire machine test ? 

In this way we can check if the problem is that my tests bumped over the limit. 

What do you think?

**Comment by aguidirh** [comment]
[machine-linux podman fedora-42 rootless host sqlite](https://github.com/containers/podman/pull/25647/checks?check_run_id=51337243044)

But if that was the case, the linux machine test above should fail as well right? The one above passed, also other jobs related to machine tests passed (applehv, hyperv and libkrun).

**Comment by mheon** [comment]
@baude @Luap99 PTAL at the machine tests here - the Linux timeout looks suspicious and is repeating

File: pkg/machine/e2e/basic_test.go [hunk 3]
```diff
@@ -287,6 +287,46 @@ var _ = Describe("run basic podman commands", func() {
 		Expect(build.outputToString()).To(ContainSubstring(name))
 	})
 
+	It("podman build with sbom flags", func() {
+
+		name := randomString()
+		i := new(initMachine)
+		session, err := mb.setName(name).setCmd(i.withImage(mb.imagePath).withNow()).run()
+		Expect(err).ToNot(HaveOccurred())
+		Expect(session).To(Exit(0))
```
Comment (Luap99) [inline pkg/machine/e2e/basic_test.go]: Is there a reason you asked for machine tests in https://github.com/containers/podman/pull/25647#issuecomment-2804735927 @l0rd?

We should keep those only to actual machine related things as they are slow/expensive and flaky. I think the normal remoteintegration target should cover this fine already.

File: test/e2e/build_test.go [hunk 4]
```diff
@@ -972,6 +974,27 @@ RUN ls /dev/test1`, CITEST_IMAGE)
...
+
+		defer os.Remove("./localsbom.txt")
+		if _, err := os.Stat("./localsbom.txt"); err != nil {
+			Expect(errors.Is(err, fs.ErrNotExist)).To(BeFalse())
+		}
+
+		defer os.Remove("./localpurl.txt")
+		if _, err := os.Stat("./localpurl.txt"); err != nil {
+			Expect(errors.Is(err, fs.ErrNotExist)).To(BeFalse())
+		}
```
Comment (Luap99) [inline test/e2e/build_test.go]: gomega has matchers which should return a much better error message if this ever fails.
use
```
Expect("path").To(BeARegularFile())
```

File: pkg/machine/e2e/basic_test.go (hunk 3 above)
Comment (l0rd) [reply pkg/machine/e2e/basic_test.go]: I am sorry, I am answering late but for some reason I didn't get any notification. I think I asked that to cover both daemonless and daemonful scenarios.

Comment (Luap99) [reply pkg/machine/e2e/basic_test.go]: Ack, the test in test/e2e and test/system already get executed locally and via remote client. It is just that client and server are on the same linux system so it is not suited to catch macos or windows client problems but for things like this the e2e case is good enough.

We need to be careful to not add to many machine tests due its slowness/flakiness so I prefer if this case is dropped.

File: test/e2e/build_test.go (hunk 4 above)
Comment (Luap99) [reply test/e2e/build_test.go]: @aguidirh I missed this the first time I looked at it but can you use and absolute path under podmanTest.TempDir instead as well, i.e.
```
localsbomFile := filepath.Join(podmanTest.TempDir, "localsbom.txt")
```

The reason is if this test fails or is aborted the file may get leaked in the cwd which is not very nice for local developers.

File: pkg/machine/e2e/basic_test.go (hunk 3 above)
Comment (l0rd) [reply pkg/machine/e2e/basic_test.go]: @Luap99 Makes sense. @aguidirh Apologies for asking to add an unnecessary test 🤷‍♂️

File: test/e2e/build_test.go (hunk 4 above)
Comment (aguidirh) [reply test/e2e/build_test.go]: @Luap99 I implemented your suggestions which made the code easier to understand, also there is no file leaking now anymore. 

Thanks.

File: pkg/machine/e2e/basic_test.go (hunk 3 above)
Comment (aguidirh) [reply pkg/machine/e2e/basic_test.go]: Don't worry @l0rd, it was good for me to learn more about how the machine tests work.

I removed them as suggested by @Luap99.

**Comment by aguidirh** [comment]
@Luap99 all tests are passing now, could you please take a look to see if there is anything missing before merging this PR?
