### PR TITLE
Fixed #27421 aritfact push and pull with authfile

### LINKED ISSUE #27421: podman-remote artifact push does not use --authfile value
### Issue Description

Using `podman-remote` from within a Toolbx container, I am unable to push OCI artifacts to an image registry that I have known-good credentials for. It appears that podman-remote is not respecting the `--authfile` flag as seen in the expected results section. I believe that only `podman-remote` is affected by this because whenever I run the same command directly on my host, it succeeds.

### Steps to reproduce the issue

Steps to reproduce the issue:
1. `podman artifact add quay.io/zzlotnik/testing:artifact ./hello.txt`
2. `podman artifact --push /path/to/authfile quay.io/zzlotnik/testing:artifact`

(Note: These commands are being run in a Toolbx container with `podman-remote` aliased to `podman`.)

### Describe the results you received

I get an unauthorized error message like this:

```
$ podman artifact push --authfile "/path/to/authfile" quay.io/zzlotnik/testing:artifact
Error: writing manifest: uploading manifest artifact to quay.io/zzlotnik/testing: unauthorized: access to the requested resource is not authorized
```

Running the same command again with `--log-level=trace` suggests that it never considers the value from the `--authfile` flag or the `REGISTRY_AUTH_FILE` env var:
```
$ podman --log-level=trace artifact push --authfile "$HOME/path/to/authfile" quay.io/zzlotnik/testing:artifact
INFO[0000] podman filtering at log level trace
DEBU[0000] Called push.PersistentPreRunE(podman --log-level=trace artifact push --authfile /home/zzlotnik/path/to/authfile quay.io/zzlotnik/testing:artifact)
DEBU[0000] DoRequest Method: GET URI: http://d/v5.6.2/libpod/_ping
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf"
DEBU[0000] No credentials matching cloud.openshift.com found in /run/user/4201110/containers/auth.json
DEBU[0000] No credentials matching cloud.openshift.com found in /home/zzlotnik/.config/containers/auth.json
DEBU[0000] Found credentials for cloud.openshift.com in credential helper containers-auth.json in file /home/zzlotnik/.docker/config.json
DEBU[0000] No credentials matching quay.io found in /run/user/4201110/containers/auth.json
DEBU[0000] No credentials matching quay.io found in /home/zzlotnik/.config/containers/auth.json
DEBU[0000] Found credentials for quay.io in credential helper containers-auth.json in file /home/zzlotnik/.docker/config.json
DEBU[0000] No credentials matching registry.build03.ci.openshift.org found in /run/user/4201110/containers/auth.json
DEBU[0000] No credentials matching registry.build03.ci.openshift.org found in /home/zzlotnik/.config/containers/auth.json
DEBU[0000] Found credentials for registry.build03.ci.openshift.org in credential helper containers-auth.json in file /home/zzlotnik/.docker/config.json
DEBU[0000] No credentials matching registry.ci.openshift.org found in /run/user/4201110/containers/auth.json
DEBU[0000] No credentials matching registry.ci.openshift.org found in /home/zzlotnik/.config/containers/auth.json
DEBU[0000] Found credentials for registry.ci.openshift.org in credential helper containers-auth.json in file /home/zzlotnik/.docker/config.json
DEBU[0000] No credentials matching registry.connect.redhat.com found in /run/user/4201110/containers/auth.json
DEBU[0000] No credentials matching registry.connect.redhat.com found in /home/zzlotnik/.config/containers/auth.json
DEBU[0000] Found credentials for registry.connect.redhat.com in credential helper containers-auth.json in file /home/zzlotnik/.docker/config.json
DEBU[0000] No credentials matching registry.redhat.io found in /run/user/4201110/containers/auth.json
DEBU[0000] No credentials matching registry.redhat.io found in /home/zzlotnik/.config/containers/auth.json
DEBU[0000] Found credentials for registry.redhat.io in credential helper containers-auth.json in file /home/zzlotnik/.docker/config.json
DEBU[0000] DoRequest Method: POST URI: http://d/v5.6.2/libpod/artifacts/quay.io%2Fzzlotnik%2Ftesting:artifact/push
Error: writing manifest: uploading manifest artifact to quay.io/zzlotnik/testing: unauthorized: access to the requested resource is not authorized
DEBU[0000] Shutting down engines
```

It found the `/home/zzlotnik/.docker/config.json` file and found Quay.io credentials in there, but I know they're not the correct credentials for this particular org/repo. If I move that file elsewhere and try again, I get the following output instead:

```
$ podman --log-level=trace artifact push --authfile "$HOME/path/to/authfile" quay.io/zzlotnik/testing:artifact
INFO[0000] podman filtering at log level trace
DEBU[0000] Called push.PersistentPreRunE(podman --log-level=trace artifact push --authfile /home/zzlotnik/path/to/authfile quay.io/zzlotnik/testing:artifact)
DEBU[0000] DoRequest Method: GET URI: http://d/v5.6.2/libpod/_ping
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf"
DEBU[0000] DoRequest Method: POST URI: http://d/v5.6.2/libpod/artifacts/quay.io%2Fzzlotnik%2Ftesting:artifact/push
Error: writing manifest: uploading manifest artifact to quay.io/zzlotnik/testing: unauthorized: access to the requested resource is not authorized
DEBU[0000] Shutting down engines
```

### Describe the results you expected

I was expecting that Podman would allow me to use the `--authfile` flag to provide an alternative push secret, but it seems like it didn't even try to use it, let alone locate it. If I try the same thing with `podman push` and a small scratch image, it finds the supplied credentials and pushes the image as expected:

```
$ podman --log-level=trace push --authfile "/path/to/authfile" quay.io/zzlotnik/testing:scratch
INFO[0000] podman filtering at log level trace
DEBU[0000] Called push.PersistentPreRunE(podman --log-level=trace push --authfile /home/zzlotnik/path/to/authfile quay.io/zzlotnik/testing:scratch)
DEBU[0000] DoRequest Method: GET URI: http://d/v5.6.2/libpod/_ping
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf"
DEBU[0000] Found credentials for quay.io in credential helper containers-auth.json in file /home/zzlotnik/path/to/authfile
DEBU[0000] DoRequest Method: POST URI: http://d/v5.6.2/libpod/images/quay.io/zzlotnik/testing:scratch/push
Getting image source signatures
Copying config sha256:592db74bc3d727dd271af54a0e4a8b595df8036c4d6036e7b80586262775429a
Writing manifest to image destination
DEBU[0001] Called push.PersistentPostRunE(podman --log-level=trace push --authfile /home/zzlotnik/path/to/authfile quay.io/zzlotnik/testing:scratch)
DEBU[0001] Shutting down engines
```

### podman info output

```yaml
$ podman info
Client:
  APIVersion: 5.6.2
  BuildOrigin: Fedora Project
  Built: 1759190400
  BuiltTime: Mon Sep 29 20:00:00 2025
  GitCommit: 9dd5e1ed33830612bc200d7a13db00af6ab865a4
  GoVersion: go1.25.1 X:nodwarf5
  Os: linux
  OsArch: linux/amd64
  Version: 5.6.2
host:
  arch: amd64
  buildahVersion: 1.41.5
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.13-1.fc42.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: '
  cpuUtilization:
    idlePercent: 96.18
    systemPercent: 1.07
    userPercent: 2.75
  cpus: 16
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: workstation
    version: "42"
  emulatedArchitectures:
  - linux/arm
  - linux/arm64
  - linux/arm64be
  - linux/loong64
  - linux/mips
  - linux/mips64
  - linux/ppc
  - linux/ppc64
  - linux/ppc64le
  - linux/riscv32
  - linux/riscv64
  - linux/s390x
  eventLogger: journald
  freeLocks: 2043
  hostname: zzlotnik-thinkpadp16vgen1.rmtuspa.csb
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 4201110
      size: 1
    - container_id: 1
      host_id: 165536
      size: 165536
    uidmap:
    - container_id: 0
      host_id: 4201110
      size: 1
    - container_id: 1
      host_id: 165536
      size: 165536
  kernel: 6.17.4-200.fc42.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1529921536
  memTotal: 65966149632
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.16.0-1.fc42.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.16.0
    package: netavark-1.16.1-1.fc42.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.16.1
  ociRuntime:
    name: crun
    package: crun-1.24-1.fc42.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.24
      commit: 54693209039e5e04cbe3c8b1cd5fe2301219f0a1
      rundir: /run/user/4201110/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20250919.g623dbf6-1.fc42.x86_64
    version: |
      pasta 0^20250919.g623dbf6-1.fc42.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: unix:///run/user/4201110/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.3.1-2.fc42.x86_64
    version: |-
      slirp4netns version 1.3.1
      commit: e5e368c4f5db6ae75c2fce786e31eef9da6bf236
      libslirp: 4.8.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.5
  swapFree: 6517530624
  swapTotal: 8589930496
  uptime: 102h 46m 42.00s (Approximately 4.25 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /home/zzlotnik/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 2
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/zzlotnik/.local/share/containers/storage
  graphRootAllocated: 1022488809472
  graphRootUsed: 156111249408
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 140
  runRoot: /run/user/4201110/containers
  transientStore: false
  volumePath: /home/zzlotnik/.local/share/containers/storage/volumes
version:
  APIVersion: 5.6.2
  BuildOrigin: Fedora Project
  Built: 1759190400
  BuiltTime: Mon Sep 29 20:00:00 2025
  GitCommit: 9dd5e1ed33830612bc200d7a13db00af6ab865a4
  GoVersion: go1.24.7
  Os: linux
  OsArch: linux/amd64
  Version: 5.6.2


$ podman version
Client:        Podman Engine
Version:       5.6.2
API Version:   5.6.2
Go Version:    go1.25.1 X:nodwarf5
Git Commit:    9dd5e1ed33830612bc200d7a13db00af6ab865a4
Built:         Mon Sep 29 20:00:00 2025
Build Origin:  Fedora Project
OS/Arch:       linux/amd64

Server:       Podman Engine
Version:      5.6.2
API Version:  5.6.2
Go Version:   go1.24.7
Git Commit:   9dd5e1ed33830612bc200d7a13db00af6ab865a4
Built:        Mon Sep 29 20:00:00 2025
OS/Arch:      linux/amd64
```

### Podman in a container

Yes

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

I indicated that I am running Podman in a container, which is sort of true. I'm using podman-remote from within a Toolbx image to my host via the user podman socket. For the most part, this works very well for my usual usage patterns. My Toolbx is based on Fedora 43 and my host is currently running Fedora 42 (I will upgrade soon).

My Toolbx image:
```
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="43 (Toolbx Container Image)"
RELEASE_TYPE=stable
ID=fedora
VERSION_ID=43
VERSION_CODENAME=""
PRETTY_NAME="Fedora Linux 43 (Toolbx Container Image)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:43"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f43/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=43
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=43
SUPPORT_END=2026-12-02
VARIANT="Toolbx Container Image"
VARIANT_ID=toolbx
```

My host:
```
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="42 (Workstation Edition)"
RELEASE_TYPE=stable
ID=fedora
VERSION_ID=42
VERSION_CODENAME=""
PLATFORM_ID="platform:f42"
PRETTY_NAME="Fedora Linux 42 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:42"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f42/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=42
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=42
SUPPORT_END=2026-05-13
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

Both podman and podman-remote binaries are built from the same Git tag, albeit with different versions of the Go toolchain:
```
$ podman version
Client:        Podman Engine
Version:       5.6.2
API Version:   5.6.2
Go Version:    go1.25.1 X:nodwarf5
Git Commit:    9dd5e1ed33830612bc200d7a13db00af6ab865a4
Built:         Mon Sep 29 20:00:00 2025
Build Origin:  Fedora Project
OS/Arch:       linux/amd64

Server:       Podman Engine
Version:      5.6.2
API Version:  5.6.2
Go Version:   go1.24.7
Git Commit:   9dd5e1ed33830612bc200d7a13db00af6ab865a4
Built:        Mon Sep 29 20:00:00 2025
OS/Arch:      linux/amd64
```

### Additional information

As mentioned above, I ran the same command directly on my host, which was successful:

```
$ podman --log-level=trace artifact push --authfile "$HOME/path/to/authfile" quay.io/zzlotnik/testing:artifact
INFO[0000] podman filtering at log level trace
DEBU[0000] Called push.PersistentPreRunE(podman --log-level=trace artifact push --authfile /home/zzlotnik/path/to/authfile quay.io/zzlotnik/testing:artifact)
INFO[0000] Setting parallel job count to 49
DEBU[0000] Using conmon: "/usr/bin/conmon"
INFO[0000] Using sqlite as database backend
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /home/zzlotnik/.local/share/containers/storage
DEBU[0000] Using run root /run/user/4201110/containers
DEBU[0000] Using static dir /home/zzlotnik/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/4201110/libpod/tmp
DEBU[0000] Using volume path /home/zzlotnik/.local/share/containers/storage/volumes
DEBU[0000] Using transient store: false
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] Cached value indicated that overlay is supported
DEBU[0000] Cached value indicated that overlay is supported
DEBU[0000] Cached value indicated that metacopy is not being used
DEBU[0000] Cached value indicated that native-diff is usable
DEBU[0000] backingFs=btrfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false
DEBU[0000] Initializing event backend journald
DEBU[0000] Configured OCI runtime crun-wasm initialization failed: no valid executable found for OCI runtime crun-wasm: invalid argument
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument
DEBU[0000] Configured OCI runtime youki initialization failed: no valid executable found for OCI runtime youki: invalid argument
DEBU[0000] Configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument
TRAC[0000] found runtime "/usr/bin/krun"
DEBU[0000] Configured OCI runtime ocijail initialization failed: no valid executable found for OCI runtime ocijail: invalid argument
TRAC[0000] found runtime "/usr/bin/crun"
TRAC[0000] found runtime "/usr/bin/crun-vm"
DEBU[0000] Using OCI runtime "/usr/bin/crun"
DEBU[0000] Using artifact store path: /home/zzlotnik/.local/share/containers/storage/artifacts
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0000] Copying source image /home/zzlotnik/.local/share/containers/storage/artifacts:quay.io/zzlotnik/testing:artifact to destination image //quay.io/zzlotnik/testing:artifact
DEBU[0000] Using registries.d directory /etc/containers/registries.d
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf"
DEBU[0000] Found credentials for quay.io/zzlotnik/testing in credential helper containers-auth.json in file /home/zzlotnik/path/to/authfile
DEBU[0000]  No signature storage configuration found for quay.io/zzlotnik/testing:artifact, using built-in default file:///home/zzlotnik/.local/share/containers/sigstore
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/quay.io
DEBU[0000] Using SQLite blob info cache at /home/zzlotnik/.local/share/containers/cache/blob-info-cache-v1.sqlite
DEBU[0000] IsRunningImageAllowed for image oci:/home/zzlotnik/.local/share/containers/storage/artifacts
DEBU[0000]  Using default policy section
DEBU[0000]  Requirement 0: allowed
DEBU[0000] Overall: allowed
Getting image source signatures
DEBU[0000] Manifest has MIME type application/vnd.oci.image.manifest.v1+json, ordered candidate list [application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.docker.distribution.manifest.v1+json]
DEBU[0000] ... will first try using the original manifest unmodified
DEBU[0000] Checking if we can reuse blob sha256:a948904f2f0f479b8f8197694b30184b0d2ed1c1cd2a1ec0fb85d299a192a447: general substitution = true, compression for MIME type "text/plain; charset=utf-8" = false
DEBU[0000] Checking /v2/zzlotnik/testing/blobs/sha256:a948904f2f0f479b8f8197694b30184b0d2ed1c1cd2a1ec0fb85d299a192a447
DEBU[0000] GET https://quay.io/v2/
DEBU[0000] Ping https://quay.io/v2/ status 401
DEBU[0000] GET https://quay.io/v2/auth?account=zzlotnik%2Bworkstation_push_creds&scope=repository%3Azzlotnik%2Ftesting%3Apull%2Cpush&service=quay.io
DEBU[0000] Increasing token expiration to: 60 seconds
DEBU[0000] HEAD https://quay.io/v2/zzlotnik/testing/blobs/sha256:a948904f2f0f479b8f8197694b30184b0d2ed1c1cd2a1ec0fb85d299a192a447
DEBU[0000] ... already exists
DEBU[0000] Skipping blob sha256:a948904f2f0f479b8f8197694b30184b0d2ed1c1cd2a1ec0fb85d299a192a447 (already present):
Copying blob a948904f2f0f skipped: already exists
DEBU[0000] No compression detected
DEBU[0000] Compression change for blob sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a ("application/vnd.oci.empty.v1+json") not supported
DEBU[0000] Using original blob without modification
DEBU[0000] Checking /v2/zzlotnik/testing/blobs/sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
DEBU[0000] HEAD https://quay.io/v2/zzlotnik/testing/blobs/sha256:44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a
Copying config 44136fa355 done   |
Copying config 44136fa355 done   |
Writing manifest to image destination
DEBU[0000] PUT https://quay.io/v2/zzlotnik/testing/manifests/artifact
DEBU[0000] Called push.PersistentPostRunE(podman --log-level=trace artifact push --authfile /home/zzlotnik/path/to/authfile quay.io/zzlotnik/testing:artifact)
DEBU[0000] Shutting down engines
INFO[0000] Received shutdown.Stop(), terminating!        PID=2580147
```

I'm happy to provide any additional information or context, if needed that might help debug things further.

### PR DESCRIPTION
**Pull request by nimdrak**
#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
Fixes the #27431, `artifact` to use `authfile` when push and pull 
```

### CODE REVIEW

**Comment by baude** [comment]
you need to rebase to pick up a fix for those test failures (not caused by this PR).

**Comment by mheon** [comment]
/approve
Code LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM
once the tests are happy

**Comment by zhangguanzhang** [comment]
After adding a new option, it should also be noted in the relevant documentation.

**Comment by nimdrak** [comment]
@zhangguanzhang Thanks for your review.
I think it's okay because they are already documented.
- https://github.com/containers/podman/blob/2b646e7cb7249373b6b5073dc53a77ad1e1a0aba/docs/source/markdown/podman-artifact-push.1.md.in#L19
- https://github.com/containers/podman/blob/2b646e7cb7249373b6b5073dc53a77ad1e1a0aba/docs/source/markdown/podman-artifact-pull.1.md.in#L24

**Comment by nimdrak** [comment]
I lately discovered a failure in the `podman-remote` integration test for `podman artifact push and pull with authfile`.

```
$ FOCUS="podman artifact push and pull with authfile" make remoteintegration
...
Running: /home/nimdrak/githubs/podman/bin/podman-remote --remote --url unix:///run/user/1000/podman-27f996ba6f4ace2d44a8faf02036e693e8773bc553ddcffd8afe5142ac0efae3.sock artifact push -q --authfile /tmp/nonexistent --tls-verify=false localhost:40257/test/artifact1

  Error: credential file is not accessible: faccessat /tmp/nonexistent: no such file or directory

  Running: /home/nimdrak/githubs/podman/bin/podman-remote --remote --url unix:///run/user/1000/podman-27f996ba6f4ace2d44a8faf02036e693e8773bc553ddcffd8afe5142ac0efae3.sock artifact push -q --authfile /home/nimdrak/tmp/podman-e2e-37057947/subtest-3709030926/p/auth.json --tls-verify=false localhost:40257/test/artifact1

  Error: trying to reuse blob sha256:0647a475f23382b694f0ef6864216dbfa6fdf979f8fde73ad7bbcfd547178b05 at destination: checking whether a blob sha256:0647a475f23382b694f0ef6864216dbfa6fdf979f8fde73ad7bbcfd547178b05 exists in localhost:40257/test/artifact1: authentication required

  [FAILED] Command failed with exit status 125. See above for error message.
...
```

So, I added the missing logic of `PushArtifact` in `pkg/api/handlers/libpod/artifacts.go`

File: test/e2e/artifact_test.go [hunk 1]
```diff
@@ -254,6 +254,58 @@ var _ = Describe("Podman artifact", func() {
...
+			strings.Join([]string{authPath, "/auth", "z"}, ":"), "-e", "REGISTRY_AUTH=htpasswd", "-e",
+			"REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm", "-e", "REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd",
+			REGISTRY_IMAGE)
+		Expect(WaitContainerReady(podmanTest, "artifact-authfile-registry", "listening on", 20, 1)).To(BeTrue(), "registry container ready")
+
+		authFile := filepath.Join(podmanTest.TempDir, "auth.json")
+		server := fmt.Sprintf("localhost:%s", port)
+		login := podmanTest.Podman([]string{"login", "--username", "podmantest", "--password", "test", "--authfile", authFile, "--tls-verify=false", server})
+		login.WaitWithDefaultTimeout()
+		Expect(login).Should(ExitCleanly())
```
Comment (Honny1) [inline test/e2e/artifact_test.go]: Non-blocking: Consider also using `PodmanExitCleanly`.

Comment (nimdrak) [reply test/e2e/artifact_test.go]: Good. Thanks, I reflected it. Please check it.

**Comment by nimdrak** [comment]
These failed tests seem unrelated to this PR.

**Comment by Honny1** [comment]
LGTM, I rerun tests.
