### PR TITLE
kube: rm secret on down, print secret on play

### LINKED ISSUE #17071: [Bug]: podman kube play does not list secrets
### Issue Description

Running `podman kube play` on a K8s YAML with a secret will create the secret but not print anything on the terminal.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run the following YAML:
```YAML
apiVersion: v1              
kind: Secret                
metadata:                   
  name: newsecret           
type: Opaque                
data:                       
  username: dXNlcg==        
  password: NTRmNDFkMTJlOGZh
```

### Describe the results you received

No output.

### Describe the results you expected

The ID of the created secret.

### podman info output

```shell
Latest HEAD and 4.3.1.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by danishprakash**
Closes #17071

Signed-off-by: danishprakash <danish.prakash@suse.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

File: test/e2e/play_kube_test.go [hunk 1]
```diff
@@ -3820,6 +3826,30 @@ invalid kube kind
 		Expect(checkls.OutputToStringArray()).To(BeEmpty())
 	})
 
+	It("podman play kube teardown with secret", func() {
+		err := writeYaml(secretYaml, kubeYaml)
+		Expect(err).ToNot(HaveOccurred())
+
+		kube := podmanTest.Podman([]string{"play", "kube", kubeYaml})
+		kube.WaitWithDefaultTimeout()
+		Expect(kube).Should(Exit(0))
```
Comment (vrothberg) [inline test/e2e/play_kube_test.go:3835]: I think we should check that the output of `play kube` also lists secrets.

File: test/e2e/play_kube_test.go [hunk 2]
```diff
@@ -3820,6 +3826,30 @@ invalid kube kind
...
+
+		ls := podmanTest.Podman([]string{"secret", "ls", "--format", "'{{.ID}}'"})
+		ls.WaitWithDefaultTimeout()
+		Expect(ls).Should(Exit(0))
+		Expect(ls.OutputToStringArray()).To(HaveLen(1))
+
+		//	 teardown
+		teardown := podmanTest.Podman([]string{"play", "kube", "--down", kubeYaml})
+		teardown.WaitWithDefaultTimeout()
+		Expect(teardown).Should(Exit(0))
```
Comment (vrothberg) [inline test/e2e/play_kube_test.go:3845]: Same here.  We should check that the output indicates that the secret has been removed.

File: test/e2e/play_kube_test.go [hunk 3]
```diff
@@ -3820,6 +3826,30 @@ invalid kube kind
 		Expect(checkls.OutputToStringArray()).To(BeEmpty())
 	})
 
+	It("podman play kube teardown with secret", func() {
+		err := writeYaml(secretYaml, kubeYaml)
+		Expect(err).ToNot(HaveOccurred())
+
+		kube := podmanTest.Podman([]string{"play", "kube", kubeYaml})
```
Comment (vrothberg) [inline test/e2e/play_kube_test.go:3833]:
```suggestion
		kube := podmanTest.Podman([]string{"kube", "play", kubeYaml})
```

File: test/e2e/play_kube_test.go [hunk 4]
```diff
@@ -3820,6 +3826,30 @@ invalid kube kind
...
+		kube.WaitWithDefaultTimeout()
+		Expect(kube).Should(Exit(0))
+
+		ls := podmanTest.Podman([]string{"secret", "ls", "--format", "'{{.ID}}'"})
+		ls.WaitWithDefaultTimeout()
+		Expect(ls).Should(Exit(0))
+		Expect(ls.OutputToStringArray()).To(HaveLen(1))
+
+		//	 teardown
+		teardown := podmanTest.Podman([]string{"play", "kube", "--down", kubeYaml})
```
Comment (vrothberg) [inline test/e2e/play_kube_test.go:3843]:
```suggestion
		teardown := podmanTest.Podman([]string{"kube", "down", kubeYaml})
```

**Review by vrothberg — COMMENTED** [review]
Thanks!  Just some minor nits.

To pass CI, please rebase on top of the latest HEAD.  We're facing some issue with the infrastructure at the moment, apologies.

File: test/e2e/play_kube_test.go (hunk 1 above)
Comment (danishprakash) [reply test/e2e/play_kube_test.go:3835]: I had included that in the existing kube play test because we're specifically testing teardown here. Here-  https://github.com/containers/podman/pull/17526/files#diff-cef3dd63f572aaef036dce65d94140edbfa8c350c2fc836e864a6b1ef653db87R1649-R1653 Does this help?

Comment (vrothberg) [reply test/e2e/play_kube_test.go:3878]: yes, thanks!

**Review by vrothberg — APPROVED** [review]
/lgtm
/hold
