### PR TITLE
Fix container clone with secret type=env

### LINKED ISSUE #28130: podman container clone fails with secret_env type mismatch when container uses --secret name,type=env
### Issue Description

podman container clone fails with a JSON unmarshaling error when the source container has secrets injected as environment variables (--secret name,type=env).

The root cause is a type mismatch between two Go structs sharing the same "secret_env" JSON tag:
- ContainerMiscConfig.EnvSecrets in libpod/container_config.go is map[string]*secrets.Secret (object)
- ContainerBasicConfig.EnvSecrets in pkg/specgen/specgen.go is map[string]string

ConfigToSpec() in pkg/specgen/generate/container.go serializes the container config to JSON and deserializes it into a SpecGenerator. The secret_env field serializes as a JSON object but the target expects a string value, causing the unmarshal to fail.

### Steps to reproduce the issue

1. Create a podman secret
echo "my-secret-value" | podman secret create MY_SECRET -

2. Run a container with the secret as an env var
podman run -d --name test_container --secret MY_SECRET,type=env docker.io/library/alpine:latest sleep 3600

3. Try to clone it
podman container clone test_container test_clone docker.io/library/alpine:latest

### Describe the results you received

Error: json: cannot unmarshal object into Go struct field SpecGenerator.ContainerBasicConfig.secret_env of type string

### Describe the results you expected

The container should be cloned successfully, preserving the secret environment variable configuration.

### podman info output

```yaml
Ubuntu 24.04 amd64 5.4.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ozgur-as**
#### Checklist

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
Fixed `podman container clone` failing when the source container uses `--secret name,type=env`.
```

`podman container clone` fails with `json: cannot unmarshal object into Go struct field SpecGenerator.ContainerBasicConfig.secret_env of type string` when the source container uses `--secret name,type=env`.

`ConfigToSpec()` serializes the container config to JSON and deserializes it into a `SpecGenerator`. Both structs use the JSON tag `secret_env` but with incompatible types: the container config uses `map[string]*secrets.Secret` (complex objects with Name, ID, Labels, etc.) while the specgen uses `map[string]string` (env var name to secret name). The Secret objects serialize as JSON objects, which cannot be unmarshaled into string values.

This is fixed by saving and clearing `EnvSecrets` before JSON marshal (same pattern as existing `tmpSystemd`/`tmpMounts`), then converting the secret objects to name strings and assigning them to the specgen afterward. Additionally, `FillOutSpecGen` is fixed to not overwrite env secrets populated by `ConfigToSpec` when no new secrets are provided on the command line.

Fixes: #28130

### CODE REVIEW

File: test/e2e/container_clone_test.go [hunk 1]
```diff
@@ -299,6 +302,31 @@ var _ = Describe("Podman container clone", func() {
 		Expect(session.OutputToString()).Should(ContainSubstring("12=3"))
 	})
 
+	It("podman container clone with secret env", func() {
+		secretsString := "somesecretdata"
+		secretFilePath := filepath.Join(podmanTest.TempDir, "secret")
+		err := os.WriteFile(secretFilePath, []byte(secretsString), 0o755)
+		Expect(err).ToNot(HaveOccurred())
+
+		session := podmanTest.Podman([]string{"secret", "create", "mysecret", secretFilePath})
```
Comment (Honny1) [inline test/e2e/container_clone_test.go]: Most of this test can be simplified using `podmanTest.PodmanExitCleanly`.

File: test/e2e/container_clone_test.go [hunk 2]
```diff
@@ -299,6 +302,31 @@ var _ = Describe("Podman container clone", func() {
...
+		session = podmanTest.Podman([]string{"run", "--secret", "source=mysecret,type=env", "--name", "secr", ALPINE, "printenv", "mysecret"})
+		session.WaitWithDefaultTimeout()
+		Expect(session).Should(ExitCleanly())
+		Expect(session.OutputToString()).To(Equal(secretsString))
+
+		session = podmanTest.Podman([]string{"container", "clone", "secr"})
+		session.WaitWithDefaultTimeout()
+		Expect(session).Should(ExitCleanly())
+
+		session = podmanTest.Podman([]string{"start", "-a", "secr-clone"})
```
Comment (Honny1) [inline test/e2e/container_clone_test.go]: Can you also verify that the secret environment variable configuration is being preserved?

**Review by Honny1 — CHANGES_REQUESTED** [review]

File: test/e2e/container_clone_test.go (hunk 1 above)
Comment (ozgur-as) [reply test/e2e/container_clone_test.go]: Done, updated to use PodmanExitCleanly.

File: test/e2e/container_clone_test.go (hunk 2 above)
Comment (ozgur-as) [reply test/e2e/container_clone_test.go]: Added an inspect check that verifies the clone has the secret env entry.

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, but the tests aren't hip.

I don't think it's related to this change, I'm going to restart them.

**Review by Honny1 — APPROVED** [review]
LGTM, Thanks.

**Review by Luap99 — APPROVED** [review]
LGTM
