### PR TITLE
fix ulimit issue

### LINKED ISSUE #18714: change in `ulimit -u` causes existing containers to not start
### Issue Description

Similar to #18555 but without using kube.

Updating my computer from Fedora Silverblue 38.20230526.0 to 38.20230527.0 slightly decreased the value output by `ulimit -u` from 63329 to 63304. This caused existing containers to not launch with the error:

```
crun: setrlimit `RLIMIT_NPROC`: Operation not permitted: OCI permission denied
```

The containers never had a ulimit set manually on the command line, however looking at the output of `podman inspect` the ulimit value did get saved into the config causing a subsequent decrease in ulimit to break the containers.

### Steps to reproduce the issue

Not a full reproduction as I'm not sure how to easily decrease the value of `ulimit -u` for your system, but just demonstrating that without using `--ulimit` a value does get saved into the config:

1. `podman create test docker.io/alpine:3.18`
2. `podman inspect test`

### Describe the results you received

Output includes:
```
"Ulimits": [
                    {
                         "Name": "RLIMIT_NOFILE",
                         "Soft": 524288,
                         "Hard": 524288
                    },
                    {
                         "Name": "RLIMIT_NPROC",
                         "Soft": 63329,
                         "Hard": 63329
                    }
               ],
```

### Describe the results you expected

Output includes:
```
"Ulimits": [],
```

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 85.64
    systemPercent: 4.35
    userPercent: 10.01
  cpus: 4
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: silverblue
    version: "38"
  eventLogger: journald
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 6.2.15-300.fc38.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 12819206144
  memTotal: 16687968256
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.5-1.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-12.fc38.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 16687034368
  swapTotal: 16687034368
  uptime: 0h 10m 8.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/jan/.config/containers/storage.conf
  containerStore:
    number: 35
    paused: 0
    running: 1
    stopped: 34
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/jan/.local/share/containers/storage
  graphRootAllocated: 1004390125568
  graphRootUsed: 115150499840
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 43
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /var/home/jan/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.0
  Built: 1681486942
  BuiltTime: Fri Apr 14 17:42:22 2023
  GitCommit: ""
  GoVersion: go1.20.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Cydox**
Fixes #18714

#### Does this PR introduce a user-facing change?

```release-note
Fixed an issue where lowering the ulimit -u after a container got created will lead to the container failing to launch.
```

This touches a lot of code I'm not familiar with, so I'm playing it slow. Starting by adding tests that are supposed to fail on current main.

### CODE REVIEW

**Comment by Cydox** [comment]
Looks like the test is "[failing successfully](https://cirrus-ci.com/build/6164579554689024)"

**Comment by Cydox** [comment]
There appear to be two different failures here.

1. The added `Container inspect WIP test` still fails for the rootfull configuration. ([example](https://api.cirrus-ci.com/v1/artifact/task/5435548785967104/html/int-podman-fedora-38-root-host-boltdb.log.html#t--Container-inspect-WIP-test--1))
2. For the rootless configurations the `limits test` is failing ([example](https://api.cirrus-ci.com/v1/artifact/task/5118889437167616/html/int-podman-fedora-38-rootless-host-boltdb.log.html#t--limits-test--1))

**Comment by Cydox** [comment]
For 2. (`limits tesst`): This test is works on my system.

Is there a simple way to get the VM image used in the CI to test locally. The script in `/hack/get_ci_vm.sh` is asking me for GCP credentials (is it trying to provision a VM on GCP?)?

File: pkg/specgen/container_validate.go [hunk 1]
```diff
@@ -135,38 +133,6 @@ func (s *SpecGenerator) Validate() error {
 	// default:
 	//	return errors.New("unrecognized option for cgroups; supported are 'default', 'disabled', 'no-conmon'")
 	// }
-	invalidUlimitFormatError := errors.New("invalid default ulimit definition must be form of type=soft:hard")
-	// set ulimits if not rootless
-	if len(s.ContainerResourceConfig.Rlimits) < 1 && !rootless.IsRootless() {
```
Comment (Luap99) [inline pkg/specgen/container_validate.go:140]: Why did you remove this? This sets the limit based on containers.conf defaults so we need to keep it. Although doing this in Validate() looks wrong.

File: pkg/specgen/generate/oci.go [hunk 2]
```diff
@@ -7,71 +7,21 @@ import (
...
-		} else if name == "RLIMIT_NPROC" {
-			nprocSet = true
-		}
-		g.AddProcessRlimits(name, u.Hard, u.Soft)
-	}
-
-	// If not explicitly overridden by the user, default number of open
-	// files and number of processes to the maximum they can be set to
-	// (without overriding a sysctl)
-	if !nofileSet {
```
Comment (Luap99) [inline pkg/specgen/generate/oci.go:42]: I am pretty sure we actually want this. The problem is that we only set it once on create instead of for each start.

So I think this must be moved into `func (c *Container) generateSpec()` instead

**Review by Luap99 — COMMENTED** [review]
@giuseppe PTAL

**Comment by Luap99** [comment]
> For 2. (`limits test`): This test works on my system.
> 
> Is there a simple way to get the VM image used in the CI to test locally? The script in `/hack/get_ci_vm.sh` is asking me for GCP credentials (is it trying to provision a VM on GCP?).

Yes, the goal is to have a VM that matches the CI environment to 100%. It is only intended for us (RedHat maintainers) as it requires special GCE permission, however I can create a VM for you and add your public ssh key if you really need access.

File: pkg/specgen/container_validate.go (hunk 1 above)
Comment (Cydox) [reply pkg/specgen/container_validate.go:140]: I'm under the impression that it's already set by
https://github.com/containers/podman/blob/77bd041a9665373b23a1cab77d4bffe28514649a/pkg/specgenutil/specgen.go#L771

Doing a quick test it looks like a ulimit from containers.conf still makes it into a container, so this was redundant. However it's in there twice right now. So I think the containers.conf defaults also make it to:
https://github.com/containers/podman/blob/77bd041a9665373b23a1cab77d4bffe28514649a/pkg/specgen/generate/container_create.go#L34

File: pkg/specgen/generate/oci.go (hunk 2 above)
Comment (Cydox) [reply pkg/specgen/generate/oci.go:42]: Is there a problem with leaving the ulimits in the spec file empty? The container process should inherit the limits, right?

Is that generateSpec invoked on each run and the spec passed to crun, or is it also saved on disk for the next time the container is started?

Comment (Cydox) [reply pkg/specgen/generate/oci.go:42]: Ok, so `func (c *Container) generateSpec()` from container_internal_common.go gets executed each time the container is started if it's in `ContainerStateConfigured` or `ContainerStateExited`. I'll put setting the max ulimits in there and see if that fixes the CI issues for rootless.

I'll also disable the new test for rootfull, as this issue is not really applicable to rootfull.

Comment (Cydox) [reply pkg/specgen/generate/oci.go:42]: Looks like this approach works on my end.

**Comment by Cydox** [comment]
Alright, ulimits are now set to the maximum possible value (if not overriden) in the `generateSpec()` function each time the container is started instead of at creation time.

Also added a test under `test/system` that starts a container, lowers the `ulimit` and starts the container a second time. Couldn't get the `assert` statement properly escaped. It's currently only matching against the number of the ulimit. I would prefer to match against `"Soft": $nproc_limit`. How do I escape this properly? Could also use `jq` alternatively.

File: pkg/specgen/generate/oci.go (hunk 2 above)
Comment (Cydox) [reply pkg/specgen/generate/oci.go:42]: Incorporated into latest version of this PR

File: pkg/specgen/container_validate.go (hunk 1 above)
Comment (Cydox) [reply pkg/specgen/container_validate.go:140]: The issue with the limits being in the list twice is fixed.

File: test/system/045-start.bats [hunk 3]
```diff
@@ -99,4 +99,45 @@ load helpers
...
+    run_podman inspect $ctrID
+    assert "$output" =~ '"Ulimits": \[\]' "Ulimits has to be empty after create"
+
+    # start containers for the first time
+    run_podman start $ctrID
+    is "$output" "$ctrID"
+
+    # inspect
+    run_podman inspect $ctrID
+    assert "$output" =~ ${nrpoc_limit} "Soft limit has to be set to ulimit -u"
```
Comment (Luap99) [inline test/system/045-start.bats:122]: > Also added a test under test/system that starts a container, lowers the ulimit and starts the container a second time. Couldn't get the assert statement properly escaped. It's currently only matching against the number of the ulimit. I would prefer to match against "Soft": $nproc_limit. How do I escape this properly? Could also use jq alternatively.

How about: 
```
podman inspect --format '{{range .HostConfig.Ulimits}}{{if eq .Name "RLIMIT_NPROC" }}{{.Soft}}:{{.Hard}}{{end}}{{end}}'
```
Then just use `assert "$output" == "${nrpoc_limit}:${nrpoc_limit}"`

Comment (Cydox) [reply test/system/045-start.bats]: Nice, didn't think of `--format`, works!

**Review by Luap99 — APPROVED** [review]
LGTM

@giuseppe @umohnani8 PTAL

**Comment by rhatdan** [comment]
/lgtm
Thanks @Cydox
