### PR TITLE
kube play: always pull when both imagePullPolicy and tag are missing

### LINKED ISSUE #21211: `imagePullPolicy` should be set to `Always` when both imagePullPolicy and tag are missing
### Issue Description

The behaviour of `podman kube play file.yaml` does not match the Kubernetes docs:

- if you omit the `imagePullPolicy` field, and you don't specify the tag for the
  container image, `imagePullPolicy` is automatically set to `Always`;

Reference:
https://github.com/kubernetes/website/blob/589540642638c035d824162ef9f57ba4234cb1e6/content/en/docs/concepts/containers/images.md?plain=1#L120-L121

### Steps to reproduce the issue

On a __Fedora CoreOS 40.20231209.91.0__ machine with __Podman 4.8.1__ do these steps

1. Create the file _/tmp/reproduce.bash_ with the contents
   ```
   #!/bin/bash

   set -o nounset
   set -o errexit

   ending=$1

   cat << EOF > alp.yaml

   apiVersion: v1
   kind: Pod
   metadata:
     name: test
     namespace: default
   spec:
     containers:
     - name: test
       image: docker.io/library/alpine
       command:
       - /bin/true
     restartPolicy: Never
   EOF

   sed -i "s/alpine/alpine${ending}/" alp.yaml

   podman pull -q docker.io/library/alpine:latest
   podman kube play --log-level=debug alp.yaml > log.txt 2>&1
   grep "GET https://" log.txt
   ```
2. Create the file _/tmp/test.bash_ with the contents
   ```
   #!/bin/bash

   set -o errexit
   set -o nounset

   user=$1
   append=$2

   sudo useradd $user
   sudo systemd-run \
     --collect \
     --machine=${user}@ \
     --pipe \
     --quiet \
     --user \
     --wait \
     bash /tmp/reproduce.bash "$append"
   ```
3. `bash /tmp/test.bash test1 ""`
4. `bash /tmp/test.bash test2 ":latest"`

### Describe the results you received

Step 3 prints the output
```
1dc785547989b0db1c3cd9949c57574393e69bea98bfe044b0588e24721aa402
```

Step 4 prints the output
```
1dc785547989b0db1c3cd9949c57574393e69bea98bfe044b0588e24721aa402
time="2024-01-09T19:37:31+01:00" level=debug msg="GET https://registry-1.docker.io/v2/"
time="2024-01-09T19:37:32+01:00" level=debug msg="GET https://auth.docker.io/token?scope=repository%3Alibrary%2Falpine%3Apull&service=registry.docker.io"
time="2024-01-09T19:37:32+01:00" level=debug msg="GET https://registry-1.docker.io/v2/library/alpine/manifests/latest"
time="2024-01-09T19:37:33+01:00" level=debug msg="GET https://registry-1.docker.io/v2/library/alpine/manifests/sha256:a70bcfbd89c9620d4085f6bc2a3e2eef32e8f3cdf5a90e35a1f95dcbd7f71548"
```

### Describe the results you expected

I would have expected step 3 and step  4 to show similar output (something like what step 4 produces).

### podman info output

```yaml
host:
  arch: arm64
  buildahVersion: 1.33.2
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.8-2.fc40.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: '
  cpuUtilization:
    idlePercent: 99.65
    systemPercent: 0.14
    userPercent: 0.21
  cpus: 1
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: coreos
    version: "40"
  eventLogger: journald
  freeLocks: 2045
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1015
      size: 1
    - container_id: 1
      host_id: 3393216
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1015
      size: 1
    - container_id: 1
      host_id: 3393216
      size: 65536
  kernel: 6.7.0-0.rc4.20231208git5e3f5b81de80.38.fc40.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 184836096
  memTotal: 2045280256
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.9.0-1.fc40.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.9.0
    package: netavark-1.9.0-1.fc40.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.9.0
  ociRuntime:
    name: crun
    package: crun-1.12-1.fc40.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.12
      commit: ce429cb2e277d001c2179df1ac66a470f00802ae
      rundir: /run/user/1015/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20231204.gb86afe3-1.fc40.aarch64
    version: |
      pasta 0^20231204.gb86afe3-1.fc40.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: false
    path: /run/user/1015/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-1.fc40.aarch64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 178h 58m 46.00s (Approximately 7.42 days)
  variant: v8
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/test13/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/test13/.local/share/containers/storage
  graphRootAllocated: 10132369408
  graphRootUsed: 7994347520
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/1015/containers
  transientStore: false
  volumePath: /var/home/test13/.local/share/containers/storage/volumes
version:
  APIVersion: 4.8.1
  Built: 1701777641
  BuiltTime: Tue Dec  5 13:00:41 2023
  GitCommit: ""
  GoVersion: go1.21.4
  Os: linux
  OsArch: linux/arm64
  Version: 4.8.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

(I also tried Podman 4.8.3)

### Additional environment details

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mporrato**
Align the behaviour of `podman kube play file.yaml` to Kubernetes' by forcing an image pull when `imagePullPolicy` is omitted and the container image does not specify a tag.

Fixes #21211 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — APPROVED** [review]
LGTM, thanks!

File: test/e2e/play_kube_test.go [hunk 1]
```diff
@@ -3163,6 +3163,40 @@ var _ = Describe("Podman kube play", func() {
...
+		tag.WaitWithDefaultTimeout()
+		Expect(tag).Should(ExitCleanly())
+
+		rmi := podmanTest.Podman([]string{"rmi", oldBB})
+		rmi.WaitWithDefaultTimeout()
+		Expect(rmi).Should(ExitCleanly())
+
+		inspect := podmanTest.Podman([]string{"inspect", BB})
+		inspect.WaitWithDefaultTimeout()
+		oldBBinspect := inspect.InspectImageJSON()
```
Comment (Luap99) [inline test/e2e/play_kube_test.go:3182]: This is missing an exit code check, needs to have an `Expect(inspect).Should(ExitCleanly())`

File: test/e2e/play_kube_test.go [hunk 2]
```diff
@@ -3163,6 +3163,40 @@ var _ = Describe("Podman kube play", func() {
...
+
+		noTagBB := "quay.io/libpod/busybox"
+		ctr := getCtr(withImage(noTagBB), withPullPolicy(""))
+		err := generateKubeYaml("pod", getPod(withCtr(ctr)), kubeYaml)
+		Expect(err).ToNot(HaveOccurred())
+
+		kube := podmanTest.Podman([]string{"kube", "play", kubeYaml})
+		kube.WaitWithDefaultTimeout()
+		// Cannot ExitCleanly() because pull output goes to stderr
```
Comment (Luap99) [inline test/e2e/play_kube_test.go:3191]: you should check the stderr output here as it should contain the pull output, i.e. `Copying blob`

**Comment by martinpitt** [comment]
There is the [podman build](https://artifacts.dev.testing-farm.io/0c666a95-9e26-40ec-b3fb-3103a2557b1c/) hang again on rawhide which I've seen several times in the last few weeks. The subsequent tests then also fail as there seems to be an unkillable `podman` process. This smells like a kernel issue at first. The [journal](https://artifacts.dev.testing-farm.io/0c666a95-9e26-40ec-b3fb-3103a2557b1c/work-podman-systemcvlzh4r7/plans/cockpit-podman/podman-system/execute/data/guest/default-0/test/browser/system-1/data/TestApplication-testBasicSystem-fedora-40-127.0.0.1-22-FAIL.log.gz) doesn't have anything unusual/interesting.

I'll add this to the TODO list to see if I can reproduce it locally with running this in a loop, but I won't get to it much next week as I'll be on a sprint.

In the meantime, you can either retry or ignore that failure (with my blessing :grin: )

**Comment by martinpitt** [comment]
I locally ran that test a few hundred times in two parallel VMs, with the same kernel version, and didn't manage to reproduce the lockup. That's either unfortunate timing or some quirk/bug on the EC2 (where Testing Farm instances run). Meh..

**Comment by Luap99** [comment]
@martinpitt follow https://github.com/containers/podman/issues/21504 for the hang, so far we were not able to reproduce either.

**Comment by mporrato** [comment]
@Luap99 anything needed on my side to move this forward?
