### PR TITLE
The `--ulimit` option now also accepts the name with an `RLIMIT_` prefix both upper and lower case.

### LINKED ISSUE #18077: Problems with RLIMIT_* resources
### Issue Description

watchtower fails to create new container with error:

```Apr 06 01:23:36 ubuntu-s-1vcpu-1gb-lon1-01 conmon[25768]: time="2023-04-05T22:23:36Z" level=info msg="Session done" Failed=0 Scanned=1 Updated=0 notify=no
Apr 06 01:23:36 ubuntu-s-1vcpu-1gb-lon1-01 conmon[25768]: time="2023-04-05T22:23:36Z" level=error msg="Error response from daemon: fill out specgen: ulimit option \"RLIMIT_NOFILE=1048576:1048576\" requires name=SOFT:HARD, failed to be parsed: invalid ulimit type: RLIMIT_NOFILE"
Apr 06 01:23:36 ubuntu-s-1vcpu-1gb-lon1-01 podman[27038]: @ - - [06/Apr/2023:01:23:36 +0300] "POST /v1.25/containers/create?name=%2Fshadowbox HTTP/1.1" 500 221 "" "Go-http-client/1.1"
Apr 06 01:23:36 ubuntu-s-1vcpu-1gb-lon1-01 podman[27038]: time="2023-04-06T01:23:36+03:00" level=info msg="Request Failed(Internal Server Error): fill out specgen: ulimit option \"RLIMIT_NOFILE=1048576:1048576\" requires name=SOFT:HARD, failed to be parsed: invalid ulimit type: RLIMIT_NOFILE"
Apr 06 01:23:36 ubuntu-s-1vcpu-1gb-lon1-01 conmon[25768]: time="2023-04-05T22:23:36Z" level=info msg="Creating /shadowbox"```

### Steps to reproduce the issue

Create outline instance with following script https://gist.github.com/xpahos/2801ae546ac00d2e269396188195d692

### Describe the results you received

```
 ulimit option \"RLIMIT_NOFILE=1048576:1048576\" requires name=SOFT:HARD, failed to be parsed: invalid ulimit type: RLIMIT_NOFILE"
```

problems with parsing resources

### Describe the results you expected

normal parsing

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 1
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: ubuntu-s-1vcpu-1gb-lon1-01
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.0-69-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 174383104
  memTotal: 2071928832
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 0
  swapTotal: 0
  uptime: 21h 58m 42.83s (Approximately 0.88 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 03:00:00 1970
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by xpahos**
RLIMIT_* resources constants are converted to the proper format for the go-units module.

Fixes #18077

#### Does this PR introduce a user-facing change?

None

Signed-off-by: Alexander Gryanko <xpahos@gmail.com>

### CODE REVIEW

File: pkg/specgenutil/specgenutil_test.go [hunk 1]
```diff
@@ -154,3 +156,64 @@ func TestParseLinuxResourcesDeviceAccess(t *testing.T) {
...
+	assert.NotNil(t, err, "err is not nil")
+
+	_, err = GenRlimits([]string{"nofile"})
+	assert.NotNil(t, err, "err is not nil")
+
+	_, err = GenRlimits([]string{"nofile=bar"})
+	assert.NotNil(t, err, "err is not nil")
+
+	_, err = GenRlimits([]string{"nofile=bar:buzz"})
+	assert.NotNil(t, err, "err is not nil")
```
Comment (Luap99) [inline pkg/specgenutil/specgenutil_test.go:218]: consider using assert.Error() for these, this will provide a much friendlier error message in case of an failure

File: pkg/specgenutil/specgenutil_test.go [hunk 2]
```diff
@@ -154,3 +156,64 @@ func TestParseLinuxResourcesDeviceAccess(t *testing.T) {
...
+
+	lowerCaseLimits := make([]string, 0, len(testLimits))
+	upperCaseLimitsWithPrefix := make([]string, 0, len(testLimits))
+	for name, limit := range testLimits {
+		lowerCaseLimits = append(lowerCaseLimits, fmt.Sprintf("%s=%s", name, limit))
+		upperCaseLimitsWithPrefix = append(upperCaseLimitsWithPrefix, strings.ToUpper(fmt.Sprintf("%s%s=%s", rlimitPrefix, name, limit)))
+	}
+
+	parsedLimits, err := GenRlimits(lowerCaseLimits)
+	assert.Nil(t, err, "err is nil")
```
Comment (Luap99) [inline pkg/specgenutil/specgenutil_test.go:187]: here as well, use assert.NoError()

File: pkg/specgenutil/specgenutil_test.go [hunk 3]
```diff
@@ -154,3 +156,64 @@ func TestParseLinuxResourcesDeviceAccess(t *testing.T) {
...
+
+	for _, limit := range parsedLimits {
+		val, ok := testLimits[limit.Type]
+		assert.True(t, ok, "%s matched", limit.Type)
+		assert.Equal(t, val, fmt.Sprintf("%d:%d", limit.Soft, limit.Hard), "soft and hard limits are equal")
+	}
+
+	parsedLimits, err = GenRlimits(upperCaseLimitsWithPrefix)
+	assert.Nil(t, err, "err is nil")
```
Comment (Luap99) [inline pkg/specgenutil/specgenutil_test.go:196]: same here

**Review by Luap99 — COMMENTED** [review]
Thanks for the PR, I just have a small nit for the test error reporting.

**Comment by Luap99** [comment]
You also need to fix the linting error, make sure to run gofmt on the file.

**Comment by Luap99** [comment]
Also consider adding a proper release note entry to your PR description, how about?
```
The `--ulimit` option now also accepts the name with an `RLIMIT_` prefix both upper and lower case.
```

**Comment by xpahos** [comment]
> You also need to fix the linting error, make sure to run gofmt on the file.

Sorry for the stupid question. Maybe you can help me with the local linter? I have tried ``make validate`` and ``podman build -t gate -f contrib/gate/Dockerfile``  but of them are not working.  The first command shows a lot of errors. Docker file doesn't exist.

**Comment by Luap99** [comment]
`make validate` should just work, it does at least on my system.
For `contrib/gate/Dockerfile` I think we removed this a while ago, looks like we did not update the docs in all places.

**Comment by xpahos** [comment]
> `make validate` should just work, it does at least on my system. For `contrib/gate/Dockerfile` I think we removed this a while ago, looks like we did not update the docs in all places.

I've got a long list of errors https://pastebin.com/7WNY5GCy 

```
go version go1.19.3 linux/amd64
``

**Comment by Luap99** [comment]
Oh yeah ignore the typecheck errors, I never figured out why or when it happens but I have seen these before.
If CI is happy then you are good.

**Comment by xpahos** [comment]
@Luap99 looks like I need more help. I'm trying to reproduce failed check in the qemu environment. ``make localsystem`` returns no error in the aarch64 emulator.

**Review by giuseppe — APPROVED** [review]
LGTM
