### PR TITLE
Fix `unless-stopped` restart policy to match Docker behavior

### LINKED ISSUE #20418: podman-restart.service Does Not Restart "unless-stopped" Containers
### Issue Description

Containers with `RestartPolicy=unless-stopped` are never started.

### Steps to reproduce the issue

1. Use docker to start a few containers with "restart: unless-stopped" configuration.
2. Reboot the system with the podman-restart.service daemon enabled.

### Describe the results you received

All containers with the "unless-stopped" configuration are not restarted by podman-restart.service.

### Describe the results you expected

All running containers with a "unless-stopped" configuration get restarted by podman-restart.service upon system boot.

### podman info output

```yaml
host:
  arch: arm64
  buildahVersion: 1.32.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 98.56
    systemPercent: 0.5
    userPercent: 0.93
  cpus: 4
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: coreos
    version: "38"
  eventLogger: journald
  freeLocks: 2038
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.5.6-200.fc38.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 1659879424
  memTotal: 4086497280
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.8.0-1.fc38.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.8.0
    package: netavark-1.8.0-2.fc38.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.8.0
  ociRuntime:
    name: crun
    package: crun-1.9.2-1.fc38.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.9.2
      commit: 35274d346d2e9ffeacb22cc11590b0266a23d634
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20231004.gf851084-1.fc38.aarch64
    version: |
      pasta 0^20231004.gf851084-1.fc38.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.1-1.fc38.aarch64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 1h 35m 16.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 3
    stopped: 4
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 6182490112
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.7.0
  Built: 1695839065
  BuiltTime: Wed Sep 27 18:24:25 2023
  GitCommit: ""
  GoVersion: go1.20.8
  Os: linux
  OsArch: linux/arm64
  Version: 4.7.0
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Running on MacOS via homebrew.

### Additional information

#17851 and #17580 have also reported this & been closed, but this is still happening.

### PR DESCRIPTION
**Pull request by Honny1**
- Update documentation: Differentiate `unless-stopped` from `always` - containers stopped by the user before a reboot will not restart.
- Add `should-start-on-boot` filter: Identify containers that require a restart after a system reboot.
- Update command documentation: Add `restart-policy` and `label!` filters to the documentation for container commands (rm, ps, start, stop, pause, unpause, restart).
- Add `restart-policy` and `shoud-start-on-boot` to completions.
- Update service: Update `podman-restart.service` to use the `needs-restart=true` filter.
- Preserve state: Preserve the `StoppedByUser` state across reboots.
- Update API: Add a `ShouldStartOnBoot()` method to the Container API.
- Update documentation: Add descriptions for the `should-start-on-boot` filter.

Fixes: https://issues.redhat.com/browse/RHEL-129405
Fixes: https://github.com/containers/podman/issues/20418

#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
The `unless-stopped` restart policy now correctly matches Docker behavior by preserving the user-stopped state across reboots, and includes a new `should-start-on-boot` filter.
```

### CODE REVIEW

**Comment by Luap99** [comment]
I haven't looked at the code but I find `needs-restart` a confusing name, internally we also already have a ShouldRestart() function so it isn't at all clear what this means.

Given this only targets the on boot start , maybe something more like `should-start-on-boot`/`ShouldStartOnBoot`?

**Comment by Honny1** [comment]
> Given this only targets the on boot start , maybe something more like `should-start-on-boot`/`ShouldStartOnBoot`?

That is a much better name. I have renamed it

**Comment by Honny1** [comment]
PTAL @mheon @Luap99

File: libpod/container_api.go [hunk 1]
```diff
@@ -1093,6 +1093,30 @@ func (c *Container) ShouldRestart(_ context.Context) bool {
 	return c.shouldRestart()
 }
 
+// Indicate whether or not the container will should start after a reboot of system
+func (c *Container) ShouldStartOnBoot() bool {
+	logrus.Debugf("Checking if container %s needs restart", c.ID())
```
Comment (mheon) [inline libpod/container_api.go]: Probably should drop this, since it's part of a filter, we'll spam the debug logs

File: libpod/container_api.go [hunk 2]
```diff
@@ -1093,6 +1093,30 @@ func (c *Container) ShouldRestart(_ context.Context) bool {
...
+		c.lock.Lock()
+		defer c.lock.Unlock()
+
+		if err := c.syncContainer(); err != nil {
+			return false
+		}
+	}
+
+	notExecuted := c.state.State == define.ContainerStateConfigured || c.state.State == define.ContainerStateCreated
+	if notExecuted {
```
Comment (mheon) [inline libpod/container_api.go]: Can use `c.ensureState` for this.

**Comment by Honny1** [comment]
@mheon I made changes based on your comments.

**Comment by mheon** [comment]
LGTM

**Review by Luap99 — APPROVED** [review]
/lgtm

The duplication in the filter description is ugly as hell, we should create an issue and make the filter option de-duplicated like the rest unless I am overlooking something why it isn't right now.

**Comment by Honny1** [comment]
@Luap99 

I created an issue for the filter documentation deduplication: https://github.com/containers/podman/issues/27681

Also, it seems that combining text with `/_lgtm` doesn't work.

**Comment by Luap99** [comment]
/lgtm

Thanks

> Also, it seems that combining text with /_lgtm doesn't work.

It does work normally, I suppose this is just one of the typical bot issues where it is offline or misses messages for short time. One of the reason why we want to remove the bot. Let's see if this works now :)

**Comment by imdaveho** [comment]
I updated to podman 5.8.0 but when changing restart: always --> restart: unless-stopped and rebooting my machine, the containers still do not restart. I was running podman 5.7.1 and rebuilt the binary from scratch following the same instructions to build 5.7.1. Podman is running on Debian 13, normal x64 arch. I also reloaded systemd services as well (daemon-reload as well as restarted the socket and podman-restart.service). No dice. Is there something I might be missing?

**Comment by Honny1** [comment]
Did you update `podman-restart.service`? The flags for filtering containers changed.

**Comment by imdaveho** [comment]
> Did you update `podman-restart.service`? The flags for filtering containers changed.

I believe so, this is my service file:

```
[Unit]
Description=Podman Start All Containers With Restart Policy Set To Always
Documentation=man:podman-start(1)
StartLimitIntervalSec=0
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=true
Environment=LOGGING="--log-level=info"
ExecStart=/usr/bin/podman $LOGGING start --all --filter should-start-on-boot=true
ExecStop=/usr/bin/podman  $LOGGING stop  --all --filter should-start-on-boot=true

[Install]
WantedBy=default.target
```

is there another filter I should be aware of?

@Honny1

**Comment by Honny1** [comment]
I figured out the problem. Thanks for your interest! I just opened an issue for it: https://github.com/containers/podman/issues/28152

**Comment by imdaveho** [comment]
> I figured out the problem. Thanks for your interest! I just opened an issue for it: https://github.com/containers/podman/issues/28152 

Thanks, appreciate the effort in triaging the issue. I'm still a newish user of podman and unfamiliar with the history and changes in the PR, otherwise I would have investigated a bit deeper myself. Appreciate the work put into this and the quick reply.
