### PR TITLE
remote build: set rootless oci isolation correctly

### LINKED ISSUE #12989: Rawhide: rootless, remote: podman build: failed to create bridge "cni-podman0": could not add "cni-podman0": EPERM
Ton of [failures in rootless gating tests](http://artifacts.dev.testing-farm.io/fbc9fba1-ac25-4cc7-b29a-780a60309cc3/work-tests.ymlR9noiC/tests-pqgAGZ/test.podman-remote-rootless.bats.log), on latest [rc2](https://bodhi.fedoraproject.org/updates/FEDORA-2022-9ab14fbba2) build:
```
# $ podman-remote build -t nomtab /tmp/podman_bats.WiYj4J/build-test
# STEP 1/2: FROM quay.io/libpod/testimage:20210610
# STEP 2/2: RUN rm /etc/mtab
# error running container: did not get container start message from parent: EOF
# Error: error building at STEP "RUN rm /etc/mtab": plugin type="bridge" failed (add): cni plugin bridge failed: failed to create bridge "cni-podman0": could not add "cni-podman0": operation not permitted
# [ rc=125 (** EXPECTED 0 **) ]
```
No idea if this is real or a flake. If the latter, it's not one I've ever seen before. I will spin up a virt and try to reproduce today, but I'm still catching up from the weekend.

### PR DESCRIPTION
**Pull request by Luap99**
When we run rootless buildah needs to have IsolationOCIRootless set
otherwise it will run code which cannot be used as rootless user.
Podman should use the buildah default if possible and change it to
rootless mode if needed.

[NO NEW TESTS NEEDED] Should be covered by existing tests once we have
podman-remote rootless tests.

Fixes #12989

### CODE REVIEW

**Comment by Luap99** [comment]
@edsantiago  @nalind @rhatdan PTAL

File: pkg/api/handlers/compat/images_build.go [hunk 1]
```diff
@@ -300,7 +301,17 @@ func BuildImage(w http.ResponseWriter, r *http.Request) {
...
 	if utils.IsLibpodRequest(r) {
-		isolation = parseLibPodIsolation(query.Isolation)
+		var err error
+		isolation, err = parseLibPodIsolation(query.Isolation)
+		if err != nil {
+			utils.Error(w, http.StatusInternalServerError, errors.Wrap(err, "failed to parse isolation"))
+			return
+		}
+
+		// make sure to force rootless as rootless otherwise buildah runs code which is intended to be run only as root.
```
Comment (rhatdan) [inline pkg/api/handlers/compat/images_build.go:311]: I think this should come prior and check if query.Isolation is not set. Users should be allowed to set Isolation=crhoot.

File: cmd/podman/images/build.go [hunk 2]
```diff
@@ -183,12 +183,6 @@ func buildFlags(cmd *cobra.Command) {
 	completion.CompleteCommandFlags(cmd, fromAndBudFlagsCompletions)
 	flags.SetNormalizeFunc(buildahCLI.AliasFlags)
 	if registry.IsRemote() {
-		flag = flags.Lookup("isolation")
```
Comment (rhatdan) [inline cmd/podman/images/build.go:186]: Does this continue to work in non rootless mode?

Comment (Luap99) [reply cmd/podman/images/build.go:186]: yes the default is handled by buildah just like the other flags

File: pkg/api/handlers/compat/images_build.go (hunk 1 above)
Comment (Luap99) [reply pkg/api/handlers/compat/images_build.go:311]: This check will only change oci -> ocirootless when running rootless, if you set chroot it will not be changed

**Comment by rhatdan** [comment]
LGTM

**Comment by nalind** [comment]
LGTM

**Comment by edsantiago** [comment]
With this, the `AllTheOptions` test in `200-pod.bats` now fails under rootless podman-remote:
```
   $ podman-remote container inspect --format {{.Name}} bc4687b5d85d7af147009582050f771a8693846cdd3bc217f7170cc90797c91e
   infra_container_4ogjc2zphi
   $ podman-remote run --rm --pod mypod quay.io/libpod/testimage:20210610 hostname
   Error: error preparing container d39b1234c4fcb39a38d4303b042ad9e771de9980df9609fc1d89ad477ae47e2c for attach: error starting some containers: internal libpod error
   [ rc=126 (** EXPECTED 0 **) ]
```
This fails the same way using v4.0.0-rc1, so I'm guessing it's a bug that crept in between 3.4 and 4.0 (oh joy).

Aside from that, it seems to pass all the tests that failed with `cni blah blah` in the [rc2 gating tests](http://artifacts.dev.testing-farm.io/fbc9fba1-ac25-4cc7-b29a-780a60309cc3/work-tests.ymlR9noiC/tests-pqgAGZ/test.podman-remote-rootless.bats.log)

**Comment by edsantiago** [comment]
/lgtm

just so I can make progress with #12993 
Thanks @Luap99
