### PR TITLE
Fix: Use absolute path to WSL binary to create ssh keys for `machine init` on Windows (Issue #14416)

### LINKED ISSUE #14416: Podman 4.1 machine init fails when run in C:\Windows\System32
/kind bug

**Description**

Simple setup and machine initialization results in error and some warnings.

**Steps to reproduce the issue:**

1. Download podman 4.1.0 MSI for Window.

2. Execute "podman machine init" in command shell.

**Describe the results you received:**

> Error: could not create ssh keys: exec: "C:\\Users\\stani\\.ssh\\wsl.exe": file does not exist

Looks like error is fatal, because none of other podman command are working with message "Cannot connect to Podman...".

**Describe the results you expected:**

Running podman machine.

**Output of `podman version`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: failed to parse identity "C:\\Users\\stani\\.ssh\\podman-machine-default": open C:\Users\stani\.ssh\podman-machine-default: The system cannot find the file specified.
```

**Output of `podman info --debug`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: failed to parse identity "C:\\Users\\stani\\.ssh\\podman-machine-default": open C:\Users\stani\.ssh\podman-machine-default: The system cannot find the file specified.
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
PS C:\Windows\System32>  Get-CimInstance -ClassName Win32_Product -Filter "name like 'Podman%'"

Name             Caption                   Vendor                    Version                   IdentifyingNumber
----             -------                   ------                    -------                   -----------------
Podman 4.1.0     Podman 4.1.0              Red Hat Inc.              4.1.0                     {F0C12B5B-290B-4C15-A0D…
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

### PR DESCRIPTION
**Pull request by Clivar**
Fixes #14416 

#### Does this PR introduce a user-facing change?
Yes

```release-note
- Fix: #14416 : `machine init` fails when ran from C:\Windows\System32 on Windows
```

[NO NEW TESTS NEEDED]

### CODE REVIEW

**Comment by n1hility** [comment]
@Clivar first off good catch, and thank you for the PR. Review coming

File: pkg/machine/keys.go [hunk 1]
```diff
@@ -55,17 +55,16 @@ func generatekeys(writeLocation string) error {
 }
 
 // generatekeys creates an ed25519 set of keys
-func generatekeysPrefix(dir string, file string, passThru bool, prefix ...string) error {
+func generatekeysPrefix(location string, passThru bool, prefix ...string) error {
 	args := append([]string{}, prefix[1:]...)
 	args = append(args, sshCommand...)
-	args = append(args, file)
+	args = append(args, location)
```
Comment (n1hility) [inline pkg/machine/keys.go:61]: Unfortunately, this should fail in most cases since location is a windows path being passed into a linux command as an argument. This approach could technically work if it was converted to the 9p mount locations on linux, although it's probably easier to go a different route, where the wsl command is changed to an absolute path that we manually lookup ourselves.

**Review by n1hility — CHANGES_REQUESTED** [review]
Thanks again for figuring out the root cause and the PR! See my comment above where this will run into trouble and a suggested alternative approach. Do you want to take a stab at that?

File: pkg/machine/keys.go (hunk 1 above)
Comment (n1hility) [reply pkg/machine/keys.go:61]: Just to clarify what I mean is that dir will still work if before creating the command we do exec.LookPath, then convert the result to an absolute path, then pass that value as the command name.

Comment (Clivar) [reply pkg/machine/keys.go]: You are right. It expects the mount location on linux. 

I agree with your suggestion to use the absolute path and keep dir as it is. See the update PR.

**Review by n1hility — APPROVED** [review]

**Comment by n1hility** [comment]
@Clivar looks good, can you push an amended commit that is signed (git commit -s --amend), we need that pass DCO

**Comment by n1hility** [comment]
@Clivar also, can you change the commit message to reflect the fix approach? (just so people aren't confused by the history) thanks!

**Comment by Clivar** [comment]
@n1hility done!

**Comment by n1hility** [comment]
LGTM 

PTAL @containers/podman-maintainers

**Review by giuseppe — APPROVED** [review]
LGTM
