### PR TITLE
test/e2e: fix ncat tests

### LINKED ISSUE #23263: CI: network bind: timeout
New flake, started July 11, same day as my local-registry PR (not sure if related, but it seems suspicious). Mostly in `network bind to 127.0.0.1` test:
```
    # podman-remote [options] run --network slirp4netns:outbound_addr=127.0.0.1,allow_host_loopback=true -dt quay.io/libpod/alpine:latest nc -w 2 10.0.2.2 5546
           b3a860c2439c32a2ee2f4a363ae08e813f8223bac6148d8a6ad5396390ef999b
           Ncat: Version 7.95 ( https://nmap.org/ncat )
           Ncat: Listening on [::]:5546
           Ncat: Listening on 0.0.0.0:5546

           [FAILED] Timed out after 90.001s.
           command timed out after 90s: [nc -v -n -l -p 5546]
           STDOUT: 
           STDERR: Ncat: Version 7.95 ( https://nmap.org/ncat )
           Ncat: Listening on [::]:5546
           Ncat: Listening on 0.0.0.0:5546
         
           Expected process to exit.  It did not.
```
...but also in a kube test (weirdly, in `pod rm`):
```
  # podman-remote [options] pod rm -fa -t 0

           [FAILED] Timed out after 90.001s.
           command timed out after 90s: [/var/tmp/go/src/github.com/containers/podman/bin/podman-remote --remote --url unix:///run/podman/podman-6f170c3cdcc4e5cc9207eaf41298d418fd0cb7f904ae8be3f5ec412f2a5909b0.sock pod rm -fa -t 0]
           STDOUT: 
           STDERR: 
           Expected process to exit.  It did not.
```
Only common factor is `root`.

My go-to when I see socket hangs is "somehow I've mixed CNI and netavark". It's possible that my local-registry work is doing that because it uses system-installed podman. But, even on f40 and rawhide? And it seems weird, because that tends to hang EVERYTHING, not just intermittent. I will look into it on Monday.

* ~~debian-13 : int remote debian-13 root host sqlite [remote]~~
    * ~~[07-11 23:13](https://api.cirrus-ci.com/v1/artifact/task/5213561172000768/html/int-remote-debian-13-root-host-sqlite.log.html#t--Podman-kube-play-test-with-annotation-size-within-limits--1) in TOP-LEVEL [AfterEach] Podman kube play test with annotation size within limits~~
* fedora-39 : int remote fedora-39 root host boltdb [remote]
    * [07-12 10:23](https://api.cirrus-ci.com/v1/artifact/task/6248076254380032/html/int-remote-fedora-39-root-host-boltdb.log.html#t--Podman-kube-play-test-with-annotation-size-within-limits--1) in TOP-LEVEL [AfterEach] Podman kube play test with annotation size within limits
* fedora-40 : int podman fedora-40 root host sqlite
    * [07-11 23:14](https://api.cirrus-ci.com/v1/artifact/task/6198723590488064/html/int-podman-fedora-40-root-host-sqlite.log.html#t--Podman-run-networking-podman-run-network-bind-to-HostIP--1) in Podman run networking podman run network bind to HostIP
    * [07-11 23:14](https://api.cirrus-ci.com/v1/artifact/task/6198723590488064/html/int-podman-fedora-40-root-host-sqlite.log.html#t--Podman-run-networking-podman-run-network-bind-to-127-0-0-1--1) in Podman run networking podman run network bind to 127.0.0.1
* fedora-40 : int remote fedora-40 root host sqlite [remote]
    * [07-11 23:14](https://api.cirrus-ci.com/v1/artifact/task/6480198567198720/html/int-remote-fedora-40-root-host-sqlite.log.html#t--Podman-run-networking-podman-run-network-bind-to-127-0-0-1--1) in Podman run networking podman run network bind to 127.0.0.1
* rawhide : int podman rawhide root host sqlite
    * [07-11 23:15](https://api.cirrus-ci.com/v1/artifact/task/5917248613777408/html/int-podman-rawhide-root-host-sqlite.log.html#t--Podman-run-networking-podman-run-network-bind-to-127-0-0-1--1) in Podman run networking podman run network bind to 127.0.0.1
* rawhide : int remote rawhide root host sqlite [remote]
    * [07-12 10:23](https://api.cirrus-ci.com/v1/artifact/task/4840701370826752/html/int-remote-rawhide-root-host-sqlite.log.html#t--Podman-run-networking-podman-run-network-bind-to-127-0-0-1--1) in Podman run networking podman run network bind to 127.0.0.1
    * [07-11 23:15](https://api.cirrus-ci.com/v1/artifact/task/5776511125422080/html/int-remote-rawhide-root-host-sqlite.log.html#t--Podman-run-networking-podman-run-network-bind-to-127-0-0-1--1) in Podman run networking podman run network bind to 127.0.0.1

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| int(8) | remote(5) | rawhide(3) | root(8) | host(8) | sqlite(7) |
|  | podman(3) | fedora-40(3) |  |  | boltdb(1) |
|  |  | fedora-39(1) |  |  |  |

### PR DESCRIPTION
**Pull request by Luap99**
These tests are flaking for unknown reasons. One problem could be ncat did not bound the port before we connect to it. Simple fix do not use ncat and just use the golang API to listen on the port without the extra ncat process. This should be race free in theory. Also do not run the nc container in the background, we want to see the errors from the ncat process in the container.

And because both tests do the same thing deduplicate them into one that just uses a loop to create both tests.

Fixes #23263

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by Luap99** [comment]
@edsantiago PTAL, I am not 100% sure it fixes the flake but it improves things

File: test/e2e/run_networking_test.go [hunk 1]
```diff
@@ -543,56 +545,58 @@ EXPOSE 2004-2005/tcp`, ALPINE)
...
+			testName = "127.0.0.1"
 		}
-	})
-
-	It("podman run network bind to HostIP", func() {
-		// Determine our likeliest outgoing IP address
-		conn, err := net.Dial("udp", "8.8.8.8:80")
-		Expect(err).ToNot(HaveOccurred())
+		It(fmt.Sprintf("podman run network slirp4netns bind to %s", testName), func() {
+			ip := "127.0.0.1"
```
Comment (rhatdan) [inline test/e2e/run_networking_test.go:555]: Would be cleaner if this was all done under the 
if local {
} else {
}
block above.

Comment (Luap99) [reply test/e2e/run_networking_test.go:555]: No the `net.Dial("udp", "8.8.8.8:80")` should be part of the test, if you move that outside it would be executed before any test is run and then only many minutes later used. In this time the host ip might have been changed (i.e. DHCP) breaking the test. Technically the risk still exists when doing it inside but the race is super narrow here.

File: test/e2e/run_networking_test.go [hunk 2]
```diff
@@ -543,56 +545,58 @@ EXPOSE 2004-2005/tcp`, ALPINE)
...
+			// now use a new goroutine to start accepting connection in the background and make the checks there
+			go func() {
+				defer GinkgoRecover()
+				defer wg.Done()
+				conn, err := listener.Accept()
+				Expect(err).ToNot(HaveOccurred())
+				defer conn.Close()
+				addr := conn.RemoteAddr()
+				// addr will be in the form ip:port, we don't care about the port as it is random
+				Expect(addr.String()).To(ContainSubstring(ip+":"), "remote address")
```
Comment (edsantiago) [inline test/e2e/run_networking_test.go:584]: Not worth a repush, but why not `To(HavePrefix())`

File: test/e2e/run_networking_test.go [hunk 3]
```diff
@@ -543,56 +545,58 @@ EXPOSE 2004-2005/tcp`, ALPINE)
...
+				gotBytes, err := io.ReadAll(conn)
+				Expect(err).ToNot(HaveOccurred())
+				Expect(string(gotBytes)).To(Equal(msg))
+			}()
+
+			session := podmanTest.Podman([]string{"run", "--network", networkConfiguration, ALPINE, "sh", "-c", "echo -n " + msg + " | nc -w 2 10.0.2.2 " + port})
```
Comment (edsantiago) [inline test/e2e/run_networking_test.go:590]: Now that I look at this closer... could it be that `-w 2` is too low a timeout for slow CI hosts? Is there a reason for such a low value?

File: test/e2e/run_networking_test.go [hunk 4]
```diff
@@ -543,56 +545,58 @@ EXPOSE 2004-2005/tcp`, ALPINE)
 		}
 	})
 
-	It("podman run network bind to 127.0.0.1", func() {
-		slirp4netnsHelp := SystemExec("slirp4netns", []string{"--help"})
-		Expect(slirp4netnsHelp).Should(ExitCleanly())
-		networkConfiguration := "slirp4netns:outbound_addr=127.0.0.1,allow_host_loopback=true"
-		port := strconv.Itoa(GetPort())
-
-		if strings.Contains(slirp4netnsHelp.OutputToString(), "outbound-addr") {
```
Comment (edsantiago) [inline test/e2e/run_networking_test.go:552]: This part of the test is gone. Fine with me, but on my f40 laptop `slirp4netns --help` shows the two `--outbound-addr` options as `(experimental)`. To me that means "may be removed without notice", and if so the test will now detect that instead of silently passing. Good. Would it be worth a quick slirp4netns PR or issue removing the "experimental"?

File: test/e2e/run_networking_test.go [hunk 5]
```diff
@@ -543,56 +545,58 @@ EXPOSE 2004-2005/tcp`, ALPINE)
...
+				defer wg.Done()
+				conn, err := listener.Accept()
+				Expect(err).ToNot(HaveOccurred())
+				defer conn.Close()
+				addr := conn.RemoteAddr()
+				// addr will be in the form ip:port, we don't care about the port as it is random
+				Expect(addr.String()).To(ContainSubstring(ip+":"), "remote address")
+				gotBytes, err := io.ReadAll(conn)
+				Expect(err).ToNot(HaveOccurred())
+				Expect(string(gotBytes)).To(Equal(msg))
```
Comment (edsantiago) [inline test/e2e/run_networking_test.go:587]: Not worth a repush, but, this would not be a very intuitive error message on failure...

**Review by edsantiago — APPROVED** [review]
Really nice work. A few nonblocking questions & suggestions inline. 

I've cherrypicked onto #17831

File: test/e2e/run_networking_test.go (hunk 2 above)
Comment (Luap99) [reply test/e2e/run_networking_test.go:584]: Because I didn't thought of it when I wrote this

File: test/e2e/run_networking_test.go (hunk 3 above)
Comment (Luap99) [reply test/e2e/run_networking_test.go:590]: Maybe? I am not sure how nc calculates this time-out, in theory with the current version I would expect the connect to work first try as we bind before starting the container

It seems to be documented as `Set a fixed timeout for connection attempts` but if it also applies to actually sending the data then maybe. I guess there is no harm bumping this up to 30s or something like this.

File: test/e2e/run_networking_test.go (hunk 4 above)
Comment (Luap99) [reply test/e2e/run_networking_test.go:552]: I think this is more of a may not work warning. I can create a issue there and ask if the experimental warning can be removed there.

Comment (Luap99) [reply test/e2e/run_networking_test.go:552]: I see open issues for outbound-addr there so I guess there is a reason to keep it marked experimental

**Comment by Luap99** [comment]
repushed with more error messages on the checks and add -w 30 just in case

**Comment by edsantiago** [comment]
LGTM
