### PR TITLE
inspect: preserve secret target name in env masking

### LINKED ISSUE #28075: --secret type=env,target= mapping lost after --restart=on-failure triggers
### Issue Description

When a container is created with `--secret name,type=env,target=MY_TARGET` and `--restart=on-failure`, the `target=` mapping is lost after Podman restarts the container due to a failure. The environment variable key reverts to the literal secret name instead of the specified target.

On initial creation, `podman inspect` correctly shows `MY_TARGET=***`. After a crash-triggered restart, it shows `test-secret=***` instead.

This silently breaks any application that relies on specific environment variable names (e.g., `POSTGRES_PASSWORD`, `JWT_SECRET`), causing authentication failures after otherwise-recoverable crashes.

### Steps to reproduce the issue

```bash
# Create a test secret
echo -n "secretvalue" | podman secret create test-secret -

# Run a container that will crash and be restarted by Podman
podman run -d \
  --name restart-target-test \
  --restart=on-failure:5 \
  --secret test-secret,type=env,target=MY_TARGET \
  docker.io/alpine:latest \
  sh -c 'sleep 2 && exit 1'

# Wait for at least one restart cycle
sleep 15

# Check the environment variable mapping
podman inspect restart-target-test \
  --format '{{range .Config.Env}}{{println .}}{{end}}' | grep -iE 'target|secret'

# Clean up
podman rm -f restart-target-test
podman secret rm test-secret
```

### Describe the results you received

After a crash-triggered restart, `podman inspect` shows:

```
test-secret=***
```

The `target=` mapping is lost and the literal secret name becomes the environment variable key.

### Describe the results you expected

After restart, `podman inspect` should show:

```
MY_TARGET=***
```

The `target=` mapping should be preserved across restarts, matching the behavior of the initial container creation.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.42.2
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.13-1.fc42.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: '
  cpus: 8
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: kde
    version: "42"
  eventLogger: journald
  hostname: fedora
  kernel: 6.18.5-100.fc42.x86_64
  linkmode: dynamic
  logDriver: journald
  memTotal: 33468936192
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.17.0-1.fc42.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.17.0
    package: netavark-1.17.1-1.fc42.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.17.1
  ociRuntime:
    name: crun
    package: crun-1.26-1.fc42.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.26
      commit: 3241e671f92c33b0c003cd7de319e4f32add6231
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  serviceIsRemote: false
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 24
    running: 24
  graphDriverName: overlay
  graphRoot: /home/user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  imageStore:
    number: 34
  transientStore: false
version:
  APIVersion: 5.7.1
  Built: 1765324800
  BuiltTime: Wed Dec 10 01:00:00 2025
  GitCommit: f845d14e941889ba4c071f35233d09b29d363c75
  GoVersion: go1.24.10
  OsArch: linux/amd64
  Version: 5.7.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes (5.7.1 is the latest available in Fedora 42 and 43)

### Additional environment details

Physical machine.

### Additional information

- A fresh `podman run` with the same `--secret` flags (without `--restart`) correctly applies `target=` every time. The issue only manifests when Podman itself restarts the container after a failure.
- The issue also reproduces inside pods (tested with `podman pod create` + `podman run --pod`).
- Real-world impact: services with multiple secrets mapped to specific env vars (e.g., `POSTGRES_PASSWORD`, `JWT_SECRET`, `DB_PASSWORD`) fail silently after a transient crash because the application can no longer find the expected variable names. The container appears "running" but the app inside is broken.
- Workaround: replace `--secret name,type=env,target=VAR` with `-e VAR=value` at the cost of losing secret masking in `podman inspect`.

### PR DESCRIPTION
**Pull request by amyssnippet**
Fixes #28075

#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #28075 ` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [ ] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [ ] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

When a container uses a secret with a custom target (e.g., --secret name=foo,target=BAR), podman inspect incorrectly masks the environment variable using the secret name (foo=*****) instead of the target name (BAR=*****). Fix: This patch updates generateInspectContainerConfig to use the environment variable key (envName) when constructing the masked string, ensuring the output matches the container's actual environment. Verification: Verified locally on Ubuntu 24.04. podman run ... --secret test,target=MY_VAR now correctly displays MY_VAR=***** in podman inspect.

### CODE REVIEW

**Comment by amyssnippet** [comment]
@jankaluza The CI is failing on tests-included because I haven't added a regression test.

Since this is a trivial display-only fix (+2/-2 lines) that only affects podman inspect output and not the runtime behavior, could you please apply the No New Tests label? Or should I add a specific E2E test case for this?

**Comment by inknos** [comment]
thanks for the PR, @amyssnippet . Please, try to address the validate comments first. you can run the check locally with `make validatepr`

**Comment by amyssnippet** [comment]
@inknos can u add No New Tests label? as i think no tests are needed here

edit: its a  display-only fix

**Comment by amyssnippet** [comment]
> thanks for the PR, @amyssnippet . Please, try to address the validate comments first. you can run the check locally with `make validatepr`

this ran successfully if i remove the noise from documentation generator trying to format text layout and are flaky for my changes

**Review by danishprakash — COMMENTED** [review]
Could you extend one of the other secret env tests that cover this use-case too?

**Comment by baude** [comment]
LGTM, but would like a test to prevent regression on this .

**Comment by inknos** [comment]
> can u add No New Tests label? as i think no tests are needed here

@amyssnippet  I also feel a regression test is needed. do you need any pointers to that?

**Comment by amyssnippet** [comment]
@inknos and @baude , i need to address some more updates as ongoing discussion with the author of the issue, will solve it soon and add the tests too

**Review by mheon — APPROVED** [review]
LGTM on my end once a test is added

**Comment by amyssnippet** [comment]
@mheon @inknos @baude @danishprakash now the issue is successfully solved

edit: i added test too

**Comment by TomSweeneyRedHat** [comment]
@amyssnippet thanks for the PR!

Changes LGTM, a couple of falining tests that I restarted, I'm not sure if they are flakes or not.

**Comment by amyssnippet** [comment]
@TomSweeneyRedHat , thanks for your review, and also right now there is only one failing ci test, and i got deep and saw the logs, it is failing during the preparation phase of the script. so guide me what should i do further??

```
No matching repositories for testing-farm-tag-repository. 
Add "--help" for more information about the arguments.
```

the script `dnf-repo-setup.sh` tried to run `dnf upgrade` with `--disable-repo=testing-farm-tag-repository` but i think the repo doesnt exists on the guest ci server. and as the script uses `set -eo pipefail`, the moment dnf complained about the missing repository, the whole script crashed with exit code 2.

<details>
<summary>entire log I found</summary>

# STDOUT:
---v---v---v---v---v---

---^---^---^---^---^---

# STDERR:
---v---v---v---v---v---
/var/ARTIFACTS/work-podman-system35a9eafo
Found 1 plan.

/plans/cockpit-podman/podman-system
summary: Run cockpit-podman system tests
    discover
        url: https://github.com/cockpit-project/cockpit-podman
        cloned-commit-hash: da80709
        ref: main
        commit-hash: da80709
        how: fmf
        tests: /test/browser/system
        summary: 1 test selected
            /test/browser/system
    provision
        queued provision.provision task #1: default-0
        
        provision.provision task #1: default-0
        how: connect
        primary address: 3.150.119.133
        topology address: 3.150.119.133
        ansible: GuestAnsible(group=None, vars={})
        port: 22
        key: /etc/citool.d/id_rsa_artemis
        hard reboot: /opt/artemis-cli/bin/artemis-cli guest reboot 054b210e-234b-4ae3-9327-006a2d3e0621
        primary address: 3.150.119.133
        topology address: 3.150.119.133
        multihost name: default-0
        arch: x86_64
        distro: Fedora Linux 45 (Cloud Edition Prerelease)
        kernel: 6.20.0-0.rc0.260212gc22e26bd0906e.3.fc45.x86_64
        package manager: dnf5
        bootc builder: dnf5
        is container: no
        is ostree: no
        is toolbox: no
        selinux: yes
        systemd: yes
        systemd soft-reboot: yes
        rsync: yes
        is superuser: yes
        can sudo: yes
        queued push task #1: push to default-0
        
        push task #1: push to default-0
    
        summary: 1 guest provisioned
    prepare
        queued push task #1: push to default-0
        
        push task #1: push to default-0
    
        queued prepare task #1: default-0 on default-0
        queued prepare task #2: essential-requires on default-0
        queued prepare task #3: requires on default-0
        
        prepare task #1: default-0 on default-0
        how: shell
        overview: 1 script found
        script: bash /var/ARTIFACTS/work-podman-system35a9eafo/plans/cockpit-podman/podman-system/tree/contrib/packit-tmt/dnf-repo-setup.sh
        fail: Command 'set -eo pipefail; bash /var/ARTIFACTS/work-podman-system35a9eafo/plans/cockpit-podman/podman-system/tree/contrib/packit-tmt/dnf-repo-setup.sh' returned 2.
        
        prepare task #2: essential-requires on default-0
        how: install
        summary: Install essential required packages
        name: essential-requires
        where: default-0
        package: 1 package requested
            /usr/bin/flock
        
        prepare task #3: requires on default-0
        how: install
        summary: Install required packages
        name: requires
        where: default-0
        package: 6 packages requested
            cockpit-podman
            cockpit-system
            cockpit-ws
            criu
            nginx
            systemd-container
    report
        how: display
        prepare
            00:00:00 fail default-0 / script #0
                Note: Exception #1: Command 'set -eo pipefail; bash /var/ARTIFACTS/work-podman-system35a9eafo/plans/cockpit-podman/podman-system/tree/contrib/packit-tmt/dnf-repo-setup.sh' returned 2.
        execute
            ..:..:.. pending /test/browser/system
        summary: 1 pending
    cleanup
        queued cleanup task #1: default-0 on default-0
        
        cleanup task #1: default-0 on default-0
        how: tmt
        summary: 1 task completed

plan failed.

The exception was caused by 1 earlier exceptions

Cause number 1:

    prepare step failed

    The exception was caused by 1 earlier exceptions

    Cause number 1:

        Command 'set -eo pipefail; bash /var/ARTIFACTS/work-podman-system35a9eafo/plans/cockpit-podman/podman-system/tree/contrib/packit-tmt/dnf-repo-setup.sh' returned 2.

        # stderr (2 lines)
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + dnf -y upgrade --allowerasing --disable-repo=testing-farm-tag-repository '--exclude=podman*'
        No matching repositories for testing-farm-tag-repository. Add "--help" for more information about the arguments.
        # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

</details>

**Comment by jankaluza** [comment]
I think that failed test is issue on testing-farm side. It's not caused by the code change introduced in this PR.

File: libpod/container_internal.go [hunk 1]
```diff
@@ -1606,6 +1606,14 @@ func (c *Container) restartWithTimeout(ctx context.Context, timeout uint) (retEr
 	if !c.ensureState(define.ContainerStateConfigured, define.ContainerStateCreated, define.ContainerStateRunning, define.ContainerStateStopped, define.ContainerStateExited) {
 		return fmt.Errorf("unable to restart a container in a paused or unknown state: %w", define.ErrCtrStateInvalid)
 	}
+	if len(c.config.EnvSecrets) > 0 {
+		logrus.Infof("DEBUG: restartWithTimeout: EnvSecrets for %s:", c.ID())
```
Comment (jankaluza) [inline libpod/container_internal.go]: I'm not sure if we want to use Infof here with DEBUG. Either remove the DEBUG or log using Debugf function.

File: libpod/container_internal_common.go [hunk 2]
```diff
@@ -3174,6 +3164,24 @@ func maybeClampOOMScoreAdj(oomScoreValue int) (int, error) {
...
 }
 
+func (c *Container) injectEnvSecrets(g *generate.Generator) error {
+	if len(c.config.EnvSecrets) > 0 {
+		manager, err := c.runtime.SecretsManager()
+		if err != nil {
+			return err
+		}
+		for name, secr := range c.config.EnvSecrets {
+			logrus.Debugf("DEBUG: generateSpec: Injecting secret %s as env %s", secr.Name, name)
```
Comment (jankaluza) [inline libpod/container_internal_common.go]: I also think DEBUG is not needed here, since you already log using Debugf.

**Comment by jankaluza** [comment]
LGTM. Just the `Infof` logging with `DEBUG:` prefix seems weird to me.

**Comment by amyssnippet** [comment]
@jankaluza now??

**Comment by jankaluza** [comment]
LGTM

**Comment by mheon** [comment]
Testing farm tests are advisory only, failure is allowed.

**Comment by mheon** [comment]
LGTM
