### PR TITLE
Fix machine list: --format implies --noheading

### LINKED ISSUE #14682: [low] podman machine list: --format should imply --noheading
While playing with command completion I noticed:
```console
$ bin/podman machine list --format '{{.Name}}'    <--- or .CPUs or .Starting or ...
NAME
```
All other podman commands (that I know of) suppress headings when invoked with `--format`.

I don't have access to a Mac, so I can't actually test `podman machine anything`. Maybe this works fine on macs, or is desirable there. If so feel free to close.

### PR DESCRIPTION
**Pull request by boaz0**
A small bug fix - closes #14682.

It seems like previously if `--format` was changed then `listFlag.noHeading` is changed accordingly however `printHeader` is used to determine whether to print header or not.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by Luap99 — APPROVED** [review]
LGTM

File: pkg/machine/e2e/list_test.go [hunk 1]
```diff
@@ -135,6 +135,13 @@ var _ = Describe("podman machine list", func() {
 		var listResponse []*machine.ListReporter
 		err = jsoniter.Unmarshal(listSession.Bytes(), &listResponse)
 		Expect(err).To(BeNil())
+
+		// table format includes the header
+		list := new(listMachine)
+		listSession, err := mb.setCmd(list.withFormat("table {{.Name}}")).run()
+		Expect(err).NotTo(HaveOccurred())
+		Expect(listSession).To(Exit(0))
+		Expect(len(listSession.outputToStringSlice())).To(Equal(2))
```
Comment (edsantiago) [inline pkg/machine/e2e/list_test.go:144]: Using `len()` is deprecated: it leads to worthless error messages like "expected 1 to equal 2". Could I ask you to change this (and like 122) to:
```go
    Expect(listSession.outputToStringSlice()).To(HaveLen(2))
```
This will show an actually useful error like 'expected "this is the string" to have length 2'. And could you add a test for `To(ContainSubstring("NAME"))` here also?

This is in no way your fault - you just copied someone else's broken code. I'm commenting because I hope you'll take the opportunity (and, sigh, the CI cycles) to tidy things up.

**Comment by baude** [comment]
@boaz0 fix it up and we can get it merged

**Comment by boaz0** [comment]
@edsantiago @baude DONE.
I did it in a separate commit - but I don't mind squashing it into the first one if you like.

Thanks.

**Comment by edsantiago** [comment]
You went above and beyond! :)

LGTM.  I usually prefer squashing, but in this case (clearly differentiated and unrelated reasons) I think two commits are fine.

File: pkg/machine/e2e/list_test.go [hunk 2]
```diff
@@ -135,6 +135,15 @@ var _ = Describe("podman machine list", func() {
 		var listResponse []*machine.ListReporter
 		err = jsoniter.Unmarshal(listSession.Bytes(), &listResponse)
 		Expect(err).To(BeNil())
+
+		// table format includes the header
+		list3 := new(listMachine)
+		listSession3, err3 := mb.setCmd(list.withFormat("table {{.Name}}")).run()
```
Comment (edsantiago) [inline pkg/machine/e2e/list_test.go:141]: OK, I'd love to give this a full thorough review and understand `listMachine` and all that, but, sorry, I'm not. (Please don't take it personally). My first thought on reading this is, did you really mean `setCmd(list`, or should that be `list3`? And that's why I hate hate hate defining new variables for everything. Too easy to mix & match.

So, should that be `list3`?

Comment (boaz0) [reply pkg/machine/e2e/list_test.go:141]: I see what you mean. I can use `list` instead of `list3`. I just saw `list2 := new(listMachine)` above and I thought why not.

**Review by ashley-cui — COMMENTED** [review]
Please squash your commits. Other than that, LGTM! Thanks @boaz0!

**Review by vrothberg — COMMENTED** [review]
/lgtm
