### PR TITLE
Fix relabeling failures with Z/z volumes on Mac

### LINKED ISSUE #19852: podman compose it not working on some projects on macOS
### Issue Description

I tried to run https://github.com/change-metrics/monocle#installation using `podman compose`

but I'm not able to make it work

issue is around volumes

There is a `:z` flag preventing the startup but even removing the :z flag we have then the error

```
monocle-elastic-1  | ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];
monocle-elastic-1  | Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
monocle-elastic-1  | 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
monocle-elastic-1  | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
monocle-elastic-1  | 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
monocle-elastic-1  | 	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
monocle-elastic-1  | 	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
monocle-elastic-1  | 	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:807)
monocle-elastic-1  | 	at java.base/java.nio.file.Files.createDirectories(Files.java:793)
monocle-elastic-1  | 	at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:300)
monocle-elastic-1  | 	at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:224)
monocle-elastic-1  | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:298)
monocle-elastic-1  | 	at org.elasticsearch.node.Node.<init>(Node.java:429)
monocle-elastic-1  | 	at org.elasticsearch.node.Node.<init>(Node.java:309)
monocle-elastic-1  | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234)
monocle-elastic-1  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234)
monocle-elastic-1  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434)
monocle-elastic-1  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:169)
monocle-elastic-1  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:160)
monocle-elastic-1  | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
monocle-elastic-1  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
monocle-elastic-1  | 	at org.elasticsearch.cli.Command.main(Command.java:77)
monocle-elastic-1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:125)
monocle-elastic-1  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)
monocle-elastic-1  | For complete error details, refer to the log at /usr/share/elasticsearch/logs/docker-cluster.log
```

in the elastic search container

### Steps to reproduce the issue

Steps to reproduce the issue
1. git clone https://github.com/change-metrics/monocle
2. cd monocole
3. echo CRAWLERS_API_KEY=$(uuidgen) > .secrets
4. podman compose up

### Describe the results you received

failure

```
~/git/containers/podman/bin/darwin/podman  compose up
>>>> Executing external compose provider "/opt/homebrew/bin/docker-compose". Please refer to the documentation for details. <<<<

[+] Running 3/0
 ✔ Container monocle-elastic-1  Recreated                                                                                                                                               0.0s
 ✔ Container monocle-api-1      Recreated                                                                                                                                               0.0s
 ✔ Container monocle-crawler-1  Recreated                                                                                                                                               0.0s
Attaching to monocle-api-1, monocle-crawler-1, monocle-elastic-1
Error response from daemon: lsetxattr /Users/benoitf/git/change-metrics/monocle/data: operation not supported
Error: executing /opt/homebrew/bin/docker-compose up: exit status 1
```

volumes are using :z suffix and it doesn't work

```
     volumes:
      - "./etc:/etc/monocle:z"
```

### Describe the results you expected

should work

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by n1hility**
Fixes #19852

Non-Linux systems, such as BSD derived kernels, constrain selinux xatter updates according to file permissions. This is in contrast to Linux selinux attr writes, which are governed by an selinux policy. By dafault this policy apllows users to relabel files owned by themselves even if file perms would otherwise disallow write.

This results in robust container relabeling results on Linux, and fragile results everywhere else. Therefore, change the mac policy to force the nfs_t context on all files, and ignore all relabel events.

As a side-effect, this will disallow any ability to store custom selinux contexts on files. However, this is of limited use in a machine context with host volumes, since files in these volumes are externally managed on systems which do not support SELinux.

```release-note
Fixes EACCESS failures on Mac volumes when using Z/z options on a directory with read only files (#19852)
```

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
Although tests are not happy.

File: pkg/machine/e2e/basic_test.go [hunk 1]
```diff
@@ -69,6 +70,37 @@ var _ = Describe("run basic podman commands", func() {
 		Expect(rmCon).To(Exit(0))
 	})
 
+	It("Volume ops", func() {
+		skipIfVmtype(define.HyperVVirt, "Hyper-V does not have functioning volume mounts yet #21036")
+
+		// golangci-lint has trouble with actually skipping tests marked Skip
+		// so skip it on cirrus envs and where CIRRUS_CI isn't set.
```
Comment (Luap99) [inline pkg/machine/e2e/basic_test.go:77]: this comment makes no sense??

File: pkg/machine/e2e/basic_test.go [hunk 2]
```diff
@@ -69,6 +70,37 @@ var _ = Describe("run basic podman commands", func() {
...
+		i := new(initMachine)
+		session, err := mb.setName(name).setCmd(i.withImage(mb.imagePath).withNow()).run()
+		Expect(err).ToNot(HaveOccurred())
+		Expect(session).To(Exit(0))
+
+		// Create under home under the VMs system mount
+		hDir, err := os.UserHomeDir()
+		Expect(err).ToNot(HaveOccurred())
+		tDir, err := os.MkdirTemp(hDir, "attr-test")
+		Expect(err).ToNot(HaveOccurred())
```
Comment (Luap99) [inline pkg/machine/e2e/basic_test.go:88]: Does this create the dir under my real homedir or the fake test homedir?
I think it would be safer to just create a tmpdir and mount that on machine init explicitly so that the container can use it.

File: pkg/machine/e2e/basic_test.go [hunk 3]
```diff
@@ -69,6 +70,37 @@ var _ = Describe("run basic podman commands", func() {
 		Expect(rmCon).To(Exit(0))
 	})
 
+	It("Volume ops", func() {
+		skipIfVmtype(define.HyperVVirt, "Hyper-V does not have functioning volume mounts yet #21036")
```
Comment (Luap99) [inline pkg/machine/e2e/basic_test.go:74]: I think this should use use the `FIXME #21036: ...` syntax so @edsantiago's scripts will catch this when he issue gets closed. But maybe he confirm on the proper syntax.

Also the message is rather confusing, the mounts work just fine. It is just that the path resolution works differently.

File: pkg/machine/e2e/basic_test.go (hunk 1 above)
Comment (n1hility) [reply pkg/machine/e2e/basic_test.go:77]: sorry that was a cut and paste artifact from the test above in the file. I don't understand the comment either, nuking it from this PR

File: pkg/machine/e2e/basic_test.go (hunk 2 above)
Comment (n1hility) [reply pkg/machine/e2e/basic_test.go]: It would end up being fakeish home since CI overrides HOME, but doing it in a test  temp should work fine for the purpose of the test so posted a change up for that

**Review by Luap99 — COMMENTED** [review]
LGTM
@ashley-cui @baude PTAL
