### PR TITLE
fix: add validation for --publish flag in container restore

### LINKED ISSUE #28031: [docs] Clarify `--publish`s behavior when using with `podman container restore`
### Issue Description

`podman container restore --publish` only works with `--import`. Even though this was seemingly intended[1], we should document this behaviour.

### Steps to reproduce the issue

```
# podman run -d --name test-ctr alpine sleep 3600
# podman container checkpoint test-ctr
# podman container restore --publish 8000:8000 test-ctr
# podman inspect test-ctr --format '{{.HostConfig.PortBindings}}'
# map[]

# podman rm -f test-ctr

```

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.41.5
  cgroupControllers:
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.13-1.2.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: unknown'
  cpuUtilization:
    idlePercent: 94.08
    systemPercent: 0.96
    userPercent: 4.96
  cpus: 16
  databaseBackend: sqlite
  distribution:
    distribution: opensuse-slowroll
    version: "20250901"
  eventLogger: journald
  freeLocks: 2048
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.16.8-1-default
  linkmode: dynamic
  logDriver: journald
  memFree: 3868430336
  memTotal: 50217230336
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.16.0-1.1.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.16.0
    package: Unknown
    path: /usr/local/libexec/podman/netavark
    version: netavark 1.17.0-dev
  ociRuntime:
    name: runc
    package: runc-1.3.1-1.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.3.1
      commit: v1.3.1-0-ge6457afc48ef
      spec: 1.2.1
      go: go1.24.6
      libseccomp: 2.6.0
  os: linux
  pasta:
    executable: /bin/pasta
    package: passt-20250611.0293c6f-0.x86_64
    version: |
      pasta 20250611.0293c6f-0
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: slirp4netns
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.3.3-1.1.x86_64
    version: |-
      slirp4netns version 1.3.3
      commit: unknown
      libslirp: 4.9.1
      SLIRP_CONFIG_VERSION_MAX: 6
      libseccomp: 2.6.0
  swapFree: 2147811328
  swapTotal: 2147811328
  uptime: 8h 51m 8.00s (Approximately 0.33 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: localhost:5000
    PullFromMirror: ""
  search:
  - registry.suse.com
  - registry.opensuse.org
  - docker.io
store:
  configFile: /home/danishprakash/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/danishprakash/.local/share/containers/storage
  graphRootAllocated: 1021788028928
  graphRootUsed: 729065328640
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/danishprakash/.local/share/containers/storage/volumes
version:
  APIVersion: 5.6.2
  Built: 1761813496
  BuiltTime: Thu Oct 30 14:08:16 2025
  GitCommit: ""
  GoVersion: go1.25.3
  Os: linux
  OsArch: linux/amd64
  Version: 5.6.2
```

### PR DESCRIPTION
**Pull request by MayorFaj**
Add validation for --publish flag in container restore
#### Checklist

Fixes: #28031

The `--publish` flag for `podman container restore` only works when used with `--import` or a checkpoint image, but was silently ignored when used with regular in-place container restores. 

This PR adds:
1. **Validation check** in the CLI to return a clear error when `--publish` is used without `--import`
2. **Documentation update** to the man page to clarify the restriction (matching the pattern used by other import-dependent flags like `--name` and `--pod`)
3. **Integration test** to verify the error is returned correctly

The behavior now matches other import-dependent options (`--name`, `--pod`, `--ignore-rootfs`, etc.) which all return helpful error messages when misused.

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
podman container restore --publish now returns an error when used without --import or a checkpoint image, instead of silently ignoring the flag
```

### CODE REVIEW

**Review by Honny1 — APPROVED** [review]
LGTM, Thanks!

File: test/e2e/checkpoint_test.go [hunk 1]
```diff
@@ -75,6 +75,31 @@ var _ = Describe("Podman checkpoint", func() {
...
+		session := podmanTest.Podman(localRunString)
+		session.WaitWithDefaultTimeout()
+		Expect(session).Should(ExitCleanly())
+		cid := session.OutputToString()
+
+		result := podmanTest.Podman([]string{"container", "checkpoint", cid})
+		result.WaitWithDefaultTimeout()
+		Expect(result).Should(ExitCleanly())
+
+		result = podmanTest.Podman([]string{"container", "restore", "-p", "8080:8080", cid})
```
Comment (baude) [inline test/e2e/checkpoint_test.go]: i like the nice clean test; but I'm wondering if it would be more efficient to do this as part of another restore test?

Comment (MayorFaj) [reply test/e2e/checkpoint_test.go]: yea Good point.I have moved the check into the existing "podman checkpoint a running container by id" test, its right after the checkpoint succeeds

**Comment by jankaluza** [comment]
LGTM.
