### PR TITLE
RHEL-14922: accept a config blob alongside the "changes" slice when committing

### LINKED ISSUE #13770: Docker APIv2 `/commit` ignores uploaded config
As consequence the `s2i` utility is not working with `podman` when used as a `docker` daemon,
because resulting image has incorrect `Cmd`.

Related to https://github.com/openshift/source-to-image/issues/1082

### PR DESCRIPTION
**Pull request by nalind**
#### Does this PR introduce a user-facing change?

```release-note
`podman container commit` now features a `--config` option which accepts a filename containing a JSON-encoded container configuration to be merged in to the newly-created image.
```

Fixes #13770.

### CODE REVIEW

File: pkg/bindings/containers/types.go [hunk 1]
```diff
@@ -29,6 +29,7 @@ type LogOptions struct {
 type CommitOptions struct {
 	Author  *string
 	Changes []string
+	Config  []byte
```
Comment (Luap99) [inline pkg/bindings/containers/types.go:32]: I think it would make more sense to accepts an io.Reader here instead.

File: pkg/domain/entities/containers.go [hunk 2]
```diff
@@ -164,6 +164,7 @@ type ContainerStatReport struct {
 type CommitOptions struct {
 	Author         string
 	Changes        []string
+	Config         []byte
```
Comment (Luap99) [inline pkg/domain/entities/containers.go:167]: also io.Reader here.

File: pkg/bindings/containers/commit.go [hunk 3]
```diff
@@ -33,7 +33,12 @@ func Commit(ctx context.Context, nameOrID string, options *CommitOptions) (entit
 		return entities.IDResponse{}, err
 	}
 	params.Set("container", nameOrID)
-	response, err := conn.DoRequest(ctx, nil, http.MethodPost, "/commit", params, nil)
+	var requestBody io.Reader
+	if config := params.Get("config"); config != "" {
+		requestBody = strings.NewReader(config)
+		params.Del("config")
+	}
```
Comment (Luap99) [inline pkg/bindings/containers/commit.go:40]: you can add `schema:"-"` to the type then it will not be added via ToParams()

File: pkg/api/handlers/libpod/images.go [hunk 4]
```diff
@@ -487,14 +487,32 @@ func CommitContainer(w http.ResponseWriter, r *http.Request) {
 		SystemContext:         sc,
 		PreferredManifestType: mimeType,
 	}
+	if r.Body != nil {
```
Comment (Luap99) [inline pkg/api/handlers/libpod/images.go:490]: can you combine the duplicate code between the libpod/compat endpoint into function instead of copy pasting please

**Review by Luap99 — COMMENTED** [review]
just some drive by comments

File: pkg/bindings/containers/commit.go (hunk 3 above)
Comment (nalind) [reply pkg/bindings/containers/commit.go]: Ah, thanks, I wouldn't have guessed that.

File: pkg/api/handlers/libpod/images.go (hunk 4 above)
Comment (nalind) [reply pkg/api/handlers/libpod/images.go:490]: Moved that into `pkg/domain/infra/abi.DecodeOverrideConfig()`.  LMK if there's a better place for it.

File: pkg/bindings/containers/types.go (hunk 1 above)
Comment (nalind) [reply pkg/bindings/containers/types.go]: Had to make it a `*io.Reader` to make the generator happy.

File: pkg/domain/entities/containers.go (hunk 2 above)
Comment (nalind) [reply pkg/domain/entities/containers.go]: Had to make it a `*io.Reader` to make the generator happy.

File: pkg/bindings/containers/types.go (hunk 1 above)
Comment (Luap99) [reply pkg/bindings/containers/types.go]: Yeah I think the generator could use some improvements, IMO a pointer to a interface makes things harder to use and more likely to cause nil derefs.
Anyway this shouldn't really block your work.

**Comment by nalind** [comment]
/override "Build Each Commit"
... because the vendoring commit isn't going to be in the final version of this PR.

**Comment by nalind** [comment]
/retitle RHEL-14922: accept a config blob alongside the "changes" slice when committing

File: pkg/domain/entities/containers.go [hunk 5]
```diff
@@ -164,6 +164,7 @@ type ContainerStatReport struct {
 type CommitOptions struct {
 	Author         string
 	Changes        []string
+	Config         io.Reader
```
Comment (mheon) [inline pkg/domain/entities/containers.go:167]: This struct is used for the REST API as well - will this break given that io.Reader can't really be serialized over the network?

Comment (nalind) [reply pkg/domain/entities/containers.go]: Changed it back to a `[]byte`.

**Comment by rhatdan** [comment]
LGTM
@mheon @vrothberg PTAL

File: docs/source/markdown/podman-commit.1.md [hunk 6]
```diff
@@ -36,6 +36,11 @@ Apply the following possible instructions to the created image:
 
 Can be set multiple times.
 
+#### **--config**=*ConfigBlobFile*
+
+Merge the JSON-encoded container configuration from the specified file into the configuration for the image
```
Comment (vrothberg) [inline docs/source/markdown/podman-commit.1.md:41]: Can we point users to a specification of the configuration?

Comment (nalind) [reply docs/source/markdown/podman-commit.1.md:41]: It varies between OCI and Docker image formats.  I don't think there's a stable location to point to for the Docker config blob format (the engine API documentation is close, but it includes the API version number), and the OCI version is missing some interesting fields.  If it wasn't being exercised in tests that I'm about to add, I could pretty easily be talked into dropping the option.
Actually, maybe even after I add the tests to the PR....

Comment (nalind) [reply docs/source/markdown/podman-commit.1.md:41]: Well, as written, it's a JSON-encoded copy of the structure defined at https://github.com/containers/image/blob/main/manifest/docker_schema2.go#L67.  Would a pointer to that be useful enough to someone who hasn't spent time staring at that code at some point already?

Comment (vrothberg) [reply docs/source/markdown/podman-commit.1.md:41]: Great idea, thanks @nalind

Comment (nalind) [reply docs/source/markdown/podman-commit.1.md]: Okay, added.  Pointed at the currently-newest tag instead of `main` in case the line number changes.

**Comment by nalind** [comment]
Changed a line in the description of the `-v` flag for `build` to match what buildah's doc says about it, which I think removes a bit of ambiguity.
