### PR TITLE
[Fixes: #27571] Fix 'shouldResolveWinPaths' returning 'false' on Windows

### LINKED ISSUE #27571: Podman/Compose: "incorrect volume format" on Windows
### Issue Description

> Error response from daemon: fill out specgen: C:\Users\vbespalov\Downloads\modules:/mnt/modules:rw: incorrect volume format, should be [host-dir:]ctr-dir[:option]

### Steps to reproduce the issue

```yaml
volumes:
  - ..:/mnt/modules
```

### Describe the results you received

Podman compose fails to parse the volume spec (Docker ok, btw)

### Describe the results you expected

The absolute path it substituted in the volume spec is parsed correctly

### podman info output

```yaml
Client:
  APIVersion: 5.7.0
  Built: 1762887477
  BuiltTime: Tue Nov 11 21:57:57 2025
  GitCommit: 0370128fc8dcae93533334324ef838db8f8da8cb
  GoVersion: go1.25.4
  Os: windows
  OsArch: windows/amd64
  Version: 5.7.0
host:
  arch: amd64
  buildahVersion: 1.42.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  - dmem
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.13-1.fc42.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: '
  cpuUtilization:
    idlePercent: 98.31
    systemPercent: 1.04
    userPercent: 0.64
  cpus: 16
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: coreos
    version: "42"
  emulatedArchitectures:
  - linux/arm64
  - linux/arm64be
  eventLogger: journald
  freeLocks: 2044
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.16.10-200.fc42.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 225783808
  memTotal: 1151410176
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.16.0-1.fc42.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.16.0
    package: netavark-1.16.1-1.fc42.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.16.1
  ociRuntime:
    name: crun
    package: crun-1.25-1.fc42.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.25
      commit: d9a0adce065c7747ab88ea6ccc42b15a626e08e1
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20250919.g623dbf6-1.fc42.x86_64
    version: |
      pasta 0^20250919.g623dbf6-1.fc42.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: unix:///run/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.3.1-2.fc42.x86_64
    version: |-
      slirp4netns version 1.3.1
      commit: e5e368c4f5db6ae75c2fce786e31eef9da6bf236
      libslirp: 4.8.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.5
  swapFree: 0
  swapTotal: 0
  uptime: 0h 43m 13.00s
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.additionalImageStores:
    - /usr/lib/containers/storage
    overlay.imagestore: /usr/lib/containers/storage
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 99252940800
  graphRootUsed: 19084902400
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 5.7.0
  BuildOrigin: 'Copr: packit/containers-podman-27500'
  Built: 1762819200
  BuiltTime: Tue Nov 11 00:00:00 2025
  GitCommit: 0370128fc8dcae93533334324ef838db8f8da8cb
  GoVersion: go1.24.9
  Os: linux
  OsArch: linux/amd64
  Version: 5.7.0
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by limitedeternity**
#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
None
```

Fixes #27571

### CODE REVIEW

**Comment by limitedeternity** [comment]
Then, maybe, you have any other idea of what caused the issue?

Because `GenVolumeMounts` returns `error` containing `volumeFormatErr` if and only if `SplitVolumeString` returns more than 3 parts. And that happens - at least, in my case - only when `shouldResolveWinPaths` returns `false`: https://play.golang.com/p/P1SrVsUcW6e

**Comment by Luap99** [comment]
Are you using hyperV instead of wsl? If you look into shouldResolveWinPaths() it seem to only match wsl so I guess it would need to check for hyperv as well.

**Comment by limitedeternity** [comment]
Yes, my Machine uses Hyper-V as its backend. However:

https://github.com/containers/podman/blob/fac259ef9c45d45597f9ae554b221fc5b55935b6/pkg/specgen/winpath_linux.go#L8-L9

The line you mentioned is in `winpath_linux.go`, which shouldn't have been compiled for Windows. Am I wrong?

For Windows, `shouldResolveWinPaths` should unconditionally return `true`:
https://github.com/containers/podman/blob/fac259ef9c45d45597f9ae554b221fc5b55935b6/pkg/specgen/winpath_windows.go#L14-L15

**Comment by Luap99** [comment]
> The line you mentioned is in winpath_linux.go, which shouldn't have been compiled for Windows. Am I wrong?

The error you are seeing is coming from the server most likely. From the error you posted in the issue it seems you are using docker-compose (which `podman compose` can call, yes it is different from `podman-compose`)
Docker sends the windows path to the server as it seems and then podman on linux must translate it to the actual linux path I guess.

File: pkg/specgen/winpath_linux.go [hunk 1]
```diff
@@ -1,3 +1,5 @@
+//go:build linux
```
Comment (Honny1) [inline pkg/specgen/winpath_linux.go]: That seems unnecessary to me. After @Luap99's explanation.

File: pkg/specgen/winpath_windows.go [hunk 2]
```diff
@@ -1,3 +1,5 @@
+//go:build windows
```
Comment (Honny1) [inline pkg/specgen/winpath_windows.go]: ditto

File: pkg/specgen/winpath_linux.go (hunk 1 above)
Comment (limitedeternity) [reply pkg/specgen/winpath_linux.go]: Removed

File: pkg/specgen/winpath_windows.go (hunk 2 above)
Comment (limitedeternity) [reply pkg/specgen/winpath_windows.go]: aye

**Comment by limitedeternity** [comment]
Is it possible to restart failed checks? Or I'm supposed to just amend+push until it's all green?

**Review by Honny1 — COMMENTED** [review]
LGTM. I'll rerun the flakes if needed.

**Comment by limitedeternity** [comment]
Pinging @Luap99 for approval
