### PR TITLE
`ps`, `pod ps`, `volume ls`: format labels as comma-separated `key=value` for Docker compatibility

### LINKED ISSUE #21847: podman ps --format='{{json .Labels}}' incompatible with docker CLI output (string vs map of strings}
### Issue Description

The output of `podman ps --format='{{json .Labels}}'` is incompatible with the Docker CLI output. Docker prints a unique json string, with comma separated `key=value`, while podman outputs a json map of objects.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Start an upstream podman container:

```
> podman run -t -i --rm --privileged --pull=always -v /shared-volume --name podman-server --hostname=podman-server quay.io/podman/upstream
```

2. Inside this podman server container, start a podman service socket and a sleeping fedora container:

```
[root@podman-server /]# podman system service -t 0 unix:///shared-volume/podman.sock &
[1] 13
[root@podman-server /]# podman run -d --rm quay.io/fedora/fedora sleep 9999999
Trying to pull quay.io/fedora/fedora:latest...
Getting image source signatures
Copying blob 718a00fe3212 done   |
Copying config 368a084ba1 done   |
Writing manifest to image destination
75d9bb0e8265d99a56ce0535040601674c69c12166159bb5f5f2055ef25e64c5
```

3. Try to show the labels of this container using podman, it outputs a json object:

```
[root@podman-server /]# podman ps --format='{{json .Labels}}'
{"license":"MIT","name":"fedora","vendor":"Fedora Project","version":"39"}
```

4. From outside of the podman server container, start another container with the docker CLI installed, and mount the same shared volume to run a similar ps command. The output this time is a string:

```
> podman run -t -i --rm --volumes-from podman-server --pull=always -e DOCKER_HOST=unix:///shared-volume/podman.sock docker.io/docker:cli docker ps --format '{{json .Labels}}'
"version=39,license=MIT,name=fedora,vendor=Fedora Project"
```

### Describe the results you received

`podman ps --format='{{json .Labels}}'` and `docker ps --format='{{json .Labels}}'` output differs (different json type).

### Describe the results you expected

Well... normally podman aims for docker compatibility...

Here to be honest, I feel the podman output is much more logical, and Docker did a very bad choice to expose a comma separated key-value list... However Docker was there first, and is the de-facto standard so... should podman behave exactly like Docker in this case ? Should podman keep `Labels` exactly like docker does and expose a new `LabelsAsObject` field to have both formats available ?

### podman info output

```yaml
Tested using latest `quay.io/podman/upstream` image.
```

### Podman in a container

Yes

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Honny1**
Fixes: https://github.com/containers/podman/issues/21847

#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
The --format '{{.Labels}}' output for ps, pod ps, and volume ls now produces comma-separated key=value pairs, matching Docker CLI behavior.
```

### CODE REVIEW

**Comment by Honny1** [comment]
PTAL @containers/podman-maintainers @containers/podman-reviewers

File: cmd/podman/containers/ps.go [hunk 1]
```diff
@@ -342,7 +342,22 @@ func (l psReporter) ImageID() string {
...
+func (l psReporter) Labels() string {
+	keys := make([]string, 0, len(l.ListContainer.Labels))
+	for k := range l.ListContainer.Labels {
+		keys = append(keys, k)
+	}
+	slices.Sort(keys)
+	list := make([]string, 0, len(keys))
+	for _, k := range keys {
+		list = append(list, k+"="+l.ListContainer.Labels[k])
+	}
```
Comment (Luap99) [inline cmd/podman/containers/ps.go]: that same code is duplicated three times here, that screams like we should just have a helper function and call it.

And then also port podman network ls, while it has the right format it does not sort the keys.

Comment (Honny1) [reply cmd/podman/containers/ps.go]: Fixed.

**Review by Luap99 — APPROVED** [review]
LGTM

File: cmd/podman/containers/ps.go (hunk 1 above)
Comment (mtrmac) [reply cmd/podman/containers/ps.go]: BTW `keys := slices.Sorted(maps.Keys(…))`, does not preallocate exactly the right size but is so much clearer/shorter.

Comment (mtrmac) [reply cmd/podman/containers/ps.go]: (^^^ is absolutely non-blocking, don’t slow down the release for this.)

File: cmd/podman/pods/ps.go [hunk 2]
```diff
@@ -194,9 +194,19 @@ func (l ListPodReporter) Created() string {
...
+	keys := make([]string, 0, len(l.ListPodsReport.Labels))
+	for k := range l.ListPodsReport.Labels {
+		keys = append(keys, k)
+	}
+	sort.Strings(keys)
+	list := make([]string, 0, len(keys))
+	for _, k := range keys {
+		list = append(list, k+"="+l.ListPodsReport.Labels[k])
+	}
+	return strings.Join(list, ",")
```
Comment (inknos) [inline cmd/podman/pods/ps.go:209]: I see an opportunity to deduplicate the code of this and the other two `Label()` functions. furthermore, out of scope of this pr, but good chance of deduplication, [network ls Labels()](https://github.com/containers/podman/blob/main/cmd/podman/networks/list.go#L155-L161) could benefit from it too and return sorted labels, currently they are unsorted

**Review by inknos — COMMENTED** [review]
Lastly, nitpicking. I saw the docs are updated for pod and ps, maybe for volume ls too? https://github.com/containers/podman/blob/main/docs/source/markdown/podman-volume-ls.1.md.in#L32C11-L32C14

File: cmd/podman/pods/ps.go (hunk 2 above)
Comment (inknos) [reply cmd/podman/pods/ps.go:209]: oh I arrived late with mine. nvmd

**Comment by Honny1** [comment]
> Lastly, nitpicking. I saw the docs are updated for pod and ps, maybe for volume ls too? https://github.com/containers/podman/blob/main/docs/source/markdown/podman-volume-ls.1.md.in#L32C11-L32C14

I had issues with the linting of completions.

File: cmd/podman/containers/ps.go (hunk 1 above)
Comment (Luap99) [reply cmd/podman/containers/ps.go]: > BTW keys := slices.Sorted(maps.Keys(…)), does not preallocate exactly the right size but is so much clearer/shorter.

which is my biggest pet peeve with the iterator APIs, we no longer get to properly allocate slices. Sure it likely does not matter here but really why write code in a way it is known cause unnecessary allocations and memory copies.

Comment (TomSweeneyRedHat) [reply cmd/podman/containers/ps.go]: FWIW, good spot, and I like the new helper function.

**Comment by TomSweeneyRedHat** [comment]
LGTM
