### PR TITLE
Fixed Healthcheck formatting, string to []string

### LINKED ISSUE #10617: podman docker-compose healthchecks issue
I am running podman 3.1.2-dev on a custom embedded Linux device.  I have a docker-compose.yml file with an application named '**app1**', which is a simple Python3 Flask webserver.  Podman successfully brings up the docker-compose environment, but my healthchecks always return error, regardless of what I use for timeouts, intervals, retries, etc. My defined healthcheck works when I exec into the container and run them manually. When I inspect the application with '**podman inspect app1**', I can see 2 '**CMD-SHELL**' instances defined. I believe it should only have mine and perhaps this is the issue.

Output of **podman inspect app1**:

```
"Healthcheck": {
    "Test": [
        "CMD-SHELL",
        "CMD-SHELL /usr/bin/wget http://127.0.0.1 || exit 1"
    ],
    "StartPeriod": 300000000000,
    "Interval": 30000000000,
    "Timeout": 60000000000,
    "Retries": 5
},

"Healthcheck": {
        "Status": "unhealthy",
        "FailingStreak": 21,
        "Log": [
            {
                "Start": "2021-06-09T14:53:29.192875476Z",
                "End": "2021-06-09T14:53:31.211062949Z",
                "ExitCode": 1,
                "Output": ""
            },
            {
                "Start": "2021-06-09T14:54:07.933818178Z",
                "End": "2021-06-09T14:54:10.368276033Z",
                "ExitCode": 1,
                "Output": ""
            },
            {
                "Start": "2021-06-09T14:54:47.115168651Z",
                "End": "2021-06-09T14:54:49.119256984Z",
                "ExitCode": 1,
                "Output": ""
            },
            {
                "Start": "2021-06-09T14:55:26.183508777Z",
                "End": "2021-06-09T14:55:28.038064193Z",
                "ExitCode": 1,
                "Output": ""
            },
            {
                "Start": "2021-06-09T14:56:02.115129058Z",
                "End": "2021-06-09T14:56:03.41780082Z",
                "ExitCode": 1,
                "Output": ""
            }
        ]
    }
},
```

Manually running healthchecks:

```
root@robot:~# podman healthcheck run app1
unhealthy
root@robot:~# 
root@robot:~# podman exec -it app1 sh
/ # 
/ # /usr/bin/wget http://127.0.0.1 || exit 1
Connecting to 127.0.0.1 (127.0.0.1:80)
saving to 'index.html'
index.html           100% |*******************************************************************************|    39  0:00:00 ETA
'index.html' saved
/ # 
/ # echo $?
0
/ # exit
root@robot:~# 

root@robot:~# podman --version
podman version 3.2.1-dev
root@robot:~# 
```

docker-compose.yml file:

```
services:
  app1:
    container_name: app1
    hostname: app1
    image: app1:1.0
    build: ./app1
    init: true
    entrypoint:
      - "python3"
      - "/app/app.py"
    security_opt:
      - seccomp=unconfined
    tty: true
    healthcheck:
      test: /usr/bin/wget http://127.0.0.1 || exit 1
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 300s
    restart: always
    volumes:
      - ./app1:/app
      - ./shared_data:/shared_data
    environment:
      HEALTHCHECK_DEBUG: 1
    cpu_count: 1
    cpus: 0.95
    cpu_percent: 10
    mem_limit: 25m
    networks:
      - robot_internal_net
```

### PR DESCRIPTION
**Pull request by cdoern**
Compat healthcheck tests are of the format []string but podman's were of
the format string. Converted podman's to []string at the specgen level since it has the same effect
and removed the incorrect parsing of compat healthchecks.

fixes #10617

Signed-off-by: cdoern <cbdoer23@g.holycross.edu>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
But tests are failing.

File: test/e2e/run_test.go [hunk 1]
```diff
@@ -1205,21 +1205,21 @@ USER mail`, BB)
 	})
 
 	It("podman run with bad healthcheck retries", func() {
-		session := podmanTest.Podman([]string{"run", "-dt", "--health-cmd", "[\"foo\"]", "--health-retries", "0", ALPINE, "top"})
+		session := podmanTest.Podman([]string{"run", "-dt", "--health-cmd", "foo", "--health-retries", "0", ALPINE, "top"})
```
Comment (jwhonce) [inline test/e2e/run_test.go:1208]:
```suggestion
		session := podmanTest.Podman([]string{"run", "-dt", "--health-cmd", "foo", "--health-retries", "0", ALPINE, "top"})
```
With this change does the health-retries error out as expected or the health-cmd not being an array?

File: cmd/podman/common/specgen.go [hunk 2]
```diff
@@ -655,26 +655,20 @@ func FillOutSpecGen(s *specgen.SpecGenerator, c *ContainerCLIOpts, args []string
 	return nil
 }
 
-func makeHealthCheckFromCli(inCmd, interval string, retries uint, timeout, startPeriod string) (*manifest.Schema2HealthConfig, error) {
+func makeHealthCheckFromCli(inCmd string, interval string, retries uint, timeout, startPeriod string) (*manifest.Schema2HealthConfig, error) {
+	cmdArr := strings.Split(inCmd, " ")
```
Comment (jwhonce) [inline cmd/podman/common/specgen.go:659]:
```suggestion
	cmdArr := strings.Fields(inCmd)
```
Will handle more inputs correctly.

**Comment by cdoern** [comment]
@jwhonce @rhatdan I am realizing now that this would be much simpler and compat if we required users (like docker) to specify `CMD-SHELL` (one command to read in as a whole) vs `CMD` (arg1, arg2 etc). Would this be something you would like me to add? I have a few fixes ready to push for this right now but they are contingent on that.

File: test/e2e/run_test.go (hunk 1 above)
Comment (cdoern) [reply test/e2e/run_test.go:1208]: healthCmd is read in as a string and then converted to an array so as long as you pass it a single string with no quotes: `foo` or a long string with quotes `"foo bar 123"` the errors don't change

**Comment by TomSweeneyRedHat** [comment]
LGTM
and happy green test buttons

File: test/e2e/run_test.go (hunk 1 above)
Comment (Luap99) [reply test/e2e/run_test.go:1208]: This is a breaking change. Why should `[\"foo\"]` no longer be valid?

Comment (cdoern) [reply test/e2e/run_test.go:1208]: I can change the parsing so [] is valid. Personally it doesn't make sense to me why we would take an array if our healthchecks on the cmd level are strings, [""] and "" are just as easy to input

Comment (Luap99) [reply test/e2e/run_test.go:1208]: The point is this is breaking users who already use the `[""]` syntax. Breaking changes should be limited to major releases. It is also documented in the man page that this syntax is valid.

**Review by vrothberg — COMMENTED** [review]
/lgtm
/hold

File: test/e2e/run_test.go (hunk 1 above)
Comment (cdoern) [reply test/e2e/run_test.go]: just changed it so `[""]` is valid @Luap99

Comment (Luap99) [reply test/e2e/run_test.go]: I think you have to use `json.Unmarshal` as this will handle special escape sequences and more. Also I do not think just removing the first bracket will not work for `["some","long","command"]`

**Comment by Luap99** [comment]
Please do not merge until https://github.com/containers/podman/pull/11048#discussion_r677442979 is resolved.

File: test/e2e/run_test.go (hunk 1 above)
Comment (cdoern) [reply test/e2e/run_test.go]: It removes both brackets. The array is technically a string so long commands wont matter (I don't think) as it reads it as one consecutive string.

Comment (Luap99) [reply test/e2e/run_test.go]: `strings.Fields(inCmd)` will only split at whitespaces but in this case it has to split at the comma and also remove the quotes. Therefore you should use `json.Unmarshal`.

Comment (cdoern) [reply test/e2e/run_test.go]: resolving now.

File: cmd/podman/common/specgen.go [hunk 3]
```diff
@@ -655,26 +655,41 @@ func FillOutSpecGen(s *specgen.SpecGenerator, c *ContainerCLIOpts, args []string
...
+		isArr = true
+		err := json.Unmarshal([]byte(inCmd), cmdArr)
+		if err != nil {
+			return nil, err
+		}
+		fmt.Println(cmdArr)
+		cmdSplit = *cmdArr
+		fmt.Println(cmdSplit)
+	}
+	if cmdSplit[0] != "CMD" && cmdSplit[0] != "none" { // if it isnt a cmd-shell or a cmd, it is a command
```
Comment (Luap99) [inline cmd/podman/common/specgen.go:672]: Also need to check for `CMD-SHELL`.

File: cmd/podman/common/specgen.go [hunk 4]
```diff
@@ -655,26 +655,41 @@ func FillOutSpecGen(s *specgen.SpecGenerator, c *ContainerCLIOpts, args []string
...
+	cmdSplit := strings.SplitN(inCmd, " ", 2)
+	if strings.Contains(inCmd, "[") { // given an array, need to unmarshall it into a pointer
+		isArr = true
+		err := json.Unmarshal([]byte(inCmd), cmdArr)
+		if err != nil {
+			return nil, err
+		}
+		fmt.Println(cmdArr)
+		cmdSplit = *cmdArr
+		fmt.Println(cmdSplit)
```
Comment (Luap99) [inline cmd/podman/common/specgen.go:670]: I think this is leftover from debugging, please remove both print statements.

File: cmd/podman/common/create_opts.go [hunk 5]
```diff
@@ -517,7 +517,12 @@ func ContainerCreateToContainerCLIOpts(cc handlers.CreateContainerConfig, rtc *c
 		cliOpts.OOMKillDisable = *cc.HostConfig.OomKillDisable
 	}
 	if cc.Config.Healthcheck != nil {
-		cliOpts.HealthCmd = strings.Join(cc.Config.Healthcheck.Test, " ")
+		finCmd := ""
+		for _, str := range cc.Config.Healthcheck.Test {
+			finCmd = finCmd + str + " "
+		}
+		finCmd = finCmd[:len(finCmd)-1]
```
Comment (mheon) [inline cmd/podman/common/create_opts.go:524]: Don't think this is safe for all commands - Manpages say that a length-1 command is allowed to be specified without brackets, so `podman run --health-cmd "./my_script,sh"` is perfectly legal, and will not work with this.

File: test/e2e/run_test.go [hunk 6]
```diff
@@ -1212,14 +1212,14 @@ USER mail`, BB)
 	})
 
 	It("podman run with bad healthcheck timeout", func() {
-		session := podmanTest.Podman([]string{"run", "-dt", "--health-cmd", "[\"foo\"]", "--health-timeout", "0s", ALPINE, "top"})
+		session := podmanTest.Podman([]string{"run", "-dt", "--health-cmd", "foo", "--health-timeout", "0s", ALPINE, "top"})
```
Comment (mheon) [inline test/e2e/run_test.go:1215]: Why change this? Is the syntax no longer legal?

File: cmd/podman/common/specgen.go [hunk 7]
```diff
@@ -655,26 +655,53 @@ func FillOutSpecGen(s *specgen.SpecGenerator, c *ContainerCLIOpts, args []string
 	return nil
 }
 
-func makeHealthCheckFromCli(inCmd, interval string, retries uint, timeout, startPeriod string) (*manifest.Schema2HealthConfig, error) {
+func makeHealthCheckFromCli(inCmd string, interval string, retries uint, timeout, startPeriod string) (*manifest.Schema2HealthConfig, error) {
```
Comment (mheon) [inline cmd/podman/common/specgen.go:658]: Why was the signature changed? Looks like addition of duplicate `string` specifiers, nothing functional

File: cmd/podman/common/specgen.go [hunk 8]
```diff
@@ -655,26 +655,53 @@ func FillOutSpecGen(s *specgen.SpecGenerator, c *ContainerCLIOpts, args []string
...
+	cmdArr := &[]string{}
```
Comment (mheon) [inline cmd/podman/common/specgen.go:659]: The double-indirection here is kind of gross - would be better to specify as `[]string{}` and then add the `&` only to the `json.Unmarshal` call below.

File: cmd/podman/common/specgen.go [hunk 9]
```diff
@@ -655,26 +655,53 @@ func FillOutSpecGen(s *specgen.SpecGenerator, c *ContainerCLIOpts, args []string
...
+	if cmdSplit[0] != "CMD" && cmdSplit[0] != "none" && cmdSplit[0] != "CMD-SHELL" { // if it isnt a cmd-shell or a cmd, it is a command
+		if isArr && len(cmdSplit) > 1 { // an array of consecutive commands
+			cmdSplit = append([]string{"CMD"}, cmdSplit...)
+		} else { // one singular command
+			if len(cmdSplit) == 1 {
+				concat = cmdSplit[0]
+			} else {
+				concat = strings.Join(cmdSplit[1:], " ")
+			}
+			cmdSplit = append([]string{"CMD-SHELL"}, concat)
```
Comment (mheon) [inline cmd/podman/common/specgen.go:680]: I'm confused as to the necessity of this. We've split the command apart on whitespace, but now we're concatenating it together again? Seems unnecessary. Seems like it would be easier to just check for certain prefixes? Especially given that I don't think that `CMD-SHELL` inside a JSON array is actually valid.

Comment (cdoern) [reply cmd/podman/common/specgen.go:680]: This is for the purpose of compat vs non compat. The compat side will always include `CMD` or `CMD-SHELL` while most podman users will not. This is similar to how this was done before, there are just more codepaths now, I think all compat healthchecks were broken and duplicating `CMD-SHELL` twice

File: cmd/podman/common/specgen.go (hunk 7 above)
Comment (cdoern) [reply cmd/podman/common/specgen.go:658]: Typo sorry. I was originally doing `[]string` on the cmd level but changed it back to `string`

File: test/e2e/run_test.go (hunk 6 above)
Comment (cdoern) [reply test/e2e/run_test.go:1215]: No it is, I just thought It would be good to alternate the tests with strings and arrays to test both

File: cmd/podman/common/create_opts.go (hunk 5 above)
Comment (cdoern) [reply cmd/podman/common/create_opts.go:524]: fixed

File: cmd/podman/common/specgen.go [hunk 10]
```diff
@@ -656,25 +655,52 @@ func FillOutSpecGen(s *specgen.SpecGenerator, c *ContainerCLIOpts, args []string
 }
 
 func makeHealthCheckFromCli(inCmd, interval string, retries uint, timeout, startPeriod string) (*manifest.Schema2HealthConfig, error) {
+	cmdArr := []string{}
+	isArr := false
+	cmdSplit := strings.SplitN(inCmd, " ", 2) // default for compat
```
Comment (mheon) [inline cmd/podman/common/specgen.go:660]: The logic here is reverse of what it should be - do a JSON unmarshal first, and if that returns an error attempt to parse as a string.

File: cmd/podman/common/specgen.go [hunk 11]
```diff
@@ -656,25 +655,52 @@ func FillOutSpecGen(s *specgen.SpecGenerator, c *ContainerCLIOpts, args []string
...
+	if strings.Contains(inCmd, "[") {         // given an array, need to unmarshall it into a pointer
+		isArr = true
+		err := json.Unmarshal([]byte(inCmd), &cmdArr)
+		if err != nil {
+			return nil, err
+		}
+		cmdSplit = cmdArr
+	}
+	concat := ""
+	if cmdSplit[0] != "CMD" && cmdSplit[0] != "none" && cmdSplit[0] != "CMD-SHELL" { // if it isnt a cmd-shell or a cmd, it is a command
```
Comment (mheon) [inline cmd/podman/common/specgen.go:670]: What if the result is len(0)? This will panic

File: cmd/podman/common/specgen.go (hunk 9 above)
Comment (mheon) [reply cmd/podman/common/specgen.go:679]: Sure, but that doesn't address the core of my concern - there's no reason I can see to split the command on whitespace, then recombine it again into a single string for the typical CLI case. It seems like you really have two separate cases - CLI input as a JSON array, and CLI input as a raw string - and both of them can be parsed differently, because I don't believe that something like `--health-cmd '["CMD-SHELL", "echo hello world"]'` is valid.

Comment (cdoern) [reply cmd/podman/common/specgen.go:679]: hmmm okay I see what you are saying, this introduces an issue with docker though, since all of their commands have to have either cmd-shell or cmd when passed to this function.

File: cmd/podman/common/specgen.go (hunk 11 above)
Comment (cdoern) [reply cmd/podman/common/specgen.go:670]: an empty string does not panic and shows no healthcheck on inspect since no cmd was specified

**Comment by TomSweeneyRedHat** [comment]
LGTM
and happy green test buttons
@Luap99 can you do the merge honors if your concerns have been addressed?
