### PR TITLE
fix pod creation with "new:" syntax

### LINKED ISSUE #7087: rootless containers cannot connect using the local host on the same pod
/kind bug

**Description**
I'm running version 2.0.3 so maybe it's a new thing because the documentation says it should work.

Running on Fedora 32 with rootless containers.
I'm creating two containers in the same pod. They should connect one another using the local host, but it does not work.

**Steps to reproduce the issue:**

1. podman run -d --pod=new:test docker.io/library/nginx:latest 

2. podman run --rm -it --pod=test fedora curl http://localhost

**Describe the results you received:**
curl: (7) Failed to connect to localhost port 80: Connection refused

**Describe the results you expected:**
The default page from the server

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 2.0.3
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.19-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.19, commit: 5dce9767526ed27f177a8fa3f281889ad509fea7'
  cpus: 4
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: ip-10-0-0-111.ec2.internal
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.6.7-300.fc32.x86_64
  linkmode: dynamic
  memFree: 11909259264
  memTotal: 16780132352
  ociRuntime:
    name: crun
    package: crun-0.14.1-1.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.14.1
      commit: 598ea5e192ca12d4f6378217d3ab1415efeddefa
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 0
  swapTotal: 0
  uptime: 5h 58m 39.45s (Approximately 0.21 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/fedora/.config/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 5
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/fedora/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 7
  runRoot: /run/user/1000/containers
  volumePath: /home/fedora/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.14.3
  OsArch: linux/amd64
  Version: 2.0.3

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.3-1.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

### PR DESCRIPTION
**Pull request by Luap99**
When you execute podman create/run with the --pod new:\<name\> syntax
the pod was created but the namespaces where not shared and
therefore containers could not communicate over localhost.

Add the default namespaces and pass the network options to the
pod create options.

Closes #7087

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@mheon @baude @haircommander @ashley-cui PTAL

File: cmd/podman/containers/create.go [hunk 1]
```diff
@@ -292,11 +292,11 @@ func createPodIfNecessary(s *specgen.SpecGenerator) (*entities.PodCreateReport,
...
 	createOptions := entities.PodCreateOptions{
-		Name:  podName,
-		Infra: true,
-		Net: &entities.NetOptions{
-			PublishPorts: s.PortMappings,
-		},
+		Name:          podName,
+		Infra:         true,
+		Net:           netOpts,
+		Share:         strings.Split(specgen.DefaultKernelNamespaces, ","),
```
Comment (mheon) [inline cmd/podman/containers/create.go:298]: It looks like we need to make sure that the defaults are used in Specgen if this is unset.

Comment (Luap99) [reply cmd/podman/containers/create.go:298]: [there?](https://github.com/containers/podman/blob/c66ce8d67f9eb53a0997da39999ed8629d3252e3/pkg/specgen/generate/namespaces.go#L462)

Comment (mheon) [reply cmd/podman/containers/create.go:298]: Yes - that looks right. If the argument to that is nil, we should return the defaults. A 0-length non-nil array would indicate nothing is shared.

Comment (Luap99) [reply cmd/podman/containers/create.go]: OK, updated.

File: cmd/podman/containers/create.go [hunk 2]
```diff
@@ -292,11 +292,10 @@ func createPodIfNecessary(s *specgen.SpecGenerator) (*entities.PodCreateReport,
...
 	createOptions := entities.PodCreateOptions{
-		Name:  podName,
-		Infra: true,
-		Net: &entities.NetOptions{
-			PublishPorts: s.PortMappings,
-		},
+		Name:          podName,
+		Infra:         true,
+		Net:           netOpts,
+		CreateCommand: os.Args,
```
Comment (mheon) [inline cmd/podman/containers/create.go:298]: Probably best to leave this empty - it's mainly used for `podman generate systemd --new`, and it could have misleading results there

**Comment by mheon** [comment]
One more comment, LGTM once it's addressed

File: cmd/podman/containers/create.go (hunk 2 above)
Comment (Luap99) [reply cmd/podman/containers/create.go:298]: I believe it is correct to set here. I checked `podman generate systemd --new` and it throws an error that you have to use `podman pod create`. This can later be used to implement this.

**Comment by mheon** [comment]
Needs a rebase to fix CI

File: cmd/podman/containers/create.go (hunk 2 above)
Comment (mheon) [reply cmd/podman/containers/create.go:298]: @vrothberg Thoughts here?

Comment (vrothberg) [reply cmd/podman/containers/create.go:298]: It looks good to me. As @Luap99 mentioned, `generate systemd` requires a pod to be generated via `pod create` and will error out otherwise (see https://github.com/containers/podman/blob/master/pkg/systemd/generate/pods.go#L265).

Setting it here will be more accurate as `generate systemd` will otherwise error out with "no create command found" which would be less informative than "pod does not appear to be created via `podman pod create`"

Comment (mheon) [reply cmd/podman/containers/create.go:298]: Alright. We should be good to merge after a rebase, then.

**Comment by TomSweeneyRedHat** [comment]
LGTM
assuming happy tests

**Comment by Luap99** [comment]
One test still failed! A Flake?

**Comment by mheon** [comment]
Looking...

**Comment by mheon** [comment]
I've never seen this one before - going to assume it's a flake and restart...

**Comment by Luap99** [comment]
Now it timed out! :(

**Comment by Luap99** [comment]
@mheon Test is green :)
