### PR TITLE
Fix a potential race around the exec cleanup process

### LINKED ISSUE #13227: podman-in-podman: Error: timed out waiting for file: internal libpod error
Fedora CI is [failing](https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/rpminspect-pipeline/job/master/77209/testReport/(root)/tests/_rpmdeps/) with:
```
Error: timed out waiting for file /var/lib/containers/storage/overlay-containers/SHA1/userdata/SHA2/exit/SHA1: internal libpod error
```
Miro Vadkerti pinged me about it last week but has not yet filed an issue because it's hard to reproduce. All I know is, this is podman-in-podman. 

```irc
  2022-02-08 18:06:06 mvadkert    esm: it happens in a quite a lot of runs in CI, I will try to get a 
  reproducer tmrw
  2022-02-08 18:06:13 mvadkert    esm: our host runs
  2022-02-08 18:07:39 mvadkert    (me looking it up)
  2022-02-08 18:09:02 mvadkert    podman-3.4.4-1.fc35.x86_64
  2022-02-08 18:09:22 esm mvadkert, which version of crun?
  2022-02-08 18:09:25 esm https://github.com/containers/podman/issues/12262
  2022-02-08 18:09:27 mvadkert    and in container we we have podman-3.4.1-3.module_el8.6.0+954+963caf
  36.x86_64
  2022-02-08 18:09:38 mvadkert    crun-1.4-1.fc35.x86_64
  2022-02-08 18:09:41 esm oh no, this is podman-in-podman??
  2022-02-08 18:09:47 mvadkert    esm: yeah
  2022-02-08 18:09:51 mvadkert    esm: crun-1.2-1.module_el8.6.0+954+963caf36.x86_64
  2022-02-08 18:09:57 mvadkert    fc35 is the main host
  2022-02-08 18:10:06 mvadkert    in it we rune centos8 image
  2022-02-08 18:10:09 mvadkert    with podman
  2022-02-08 18:10:24 mvadkert    image is based on podman stable, but it is build on centos 8 stream 
  2022-02-08 18:10:38 mvadkert    esm: it is rootless podman in privileged podman
  2022-02-08 18:10:44 mvadkert    esm: but the problem seems random
  2022-02-08 18:11:10 mvadkert    esm: or test tools runs podman start and then podman exec to run ins
  ide the container commands
  2022-02-08 18:11:17 mvadkert    esm: anwyay, I will try to find some reproducer
  2022-02-08 18:11:24 mvadkert    it is quite common latel y :(
  2022-02-08 18:12:09 esm check conmon maybe?
  2022-02-08 18:12:28 mvadkert    aconmon-2.0.30-2.fc35.x86_64
  2022-02-08 18:12:36 ✭ esm doesn't even want to think about what time it is in cz
  2022-02-08 18:12:37 mvadkert    conmon-2.0.30-1.module_el8.6.0+944+d413f95e.x86_64
  2022-02-08 18:12:46 mvadkert    esm: yeah, I am not really here :)
  2022-02-08 18:12:48 esm oh, okay, that looks good
  2022-02-08 18:12:57 mvadkert    esm: will try to find some reproducer and I guess file it :)
  2022-02-08 18:13:10 mvadkert    esm: the erorrs are hidden a bit inside test failures
  2022-02-08 18:13:18 mvadkert    esm: so we did not spot it early enough
```

### PR DESCRIPTION
**Pull request by mheon**
Every exec session run attached will, on exit, do two things: it will signal the associated `podman exec` that it is finished (to allow Podman to collect the exit code and exit), and spawn a cleanup process to clean up the exec session (in case the `podman exec` process died, we still need to clean up). If an exec session is created that exits almost instantly, but generates a large amount of output (e.g. prints thousands of lines), the cleanup process can potentially execute before `podman exec` has a chance to read the exit code, resulting in errors. Handle this by detecting if the cleanup process has already removed the exec session before handling the error from reading the exec exit code.

[NO NEW TESTS NEEDED] I have no idea how to test this in CI.

Fixes #13227

### CODE REVIEW

File: libpod/container_exec.go [hunk 1]
```diff
@@ -341,22 +341,60 @@ func (c *Container) ExecStartAndAttach(sessionID string, streams *define.AttachS
...
+	if !c.batched {
+		c.lock.Lock()
+	}
+	// We can't reuse the old exec session (things may have changed from
+	// under use, the container was unlocked).
+	// So re-sync and get a fresh copy.
+	// If we can't do this, no point in continuing, any attempt to save
+	// would write garbage to the DB.
+	if err := c.syncContainer(); err != nil {
+		if errors.Cause(err) == define.ErrNoSuchCtr || errors.Cause(err) == define.ErrCtrRemoved {
```
Comment (Luap99) [inline libpod/container_exec.go:358]: please start using errors.Is for new code

File: libpod/container_exec.go [hunk 2]
```diff
@@ -341,22 +341,60 @@ func (c *Container) ExecStartAndAttach(sessionID string, streams *define.AttachS
...
+			// The exec session was removed entirely, probably by
+			// the cleanup process. When it did so, it should have
+			// written an event with the exit code.
+			// Given that, there's nothing more we can do.
+			logrus.Infof("Container %s exec session %s already removed", c.ID(), session.ID())
+			return lastErr
+		}
 
-	logrus.Debugf("Container %s exec session %s completed with exit code %d", c.ID(), session.ID(), exitCode)
+		if newSess.State == define.ExecStateStopped && os.IsNotExist(exitCodeErr) {
```
Comment (Luap99) [inline libpod/container_exec.go:382]: same here use errors.Is instead of os.IsNotExist

**Comment by mheon** [comment]
Adding WIP this isn't doing what I expect

**Comment by mheon** [comment]
I think I fixed it, going to repush

**Comment by mheon** [comment]
@edsantiago PTAL, I have this running on a 1MT and it seems to be running through the reproducer without issue.

**Comment by edsantiago** [comment]
@thrix FYI

**Review by edsantiago — COMMENTED** [review]
There's no way I can review the locking flow; and I shudder at the thought of building this in a CentOS container. I'll trust your testing. Two very minor comments.

**Comment by mheon** [comment]
@containers/podman-maintainers PTAL

File: libpod/container_exec.go [hunk 3]
```diff
@@ -341,22 +341,60 @@ func (c *Container) ExecStartAndAttach(sessionID string, streams *define.AttachS
...
+			// been entirely removed, we don't have to; exit cleanly
+			return lastErr
+		}
 		if lastErr != nil {
 			logrus.Errorf("Container %s exec session %s error: %v", c.ID(), session.ID(), lastErr)
 		}
-		lastErr = err
-	}
+		lastErr = errors.Wrapf(err, "error syncing container %s state to remove exec session %s", c.ID(), sessionID)
+	}
```
Comment (TomSweeneyRedHat) [inline libpod/container_exec.go:367]: if err at line 357 is not ErrNoSuchCtr or ErrCtrRemoved, it looks like we ignore it and continue on.  Is that OK?

**Comment by giuseppe** [comment]
> If an exec session is created that exits almost instantly, but generates a large amount of output (e.g. prints thousands of lines), the cleanup process can potentially execute before podman exec has a chance to read the exit code, resulting in errors.

is it a race in conmon?  I don' think it should call the cleanup process before reading all the container output and writing the exit code

**Comment by mheon** [comment]
Can we merge this, or are there further questions?

**Comment by mheon** [comment]
@baude @Luap99 @vrothberg PTAL

File: libpod/container_exec.go [hunk 4]
```diff
@@ -341,22 +341,60 @@ func (c *Container) ExecStartAndAttach(sessionID string, streams *define.AttachS
...
 
-	exitCode, err := c.readExecExitCode(session.ID())
-	if err != nil {
+	exitCode, exitCodeErr := c.readExecExitCode(session.ID())
+
+	// Lock again.
+	// Important: we must lock and sync *before* the above error is handled.
+	// We need info from the database to handle the error.
+	if !c.batched {
+		c.lock.Lock()
```
Comment (vrothberg) [inline libpod/container_exec.go:350]: I miss an `Unlock()` somewhere.

Comment (edsantiago) [reply libpod/container_exec.go:350]: It's way, way above

Comment (mheon) [reply libpod/container_exec.go:350]: It lives at https://github.com/containers/podman/blob/5b2597d5232627b5560bf628276ec67b35aba4bf/libpod/container_exec.go#L287

We don't use a locked/unlocked bool because there are no returns while the container is unlocked.
