### PR TITLE
Always chown volumes when mounting into a container

### LINKED ISSUE #22571: Volume mounting ownership inconsistent between Docker & Podman
### Issue Description

Volume ownership within Podman is different to Docker, and has unexpected behaviors that are detrimental to designing container images that will work on both platforms. 

The issue is explained with a test rig at https://github.com/BarDweller/mountperms

### Steps to reproduce the issue

The issue is explained with a test rig at https://github.com/BarDweller/mountperms

### Describe the results you received

Mounted volume ownership can ignore ownership of mountpoint directories in the container image, and does not behave consistently with Docker when mounting volumes to non-existing mountpoints.

### Describe the results you expected

Mounted volume ownership should be predictable, and ideally match Dockers.

### podman info output

```yaml
$ podman info
host:
  arch: amd64
  buildahVersion: 1.32.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.10-1.fc39.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: '
  cpuUtilization:
    idlePercent: 97.46
    systemPercent: 0.57
    userPercent: 1.97
  cpus: 2
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: workstation
    version: "39"
  eventLogger: journald
  freeLocks: 2031
  hostname: PODMANVM
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 6.7.5-200.fc39.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 4063780864
  memTotal: 10923556864
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.10.0-1.fc39.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.10.0
    package: netavark-1.10.3-1.fc39.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.10.3
  ociRuntime:
    name: crun
    package: crun-1.14.3-1.fc39.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.14.3
      commit: 1961d211ba98f532ea52d2e80f4c20359f241a98
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240220.g1e6f92b-1.fc39.x86_64
    version: |
      pasta 0^20240220.g1e6f92b-1.fc39.x86_64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-1.fc39.x86_64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 1941434368
  swapTotal: 1989144576
  uptime: 578h 8m 19.00s (Approximately 24.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  127.0.0.1:5000:
    Blocked: false
    Insecure: true
    Location: 127.0.0.1:5000
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: 127.0.0.1:5000
    PullFromMirror: ""
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/ajo1/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/ajo1/.local/share/containers/storage
  graphRootAllocated: 19769851904
  graphRootUsed: 19056824320
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 25
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/ajo1/.local/share/containers/storage/volumes
version:
  APIVersion: 4.7.0
  Built: 1695838680
  BuiltTime: Wed Sep 27 14:18:00 2023
  GitCommit: ""
  GoVersion: go1.21.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.7.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by mheon**
This is done to better match Docker's behavior. Our current behavior is to only chown a volume once, the first time it is mounted into a container; that doesn't match what Docker does. Docker chowns every time a container mounts a volume, to ensure it is always accessible to the last container to mount it.

Fortunately, this is a relatively easy fix. We have a bool in volume state as to whether a volume needs to be chowned, which we set to false when the volume was first chowned; so just stop doing that.

I was really hoping to eliminate the NeedsChown bool entirely, but things are a bit of a mess. There are some cases where we do want to completely inhibit chowning, like when the user explicitly requests that a volume be a specific UID and GID. Unfortunately, those are both ints, not *int, so we can't tell whether they were actually set, and the solution we were using was to force the NeedsChown bool to false - so we really need to keep it around. And even if we could change volume UID/GID to pointers, we're setting them in places we really shouldn't be - for example, container anonymous volumes set UID/GID to current container UID/GID, despite the fact that the volume will immediately chown itself from that to match the directory it's mounting over? In short, the current code's a mess and I don't see a way to fix it without breaking changes.

Fixes #22571

#### Does this PR introduce a user-facing change?

```release-note
Podman now changes volume ownership every time a volume is mounted into a container, not just the first time.
```

### CODE REVIEW

**Comment by mheon** [comment]
Still needs a test

**Comment by Luap99** [comment]
btw this branch seems very out of date so you must rebase

File: libpod/container_internal_common.go [hunk 1]
```diff
@@ -2827,8 +2827,6 @@ func (c *Container) fixVolumePermissions(v *ContainerNamedVolume) error {
 	// Volumes owned by a volume driver are not chowned - we don't want to
 	// mess with a mount not managed by us.
 	if vol.state.NeedsChown && (!vol.UsesVolumeDriver() && vol.config.Driver != "image") {
-		vol.state.NeedsChown = false
```
Comment (Luap99) [inline libpod/container_internal_common.go:2830]: this field is exposed with volume inspect and has public documentation so that must be changed

I think always doing the chown should not be a breaking change so it is fine but if you have more plans to change the volume behaviour then we should be really careful to not break existing podman users

Comment (rhatdan) [reply libpod/container_internal_common.go:2830]: Make sure it is a safechown, don't change uid=0 to uid=0.

**Comment by mheon** [comment]
Logic majorly updated to reflect further observations of Docker. Tests added.

**Comment by mheon** [comment]
Each of the 3 tests I added is taking ~30s to run, which is suboptimal. Maybe I should push the image to Quay and cache it?

**Comment by Luap99** [comment]
> Each of the 3 tests I added is taking ~30s to run, which is suboptimal. Maybe I should push the image to Quay and cache it?

How big is the final image? If the image is the same for all three tests than pushing to quay.io/libpod and adding in the image cache will almost certainly help speed compared to having it to build three times

**Comment by Luap99** [comment]
> > Each of the 3 tests I added is taking ~30s to run, which is suboptimal. Maybe I should push the image to Quay and cache it?
> 
> How big is the final image? If the image is the same for all three tests than pushing to quay.io/libpod and adding in the image cache will almost certainly help speed compared to having it to build three times

If you do decide to push the image in quay then please make sure to add the Containefile + build instructions here in the repo somewhere under test, e.g. like `test/testvol`

**Comment by mheon** [comment]
The final image shouldn't be much bigger than the `fedoraMinimal` we already cache, it has extra layers but they're all useradd/chown, no files of substance. The image is different for all 3 but not sufficiently different that I can't combine them.

File: test/e2e/run_volume_test.go [hunk 2]
```diff
@@ -30,6 +30,16 @@ var _ = Describe("Podman run with volumes", func() {
...
 	}
 
+	//nolint:unparam
+	mountVolumeAndCheckDirectory := func(volName, volPath, expectedOwner, imgName string) {
+		check := podmanTest.Podman([]string{"run", "-v", fmt.Sprintf("%s:%s", volName, volPath), imgName, "ls", "-al", volPath})
+		check.WaitWithDefaultTimeout()
+		Expect(check).Should(ExitCleanly())
+		Expect(check.OutputToString()).To(MatchRegexp(`^drwxr-xr-x\.\s+[0-9]+\s+%s\s+%s\s*[0-9]\s+.+\s+\.$`, expectedOwner, expectedOwner))
+		// Should match lines of this format, but with arbitrary username. Permissions always fixed, directory always .
+		// drwxr-xr-x. 1 mheon mheon    0 May 22 09:49 .
```
Comment (Luap99) [inline test/e2e/run_volume_test.go:40]: why use `ls -al` when the output is hard to match? either use `ls -n` to only get the ids or better use `stat -c %u:%g`
stat should be part of the regual alpine based image

File: test/e2e/run_volume_test.go [hunk 3]
```diff
@@ -970,4 +980,89 @@ USER testuser`, CITEST_IMAGE)
...
+RUN groupadd -g 4567 test2
+RUN groupadd -g 7890 test3
+RUN useradd -u 1234 -g 1234 test1
+RUN useradd -u 4567 -g 4567 test2
+RUN useradd -u 7890 -g 7890 test3
+RUN mkdir /test1 /test2 /test3 /test4
+RUN chown test1:test1 /test1
+RUN chown test2:test2 /test2
+RUN chown test3:test3 /test4
+RUN chmod 755 /test1 /test2 /test3 /test4`, fedoraMinimal)
```
Comment (Luap99) [inline test/e2e/run_volume_test.go:997]: is there a reason for fedora-minimal? The image is still much bigger than alpine based so it slows the build down.

Comment (mheon) [reply test/e2e/run_volume_test.go:997]: Presence of useradd, vs adduser, useradd being a lot easier to use with numeric groups. I can refactor to use alpine though.

**Comment by rhatdan** [comment]
LGTM

**Comment by mheon** [comment]
Passing now

**Review by Luap99 — APPROVED** [review]
/lgtm
