### PR TITLE
Change priority for cli flags for remotely operating Podman

### LINKED ISSUE #15588: CONTAINER_HOST takes precedence over --connection argument
/kind bug

**Description**

When connecting to a remote podman server, `CONTAINER_HOST` takes precedence over the `--connection` argument and `CONTAINER_CONNECTION` variable when selecting the remote in a way that is confusing to the user.

**Steps to reproduce the issue:**

With two VMs setup with ssh over ports 48011 and 48012:

1. `podman-remote system connection add foo --identity ~/.ssh/id_rsa ssh://root@localhost:48011/run/podman/podman.sock` (add foo remote)

2. `podman-remote system connection add bar --identity ~/.ssh/id_rsa ssh://root@localhost:48012/run/podman/podman.sock` (add bar remote)

3. `export CONTAINER_HOST=ssh://root@localhost:48011/run/podman/podman.sock` (set foo as host)

3. `podman-remote run -it ubuntu bash` (launch container on foo)

4. `podman-remote --connection bar ps` (check running containers on bar)

**Describe the results you received:**

When attempting to connect to the `bar` VM which has no running containers, `podman-remote` picks up the `foo` connection from `CONTAINER_HOST` and shows me:

```
CONTAINER ID  IMAGE                            COMMAND     CREATED        STATUS            PORTS       NAMES
ff3c2b87d384  docker.io/library/ubuntu:latest  bash        7 seconds ago  Up 7 seconds ago              eloquent_bell
```

**Describe the results you expected:**

I expect no containers to be running because I have explicitly passed a connection to the `bar` remote.

Expect `CONTAINER_CONNECTION` and the `--connection` argument to take precedence over the `CONTAINER_HOST` variable.

**Additional information you deem important (e.g. issue happens only occasionally):**

Even when the default connection is set to be `bar`, if `CONTAINER_HOST` points at `foo` then `podman-remote` connects to `foo`. It is not always obvious that an environment variable is set and can be confusing when a CLI arg is used that it does not take precedence.

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 6
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: ubuntu
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.0-30-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 3350441984
  memTotal: 6222995456
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 0
  swapTotal: 0
  uptime: 28m 24.69s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/jammy,now 3.4.4+ds1-1ubuntu1 amd64 [installed]
```

Tried on latest podman?

No

### PR DESCRIPTION
**Pull request by cgiradkar**
--connection flag couldn't override the active-destination when CONTAINER_HOST env variable was set. As a remedy, the precedence of --connection flag has been changed.

#### Does this PR introduce a user-facing change?

```release-note
For operating Podman remotely, the order of priority is:

1.  cli flags (--connection ,--url ,--context ,--host)
2.  Env variables (CONTAINER_HOST and CONTAINER_CONNECTION)
3.  ActiveService from containers.conf
4.  RemoteURI

```
Closes #15588 

Signed-off-by: Chetan Giradkar <cgiradka@redhat.com>

### CODE REVIEW

File: cmd/podman/root.go [hunk 1]
```diff
@@ -142,6 +141,75 @@ func Execute() {
...
+		}
+
+		if dest, ok := conf.Engine.ServiceDestinations[conn.Value.String()]; ok {
+			podmanConfig.URI = dest.URI
+			podmanConfig.Identity = dest.Identity
+			podmanConfig.MachineMode = dest.IsMachine
+			return nil
+		} else {
+			return fmt.Errorf("connection %q not found", conn.Value.String())
+		}
```
Comment (Luap99) [inline cmd/podman/root.go:170]: else is not needed because of the return above, you can just return the error here without the extra else {} block

File: cmd/podman/root.go [hunk 2]
```diff
@@ -142,6 +141,75 @@ func Execute() {
...
+			podmanConfig.MachineMode = dest.IsMachine
+			return nil
+		}
+		return fmt.Errorf("connection %q not found", connEnv)
+	case hostEnv != "":
+		if sshkeyEnv != "" {
+			podmanConfig.Identity = sshkeyEnv
+		}
+		podmanConfig.URI = hostEnv
+		return nil
```
Comment (Luap99) [inline cmd/podman/root.go:201]: you can remove this return nil because you use a switch case and we return after it anyway

File: cmd/podman/root.go [hunk 3]
```diff
@@ -142,6 +141,75 @@ func Execute() {
...
+	case destFound:
+		podmanConfig.URI = dest.URI
+		podmanConfig.Identity = dest.Identity
+		podmanConfig.MachineMode = dest.IsMachine
+		return nil
```
Comment (Luap99) [inline cmd/podman/root.go:206]: same here the return can be removed

File: cmd/podman/root.go [hunk 4]
```diff
@@ -196,45 +264,8 @@ func persistentPreRunE(cmd *cobra.Command, args []string) error {
...
-	if contextConn != nil && contextConn.Changed {
-		service := contextConn.Value.String()
-		if service != "default" {
-			podmanConfig.ContainersConf.Engine.ActiveService = service
-			if err := setupConnection(); err != nil {
-				return err
-			}
-		}
+	if err := setupRemoteConnection(cmd, podmanConfig); err != nil {
+		return err
```
Comment (Luap99) [inline cmd/podman/root.go:268]: lets wrap the error here:
```
fmt.Errorf("setup remote connection: %w", err)
```

File: pkg/domain/infra/runtime_abi.go [hunk 5]
```diff
@@ -36,7 +36,10 @@ func NewImageEngine(facts *entities.PodmanConfig) (entities.ImageEngine, error)
 	case entities.TunnelMode:
 		// TODO: look at me!
 		ctx, err := bindings.NewConnectionWithIdentity(context.Background(), facts.URI, facts.Identity, facts.MachineMode)
-		return &tunnel.ImageEngine{ClientCtx: ctx}, err
+		if err != nil {
+			return nil, fmt.Errorf("%s: %s", err.Error(), facts.URI)
+		}
```
Comment (Luap99) [inline pkg/domain/infra/runtime_abi.go:41]: this breaks error wrapping,
callers that try to check the error with errors.Is() or errorsAs() will no longer match the original error.
For example here: https://github.com/containers/podman/blame/d912e735a30ab89e3b9522338afa5f89a73a85f1/cmd/podman/root.go#L120-L122

You have to change this to
```
fmt.Errorf("%w: %s", err, facts.URI)
```

File: test/system/272-system-connection.bats [hunk 6]
```diff
@@ -180,4 +180,73 @@ $c2[ ]\+tcp://localhost:54321[ ]\+true" \
     run_podman system connection rm mysshconn
 }
 
+# Check the priority of --connection flag vs CONTAINER_HOST env variable
```
Comment (Luap99) [inline test/system/272-system-connection.bats:183]: you can remote this comment as this tests much more as shown below

File: test/system/272-system-connection.bats [hunk 7]
```diff
@@ -180,4 +180,73 @@ $c2[ ]\+tcp://localhost:54321[ ]\+true" \
...
+@test "podman-remote: non-default connection" {
```
Comment (Luap99) [inline test/system/272-system-connection.bats:184]: @edsantiago PTAL at the test, I am not sure if you have a better idea to structure this: the full matrix is quite complex.

File: test/system/272-system-connection.bats [hunk 8]
```diff
@@ -180,4 +180,72 @@ $c2[ ]\+tcp://localhost:54321[ ]\+true" \
...
+
+    # setup
+    run_podman system connection add test1 unix:/run/user/test1/podman/podman.sock   # default=true
+    run_podman system connection add test2 unix:/run/user/test2/podman/podman.sock
+    run_podman system connection add test3 unix:/run/user/test3/podman/podman.sock
+
+    # Test priority of Env variables wrt cli flags
+    # test env variable CONTAINER_CONNECTION wrt --connection cli flag
+    CONTAINER_CONNECTION=test2 run_podman 125 --connection=test3 ps
+    assert "$output" =~ ".*/run/user/test3/podman/podman.sock.*" "Run Podman with connection flag and env variable CONTAINER_CONNECTION"
```
Comment (edsantiago) [inline test/system/272-system-connection.bats:198]: Hint: you don't need `.*` when using `=~`. (Clarification: not at beginning or end. You still need it in the bottommost one. Like, `=~ ".*foo.*"` should just be `=~ "foo"`, but `=~ "foo.*bar"` stays as-is)

File: test/system/272-system-connection.bats [hunk 9]
```diff
@@ -180,4 +180,72 @@ $c2[ ]\+tcp://localhost:54321[ ]\+true" \
...
+    # priority:
+    #   1. cli flags (--connection ,--url ,--context ,--host)
+    #   2. Env variables (CONTAINER_HOST and CONTAINER_CONNECTION)
+    #   3. ActiveService from containers.conf
+    #   4. RemoteURI
+
+    # setup
+    run_podman system connection add test1 unix:/run/user/test1/podman/podman.sock   # default=true
+    run_podman system connection add test2 unix:/run/user/test2/podman/podman.sock
+    run_podman system connection add test3 unix:/run/user/test3/podman/podman.sock
```
Comment (edsantiago) [inline test/system/272-system-connection.bats:193]: I've tried but can't find a way to refactor the tests. However, I think they would be a lot more readable if you
1. rename test1-test2-test3 to "defaultconnection", "env-override", "cmdline-override" or something along those lines; and
2. remove the comments before each assertion, and edit the assertion messages instead.

I can't believe I said "remove comments".

File: cmd/podman/root.go [hunk 10]
```diff
@@ -404,25 +430,20 @@ func stdOutHook() {
...
-	// non configurable option to help ssh dialing
-	podmanConfig.MachineMode = machine
-
 	sshFlagName := "ssh"
 	lFlags.StringVar(&podmanConfig.SSHMode, sshFlagName, string(ssh.GolangMode), "define the ssh mode")
 	_ = cmd.RegisterFlagCompletionFunc(sshFlagName, common.AutocompleteSSH)
 
 	connectionFlagName := "connection"
-	lFlags.StringP(connectionFlagName, "c", srv, "Connection to use for remote Podman service")
+	lFlags.StringP(connectionFlagName, "c", "", "Connection to use for remote Podman service")
```
Comment (rhatdan) [inline cmd/podman/root.go:440]: Why are we hiding this information from the user.  It is useful, when the user executes podman --help

**Comment by mheon** [comment]
Your test seems to be failing.

**Comment by cgiradkar** [comment]
Have refactored the method ```setupRemoteConnection``` and split into 2 parts for populating the rootflags method.
The original method had a switch block which when split, created some complications, hence used a boolean flag to prevent  the fallthrough. Any suggestion to make the code more readable is welcome!

File: cmd/podman/root.go (hunk 10 above)
Comment (cgiradkar) [reply cmd/podman/root.go]: Thanks Dan! I've added it back with some refactored code.
FYI @Luap99

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
/lgtm
Nice work @cgiradkar
