### PR TITLE
libpod: do not Cleanup() more than once

### LINKED ISSUE #18460: --pid host causes podman stop to print oci runtime errors when the container is already stopped
### Issue Description

Podman stop prints error on stderr when it shouldn't, it looks like we try to call the oci runtime every time.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman run --pid host alpine true`
2. `podman stop --all`

Repeat to call podman stop, you will see message every time.

### Describe the results you received

An extra error message from crun on stderr, exit code is still 0
```
2023-05-04T11:05:37.592448Z: error opening file `/run/user/1000/crun/832d948a97ade6e92350c1413c345b7e390909782311684583087d32cb2fea31/status`: No such file or directory
832d948a97ade6e92350c1413c345b7e390909782311684583087d32cb2fea31
```

with runc
```
ERRO[0000] container does not exist                     
e3b02bf539a8e2a407fe2df8d60addc556a8725127d9217577d7a60de9535550
```

### Describe the results you expected

no error message

### podman info output

```yaml
latest @main
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Found in #18442 which shows how important such checks are.

### PR DESCRIPTION
**Pull request by Luap99**
If the container was already cleaned up we should not try to do it again. Podman stop will always try to call Cleanup() if you look at the podman event log and just keep calling podman stop --all you see a cleanup event every time. This is not wanted. Also in case of the host pidns we report a error every single time, see the linked issue.

Fixes #18460

#### Does this PR introduce a user-facing change?

```release-note
Containers created with --pid=host will no longer print errors on podman stop.
```

### CODE REVIEW

File: test/e2e/stop_test.go [hunk 1]
```diff
@@ -126,6 +126,12 @@ var _ = Describe("Podman stop", func() {
 		finalCtrs.WaitWithDefaultTimeout()
 		Expect(finalCtrs).Should(Exit(0))
 		Expect(strings.TrimSpace(finalCtrs.OutputToString())).To(Equal(""))
+
+		// make sure we only have one cleanup event for this container
+		events := podmanTest.Podman([]string{"events", "--since=30s", "--stream=false"})
```
Comment (vrothberg) [inline test/e2e/stop_test.go:131]: Any chance we use a timestamp created at the beginning of the test?

**Comment by Luap99** [comment]
@mheon @vrothberg PTAL

**Review by vrothberg — COMMENTED** [review]
Other than the test nit
LGTM

**Comment by mheon** [comment]
Sure, LGTM.

I have vague concerns that we could somehow get a container in Exited that still had a network namespace associated with it through a cleanup failure, but even in this worst-case the only end result is a small resource leak that should fix itself on restarting the container.

I'll hold off on a hold/lgtm until @vrothberg confirms that the tests are good.
