### PR TITLE
fix(#28429): OCIRuntime field in SpecGenerator is ignored when called through HTTP Rest API

### LINKED ISSUE #28429: OCIRuntime field in SpecGenerator is ignored
### Issue Description

Hi,

When trying to create containers with the `crun-krun` runtime with the API I stumbled accros a bug where the OCIRuntime field is ignored in the final container spec. Looking more carefully with the help of an LLM, it looks like the code [here](https://github.com/containers/podman/blob/main/pkg/specgen/generate/container_create.go#L168C1-L175C3) does not use `s.OCIRuntime` at all, which could explain the behaviour.

### Steps to reproduce the issue

1. Create a container with OCIRuntime set to a valid runtime different from the default one
2. Observe that the container uses the default runtime from containers.conf instead

### Describe the results you received

The created container uses the default runtime from containers.conf and not the runtime as asked, but creating the same container with `podman` cli and the `--runtime` flag works as expected

### Describe the results you expected

Container using the specified runtime.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.43.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2.1.13+ds1-2_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: unknown'
  cpuUtilization:
    idlePercent: 94.25
    systemPercent: 2.64
    userPercent: 3.11
  cpus: 16
  databaseBackend: sqlite
  distribution:
    codename: forky
    distribution: debian
    version: unknown
  eventLogger: journald
  freeLocks: 2027
  hostname: work-laptop
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.19.8+deb14-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 8174960640
  memTotal: 32903397376
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    defaultNetwork: podman
    dns:
      package: aardvark-dns_1.16.0-2_amd64
      path: /usr/lib/podman/aardvark-dns
      version: aardvark-dns 1.16.0
    package: netavark_1.16.1-3.1_amd64
    path: /usr/lib/podman/netavark
    version: netavark 1.16.1
  ociRuntime:
    name: crun
    package: crun_1.26-1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.26
      commit: 3241e671f92c33b0c003cd7de319e4f32add6231
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt_0.0~git20260120.386b5f5-1_amd64
    version: |
      pasta 0.0~git20260120.386b5f5-1
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.3.3-1_amd64
    version: |-
      slirp4netns version 1.3.3
      commit: 944fa94090e1fd1312232cbc0e6b43585553d824
      libslirp: 4.9.1
      SLIRP_CONFIG_VERSION_MAX: 6
      libseccomp: 2.6.0
  swapFree: 25220345856
  swapTotal: 25220345856
  uptime: 3h 56m 20.00s (Approximately 0.12 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/bogier/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/bogier/.local/share/containers/storage
  graphRootAllocated: 464207183872
  graphRootUsed: 205079375872
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 138
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/bogier/.local/share/containers/storage/volumes
version:
  APIVersion: 5.8.1
  BuildOrigin: Debian
  Built: 1774364999
  BuiltTime: Tue Mar 24 16:09:59 2026
  GitCommit: ""
  GoVersion: go1.26.1
  Os: linux
  OsArch: linux/amd64
  Version: 5.8.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by aadi58002**
#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [X] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [X] Referenced issues using `Fixes: #28429 ` in commit message (if applicable)
- [X] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [X] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [X] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

Fixes: #28429

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

File: pkg/specgen/generate/container_create.go [hunk 1]
```diff
@@ -169,7 +169,9 @@ func MakeContainer(ctx context.Context, rt *libpod.Runtime, s *specgen.SpecGener
 		ociRuntimeVariant := rtc.Engine.ImagePlatformToRuntime(imageData.Os, imageData.Architecture)
 		// Don't unnecessarily set and invoke additional libpod
 		// option if OCI runtime is still default.
-		if ociRuntimeVariant != rtc.Engine.OCIRuntime {
+		if s.OCIRuntime != rtc.Engine.OCIRuntime {
```
Comment (Luap99) [inline pkg/specgen/generate/container_create.go]: that check triggers even if OCIRuntime is empty.

Generally speaking if a specific runtime is requested here we should use it so just checking if OCIRuntime is not empty should be the correct thing

And that should be done outside the imageData branch, this could be used with a rootfs container.

File: test/apiv2/20-containers.at [hunk 2]
```diff
@@ -915,3 +915,32 @@ t POST containers/create?platform=linux/aarch64 \
   Image=$IMAGE \
   404
 podman rmi -f $IMAGE
+
+# test apiv2 create container with oci_runtime option :- https://github.com/containers/podman/issues/28429
+# --data '{"Image":"quay.io/libpod/some:thing","oci_runtime": "runc"}'
+# --data '{"Image":"quay.io/libpod/some:thing","oci_runtime": "crun"}'
+
+podman pull $IMAGE
```
Comment (Luap99) [inline test/apiv2/20-containers.at]: to avoid unnecessary pull this should be moved above before we delete the image

File: test/apiv2/20-containers.at [hunk 3]
```diff
@@ -915,3 +915,32 @@ t POST containers/create?platform=linux/aarch64 \
...
+t POST libpod/containers/create \
+  Image=$IMAGE \
+  "oci_runtime"="crun" \
+  201 \
+  .Id~[0-9a-f]\\{64\\}
+cid_crun=$(jq -r '.Id' <<<"$output")
+echo $cid_crun
+t GET libpod/containers/$cid_crun/json 200 \
+  .OCIRuntime="crun"
+t DELETE containers/$cid_crun 204
```
Comment (Luap99) [inline test/apiv2/20-containers.at]: to avoid duplication this could be a loop over crun runc

**Review by Luap99 — CHANGES_REQUESTED** [review]
Thanks for the PR, please squash the commits into one and give it a proper commit message, the `Fixes: #28429` part should be at the end of the body not the title.

File: test/apiv2/20-containers.at (hunk 2 above)
Comment (aadi58002) [reply test/apiv2/20-containers.at]: Thanks for the comment. Just saw that the image is already being pulled at the top and didn't need to pull it again

**Comment by Luap99** [comment]
@aadi58002 please run the API tests locally, as long as they fail we cannot merge

**Review by Honny1 — APPROVED** [review]
LGTM

**Review by Luap99 — APPROVED** [review]
LGTM

**Comment by giuseppe** [comment]
does it make sense to backport to 5.8?  I was playing with OpenShell trying to run containers with different runtimes, but it doesn't work on 5.8 since OCIRuntime is ignored
