### PR TITLE
Ensure podman temp directory is created on Start as well.

### LINKED ISSUE #21288: `podman machine start` fails after reboot (recurrence of #10824 but with the `applehv` provider.)
### Issue Description

It appears that the previous issue (#10824) which seemed to be specific to the qemu machine provider is now reoccurring with the `applehv` machine provider. Once you `podman machine init` and `podman machine start`, if you then reboot the host, `$TMPDIR` is purged, and the paths in `.config/containers/podman/machine/applehv/podman-machine-default.json` referring to the `podman ` subdirectory of `$TMPDIR` become invalid. As requested in the previous ticket, I've tried `podman machine stop` before rebooting. The result is the same.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Install podman and dependencies (vfkit, gvproxy, etc.)
2. Enable the `applehv` provider via `.config/containers/containers.conf`.
3. `podman machine init --now` (or `init` + `start`.)
4. `podman machine stop` (optionally.)
5. Reboot the host.
6. `podman machine start`.

### Describe the results you received

`podman --log-level=debug machine start` returns a failure to start gvproxy due to missing path. Output below:

```
INFO[0000] podman filtering at log level debug
DEBU[0000] Using Podman machine with `applehv` virtualization provider
DEBU[0000] connection refused: http://localhost:8081/vm/state
Starting machine "podman-machine-default"
DEBU[0000] connection refused: http://localhost:8081/vm/state
DEBU[0000] gvproxy binary being used: /Users/nn/.sandbox/libexec/podman/gvproxy
DEBU[0000] [-debug -mtu 1500 -ssh-port 51540 -listen-vfkit unixgram:///var/folders/cv/w6b1bgq95x35fzl9y6c10kl40000gn/T/podman/gvproxy.sock -forward-dest /run/user/501/podman/podman.sock -forward-user core -forward-identity /Users/nn/.ssh/podman-machine-default -forward-sock /Users/nn/.local/share/containers/podman/machine/applehv/podman.sock -pid-file /var/folders/cv/w6b1bgq95x35fzl9y6c10kl40000gn/T/podman/gvproxy.pid]
DEBU[0000] gvproxy unixgram socket "/var/folders/cv/w6b1bgq95x35fzl9y6c10kl40000gn/T/podman/gvproxy.sock" not found: stat /var/folders/cv/w6b1bgq95x35fzl9y6c10kl40000gn/T/podman/gvproxy.sock: no such file or directory
Error: gvproxy exited unexpectedly with exit code 1
DEBU[0000] Shutting down engines
```

### Describe the results you expected

`podman machine start` returns successfully.

### podman info output

```yaml
OS: darwin/arm64
provider: applehv
version: 4.8.3

This issue pertains to a `podman machine start` failure, so the above is the only non-error output.
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Host is macOS Sonoma (14.3).
Host architecture is aarch64/arm64.
The variant is the Apple M3 Pro which necessitated the use of the `applehv` provider (due to upstream qemu issues with EDK2 and the shim.)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kaorihinata**
`getRuntimeDir()` (which is also responsible for creating TMPDIR if it doesn't exist) was being called on `Init()` but not on `Start()` which meant that after the host was restarted and TMPDIR was wiped, `startHostNetworking()` would try to start gvproxy and immediately bail.

Fixes #21288 

#### Does this PR introduce a user-facing change?

```release-note
None
```
[NO NEW TESTS NEEDED]

### CODE REVIEW

**Comment by kaorihinata** [comment]
Building succeeds, but not sure how, or even if tests should be addressed at this juncture. Brent Baude originally changed how `getRuntimeDir()` worked 3 months ago, and the change specifically said no new tests. I checked the test directory and there's nothing to jump off of for testing `machine` beyond `init`. Any recommendations?

File: pkg/machine/applehv/machine.go [hunk 1]
```diff
@@ -572,6 +572,11 @@ func (m *MacMachine) Start(name string, opts machine.StartOptions) error {
 		return machine.ErrVMAlreadyRunning
 	}
 
+	_, err = m.getRuntimeDir()
```
Comment (rhatdan) [inline pkg/machine/applehv/machine.go:575]: Nit: could you do this as a single line
```
if _, err := m.getRuntimeDir(); err != nil {
     return err
}
```

**Comment by rhatdan** [comment]
Make the small change and repush, I added the NO NEW TESTS NEEDED flag.

**Comment by rhatdan** [comment]
Thanks @kaorihinata

**Comment by rhatdan** [comment]
LGTM
/approve
@containers/podman-maintainers PTAL

**Comment by mheon** [comment]
/lgtm
/hold
Waiting on a flake to rerun
