### PR TITLE
fix wsl install workflow on machine init command

### LINKED ISSUE #25523: Automatic installation of WSL fails
### Issue Description

If WSL isn't installed, and a user tries to run `podman machine init` on Windows, Podman tries to install WSL automatically. This flow is currently broken.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Disable the Windows feature `VirtualMachinePlatform` and reboot
2. (until #25522 get merged) Build podman from PR #25522  
3. Run `podman machine init`

### Describe the results you received

When `machine init` is run from an Admin terminal, the command fails with the error `Error: could not enable Virtual Machine Feature: command dism [/online /enable-feature /featurename:VirtualMachinePlatform /all /norestart] failed: exit status 3010`.

When `machine init` is run from a non-Admin terminal, the command fails because `podman machine init` is re-executed with elevated privileges and the hidden parameter `--reexec`. It fails when it tries to recreate the system connection with the same name (the system connection was already created before the WSL check).

### Describe the results you expected

WSL should be enabled successfully

### podman info output

```yaml
OS: windows/amd64
provider: wsl
version: 5.5.0-dev

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v5.5.0/libpod/_ping": dial unix /run/podman/podman.sock: connect: A socket operation encountered a dead network.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by lstocchi**
this patch changes how the detection of wsl works. The old way of using wsl --status command output to detect some missing features required by WSL is not fully reliable. WSL checks if the wsl feature is enabled and if the vmcompute service do exist. However, this is not enough to identify if the virtual machine platform feature is enabled. The vmcompute service could exist because it has been installed by other tools or it could exist but being stopped.

The way proposed by this patch is to try execute the import command and, if it fails, check the error and if it is related to the Host Compute Service try to install all features required by WSL.

The flow is the same as before, the user is asked to execute the podman machine init command with elevated privileges. Eventually, after enabling WSL and VMP features, the user is asked to reboot the machine.

When the machine restarts, the powershell gets invoked again and execute the command init.

The code also fixes some issues that could cause misbehaviors when invoking recursively the elevated shell, like an unreleased lock, or a missing file.

it fixes #25523

```release-note
Fix the check and the automatic installation of WSL2 on Windows when the command `podman machine init` is executed.
```

### CODE REVIEW

File: pkg/machine/wsl/machine.go [hunk 1]
```diff
@@ -95,7 +94,21 @@ func provisionWSLDist(name string, imagePath string, prompt string) (string, err
 
 	dist := env.WithPodmanPrefix(name)
 	fmt.Println(prompt)
-	if err = runCmdPassThrough("wsl", "--import", dist, distTarget, imagePath, "--version", "2"); err != nil {
+
+	// Run WSL import and capture output to check for known errors
+	// If virtual machine platform feature is not enabled it should fail with
+	// Error code: Wsl/Service/RegisterDistro/CreateVm/HCS/ERROR_NOT_SUPPORTED
```
Comment (l0rd) [inline pkg/machine/wsl/machine.go:100]: You should check more errors. For example I got `Wsl/Service/RegisterDistro/CreateVm/HCS/HCS_E_SERVICE_NOT_AVAILABLE` (when all features are turned off).

**Review by l0rd — COMMENTED** [review]
`.\winmake lint` is failing. It's not related to this PR but you need to rebase to current main branch to make it work.

File: pkg/machine/shim/host.go [hunk 2]
```diff
@@ -264,6 +267,11 @@ func Init(opts machineDefine.InitOptions, mp vmconfigs.VMProvider) error {
 	}
 	ignBuilder.WithUnit(readyUnit)
 
+	err = mp.CreateVM(createOpts, mc, &ignBuilder)
+	if err != nil {
+		return err
+	}
```
[the remark this answers is not in the document]
Comment (lstocchi) [reply pkg/machine/shim/host.go]: Added a comment. Basically i want to avoid creating any resources before the CreateVM that could be responsible to invoke a new init that will perform the setup. So i switched the order with the `AddSSHConnectionsToPodmanSocket`

File: pkg/machine/wsl/machine.go [hunk 3]
```diff
@@ -473,24 +415,14 @@ func getElevatedOutputFileWrite() (*os.File, error) {
...
-}
-
 func truncateElevatedOutputFile() error {
 	name, err := getElevatedOutputFileName()
 	if err != nil {
 		return err
 	}
 
-	return os.Truncate(name, 0)
+	_, err = os.Create(name)
```
[the remark this answers is not in the document]
Comment (lstocchi) [reply pkg/machine/wsl/machine.go:429]: renamed 👍

**Comment by lstocchi** [comment]
> @lstocchi, thank you for this PR. The approach is the right one. I hope you find a way to release the machine lock later in the process (i.e., before restarting in elevated mode), or we should consider another way to check for WSL before the machine lock is acquired. 

it's quite a mess with the current workflow. I tried not to change the code too much so if you have any suggestions, feel free to let me know.

> It's also important to find out the different error codes that can be returned when the features are missing (see [this comment too](https://github.com/containers/podman/issues/25523#issuecomment-2789133982)), but this is probably less critical.

Yes i agree, if we find an agreement on this PR, we could always enhance the list of errors related to WSL features later on when users face them. BTW I'll give a look at the WSL source code to see if i can find out some other known errors

**Comment by l0rd** [comment]
I tried again to run `machine init` on my laptop with the Virtual Machine Platform disabled, and it behaved as expected: WSL got installed, etc. I will continue the review tomorrow.

File: pkg/machine/wsl/machine.go (hunk 1 above)
Comment (l0rd) [reply pkg/machine/wsl/machine.go:100]: You may want to update the comment here

File: pkg/machine/define/errors.go [hunk 4]
```diff
@@ -8,9 +8,10 @@ import (
 )
 
 var (
-	ErrWrongState      = errors.New("VM in wrong state to perform action")
-	ErrVMAlreadyExists = errors.New("VM already exists")
-	ErrNotImplemented  = errors.New("functionality not implemented")
+	ErrWrongState          = errors.New("VM in wrong state to perform action")
+	ErrVMAlreadyExists     = errors.New("VM already exists")
+	ErrNotImplemented      = errors.New("functionality not implemented")
+	ErrInitRelaunchAttempt = errors.New("stopping execution: 'init' relaunched with --re-exec flag to reinitialize the VM")
```
Comment (l0rd) [inline pkg/machine/define/errors.go]: `--re-exec` should be `--reexec`

File: pkg/machine/shim/host.go [hunk 5]
```diff
@@ -101,7 +101,13 @@ func Init(opts machineDefine.InitOptions, mp vmconfigs.VMProvider) error {
 		return err
 	}
 	machineLock.Lock()
-	defer machineLock.Unlock()
+	unlock := true
+	defer func() {
+		// The machine lock is only unlocked if the machine was not re-launched
+		if unlock {
```
Comment (l0rd) [inline pkg/machine/shim/host.go]: Instead of introducing the new variable `unlock`, can we use `opt.ReExec` instead? Maybe commenting that `machine init --reexec` is executed by another `machine init` and we require to keep the machine resource locked.

File: pkg/machine/wsl/util_windows.go [hunk 6]
```diff
@@ -239,6 +239,10 @@ func reboot() error {
 		return fmt.Errorf("cannot reboot system: %w", err)
 	}
 
+	// when rebooting we exit with an error code to stop podman execution.
+	// If we don't do this, podman keeps creating the system connection + config file for the machine
+	// and the init command that gets re-executed after the reboot will fail
+	os.Exit(ErrorSuccessRebootRequired)
```
Comment (l0rd) [inline pkg/machine/wsl/util_windows.go]: It would be better to exit gracefully instead of exit with an error (c.f. comment in `cmd\podman\machine\init.go` before the call to `shim.Init()`).

File: pkg/machine/shim/host.go (hunk 5 above)
Comment (l0rd) [reply pkg/machine/shim/host.go]: And if `reexec` doesn't need to write any resource, it would be even better to avoid acquiring the lock.

File: pkg/machine/wsl/util_windows.go (hunk 6 above)
Comment (l0rd) [reply pkg/machine/wsl/util_windows.go]: And we should invoke `addRunOnceRegistryEntry` before asking users if they are ok to reboot (so that machine init is executed in any case at reboot).

File: pkg/machine/shim/host.go (hunk 5 above)
Comment (lstocchi) [reply pkg/machine/shim/host.go]: done. I was avoiding it because i thought the user could also invoke `podman machine init --reexec` manually and in that case the machine was not locked... but that flag is not even shown in the help message so it should not be an issue

File: pkg/machine/wsl/util_windows.go (hunk 6 above)
Comment (lstocchi) [reply pkg/machine/wsl/util_windows.go]: updated. 
For the first point i handled it in the init command as suggested.
For the second i moved it and added a `removeRunOnceRegistryEntry` if the reboot is cancelled by the user

**Comment by lstocchi** [comment]
> I have added some new comments. Other suggestions:
> 
> 1. avoiding pulling the WSL machine OS image at every invocation of `machine init` (3 times) but only the first time
> 2. better rendering of the progress bars when the Windows features are installed (I am not sure if we can do much)
> 3. provide a message to the user mentioning that podman won't be available until Windows is rebooted (instead of showing an error). This is particularly important if the user accepts to install WSL but refuse to boot the machine imediately.
> 
> None of these are blocking from my point view for this PR (automatically WSL installation is fixed) but I would apreciate if you could work at least on avoiding returning an error before the reboot.

I would open two separate issues for the first 2 points. 
Mainly the first one is quite intrusive. I guess it would change the workflow for other OSes as well

File: pkg/machine/wsl/util_windows.go [hunk 7]
```diff
@@ -216,20 +217,23 @@ func reboot() error {
...
+		return err
+	}
+
 	message := "To continue the process of enabling WSL, the system needs to reboot. " +
 		"Alternatively, you can cancel and reboot manually\n\n" +
 		"After rebooting, please wait a minute or two for podman machine to relaunch and continue installing."
 
 	if MessageBox(message, "Podman Machine", false) != 1 {
 		fmt.Println("Reboot is required to continue installation, please reboot at your convenience")
+		if err := removeRunOnceRegistryEntry(); err != nil {
```
Comment (l0rd) [inline pkg/machine/wsl/util_windows.go]: If you remove the entry from the registry, then `podman machine init` won't run at restart?

Comment (lstocchi) [reply pkg/machine/wsl/util_windows.go]: No, but this is when the user needs to reboot manually. I'm removing that on purpose bc, at that point, it's up to them to execute the command again imo. If you cancel the automatic reboot, you also cancel the init on restart

Comment (l0rd) [reply pkg/machine/wsl/util_windows.go]: Asking users to re-run `podman machine init` a second time is bad UX. And the message states that installation continues after rebooting (even if reboot is done manually):

> After rebooting, please wait a minute or two for podman machine to relaunch and continue installing.

Comment (lstocchi) [reply pkg/machine/wsl/util_windows.go]: I don't fully agree as if you stop the automatic reboot maybe working on podman is not your priority anymore. Maybe you reboot the machine few hours later/the day after and you even forgot about this action 🤷‍♂️ 
BTW removed it as it always worked this way

Comment (l0rd) [reply pkg/machine/wsl/util_windows.go]: Thank you.

**Comment by l0rd** [comment]
/lgtm
/hold

@Luap99 @baude PTAL

@lstocchi you should add a release notes section in the description. Something like:

````
```release-note
Fix the check and the automatic installation of WSL2 on Windows when the command `podman machine init` is executed.
```
````

**Review by l0rd — APPROVED** [review]
