### PR TITLE
libpod: fix data race on deferredErr in attachExecHTTP

### LINKED ISSUE #28277: hijackWriteErrorAndClose use in podman service is unsound
seen once in CI

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x69b8a0]

goroutine 14099 [running]:
net.(*OpError).Unwrap(0x2c31560?)
	/usr/lib/golang/src/net/net.go:499
errors.is({0x1f6eee0?, 0x0?}, {0x1f6e060, 0x2c2cab0}, 0x1)
	/usr/lib/golang/src/errors/wrap.go:63 +0x13c
errors.Is({0x1f6eee0, 0x0}, {0x1f6e060, 0x2c2cab0})
	/usr/lib/golang/src/errors/wrap.go:50 +0x7e
github.com/containers/podman/v6/libpod.hijackWriteError({0x1f6eee0, 0x0}, {0xc00077ee80, 0x40}, 0x0, 0xc0008e78b0)
	/var/tmp/go/src/github.com/containers/podman/libpod/util.go:130 +0x79
github.com/containers/podman/v6/libpod.hijackWriteErrorAndClose({0x1f6eee0?, 0x0?}, {0xc00077ee80, 0x40}, 0x0?, {0x7f404c6261d0, 0xc0005a4b48}, 0xc000057a01?)
	/var/tmp/go/src/github.com/containers/podman/libpod/util.go:152 +0x47
github.com/containers/podman/v6/libpod.attachExecHTTP.func3()
	/var/tmp/go/src/github.com/containers/podman/libpod/oci_conmon_exec_common.go:612 +0x248
created by github.com/containers/podman/v6/libpod.attachExecHTTP in goroutine 14033
	/var/tmp/go/src/github.com/containers/podman/libpod/oci_conmon_exec_common.go:593 +0xab9
```
https://api.cirrus-ci.com/v1/artifact/task/5261985647951872/html/sys-remote-fedora-43-rootless-host.log.html
https://api.cirrus-ci.com/v1/artifact/task/5261985647951872/server_log/podman-server.log

Looking at this the stack trace seems weird, nil panic in errors.Is()?!

However a closer look shows the first error argument with the address of `{0x1f6eee0, 0x0}`, this is the error interface, like any interface it has two addresses, the itable and the data, so somehow the table is set but the data is a nil pointer. Hence once the function is called with the nil pointer it failed.

Now the question how does the interface end up with such an seemingly invalid assignment?

Looking at hijackWriteErrorAndClose() the first error argument is deferredErr which is the return value from the outer function while hijackWriteErrorAndClose() is called within another goroutine.

So my guess the outer function write the value to the deferredErr while the hijackWriteErrorAndClose accessed it from the other goroutine causing unsafe memory access as the interface assignment is not concurrent safe

> This means that races on multiword data structures can lead to inconsistent values not corresponding to a single write. When the values depend on the consistency of internal (pointer, length) or (pointer, type) pairs, as can be the case for interface values, maps, slices, and strings in most Go implementations, such races can in turn lead to arbitrary memory corruption.

https://go.dev/ref/mem

### PR DESCRIPTION
**Pull request by crawfordxx**
## Description

`ExecContainerHTTP` returns `attachChan` to its caller *before* `attachExecHTTP` has finished. The caller holds a deferred `close(holdConnOpen)` that fires when the calling function returns — which can happen while `attachExecHTTP` is still running through its own deferred cleanup functions.

This creates a data race: the goroutine inside `attachExecHTTP` reads the named return `deferredErr` after `<-holdConnOpen` unblocks, but `attachExecHTTP` may still be assigning `deferredErr` (directly or via deferred functions) at that moment. Concurrent access to an interface value without synchronization is unsound per the Go memory model and can produce torn reads (non-nil type with nil data pointer), leading to the nil-pointer panic observed in CI:

```
panic: runtime error: invalid memory address or nil pointer dereference
net.(*OpError).Unwrap(0x2c31560?)
errors.is({0x1f6eee0?, 0x0?}, ...)   ← interface type set, data nil
github.com/containers/podman/v6/libpod.hijackWriteError(...)
github.com/containers/podman/v6/libpod.attachExecHTTP.func3()
```

## Fix

Add a `done` channel that is closed by the first-registered (last-to-run) deferred function in `attachExecHTTP`, i.e. after every other cleanup defer has completed. The goroutine now waits for both `<-holdConnOpen` and `<-done` before reading `deferredErr`. This establishes a proper happens-before relationship between the final write to `deferredErr` and the goroutine's read.

Fixes #28277

## Testing

The race is intermittent and only reproducible under CI load. The fix is provably correct by Go memory model analysis: `close(done)` happens-after the last write to `deferredErr`, and `<-done` happens-before the goroutine's read.

### CODE REVIEW

**Comment by Honny1** [comment]
Thanks for the contribution! The fix looks correct to me. But I have a question: Did you consider using a `sync.Mutex` to protect `deferredErr` instead of a channel? Could you explain why you went with the channel approach?

> Adding `No New Test` Label.

**Comment by crawfordxx** [comment]
The channel approach fits the problem more naturally here.  is written by multiple deferred functions in  (directly, and through ) — protecting those with a  would mean adding lock/unlock around every assignment site scattered across the deferred stack, which is fragile.

More importantly, what we actually need is not mutual exclusion but *completion signaling*: the goroutine should not read  until all cleanup code in  has finished running. A channel closed by the first-registered (last-to-run) defer precisely expresses that: `close(done)` happens-after every other deferred write, and `<-done` happens-before the read. This directly maps to the Go memory model's happens-before guarantee we need.

A `sync.WaitGroup` would also work, but it is more verbose for a single-event signal. A `sync.Mutex` would work too, but it would require touching every write site and doesn't convey the intent as clearly.

**Review by Honny1 — APPROVED** [review]
Thanks, LGTM.

File: libpod/oci_conmon_exec_common.go [hunk 1]
```diff
@@ -511,6 +511,13 @@ func attachExecHTTP(c *Container, sessionID string, r *http.Request, w http.Resp
 		return err
 	}
 
+	// done is closed when this function fully returns (including all deferred
+	// cleanup). The goroutine below waits on done before reading deferredErr
+	// to avoid a data race: holdConnOpen may be closed by the caller while
+	// this function's deferred functions are still running.
+	done := make(chan struct{})
```
Comment (giuseppe) [inline libpod/oci_conmon_exec_common.go]: can we use a chan to pass the error instead?  So it is clearer what we are waiting for

Comment (crawfordxx) [reply libpod/oci_conmon_exec_common.go]: Good point — updated in the latest commit to use `errCh := make(chan error, 1)` with `defer func() { errCh <- deferredErr }()`. The goroutine now reads `<-errCh` directly instead of the two-step `<-done` + reading the named return variable, which makes the intent clearer.

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by Honny1** [comment]
LGTM! Once you fix the DCO and squash commits, we can merge.
