### PR TITLE
Hide secrets from container inspect command

### LINKED ISSUE #23788: Podman secrets value of type `env` revealed in container inspection
### Issue Description

Values of secrets attached to containers with `type=env` option are available on container inspection (running or exited). 
It is not the case with secrets attached with `type=mount` option.

I do not know if this is expected per specs?

### Steps to reproduce the issue

Steps to reproduce the issue
1. `printf 'secret value' | podman secret create mysecret -`
2. `podman container run --rm --secret mysecret,type=env -d alpine sleep 300`
3. `podman container inspect -l --format '{{ .Config.Env }}'`

### Describe the results you received

The value of the secret is disclosed on container inspection in the `Config.Env` attribute: `[... mysecret=secret value]`
It is not listed in the `Config.Secrets` attribute. 

### Describe the results you expected

I’d expect it to **not** appear in the `Config.Env` attribute.
I’d expect to find it (undisclosed) in the `Config.Secrets` attribute, like mount type secrets are. 

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.37.1
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.10-1.fc40.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: '
  cpuUtilization:
    idlePercent: 99
    systemPercent: 0.31
    userPercent: 0.69
  cpus: 16
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: workstation
    version: "40"
  eventLogger: journald
  freeLocks: 2015
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 589824
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 589824
      size: 65536
  kernel: 6.10.6-200.fc40.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 372310016
  memTotal: 14339981312
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.12.1-1.fc40.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.12.1
    package: netavark-1.12.1-1.fc40.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.12.1
  ociRuntime:
    name: crun
    package: crun-1.15-1.fc40.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.15
      commit: e6eacaf4034e84185fd8780ac9262bbf57082278
      rundir: /run/user/1001/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240821.g1d6142f-1.fc40.x86_64
    version: |
      pasta 0^20240821.g1d6142f-1.fc40.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: false
    path: /run/user/1001/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8586260480
  swapTotal: 8589930496
  uptime: 3h 28m 1.00s (Approximately 0.12 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /home/bmenant/.config/containers/storage.conf
  containerStore:
    number: 16
    paused: 0
    running: 0
    stopped: 16
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/bmenant/.local/share/containers/storage
  graphRootAllocated: 498387124224
  graphRootUsed: 115184447488
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 134
  runRoot: /run/user/1001/containers
  transientStore: false
  volumePath: /home/bmenant/.local/share/containers/storage/volumes
version:
  APIVersion: 5.2.1
  Built: 1723593600
  BuiltTime: Wed Aug 14 02:00:00 2024
  GitCommit: ""
  GoVersion: go1.22.5
  Os: linux
  OsArch: linux/amd64
  Version: 5.2.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by auyer**
Secret mounted as an env variables are exposed by the `podman container inspect` command.

This change replaces the content of the env var by `*******`.

To reproduce this, follow the commands reported by the original issue:
```bash
printf 'secret value' | podman secret create mysecret -
podman container run --rm --secret mysecret,type=env -d alpine sleep 300
podman container inspect -l --format '{{ .Config.Env }}'
```

Fixes #23788

```release-note
Fixed secrets being exposed by `podman container inspect` when mounted as an env var
```

### CODE REVIEW

File: libpod/container_inspect.go [hunk 1]
```diff
@@ -372,6 +372,16 @@ func (c *Container) generateInspectContainerConfig(spec *spec.Spec) *define.Insp
...
 		ctrConfig.Env = append([]string{}, spec.Process.Env...)
+		envSecrets := c.config.ContainerMiscConfig.EnvSecrets
+
+		for k := range envSecrets {
+			for i, v := range ctrConfig.Env {
+				if strings.HasPrefix(v, k+"=") {
+					ctrConfig.Env[i] = k + "=*******"
+				}
+			}
+		}
```
Comment (Luap99) [inline libpod/container_inspect.go:383]: Given EnvSecrets is a map it would be more efficient to loop over ctrConfig.Env first and then just lookup the key in EnvSecrets

File: test/e2e/container_inspect_test.go [hunk 2]
```diff
@@ -82,4 +82,24 @@ var _ = Describe("Podman container inspect", func() {
 		Expect(data[0].HostConfig.VolumesFrom).To(Equal([]string{volsctr}))
 		Expect(data[0].Config.Annotations[define.VolumesFromAnnotation]).To(Equal(volsctr))
 	})
+
+	It("podman inspect hides secrets mounted to env", func() {
+		secretName := "mysecret"
+		secretValue := "mysecretValue"
+
+		session := podmanTest.Podman([]string{"secret", "create", secretName, secretValue})
```
Comment (Luap99) [inline test/e2e/container_inspect_test.go:90]: Th env value is read from a file or stidn so the second arg is wrong.

File: test/e2e/container_inspect_test.go [hunk 3]
```diff
@@ -82,4 +82,24 @@ var _ = Describe("Podman container inspect", func() {
...
+
+		name := "testcon"
+		session = podmanTest.Podman([]string{"run", "--secret", fmt.Sprintf("%s,type=env", secretName), "--name", name, CITEST_IMAGE})
+		session.WaitWithDefaultTimeout()
+		Expect(session).Should(ExitCleanly())
+
+		data := podmanTest.InspectContainer(name)
+		Expect(data).To(HaveLen(1))
+		Expect(data[0].Config.Env).To(HaveLen(1))
+		Expect(data[0].Config.Env[0]).To(HavePrefix(secretName+"="), Not(HaveSuffix(secretValue)))
```
Comment (Luap99) [inline test/e2e/container_inspect_test.go:103]: This isn't doing what you think. The second argument to To() is a description not a a matcher so the `Not(HaveSuffix(...))` part is not checked.
In general it is always best to do exact matches, i.e. `Equal(secretName+"=*******")`

**Review by Luap99 — COMMENTED** [review]
I am not sure if this breaks anyone but I agree it seems reasonable to have the env value hidden like this by default. @mheon @ashley-cui opinions? 

And please squash your commits into one.

**Comment by auyer** [comment]
Hi, thanks. 
I will squash the commits. 
I was unable to run the e2e tests in my machines (and found no assistance in Matrix or irc). So I created the draft PR to at least see the test results (I'm not too familiar with Ginkgo).

**Comment by ashley-cui** [comment]
> I am not sure if this breaks anyone but I agree it seems reasonable to have the env value hidden like this by default. @mheon @ashley-cui opinions?

Probably a good idea, thanks!

**Comment by mheon** [comment]
I'm in favor, seems incorrect to be displaying these in inspect output.

**Comment by rhatdan** [comment]
I agree. `podman secret inspect` hides it by default as well, and has a --showsecret option.

**Comment by auyer** [comment]
Thanks for the input. I applied the changes and fixes my tests. All commits squashed into one.
Let me know if I should make other changes (maybe move this elsewhere?), or if can help with anything else.

> What is the error/problem?

I was unable to run the tests in my Arch system. But I booted a Fedora machine and it worked fine.

In Arch, I saw this error:
```
configure.ac:34: error: AM_INIT_AUTOMAKE expanded multiple times
/usr/share/aclocal-1.17/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:19: the top level
/usr/share/aclocal-1.17/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:34: the top level
autom4te: error: /usr/bin/m4 failed with exit status: 1
aclocal: error: /usr/bin/autom4te failed with exit status: 1
autoreconf: error: aclocal failed with exit status: 1
```
If I track it down, I'll open an issue/PR about it.

Thanks!

File: test/e2e/container_inspect_test.go [hunk 4]
```diff
@@ -78,8 +78,28 @@ var _ = Describe("Podman container inspect", func() {
 		Expect(session).Should(ExitCleanly())
 
 		data := podmanTest.InspectContainer(ctr2)
-		Expect(data).To(HaveLen(1))
```
Comment (Luap99) [inline test/e2e/container_inspect_test.go:81]: This should not be removed.

File: test/e2e/container_inspect_test.go [hunk 5]
```diff
@@ -14,7 +15,6 @@ import (
 )
 
 var _ = Describe("Podman container inspect", func() {
-
```
Comment (Luap99) [inline test/e2e/container_inspect_test.go:17]: unnecessary whiteline change (not blocking but best to avoid changes these unrelated things)

**Review by Luap99 — CHANGES_REQUESTED** [review]

File: test/e2e/container_inspect_test.go (hunk 4 above)
Comment (auyer) [reply test/e2e/container_inspect_test.go]: Oops, this should not have been committed.
While at it, I found no way to pass the secret value with stdin, so I used a file. attribute. Do know a way ?

File: test/e2e/container_inspect_test.go (hunk 5 above)
Comment (auyer) [reply test/e2e/container_inspect_test.go]: Sorry, auto format did it, and I missed it.

**Review by Luap99 — APPROVED** [review]
LGTM
