### PR TITLE
libpod: stop containers with --restart=always

### LINKED ISSUE #18259: restart=always not properly working with podman stop
### Issue Description

Another bug found in my ginkgov2 work. `podman kube play` seems to configure the pod/container in a different way which causes `podman stop --all` to fail. It is a race condition I see quite a lot in the CI logs, however I can reproduce locally in about 1 out of 3 tries. 

### Steps to reproduce the issue

Steps to reproduce the issue
1. create yaml file
```
$ cat > t.yaml <<EOF
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-04-18T16:58:12Z"
  labels:
    app: test
  name: test
spec:
  containers:
  - command:
    - ip
    - a
    image: docker.io/library/alpine:latest
    name: laughinghaibt
EOF
```
2. run `bin/podman kube play t.yaml && bin/podman stop --all  && bin/podman rm -fa`
Note this is a flake so you may need to run into several times until it fails.

### Describe the results you received

podman stop fails and exits with 125
```
Pod:
2cde8e2fc327ebc2444339244ead6b7bb31693c99e8d4f45cb8fc4711b239822
Container:
01552f3338e7a0f9d04b6519d213983dccceefdb4ab00a5708cda081173b0311

4bc7eecf0816790bec3675f2f68950f8a49b0430a855f7a5706209b927f249c1
Error: cannot get namespace path unless container 4bc7eecf0816790bec3675f2f68950f8a49b0430a855f7a5706209b927f249c1 is running: container is stopped
```

### Describe the results you expected

Podman stop should work.

### podman info output

```yaml
latest main branch
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

_No response_

### Additional information

CI log: https://api.cirrus-ci.com/v1/artifact/task/5261073197039616/html/int-podman-debian-12-root-host-boltdb.log.html#t--podman-generate-kube-privileged-container--1
search for `cannot get namespace path unless container`

Interestingly enough I was not able to reproduce with pod create and run, CI logs also seems to only show it with play kube.

### PR DESCRIPTION
**Pull request by Luap99**
Commit 1ab833fb73 improved the situation but it is still not enough. If you run short lived containers with --restart=always podman is basically permanently restarting them. To only way to stop this is podman stop. However podman stop does not do anything when the container is already in a not running state. While this makes sense we should still mark the container as explicitly stopped by the user.

Together with the change in shouldRestart() which now checks for StoppedByUser this makes sure the cleanup process is not going to start it back up again.

A simple reproducer is:
```
podman run --restart=always --name test -d alpine true
podman stop test
```
then check if the container is still running, the behavior is very flaky, it took me like 20 podman stop tries before I finally hit the correct window were it was stopped permanently.
With this patch it worked on the first try.

Fixes #18259

[NO NEW TESTS NEEDED] This is super flaky and hard to correctly test in CI. MY ginkgo v2 work seems to trigger this in play kube tests so that should catch at least some regressions. Also this may be something that should be tested at podman test days by users (#17912).

#### Does this PR introduce a user-facing change?

```release-note
podman stop will now correctly stop containers created with --restart=always in all cases.
```

### CODE REVIEW

File: libpod/container_internal.go [hunk 1]
```diff
@@ -1307,16 +1311,35 @@ func (c *Container) stop(timeout uint) error {
...
 
-	// Set the container state to "stopping" and unlock the container
-	// before handing it over to conmon to unblock other commands.  #8501
-	// demonstrates nicely that a high stop timeout will block even simple
-	// commands such as `podman ps` from progressing if the container lock
-	// is held when busy-waiting for the container to be stopped.
+	// OK, the following code looks a bit weird but we have to make sure we can stop
+	// containers with the restart policy always, to do this we have to set
+	// StoppedByUser even when there is nothing to stop right now. This is due the
+	// cleanup process waiting on the contianer lock and then afterwards restarts it.
```
Comment (edsantiago) [inline libpod/container_internal.go:1317]: wow - typo is causing CI to fail. Anyhow, "contianer" is mipseled.

File: libpod/container_internal.go [hunk 2]
```diff
@@ -1307,16 +1311,35 @@ func (c *Container) stop(timeout uint) error {
...
 	}
 
-	// Set the container state to "stopping" and unlock the container
-	// before handing it over to conmon to unblock other commands.  #8501
-	// demonstrates nicely that a high stop timeout will block even simple
-	// commands such as `podman ps` from progressing if the container lock
-	// is held when busy-waiting for the container to be stopped.
+	// OK, the following code looks a bit weird but we have to make sure we can stop
+	// containers with the restart policy always, to do this we have to set
+	// StoppedByUser even when there is nothing to stop right now. This is due the
```
Comment (edsantiago) [inline libpod/container_internal.go:1316]: As long as we're repushing for language: `s/due the/due to the/`. Also, the "then restarts it" in the line below, the "contianer" one, should maybe be "restarting it"?

File: libpod/container_internal.go [hunk 3]
```diff
@@ -1307,16 +1311,35 @@ func (c *Container) stop(timeout uint) error {
...
+	// cleanup process waiting on the contianer lock and then afterwards restarts it.
+	// shouldRestart() then checks for StoppedByUser and does not restart it.
+	// https://github.com/containers/podman/issues/18259
+	var canNotStopErr error
```
Comment (edsantiago) [inline libpod/container_internal.go:1320]: One more: "cannot" is one word. Can you lower-case that `N` please?

**Review by edsantiago — COMMENTED** [review]
language, language

**Comment by Luap99** [comment]
@vrothberg @mheon PTAL

File: libpod/container_internal.go [hunk 4]
```diff
@@ -1307,16 +1312,35 @@ func (c *Container) stop(timeout uint) error {
...
+	// containers with the restart policy always, to do this we have to set
+	// StoppedByUser even when there is nothing to stop right now. This is due to the
+	// cleanup process waiting on the container lock and then afterwards restarts it.
+	// shouldRestart() then checks for StoppedByUser and does not restart it.
+	// https://github.com/containers/podman/issues/18259
+	var cannotStopErr error
+	if c.ensureState(define.ContainerStateStopped, define.ContainerStateExited) {
+		cannotStopErr = define.ErrCtrStopped
+	}
+	if !c.ensureState(define.ContainerStateCreated, define.ContainerStateRunning, define.ContainerStateStopping) {
```
Comment (vrothberg) [inline libpod/container_internal.go:1325]: `else if`?

**Review by vrothberg — COMMENTED** [review]
LGTM

File: libpod/container_internal.go (hunk 4 above)
Comment (Luap99) [reply libpod/container_internal.go:1325]: yes you are right, forgot to adapt this because it used early return in the branch before.

**Comment by edsantiago** [comment]
LGTM. I'd really, really like to see this behavior unambiguously documented in `podman-stop(1)` but that can be a followup.

**Comment by edsantiago** [comment]
Also: https://github.com/containers/podman/blob/53d8e4b50ffc85f5b8244f4a160aa05c667fbf0d/docs/source/markdown/options/restart.md?plain=1#L8

...I think a similar fix will be needed for `podman kill -a`.

**Comment by edsantiago** [comment]
>Kill should work with this correctly

I did try it before reporting, and just tried it again (f3d453c1fea032db312d0794dcec076754317d3e):
```console
$ bin/podman run -d --restart=always quay.io/libpod/testimage:20221018 date
1f4811e1e807232762bd620614b70ecb2bd713ec737efda20f1430f68e2e2846
$ bin/podman kill -a
$ bin/podman ps -a
...keeps showing "Exited (0) Less than a second ago"; once in a while shows "Up Less than a second"
```

**Comment by Luap99** [comment]
Kill is not supposed to work on non running containers. You have to test with `podman kill <name>`, then you see it exists out with an error. `--all` is of course a NOP if the continuer is not running. If you try it often enough and hit the window were the container is really running then it works:
```
$ podman kill test
Error: can only kill running containers. 7b6a2199d8e9d1e5148c23706bec7851ba748de23170bdd0a1f514dcf9669e1e is in state stopped: container state improper
$ podman kill test
Error: can only kill running containers. 7b6a2199d8e9d1e5148c23706bec7851ba748de23170bdd0a1f514dcf9669e1e is in state stopped: container state improper
$ podman kill test
test
$ podman ps
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
```

**Comment by mheon** [comment]
This seems a little iffy - it can change a container that is already in
Exited state to Stopping from my read, which does not seem correct. Is just
setting StoppedByUser not sufficient?

**Comment by Luap99** [comment]
> This seems a little iffy - it can change a container that is already in Exited state to Stopping from my read, which does not seem correct. Is just setting StoppedByUser not sufficient?


Stopping is not set when the sate is not correct see the `if cannotStopErr == nil {` block, so yes I am only setting StoppedByUser. The reason I choose to do it that way is to only have one `c.save()` because we care about the performance of these calls AFAIK.

File: libpod/container_internal.go [hunk 5]
```diff
@@ -1307,16 +1312,34 @@ func (c *Container) stop(timeout uint) error {
...
+	if cannotStopErr == nil {
+		// Set the container state to "stopping" and unlock the container
+		// before handing it over to conmon to unblock other commands.  #8501
+		// demonstrates nicely that a high stop timeout will block even simple
+		// commands such as `podman ps` from progressing if the container lock
+		// is held when busy-waiting for the container to be stopped.
+		c.state.State = define.ContainerStateStopping
+	}
 	if err := c.save(); err != nil {
 		return fmt.Errorf("saving container %s state before stopping: %w", c.ID(), err)
```
Comment (mheon) [inline libpod/container_internal.go:1338]: Maybe log this instead if `cannotStopErr` is not nil, so we don't lose the real error?

**Comment by mheon** [comment]
One suggestion, otherwise LGTM

File: libpod/container_internal.go (hunk 5 above)
Comment (Luap99) [reply libpod/container_internal.go]: done

**Comment by Luap99** [comment]
tests are green, please merge

**Review by vrothberg — APPROVED** [review]
/lgtm
