### PR TITLE
rootless: detect and remove stale pause.pid with recycled PIDs

### LINKED ISSUE #28157: Rootless podman trying to join a stale process PID from pause.pid and display `cannot set user namespace` error
### Issue Description

When you're running rootless podman, the first time it will create `pause.pid` in the runtime folder. For example, `/tmp/storage-run-1000/libpod/tmp/pause.pid`. But if the pid is actually stale, the original pause process created by podman rootless was no longer there, however, there might be another process happen to have the same pid, you will see an error like:

```
cannot set user namespace
```

The problem can be resolved by removing the stale pid as described here

https://github.com/containers/podman/issues/10135#issuecomment-827742957

But it still seems like a bug to me, as I would expect podman to know that the process pid is stale and fallback to creating a new one and clear the stale one.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Setup an environment to run podman in rootless mode (update `/etc/subuid` and `/etc/subgid`, create new user and etc)
2. Add a `pause.pid` file at the expected location, like, for example `/tmp/storage-run-1000/libpod/tmp/pause.pid`, write a pid pointing to a running process that's not the a valid pause created by podman
3. Run almost any podman cmd, even as simple as such as `podman system info` with the rootless user you've just created
4. You should see `cannot set user namespace` error as the podman in root

I created a repo with docker compose in it to make reproducing the bug much easier:

https://github.com/fangpenlin/podman-stale-pause-pid-bug

Usage, build the image:

```bash
docker build -t podman-stale-pause-pid-bug .
```

Run with Compose:

```bash
docker compose up
```

### Describe the results you received

> cannot set user namespace

### Describe the results you expected

podman should have a way to tell if the processing provided by the `pause.pid` file an actual pause process created by podman to help speeding up the exec. and if the pid is already stale, it should not print `cannot set user namespace` and exit, it should remove the pid file and create a new one

### podman info output

```yaml
podman info
host:
  arch: amd64
  buildahVersion: 1.42.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon_2.1.13+ds1-2_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.13, commit: unknown'
  cpuUtilization:
    idlePercent: 85.72
    systemPercent: 3.79
    userPercent: 10.48
  cpus: 4
  databaseBackend: sqlite
  distribution:
    codename: forky
    distribution: debian
    version: unknown
  eventLogger: file
  freeLocks: 2048
  hostname: makerrepo-web-worker-85f59c568c-kdrzt
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.1.158-180.294.amzn2023.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 614301696
  memTotal: 16558186496
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: Unknown
    package: netavark_1.16.1-3.1_amd64
    path: /usr/lib/podman/netavark
    version: netavark 1.16.1
  ociRuntime:
    name: runc
    package: runc_1.3.3+ds1-2_amd64
    path: /usr/bin/runc
    version: |-
      runc version 1.3.3+ds1
      commit: 1.3.3+ds1-2
      spec: 1.2.1
      go: go1.24.9
      libseccomp: 2.5.4
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: true
    path: /tmp/storage-run-1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 1420h 47m 43.00s (Approximately 59.17 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  localhost:7000:
    Blocked: false
    Insecure: true
    Location: localhost:7000
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: localhost:7000
    PullFromMirror: ""
store:
  configFile: /home/makerrepo/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fusermount3 version: 3.18.1
        fuse-overlayfs: version 1.13-dev
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev
  graphRoot: /home/makerrepo/.local/share/containers/storage
  graphRootAllocated: 137359241216
  graphRootUsed: 49960837120
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /tmp/storage-run-1000/containers
  transientStore: true
  volumePath: /home/makerrepo/.local/share/containers/storage/volumes
version:
  APIVersion: 5.7.0
  BuildOrigin: Debian
  Built: 1764725792
  BuiltTime: Wed Dec  3 01:36:32 2025
  GitCommit: ""
  GoVersion: go1.24.9
  Os: linux
  OsArch: linux/amd64
  Version: 5.7.0
```

### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### PR DESCRIPTION
**Pull request by giuseppe**
When a pause process dies and its PID gets recycled by an unrelated process, the stale pause.pid file causes join failures.  Detect this by checking /proc/<pid>/environ for _PODMAN_PAUSE=1 after a failed join attempt.  If the process is not a pause process, remove the stale file and log a warning so the caller can create a fresh pause process on the first try.

Closes: https://github.com/containers/podman/issues/28157

#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [ ] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [ ] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [ ] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [ ] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [ ] All commits pass `make validatepr` (format/lint checks)
- [ ] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by Honny1 — COMMENTED** [review]
The code looks good to me, but I'll defer to the conmon experts.


PTAL @jankaluza

File: pkg/rootless/rootless_linux.c [hunk 1]
```diff
@@ -842,14 +879,35 @@ static void __attribute__((constructor)) init()
 
       userns_fd = open_namespace (pid, "user");
       if (userns_fd < 0)
-        return;
+        {
+          if (!is_pause_process (pid))
+            {
+              fprintf (stderr, "pause.pid file refers to PID %ld which is not a pause process, the process may have exited and the PID been recycled. Deleting %s\n", pid, path);
+              unlink (path);
+            }
```
Comment (Luap99) [inline pkg/rootless/rootless_linux.c]: that seems to be duplicated for all callers, could we just inline that into the function or at least share the error message string?

**Review by Luap99 — COMMENTED** [review]
The namespace creation post boot (i.e. without alive lock held) is unlocked I belive, does check if valid and deleting the file not open us to rare race conditions.

process A checks if file exists
process B checks if file exists
process A removes file

process C has no pause pid file and creates it
Process B removes the file

Process C now has a stale namespace

Just a theory, I am not sure this would actually cause real problems. I guess if there is a such a race then this would not really make it worse as currently the user would need to delete the file manually.

On thing I would like to see though is a test case in test/system/550-pause-process.bats because the reexec logic is quite fragile.
We already kill the pause process in tests there, I think we could kill + create some sleep process and write its pid to the pause pid file and check that this recovers from that scenario with the warning message automatically.

**Comment by giuseppe** [comment]
> The namespace creation post boot (i.e. without alive lock held) is unlocked I belive, does check if valid and deleting the file not open us to rare race conditions.
> 
> process A checks if file exists process B checks if file exists process A removes file
> 
> process C has no pause pid file and creates it Process B removes the file
> 
> Process C now has a stale namespace
> 
> Just a theory, I am not sure this would actually cause real problems. I guess if there is a such a race then this would not really make it worse as currently the user would need to delete the file manually.
> 
> On thing I would like to see though is a test case in test/system/550-pause-process.bats because the reexec logic is quite fragile. We already kill the pause process in tests there, I think we could kill + create some sleep process and write its pid to the pause pid file and check that this recovers from that scenario with the warning message automatically.

sure, in theory that can happen but the assumption is that it is such an exceptional error, that we won't hit that race condition.

I don't want to overengineer this with locks, so alternatively we could just print an error asking users to delete that file and don't have to deal with it directly.

**Comment by Luap99** [comment]
> I don't want to overengineer this with locks, so alternatively we could just print an error asking users to delete that file and don't have to deal with it directly.

Yeah like I said the alternative is we move this to the user which does not solve the race so we do not make anything worse as such I agree it is fine to not introduce more locks. And I agree it will be so exceptional that I am not sure we would ever hit this in the wild so not worth trying to spend to much time on it.

I guess overall this is just another argument for your new ns refernce code path on newer kernels where we no longer track pids.

**Review by Luap99 — APPROVED** [review]
LGTM
