### PR TITLE
test/e2e: do not use apk in builds

### LINKED ISSUE #16391: New f37 flake: podman image prune: APK error or timeout
Seems to be timing out and failing in an apk command:
```
podman [options] build --pull-never --layers=true --file /tmp/podman_test3730377924/Dockerfile -t alpine_bash:latest /tmp/podman_test3730377924
         STEP 1/4: FROM quay.io/libpod/alpine:latest
         STEP 2/4: LABEL RUN podman --version
         --> 033b2b638ee
         STEP 3/4: RUN apk update
         fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
```
Lots of f37 flakes, none on f36.

### Podman prune [It] podman image prune - remove only dangling images 
* fedora-37 : int podman fedora-37 root container
  * PR #16389
    * [11-02 18:58](https://api.cirrus-ci.com/v1/artifact/task/6370124769263616/html/int-podman-fedora-37-root-container.log.html#t--podman-image-prune---remove-only-dangling-images--1)
    * [11-02 18:58](https://api.cirrus-ci.com/v1/artifact/task/6370124769263616/html/int-podman-fedora-37-root-container.log.html#t--podman-image-prune---remove-only-dangling-images--2)
    * [11-02 18:58](https://api.cirrus-ci.com/v1/artifact/task/6370124769263616/html/int-podman-fedora-37-root-container.log.html#t--podman-image-prune---remove-only-dangling-images--3)
    * [11-02 18:21](https://api.cirrus-ci.com/v1/artifact/task/5355295198150656/html/int-podman-fedora-37-root-container.log.html#t--podman-image-prune---remove-only-dangling-images--1)
    * [11-02 18:21](https://api.cirrus-ci.com/v1/artifact/task/5355295198150656/html/int-podman-fedora-37-root-container.log.html#t--podman-image-prune---remove-only-dangling-images--2)
* fedora-37 : int podman fedora-37 root host
  * PR #15760
    * [11-02 14:33](https://api.cirrus-ci.com/v1/artifact/task/6050840522784768/html/int-podman-fedora-37-root-host.log.html#t--podman-image-prune---remove-only-dangling-images--1)
    * [11-02 14:33](https://api.cirrus-ci.com/v1/artifact/task/6050840522784768/html/int-podman-fedora-37-root-host.log.html#t--podman-image-prune---remove-only-dangling-images--2)
    * [11-02 14:33](https://api.cirrus-ci.com/v1/artifact/task/6050840522784768/html/int-podman-fedora-37-root-host.log.html#t--podman-image-prune---remove-only-dangling-images--3)

### PR DESCRIPTION
**Pull request by Luap99**
As far as I can tell there is no reason to use apk in these tests. They just build an image and check for it and never use the installed binary. Network calls are always unstable and therefore should be avoided when possible, this ensures no/less flakes.

Fixes #16391

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by vrothberg — COMMENTED** [review]
LGTM

Nice catch!

**Comment by Luap99** [comment]
windows smoke test looks broken, was already rerun once: https://cirrus-ci.com/task/6678299677032448
@cevich @n1hility PTAL

**Comment by cevich** [comment]
`Expand-Archive : The path 'podman-remote-release-windows_amd64.zip' either does not exist or is not a valid file 
system path.`

This smells like a task-dependency problem to me, but the YAML looks correct :confused: Did the `Windows Cross` task fail silently or not attach the binary for some reason...

**Comment by cevich** [comment]
...ya, looks like [the `Windows Cross` task is failing silently](https://cirrus-ci.com/task/5649554681888768).  That's definitely not good :confounded:  Ahh, I re-ran it and got something helpful:

```
/usr/bin/time --verbose --output="$STATS_LOGFILE" $GOSRC/$SCRIPT_BASE/runner.sh
************************************************************
Runner executing altbuild podman-tests as root on fedora-37(fedora-37)
Current environment VM image: fedora-c5178639502278656
************************************************************
SKIPPING: This is a doc- and/or test-only PR with no changes under docs
```

I know how to fix this...

**Comment by cevich** [comment]
...okay, that should get this PR sorted once it (or something similar) merges and you rebase this one.

**Comment by cevich** [comment]
un-ping @n1hility

**Comment by cevich** [comment]
@Luap99 for future reference, if you get completely wedged like this, please feel free to ping me on IRC or matrix.  I'm sometimes slow to notice my github mail (and sometimes it gets delivered pretty slowly).

File: test/e2e/prune_test.go [hunk 1]
```diff
@@ -13,8 +13,8 @@ import (
 var pruneImage = fmt.Sprintf(`
 FROM  %s
 LABEL RUN podman --version
-RUN apk update
-RUN apk add bash`, ALPINE)
+RUN echo hello > /hello
+RUN echo hello2 > /hello2`, ALPINE)
```
Comment (rhatdan) [inline test/e2e/prune_test.go:17]: This looks like a cut and paste error `, ALPINE)`

Comment (edsantiago) [reply test/e2e/prune_test.go:17]: I think it's OK? That's the argument for the `FROM %s` in the sprintf()?

**Review by edsantiago — APPROVED** [review]
LGTM, thanks for doing this

**Comment by edsantiago** [comment]
I'm OK with someone force-merging this, but since it's (probably) not urgent, I have a preference for rebasing on main (with #16401) so we can confirm that that PR works as it was meant to.
